{"metadata":{"modules":[{"name":"TeadsSDK"}],"roleHeading":"Framework","role":"collection","symbolKind":"module","title":"TeadsSDK","externalID":"TeadsSDK"},"kind":"symbol","hierarchy":{"paths":[[]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Prepare SDK","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/configure()"],"anchor":"Prepare-SDK"},{"title":"Create Ad Placements","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createNativePlacement(pid:settings:delegate:)"],"anchor":"Create-Ad-Placements"},{"title":"Request Ads over placements","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)"],"anchor":"Request-Ads-over-placements"},{"title":"Settings","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"],"anchor":"Settings"},{"title":"Classes","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ContainerComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdChoicesView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent"],"anchor":"Classes"},{"title":"Protocols","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsFluentProtocol","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadFluentProtocol","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeFluentProtocol","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement"],"anchor":"Protocols"},{"title":"Structures","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative"],"anchor":"Structures"},{"title":"Type Aliases","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdRequestSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdRequestSettings"],"anchor":"Type-Aliases"},{"title":"Enumerations","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion"],"anchor":"Enumerations"},{"title":"Extended Modules","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUI","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/UIKit"],"anchor":"Extended-Modules"}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"%F0%9F%93%A3-Overview","text":"📣 Overview","type":"heading"},{"inlineContent":[{"type":"image","identifier":"logo.png"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"TeadsSDK supports two formats:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"inRead"}],"type":"strong"},{"text":": Rich resizable Ad Content","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Native"}]},{"type":"text","text":": Fully customizable native ad"}],"type":"paragraph"}]}],"type":"unorderedList"},{"level":2,"anchor":"%F0%9F%9A%80-Integration-Documentation","text":"🚀 Integration Documentation","type":"heading"},{"inlineContent":[{"text":"Integration instructions are available on ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314785"},{"text":".","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"%F0%9F%93%A6-Install-the-Teads-SDK-iOS-framework","text":"📦 Install the Teads SDK iOS framework","type":"heading"},{"inlineContent":[{"type":"text","text":"Teads SDK is currently distributed through CocoaPods and Swift Package Manager. It includes everything you need to serve “outstream” video ads."}],"type":"paragraph"},{"level":3,"anchor":"Swift-Package-Manager","text":"Swift Package Manager","type":"heading"},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/swift.org\/package-manager\/"},{"text":" is a tool for managing the distribution of Swift code. It’s integrated with the Swift build system to automate the process of downloading, compiling, and linking dependencies.","type":"text"}],"type":"paragraph"},{"level":4,"anchor":"Installing-from-Xcode","text":"Installing from Xcode","type":"heading"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Add a package by selecting "},{"code":"File","type":"codeVoice"},{"type":"text","text":" → "},{"code":"Add Packages…","type":"codeVoice"},{"type":"text","text":" in Xcode’s menu bar."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Search for the Teads iOS SDK using the repo’s URL:"}]}]}]},{"type":"codeListing","code":["https:\/\/github.com\/teads\/TeadsSDK-iOS"],"syntax":"console"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Next, set the ","type":"text"},{"type":"strong","inlineContent":[{"text":"Dependency Rule","type":"text"}]},{"text":" to be ","type":"text"},{"type":"codeVoice","code":"Up to Next Major Version"},{"text":" and keep ","type":"text"},{"type":"codeVoice","code":"5.0.0 < 6.0.0"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Choose the Teads product that you want to be installed in your app: "},{"type":"codeVoice","code":"TeadsSDK"}]}]}],"start":3},{"type":"heading","level":4,"text":"Alternatively, add Teads to your Package.swift manifest","anchor":"Alternatively-add-Teads-to-your-Packageswift-manifest"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Add it to the "},{"type":"codeVoice","code":"dependencies"},{"type":"text","text":" of your "},{"type":"codeVoice","code":"Package.swift"},{"type":"text","text":":"}],"type":"paragraph"}]}]},{"type":"codeListing","code":["dependencies: [","    .package(url: \"https:\/\/github.com\/teads\/TeadsSDK-iOS\", .upToNextMajor(from: \"5.0.0\"))","]"],"syntax":"swift"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"in any target that depends on a Teads product, add it to the "},{"type":"codeVoice","code":"dependencies"},{"type":"text","text":" array of that target:"}],"type":"paragraph"}]}],"start":2},{"type":"codeListing","code":[".target(","  name: \"MyTargetName\",","  dependencies: [","    \/\/ The product(s) you want (e.g. TeadsSDK).","    .product(name: \"TeadsSDK\", package: \"Teads\"),","  ]","),"],"syntax":"swift"},{"type":"heading","level":3,"text":"Cocoapods","anchor":"Cocoapods"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To install the TeadsSDK just put this in your podfile, if you’ve never used Cocoapods before please check the "},{"identifier":"https:\/\/guides.cocoapods.org\/using\/using-cocoapods.html","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"type":"codeListing","code":["pod 'TeadsSDK', '~> 5.1'"],"syntax":"ruby"},{"type":"paragraph","inlineContent":[{"text":"On your terminal, go to the directory containing your project’s ","type":"text"},{"code":".xcodeproj","type":"codeVoice"},{"text":" file and your Podfile then run ","type":"text"},{"code":"pod install","type":"codeVoice"},{"text":" command. This will install Teads SDK along with our needed dependencies.","type":"text"}]},{"type":"codeListing","code":["pod install --repo-update"],"syntax":"bash"},{"type":"heading","level":2,"text":"🎓 Certifications","anchor":"%F0%9F%8E%93-Certifications"},{"type":"paragraph","inlineContent":[{"text":"Teads SDK supports the ","type":"text"},{"identifier":"https:\/\/www.iabcertification.com\/","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"identifier":"https:\/\/iabtechlab.com\/standards\/open-measurement-sdk\/","isActive":true,"type":"reference"},{"text":" SDK, also known as OM SDK. The OM SDK brings transparency to the advertising world, giving a way to standardize the viewability and verification measurement for the ads served through mobile apps. Teads is part of the ","type":"text"},{"identifier":"https:\/\/iabtechlab.com\/compliance-programs\/compliant-companies\/","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"OMCompliant.png"}]}]}],"variants":[{"paths":["\/documentation\/teadssdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsNativeAd","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativead","kind":"symbol","title":"TeadsNativeAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","role":"symbol"},"logo.png":{"type":"image","alt":"Teads","variants":[{"traits":["1x","light"],"url":"\/images\/tv.teads.TeadsSDK.TeadsSDK\/logo.png"}],"identifier":"logo.png"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"type":"topic","title":"TeadsPrebidAdPlacement","abstract":[{"type":"text","text":"\/ Prebid ad placement to load inRead ads from Prebid winning bid"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement","url":"\/documentation\/teadssdk\/teadsprebidadplacement","role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OverlayComponent":{"abstract":[{"text":"Native overlay component that could be put over playerView such as ","type":"text"},{"inlineContent":[{"text":"AdChoices","type":"text"}],"type":"strong"},{"text":" or ","type":"text"},{"inlineContent":[{"type":"text","text":"ClickToAction"}],"type":"strong"}],"type":"topic","title":"OverlayComponent","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent","url":"\/documentation\/teadssdk\/overlaycomponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverlayComponent","kind":"identifier"}],"navigatorTitle":[{"text":"OverlayComponent","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsLogMessageDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","abstract":[{"text":"Log delegate enabling you to route every log message written in console into a dedicated area of your choice","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"role":"symbol","type":"topic","title":"TeadsLogMessageDelegate","kind":"symbol","url":"\/documentation\/teadssdk\/teadslogmessagedelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","navigatorTitle":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}],"title":"TeadsInReadAdPlacementDelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads inRead ad requests flow"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"abstract":[{"type":"text","text":"Specify which settings you want to set for your Teads placement."}],"title":"TeadsAdPlacementSettings","url":"\/documentation\/teadssdk\/teadsadplacementsettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","navigatorTitle":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:tagBinder:)":{"title":"bind(_:tagBinder:)","role":"symbol","url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)","kind":"symbol","abstract":[{"text":"Binds the native asset ad views to this native ad using view tags binder","type":"text"}],"navigatorTitle":[{"text":"bind:tagBinder:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd"},{"text":", ","kind":"text"},{"text":"tagBinder","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"TagBinderBuilder","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate","abstract":[{"type":"text","text":"Delegate methods sending informations about Teads ads playback states."}],"url":"\/documentation\/teadssdk\/teadsplaybackdelegate","kind":"symbol","title":"TeadsPlaybackDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createInReadPlacement(pid:settings:delegate:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createInReadPlacementWithPid:settings:delegate:"}],"abstract":[{"type":"text","text":"Create an inRead ad placement to request inRead ads"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInReadPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","kind":"typeIdentifier","text":"TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate","kind":"typeIdentifier","text":"TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacement","kind":"typeIdentifier","text":"TeadsInReadAdPlacement"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)","title":"createInReadPlacement(pid:settings:delegate:)","url":"\/documentation\/teadssdk\/teads\/createinreadplacement(pid:settings:delegate:)","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"url":"\/documentation\/teadssdk\/teadsadrequestsettings","type":"topic","title":"TeadsAdRequestSettings","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRequestSettings","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","navigatorTitle":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"abstract":[{"text":"Specify which settings you want to set for the related ad request.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsFluentProtocol":{"title":"TeadsFluentProtocol","url":"\/documentation\/teadssdk\/teadsfluentprotocol","role":"symbol","navigatorTitle":[{"text":"TeadsFluentProtocol","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsFluentProtocol","type":"topic","abstract":[{"text":"Fluent Interface for SwifUI implementation","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsFluentProtocol","kind":"identifier"}],"kind":"symbol"},"OMCompliant.png":{"type":"image","alt":"iab certification badge","variants":[{"traits":["1x","light"],"url":"\/images\/tv.teads.TeadsSDK.TeadsSDK\/OMCompliant.png"}],"identifier":"OMCompliant.png"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdChoicesView":{"url":"\/documentation\/teadssdk\/teadsadchoicesview","abstract":[{"text":"The Teads AdChoices view is responsible to render the optionView or AdChoices view.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdChoicesView","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdChoicesView","kind":"identifier"}],"role":"symbol","title":"TeadsAdChoicesView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdChoicesView","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeFluentProtocol":{"type":"topic","url":"\/documentation\/teadssdk\/teadsnativefluentprotocol","title":"TeadsNativeFluentProtocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeFluentProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeFluentProtocol","navigatorTitle":[{"text":"TeadsNativeFluentProtocol","kind":"identifier"}],"abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsSDKVersionString":{"title":"TeadsSDKVersionString","fragments":[{"kind":"identifier","text":"TeadsSDKVersionString"}],"kind":"symbol","role":"symbol","url":"\/documentation\/teadssdk\/teadssdkversionstring","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsSDKVersionString","abstract":[{"type":"text","text":"Project version string for TeadsSDK."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ContainerComponent":{"title":"ContainerComponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerComponent","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ContainerComponent","kind":"identifier"}],"url":"\/documentation\/teadssdk\/containercomponent","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ContainerComponent","abstract":[{"type":"text","text":"Native container component: represent the overall container of native ad view"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead":{"navigatorTitle":[{"kind":"identifier","text":"TeadsInRead"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInRead"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","title":"TeadsInRead","url":"\/documentation\/teadssdk\/teadsinread"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement/requestAd(requestSettings:)":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestAdWithRequestSettings:"}],"title":"requestAd(requestSettings:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23NativeAdRequestSettingsa"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement\/requestad(requestsettings:)","abstract":[{"type":"text","text":"Request a native ad on this placement"},{"type":"text","text":" "},{"type":"text","text":"listen for events by implementing "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","type":"reference","isActive":true}]},"https://support.teads.tv/support/solutions/articles/36000314785":{"title":"Teads SDK Documentation","titleInlineContent":[{"type":"text","text":"Teads SDK Documentation"}],"type":"link","url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314785","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314785"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Teads","kind":"identifier"}],"navigatorTitle":[{"text":"Teads","kind":"identifier"}],"title":"Teads","url":"\/documentation\/teadssdk\/teads","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Teads"},{"type":"text","text":" class defines the main entry point to start implementing TeadsSDK."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"title":"CommonComponent","abstract":[{"type":"text","text":"Native Root Component"}],"type":"topic","url":"\/documentation\/teadssdk\/commoncomponent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"navigatorTitle":[{"kind":"identifier","text":"CommonComponent"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason":{"url":"\/documentation\/teadssdk\/adfailreason","title":"AdFailReason","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdFailReason"}],"navigatorTitle":[{"kind":"identifier","text":"AdFailReason"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","abstract":[{"text":"Error returned when ad request has failed. The failure is usually due to network","type":"text"},{"text":" ","type":"text"},{"text":"connectivity or ad availablility (i.e., no fill).","type":"text"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent/clickThroughUrl":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","type":"topic","abstract":[{"text":"Reach the URL that should be used when the ‘Ad Choices’ button is tapped.","type":"text"},{"text":" ","type":"text"},{"text":"Common behavior: open a Safari Web Browser with ","type":"text"},{"type":"codeVoice","code":"clickThroughUrl"}],"kind":"symbol","url":"\/documentation\/teadssdk\/adchoicescomponent\/clickthroughurl","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clickThroughUrl","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"}],"title":"clickThroughUrl"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdRequestSettings":{"url":"\/documentation\/teadssdk\/teadsinreadadrequestsettings","title":"TeadsInReadAdRequestSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdRequestSettings","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdRequestSettings","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsInReadAdRequestSettings","kind":"identifier"}],"abstract":[{"type":"text","text":"Convenience closure typealias for "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)","isActive":true}]},"https://iabtechlab.com/compliance-programs/compliant-companies/":{"title":"IAB’s compliant companies","titleInlineContent":[{"text":"IAB’s compliant companies","type":"text"}],"type":"link","url":"https:\/\/iabtechlab.com\/compliance-programs\/compliant-companies\/","identifier":"https:\/\/iabtechlab.com\/compliance-programs\/compliant-companies\/"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"navigatorTitle":[{"text":"TeadsNativeAdView","kind":"identifier"}],"title":"TeadsNativeAdView","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","abstract":[{"text":"The Teads native ad view is responsible to manage a Teads native ad.","type":"text"}],"url":"\/documentation\/teadssdk\/teadsnativeadview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"kind":"symbol","url":"\/documentation\/teadssdk\/teadsinreadadview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"type":"topic","role":"symbol","title":"TeadsInReadAdView","navigatorTitle":[{"text":"TeadsInReadAdView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdRequestSettings":{"title":"TeadsNativeAdRequestSettings","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdRequestSettings"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdRequestSettings"}],"url":"\/documentation\/teadssdk\/teadsnativeadrequestsettings","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdRequestSettings","abstract":[{"text":"Convenience closure typealias for ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)","isActive":true,"type":"reference"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/VideoComponent":{"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent","url":"\/documentation\/teadssdk\/videocomponent","type":"topic","title":"VideoComponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoComponent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoComponent","kind":"identifier"}],"abstract":[{"type":"text","text":"Native video component containing media content"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacement":{"kind":"symbol","navigatorTitle":[{"text":"TeadsInReadAdPlacement","kind":"identifier"}],"abstract":[{"type":"text","text":"InRead ad placement to request inRead ads"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacement"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement","title":"TeadsInReadAdPlacement","url":"\/documentation\/teadssdk\/teadsinreadadplacement","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"title":"TeadsAdapterSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","navigatorTitle":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView":{"role":"symbol","title":"TeadsMediaView","url":"\/documentation\/teadssdk\/teadsmediaview","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsMediaView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","abstract":[{"type":"text","text":"The TeadsMediaView can load either images, videos and VPAID content."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediaView"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createPrebidPlacement(settings:delegate:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createPrebidPlacementWithSettings:delegate:"}],"title":"createPrebidPlacement(settings:delegate:)","abstract":[{"text":"Create an  inRead ad placement to request load Prebid ad response","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createPrebidPlacement(settings:delegate:)","url":"\/documentation\/teadssdk\/teads\/createprebidplacement(settings:delegate:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPrebidPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TeadsPrebidAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsPrebidAdPlacement"},{"kind":"text","text":"?"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"title":"TeadsNativeAdPlacement","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement","abstract":[{"text":"Native ad placement to request native ads","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore","abstract":[],"url":"\/documentation\/teadssdk\/swiftuicore","kind":"symbol","title":"SwiftUICore","type":"topic","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","navigatorTitle":[{"text":"TeadsAdRatio","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadratio","abstract":[{"text":"This class is used to help in resizing a given ad view to a given aspect ratio.","type":"text"}],"title":"TeadsAdRatio","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRatio","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"title":"TeadsNativeAdPlacementDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads native ad requests flow"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/UIKit":{"title":"UIKit","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/UIKit","url":"\/documentation\/teadssdk\/uikit","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createNativePlacement(pid:settings:delegate:)":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createNativePlacement(pid:settings:delegate:)","role":"symbol","title":"createNativePlacement(pid:settings:delegate:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNativePlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement"},{"kind":"text","text":"?"}],"url":"\/documentation\/teadssdk\/teads\/createnativeplacement(pid:settings:delegate:)","abstract":[{"type":"text","text":"Create a native ad placement to request native ads"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder":{"url":"\/documentation\/teadssdk\/tagbinderbuilder","navigatorTitle":[{"kind":"identifier","text":"TagBinderBuilder"}],"title":"TagBinderBuilder","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","abstract":[{"type":"text","text":"This builder allows you to bind UI elements programmatically using "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","type":"reference","isActive":true}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagBinderBuilder"}],"role":"symbol"},"https://swift.org/package-manager/":{"title":"SPM","titleInlineContent":[{"text":"SPM","type":"text"}],"type":"link","url":"https:\/\/swift.org\/package-manager\/","identifier":"https:\/\/swift.org\/package-manager\/"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","role":"symbol","title":"TeadsAdOpportunityTrackerView","url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","abstract":[{"text":"adOpportunity is a key metrics to evaluate the performance of your inventory.","type":"text"},{"text":" ","type":"text"},{"text":"It builds the visibility score of your placement in publisher dashboards.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacement":{"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacement"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacement"}],"title":"TeadsAdPlacement","type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacement"},"https://guides.cocoapods.org/using/using-cocoapods.html":{"title":"offical documentation","titleInlineContent":[{"type":"text","text":"offical documentation"}],"type":"link","url":"https:\/\/guides.cocoapods.org\/using\/using-cocoapods.html","identifier":"https:\/\/guides.cocoapods.org\/using\/using-cocoapods.html"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacement/requestAd(requestSettings:)":{"abstract":[{"text":"Request an InRead ad on this placement","type":"text"},{"text":" ","type":"text"},{"text":"listen for events by implementing ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","type":"reference"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsinreadadplacement\/requestad(requestsettings:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)","required":true,"type":"topic","title":"requestAd(requestSettings:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAdRequestSettings","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa"},{"text":") -> ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"}],"navigatorTitle":[{"text":"requestAdWithRequestSettings:","kind":"identifier"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode":{"url":"\/documentation\/teadssdk\/aderrorcode","title":"AdErrorCode","navigatorTitle":[{"kind":"identifier","text":"AdErrorCode"}],"kind":"symbol","abstract":[{"type":"text","text":"Enumeration of Teads’ error codes."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdErrorCode"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd":{"navigatorTitle":[{"kind":"identifier","text":"TeadsAd"}],"url":"\/documentation\/teadssdk\/teadsad","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAd"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","title":"TeadsAd","abstract":[{"type":"text","text":"Root Ad Object inherited by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd"},{"type":"text","text":" & "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdView":{"url":"\/documentation\/teadssdk\/teadsadview","abstract":[{"text":"Root view inherited by ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","isActive":true,"type":"reference"},{"text":" & ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","isActive":true,"type":"reference"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdView","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdView","kind":"identifier"}],"kind":"symbol","title":"TeadsAdView","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAd"}],"abstract":[{"text":"A TeadsInReadAd represents an InRead ad that will be binded to a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","type":"reference"},{"text":" instance","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAd"}],"type":"topic","role":"symbol","title":"TeadsInReadAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","url":"\/documentation\/teadssdk\/teadsinreadad"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate","kind":"symbol","url":"\/documentation\/teadssdk\/teadsaddelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads ads lifecycle."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdDelegate"}],"type":"topic","title":"TeadsAdDelegate","navigatorTitle":[{"kind":"identifier","text":"TeadsAdDelegate"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsSDKVersionNumber":{"title":"TeadsSDKVersionNumber","fragments":[{"kind":"identifier","text":"TeadsSDKVersionNumber"}],"kind":"symbol","role":"symbol","url":"\/documentation\/teadssdk\/teadssdkversionnumber","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsSDKVersionNumber","abstract":[{"text":"Project version number for TeadsSDK.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUI":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUI","url":"\/documentation\/teadssdk\/swiftui","abstract":[],"type":"topic","role":"collection","kind":"symbol","title":"SwiftUI"},"https://www.iabcertification.com/":{"type":"link","titleInlineContent":[{"type":"text","text":"IAB"}],"identifier":"https:\/\/www.iabcertification.com\/","title":"IAB","url":"https:\/\/www.iabcertification.com\/"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/configure()":{"title":"configure()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"configure","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teads\/configure()","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/configure()","abstract":[{"text":"In order to increase TeadsSDK launch speed and load ads faster, call ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/configure()"},{"text":" into ","type":"text"},{"type":"codeVoice","code":"AppDelegate.didFinishLaunchingWithOptions"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate":{"kind":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementDelegate","kind":"identifier"}],"title":"TeadsAdPlacementDelegate","abstract":[{"text":"Root placement delegate methods needed to follow Teads ad requests flow","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadplacementdelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementDelegate","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale":{"url":"\/documentation\/teadssdk\/mediascale","abstract":[{"type":"text","text":"A flag used to determine how TeadsMediaView lays out its content when its bounds change."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale","navigatorTitle":[{"kind":"identifier","text":"MediaScale"}],"type":"topic","role":"symbol","title":"MediaScale","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaScale"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent":{"abstract":[{"text":"Native image component containing image url","type":"text"}],"role":"symbol","url":"\/documentation\/teadssdk\/imagecomponent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageComponent"}],"title":"ImageComponent","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageComponent"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent":{"abstract":[{"text":"Native Component containing AdChoices ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl"}],"url":"\/documentation\/teadssdk\/adchoicescomponent","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdChoicesComponent","kind":"identifier"}],"navigatorTitle":[{"text":"AdChoicesComponent","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","kind":"symbol","title":"AdChoicesComponent","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TCFVersion":{"abstract":[{"text":"EU Transparency & Consent Framework versions","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TCFVersion"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TCFVersion"}],"url":"\/documentation\/teadssdk\/tcfversion","title":"TCFVersion","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement/loadAd(adResponse:requestSettings:)":{"title":"loadAd(adResponse:requestSettings:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"requestSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAdRequestSettings","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa"},{"text":") -> ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadAdWithAdResponse:requestSettings:"}],"url":"\/documentation\/teadssdk\/teadsprebidadplacement\/loadad(adresponse:requestsettings:)","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/loadAd(adResponse:requestSettings:)","required":true,"abstract":[{"type":"text","text":"Load an InRead ad on this placement by passing adResponse value"},{"type":"text","text":" "},{"type":"text","text":"listen for events by implementing "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","isActive":true}]},"https://iabtechlab.com/standards/open-measurement-sdk/":{"identifier":"https:\/\/iabtechlab.com\/standards\/open-measurement-sdk\/","type":"link","titleInlineContent":[{"text":"Open Measurement","type":"text"}],"url":"https:\/\/iabtechlab.com\/standards\/open-measurement-sdk\/","title":"Open Measurement"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediatedAdViewDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsmediatedadviewdelegate","navigatorTitle":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"abstract":[{"text":"When using mediation adapters on inRead placement you must register your view in order to monitor and perform resize updates","type":"text"}],"title":"TeadsMediatedAdViewDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"title":"TeadsAdapterIntegrationType","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","type":"topic","navigatorTitle":[{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadapterintegrationtype","abstract":[{"text":"Never create your own TeadsAdapterIntegrationType directly. Use one of the predefined standard values.","type":"text"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"url":"\/documentation\/teadssdk\/teadsnative","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNative"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsNative"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","abstract":[],"type":"topic","role":"symbol","title":"TeadsNative","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadFluentProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadFluentProtocol","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadFluentProtocol","title":"TeadsInReadFluentProtocol","url":"\/documentation\/teadssdk\/teadsinreadfluentprotocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"TeadsInReadFluentProtocol","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Prepare-SDK","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/configure()"],"title":"Prepare SDK"},{"anchor":"Create-Ad-Placements","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)"],"title":"Create Ad Placements"},{"anchor":"Request-Ads-over-placements","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)"],"title":"Request Ads over placements"},{"anchor":"Settings","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"],"title":"Settings"},{"anchor":"Classes","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ContainerComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdChoicesView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent"],"generated":true,"title":"Classes"},{"anchor":"Protocols","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement"],"generated":true,"title":"Protocols"},{"anchor":"Variables","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsSDKVersionNumber","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsSDKVersionString"],"generated":true,"title":"Variables"},{"anchor":"Enumerations","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion"],"generated":true,"title":"Enumerations"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title","value":"TeadsNativeAd","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments","value":[{"kind":"identifier","text":"TeadsNativeAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle","value":[{"text":"TeadsNativeAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/title","value":"TeadsPrebidAdPlacement","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/fragments","value":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/navigatorTitle","value":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/title","value":"OverlayComponent","op":"replace"},{"op":"replace","value":[{"text":"OverlayComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OverlayComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/navigatorTitle"},{"op":"replace","value":"TeadsLogMessageDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/title"},{"op":"replace","value":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/navigatorTitle"},{"op":"replace","value":"TeadsInReadAdPlacementDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title"},{"op":"replace","value":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle"},{"op":"replace","value":"TeadsAdPlacementSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle"},{"op":"replace","value":"bind:tagBinder:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bind:tagBinder:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/fragments"},{"op":"replace","value":"TeadsPlaybackDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/fragments"},{"op":"replace","value":[{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/navigatorTitle"},{"op":"replace","value":"createInReadPlacementWithPid:settings:delegate:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createInReadPlacement(pid:settings:delegate:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createInReadPlacementWithPid:settings:delegate:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createInReadPlacement(pid:settings:delegate:)\/fragments"},{"op":"replace","value":"TeadsAdRequestSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/navigatorTitle"},{"op":"replace","value":"TeadsAdChoicesView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdChoicesView\/title"},{"op":"replace","value":[{"text":"TeadsAdChoicesView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdChoicesView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdChoicesView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdChoicesView\/navigatorTitle"},{"op":"replace","value":"ContainerComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ContainerComponent\/title"},{"op":"replace","value":[{"text":"ContainerComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ContainerComponent\/fragments"},{"op":"replace","value":[{"text":"ContainerComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ContainerComponent\/navigatorTitle"},{"op":"replace","value":"requestAdWithRequestSettings:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1requestAd(requestSettings:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAdWithRequestSettings:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1requestAd(requestSettings:)\/fragments"},{"op":"replace","value":"Teads","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Teads"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/fragments"},{"op":"replace","value":[{"text":"Teads","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/navigatorTitle"},{"op":"replace","value":"CommonComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CommonComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments"},{"op":"replace","value":[{"text":"CommonComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle"},{"op":"replace","value":"AdFailReason","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/title"},{"op":"replace","value":[{"text":"AdFailReason","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AdFailReason"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/navigatorTitle"},{"op":"replace","value":"TeadsNativeAdView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title"},{"op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle"},{"op":"replace","value":"TeadsInReadAdView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments"},{"op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle"},{"op":"replace","value":"VideoComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"VideoComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VideoComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/navigatorTitle"},{"op":"replace","value":"TeadsInReadAdPlacement","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdPlacement"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdPlacement"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement\/navigatorTitle"},{"op":"replace","value":"TeadsAdapterSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title"},{"op":"replace","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"op":"replace","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle"},{"op":"replace","value":"TeadsMediaView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/title"},{"op":"replace","value":[{"text":"TeadsMediaView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/fragments"},{"op":"replace","value":[{"text":"TeadsMediaView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/navigatorTitle"},{"op":"replace","value":"createPrebidPlacementWithSettings:delegate:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createPrebidPlacement(settings:delegate:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createPrebidPlacementWithSettings:delegate:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createPrebidPlacement(settings:delegate:)\/fragments"},{"op":"replace","value":"TeadsNativeAdPlacement","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/title"},{"op":"replace","value":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/fragments"},{"op":"replace","value":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/navigatorTitle"},{"op":"replace","value":"TeadsAdRatio","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdRatio"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/fragments"},{"op":"replace","value":[{"text":"TeadsAdRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/navigatorTitle"},{"op":"replace","value":"TeadsNativeAdPlacementDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments"},{"op":"replace","value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle"},{"op":"replace","value":"TagBinderBuilder","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TagBinderBuilder"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/fragments"},{"op":"replace","value":[{"text":"TagBinderBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/navigatorTitle"},{"op":"replace","value":"TeadsAdOpportunityTrackerView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title"},{"op":"replace","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments"},{"op":"replace","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle"},{"op":"replace","value":"TeadsAdPlacement","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacement","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacement"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/navigatorTitle"},{"op":"replace","value":"requestAdWithRequestSettings:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1requestAd(requestSettings:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestAdWithRequestSettings:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1requestAd(requestSettings:)\/fragments"},{"op":"replace","value":"AdErrorCode","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/title"},{"op":"replace","value":[{"text":"AdErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AdErrorCode"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/navigatorTitle"},{"op":"replace","value":"TeadsAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/title"},{"op":"replace","value":[{"text":"TeadsAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/fragments"},{"op":"replace","value":[{"text":"TeadsAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/navigatorTitle"},{"op":"replace","value":"TeadsAdView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/title"},{"op":"replace","value":[{"text":"TeadsAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/fragments"},{"op":"replace","value":[{"text":"TeadsAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/navigatorTitle"},{"op":"replace","value":"TeadsInReadAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title"},{"op":"replace","value":[{"text":"TeadsInReadAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments"},{"op":"replace","value":[{"text":"TeadsInReadAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle"},{"op":"replace","value":"TeadsAdDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/title"},{"op":"replace","value":[{"text":"TeadsAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/navigatorTitle"},{"op":"replace","value":"configure","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1configure()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"configure","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1configure()\/fragments"},{"op":"replace","value":"TeadsAdPlacementDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/navigatorTitle"},{"op":"replace","value":"MediaScale","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MediaScale"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MediaScale"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/navigatorTitle"},{"op":"replace","value":"ImageComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/title"},{"op":"replace","value":[{"text":"ImageComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ImageComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/navigatorTitle"},{"op":"replace","value":"AdChoicesComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/title"},{"op":"replace","value":[{"text":"AdChoicesComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/fragments"},{"op":"replace","value":[{"text":"AdChoicesComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/navigatorTitle"},{"op":"replace","value":"TCFVersion","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/title"},{"op":"replace","value":[{"text":"TCFVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/fragments"},{"op":"replace","value":[{"text":"TCFVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/navigatorTitle"},{"op":"replace","value":"loadAdWithAdResponse:requestSettings:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1loadAd(adResponse:requestSettings:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadAdWithAdResponse:requestSettings:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1loadAd(adResponse:requestSettings:)\/fragments"},{"op":"replace","value":"TeadsMediatedAdViewDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/fragments"},{"op":"replace","value":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/navigatorTitle"},{"op":"replace","value":"TeadsAdapterIntegrationType","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/title"},{"op":"replace","value":[{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/fragments"},{"op":"replace","value":[{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/navigatorTitle"}]}]}