{"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"didClose(ad:)","roleHeading":"Instance Method","externalID":"s:8TeadsSDK0A6NativeV6AdViewV11CoordinatorC8didClose2adyAA0aD0C_tF","platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false}],"modules":[{"name":"TeadsSDK"}],"symbolKind":"method"},"abstract":[{"text":"Called when the ad has been close, in this case you need to close the slot or you will have a blank space.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"_","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","text":"TeadsAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The Teads ad that you need to close."}],"type":"paragraph"}],"name":"ad"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Only relevant for ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","type":"reference","isActive":true},{"text":", you can remove the ``TeadsInReadAdView` from your super view.","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnative\/adview\/coordinator\/didclose(ad:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator\/didClose(ad:)","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"type":"topic","title":"TeadsInReadAd","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAd","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TeadsInReadAd","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsinreadad","abstract":[{"type":"text","text":"A TeadsInReadAd represents an InRead ad that will be binded to a "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","type":"reference","isActive":true},{"type":"text","text":" instance"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd":{"role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","abstract":[{"type":"text","text":"Root Ad Object inherited by "},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","type":"reference"},{"type":"text","text":" & "},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","type":"reference"}],"title":"TeadsAd","kind":"symbol","url":"\/documentation\/teadssdk\/teadsad","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAd"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAd"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"type":"topic","title":"TeadsInReadAdView","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdView"}],"url":"\/documentation\/teadssdk\/teadsinreadadview","abstract":[{"text":"The Teads inRead ad view is responsible to manage a Teads inRead ad.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/Coordinator":{"kind":"symbol","title":"TeadsNative.AdView.Coordinator","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator","url":"\/documentation\/teadssdk\/teadsnative\/adview\/coordinator","type":"topic","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/Coordinator/didClose(ad:)":{"title":"didClose(ad:)","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator\/didClose(ad:)","abstract":[{"text":"Called when the ad has been close, in this case you need to close the slot or you will have a blank space.","type":"text"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsnative\/adview\/coordinator\/didclose(ad:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClose"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier","text":"TeadsAd"},{"kind":"text","text":")"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"url":"\/documentation\/teadssdk\/teadsnativead","abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"type":"topic","title":"TeadsNativeAd","kind":"symbol","navigatorTitle":[{"text":"TeadsNativeAd","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","title":"TeadsNative","url":"\/documentation\/teadssdk\/teadsnative","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView":{"navigatorTitle":[{"kind":"identifier","text":"AdView"}],"title":"TeadsNative.AdView","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdView"}],"abstract":[{"type":"text","text":"The AdView is responsible to manage manage a Teads native ad."}],"url":"\/documentation\/teadssdk\/teadsnative\/adview","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title","value":"TeadsInReadAd"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAd"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle","op":"replace","value":[{"text":"TeadsInReadAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/title","op":"replace","value":"TeadsAd"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/fragments","op":"replace","value":[{"text":"TeadsAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAd"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","op":"replace","value":"TeadsInReadAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdView"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdView"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title","op":"replace","value":"TeadsNativeAd"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAd"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}