{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/View"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/View\/bind(component:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonComponent","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"},{"text":"?) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/teadssdk\/swiftuicore\/view\/bind(component:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"relatedModules":["SwiftUICore"],"name":"TeadsSDK"}],"roleHeading":"Instance Method","title":"bind(component:)","externalID":"s:7SwiftUI4ViewP8TeadsSDKE4bind9componentxAD15CommonComponentCSg_tF","role":"symbol","platforms":[{"deprecated":false,"introducedAt":"13.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"13.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"13.0","beta":false,"name":"Mac Catalyst","unavailable":false}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonComponent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"},{"text":"?) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"extendedModule":"SwiftUICore"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore":{"abstract":[],"title":"SwiftUICore","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore","url":"\/documentation\/teadssdk\/swiftuicore","kind":"symbol","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore/View/bind(component:)":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/View\/bind(component:)","url":"\/documentation\/teadssdk\/swiftuicore\/view\/bind(component:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","kind":"typeIdentifier","text":"CommonComponent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"bind(component:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore/View":{"navigatorTitle":[{"kind":"identifier","text":"View"}],"abstract":[],"title":"View","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/View","url":"\/documentation\/teadssdk\/swiftuicore\/view","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"kind":"symbol","url":"\/documentation\/teadssdk\/commoncomponent","role":"symbol","abstract":[{"type":"text","text":"Native Root Component"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommonComponent"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"title":"CommonComponent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CommonComponent","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title"},{"value":[{"kind":"identifier","text":"CommonComponent"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments"},{"value":[{"text":"CommonComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle"}]}]}