{"metadata":{"role":"symbol","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementMedia(im)initWithPid:articleUrl:enableValidationMode:delegate:","symbolKind":"init","title":"init(pid:articleUrl:enableValidationMode:delegate:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithPid:articleUrl:enableValidationMode:delegate:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"articleUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"enableValidationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"TeadsSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"pid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"articleUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"enableValidationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:enableValidationMode:delegate:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/init(pid:articleurl:enablevalidationmode:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/init(pid:articleurl:enablevalidationmode:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/init(pid:articleUrl:enableValidationMode:delegate:)":{"abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"articleUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"enableValidationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"initWithPid:articleUrl:enableValidationMode:delegate:","kind":"identifier"}],"title":"init(pid:articleUrl:enableValidationMode:delegate:)","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/init(pid:articleurl:enablevalidationmode:delegate:)","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:enableValidationMode:delegate:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"title":"TeadsAdPlacementEventsDelegate","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"title":"TeadsAdPlacementMedia","url":"\/documentation\/teadssdk\/teadsadplacementmedia","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithPid:articleUrl:enableValidationMode:delegate:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPid:articleUrl:enableValidationMode:delegate:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pid"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"articleUrl"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableValidationMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enableValidationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<TeadsAdPlacementEventsDelegate>","preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithPid:articleUrl:enableValidationMode:delegate:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1init(pid:articleUrl:enableValidationMode:delegate:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPid:articleUrl:enableValidationMode:delegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1init(pid:articleUrl:enableValidationMode:delegate:)\/fragments","op":"replace"},{"value":"TeadsAdPlacementEventsDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title","op":"replace"},{"value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments","op":"replace"},{"value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle","op":"replace"},{"value":"TeadsAdPlacementMedia","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments","op":"replace"},{"value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle","op":"replace"}]}]}