{"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/teadsadplacementdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/teadsadplacementdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"article","metadata":{"roleHeading":"API Collection","modules":[{"name":"TeadsSDK"}],"role":"collectionGroup","title":"TeadsAdPlacementDelegate Implementations"},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsAdPlacementDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/adOpportunityTrackerView(trackerView:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/didFailToReceiveAd(reason:)"],"title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/adOpportunityTrackerView(trackerView:)":{"title":"adOpportunityTrackerView(trackerView:)","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/adopportunitytrackerview(trackerview:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adOpportunityTrackerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackerView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/adOpportunityTrackerView(trackerView:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"title":"TeadsAdPlacementMedia","url":"\/documentation\/teadssdk\/teadsadplacementmedia","type":"topic","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/didFailToReceiveAd(reason:)":{"role":"symbol","title":"didFailToReceiveAd(reason:)","abstract":[{"type":"text","text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter"}],"navigatorTitle":[{"text":"didFailToReceiveAdWithReason:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/didfailtoreceivead(reason:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason","text":"AdFailReason"},{"kind":"text","text":")"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/didFailToReceiveAd(reason:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/adOpportunityTrackerView(trackerView:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/didFailToReceiveAd(reason:)"],"generated":true}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"adOpportunityTrackerViewWithTrackerView:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1adOpportunityTrackerView(trackerView:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1adOpportunityTrackerView(trackerView:)\/fragments"},{"op":"replace","value":"TeadsAdPlacementMedia","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments"},{"op":"replace","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle"},{"op":"replace","value":"didFailToReceiveAdWithReason:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1didFailToReceiveAd(reason:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFailToReceiveAdWithReason:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1didFailToReceiveAd(reason:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}