{"abstract":[{"text":"Default implementation that delegates to loadAd()","type":"text"},{"text":" ","type":"text"},{"text":"This maintains consistency with the existing TeadsAdPlacementProtocol pattern","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/uiViewResult"},"metadata":{"modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uiViewResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ViewType","preciseIdentifier":"s:8TeadsSDK0A15UIViewPlacementP8ViewTypeQa","kind":"typeIdentifier"}],"extendedModule":"TeadsSDK","role":"symbol","conformance":{"constraints":[{"type":"codeVoice","code":"PlacementResult"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"Self.ViewType"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"externalID":"s:8TeadsSDK0A15UIViewPlacementPAA8ViewTypeQz0D6ResultRtzrlE02uieG0AGvp::SYNTHESIZED::c:@M@TeadsSDK@objc(cs)TeadsAdPlacementMedia","title":"uiViewResult","roleHeading":"Instance Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"]]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/uiviewresult"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiViewResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement\/ViewType","text":"ViewType","preciseIdentifier":"s:8TeadsSDK0A15UIViewPlacementP8ViewTypeQa"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/uiViewResult":{"title":"uiViewResult","type":"topic","abstract":[{"text":"Default implementation that delegates to loadAd()","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This maintains consistency with the existing TeadsAdPlacementProtocol pattern"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uiViewResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ViewType","preciseIdentifier":"s:8TeadsSDK0A15UIViewPlacementP8ViewTypeQa","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/uiviewresult","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/uiViewResult","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"PlacementResult"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"Self.ViewType"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsUIViewPlacement/ViewType":{"url":"\/documentation\/teadssdk\/teadsuiviewplacement\/viewtype","abstract":[{"type":"text","text":"The specific UIView type this placement returns"},{"type":"text","text":" "},{"type":"text","text":"Must be a subclass or composition that includes UIView"}],"type":"topic","fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement\/ViewType","title":"ViewType"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"title":"TeadsAdPlacementMedia","url":"\/documentation\/teadssdk\/teadsadplacementmedia","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title","value":"TeadsAdPlacementMedia"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}