{"abstract":[{"text":"The specific UIView type this placement returns","type":"text"},{"text":" ","type":"text"},{"text":"Must be a subclass or composition that includes UIView","type":"text"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/viewtype"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewType"},{"kind":"text","text":" = "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/ViewType"},"metadata":{"symbolKind":"typealias","roleHeading":"Type Alias","modules":[{"name":"TeadsSDK"}],"title":"TeadsAdPlacementMedia.ViewType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewType"}],"role":"symbol","navigatorTitle":[{"text":"ViewType","kind":"identifier"}],"externalID":"s:8TeadsSDK0A16AdPlacementMediaC8ViewTypea"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/ViewType":{"abstract":[{"type":"text","text":"The specific UIView type this placement returns"},{"type":"text","text":" "},{"type":"text","text":"Must be a subclass or composition that includes UIView"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewType","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/viewtype","navigatorTitle":[{"text":"ViewType","kind":"identifier"}],"title":"TeadsAdPlacementMedia.ViewType","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/ViewType"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"title":"TeadsAdPlacementMedia","url":"\/documentation\/teadssdk\/teadsadplacementmedia","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title","value":"TeadsAdPlacementMedia","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"op":"replace"}]}]}