{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/willMove(toWindow:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","title":"willMove(toWindow:)","navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView(im)willMoveToWindow:","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willMove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toWindow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willMove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toWindow","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"newWindow","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsinreadadview\/willmove(towindow:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsinreadadview\/willmove(towindow:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/willMove(toWindow:)":{"navigatorTitle":[{"text":"willMoveToWindow:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/willMove(toWindow:)","url":"\/documentation\/teadssdk\/teadsinreadadview\/willmove(towindow:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willMove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toWindow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"willMove(toWindow:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"type":"topic","title":"TeadsInReadAdView","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdView"}],"url":"\/documentation\/teadssdk\/teadsinreadadview","abstract":[{"text":"The Teads inRead ad view is responsible to manage a Teads inRead ad.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willMoveToWindow:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"willMoveToWindow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"newWindow","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1willMove(toWindow:)\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1willMove(toWindow:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToWindow:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","value":"TeadsInReadAdView"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","value":[{"text":"TeadsInReadAdView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsInReadAdView"}]}]}]}