{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bind:tagBinder:"}],"modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView(im)bind:tagBinder:","roleHeading":"Instance Method","symbolKind":"method","title":"bind(_:tagBinder:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bind","kind":"identifier"},{"kind":"text","text":"("},{"text":"TeadsNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd"},{"kind":"text","text":", "},{"text":"tagBinder","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","text":"TagBinderBuilder"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"abstract":[{"type":"text","text":"Binds the native asset ad views to this native ad using view tags binder"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)"]},{"paths":["\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"ad"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tagBinder"},{"kind":"text","text":": ("},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","kind":"typeIdentifier","text":"TagBinderBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ad that should be binded to the ad view.","type":"text"}]}],"name":"ad"},{"name":"tagBinder","content":[{"inlineContent":[{"type":"text","text":"Binds the native asset ad views to this native ad using view tags."}],"type":"paragraph"}]}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Specify a unique ","type":"text"},{"code":"tag","type":"codeVoice"},{"type":"text","text":" value for each UI element on InterfaceBuilder: make sure to match them using builder"}]},{"syntax":null,"type":"codeListing","code":["adView.bind(ad) { builder in","    builder.titleLabelTag = 1","    builder.contentLabelTag = 2","    builder.mediaViewTag = 3","    builder.iconImageViewTag = 4","    builder.callToActionButtonTag = 5","    builder.advertiserLabelTag = 6","}"]}],"kind":"content"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"title":"TeadsNativeAdView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdView"}],"abstract":[{"type":"text","text":"The Teads native ad view is responsible to manage a Teads native ad."}],"url":"\/documentation\/teadssdk\/teadsnativeadview","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"title":"TeadsNativeAd","url":"\/documentation\/teadssdk\/teadsnativead","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAd"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsNativeAd","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","title":"TagBinderBuilder","abstract":[{"text":"This builder allows you to bind UI elements programmatically using ","type":"text"},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","isActive":true}],"role":"symbol","url":"\/documentation\/teadssdk\/tagbinderbuilder","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagBinderBuilder"}],"navigatorTitle":[{"text":"TagBinderBuilder","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:tagBinder:)":{"title":"bind(_:tagBinder:)","role":"symbol","abstract":[{"type":"text","text":"Binds the native asset ad views to this native ad using view tags binder"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","navigatorTitle":[{"text":"bind:tagBinder:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tagBinder","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","kind":"typeIdentifier","text":"TagBinderBuilder"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bind:tagBinder:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bind:tagBinder:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"bind:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","text":"TeadsNativeAd"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ad"},{"text":" ","kind":"text"},{"text":"tagBinder:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","text":"TagBinderBuilder"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"tagBinder","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ad that should be binded to the ad view."}]}]},{"name":"tagBinder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Binds the native asset ad views to this native ad using view tags."}]}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title","op":"replace","value":"TeadsNativeAdView"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsNativeAdView"}],"op":"replace"},{"value":"TeadsNativeAd","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments","value":[{"kind":"identifier","text":"TeadsNativeAd"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle","value":[{"text":"TeadsNativeAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/title","value":"TagBinderBuilder"},{"value":[{"text":"TagBinderBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/fragments","op":"replace"},{"value":[{"text":"TagBinderBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/title","value":"bind:tagBinder:"},{"value":[{"text":"- ","kind":"text"},{"text":"bind:tagBinder:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}