{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleAspectFit"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Behaviour is similar to "},{"type":"codeVoice","code":"UIView.ContentMode.scaleAspectFit"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/mediascale\/scaleaspectfit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/mediascale\/scaleaspectfit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contents scaled to fit with fixed aspect. remainder is transparent."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleAspectFit"}],"title":"MediaScale.scaleAspectFit","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TeadsSDK@E@MediaScale@MediaScaleScaleAspectFit","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MediaScaleScaleAspectFit"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale":{"role":"symbol","title":"MediaScale","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaScale"}],"abstract":[{"type":"text","text":"A flag used to determine how TeadsMediaView lays out its content when its bounds change."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaScale"}],"url":"\/documentation\/teadssdk\/mediascale"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale/scaleAspectFit":{"role":"symbol","title":"MediaScale.scaleAspectFit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleAspectFit"}],"abstract":[{"type":"text","text":"Contents scaled to fit with fixed aspect. remainder is transparent."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaScaleScaleAspectFit"}],"url":"\/documentation\/teadssdk\/mediascale\/scaleaspectfit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MediaScaleScaleAspectFit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MediaScaleScaleAspectFit"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MediaScaleScaleAspectFit"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/title","value":"MediaScale"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/fragments","value":[{"kind":"identifier","text":"MediaScale"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale~1scaleAspectFit\/title","value":"MediaScaleScaleAspectFit"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale~1scaleAspectFit\/fragments","value":[{"kind":"identifier","text":"MediaScaleScaleAspectFit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}