{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUI\/Button\/init(component:default:label:)"},"metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"s:7SwiftUI6ButtonV8TeadsSDKE9component7default5labelACyxGSgAD15CommonComponentCSg_SSSgxSSXEtcfc","modules":[{"relatedModules":["SwiftUI"],"name":"TeadsSDK"}],"extendedModule":"SwiftUI","platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"13.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"13.0","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.0","unavailable":false}],"title":"init(component:default:label:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","kind":"typeIdentifier","text":"CommonComponent"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"default"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"label"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7SwiftUI6ButtonV8TeadsSDKE5Labelxmfp","kind":"typeIdentifier","text":"Label"},{"kind":"text","text":")"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Label"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"View"},{"type":"text","text":"."}]}},"variants":[{"paths":["\/documentation\/teadssdk\/swiftui\/button\/init(component:default:label:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"if default value is not provided and component does not contains text value, init will fail by returning a nil value, this will ensure Button UI element is not displayed"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","text":"CommonComponent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"},{"text":"?, ","kind":"text"},{"text":"default","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"defaultText","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"ViewBuilder","kind":"attribute","preciseIdentifier":"s:7SwiftUI11ViewBuilderV"},{"text":" ","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Label","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI6ButtonV8TeadsSDKE5Labelxmfp"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUI","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUI\/Button"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUI/Button":{"abstract":[],"url":"\/documentation\/teadssdk\/swiftui\/button","type":"topic","title":"Button","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUI\/Button","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7SwiftUI6ButtonV","text":"Button"}],"navigatorTitle":[{"kind":"identifier","text":"Button"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUI/Button/init(component:default:label:)":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Label","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"View","type":"codeVoice"},{"text":".","type":"text"}]},"abstract":[{"text":"if default value is not provided and component does not contains text value, init will fail by returning a nil value, this will ensure Button UI element is not displayed","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/swiftui\/button\/init(component:default:label:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"default","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Label","preciseIdentifier":"s:7SwiftUI6ButtonV8TeadsSDKE5Labelxmfp","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(component:default:label:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUI\/Button\/init(component:default:label:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUI":{"url":"\/documentation\/teadssdk\/swiftui","type":"topic","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUI","title":"SwiftUI"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"title":"CommonComponent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonComponent"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","kind":"symbol","url":"\/documentation\/teadssdk\/commoncomponent","abstract":[{"text":"Native Root Component","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"CommonComponent","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title"},{"value":[{"text":"CommonComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments"},{"value":[{"kind":"identifier","text":"CommonComponent"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}