{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didexpandedtofullscreen(ad:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator"]]},"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didExpandedToFullscreen(ad:)","interfaceLanguage":"swift"},"metadata":{"title":"didExpandedToFullscreen(ad:)","symbolKind":"method","roleHeading":"Instance Method","externalID":"s:8TeadsSDK0A6InReadV6AdViewV11CoordinatorC23didExpandedToFullscreen2adyAA0aE0C_tF","platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didExpandedToFullscreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"TeadsSDK"}],"role":"symbol"},"abstract":[{"text":"Called when an ad is shown in fullscreen.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didExpandedToFullscreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"_","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TeadsAd","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"text":"The ad that is shown in fullscreen.","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAd"}],"abstract":[{"text":"A TeadsInReadAd represents an InRead ad that will be binded to a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","type":"reference"},{"text":" instance","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAd"}],"type":"topic","role":"symbol","title":"TeadsInReadAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","url":"\/documentation\/teadssdk\/teadsinreadad"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd":{"navigatorTitle":[{"kind":"identifier","text":"TeadsAd"}],"url":"\/documentation\/teadssdk\/teadsad","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAd"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","title":"TeadsAd","abstract":[{"type":"text","text":"Root Ad Object inherited by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd"},{"type":"text","text":" & "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead":{"navigatorTitle":[{"kind":"identifier","text":"TeadsInRead"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInRead"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","title":"TeadsInRead","url":"\/documentation\/teadssdk\/teadsinread"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didExpandedToFullscreen(ad:)":{"role":"symbol","type":"topic","title":"didExpandedToFullscreen(ad:)","abstract":[{"text":"Called when an ad is shown in fullscreen.","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didExpandedToFullscreen(ad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didExpandedToFullscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd"},{"kind":"text","text":")"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didexpandedtofullscreen(ad:)","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"title":"TeadsInRead.AdView.Coordinator","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator","kind":"symbol","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView":{"title":"TeadsInRead.AdView","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdView","kind":"identifier"}],"navigatorTitle":[{"text":"AdView","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsNativeAd","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativead","kind":"symbol","title":"TeadsNativeAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TeadsInReadAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle"},{"op":"replace","value":"TeadsAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/title"},{"op":"replace","value":[{"text":"TeadsAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/navigatorTitle"},{"op":"replace","value":"TeadsNativeAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"}]}]}