{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateRatio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd","kind":"typeIdentifier","text":"TeadsInReadAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adRatio"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","kind":"typeIdentifier","text":"TeadsAdRatio"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"text":"The teadsAd object","type":"text"}]}]},{"name":"adRatio","content":[{"type":"paragraph","inlineContent":[{"text":"An object that will help you display the ad correctly","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"When it called it is the right place to update your view ratio. A basic implementation may look litke this:","type":"text"}]},{"type":"codeListing","code":["func didUpdateRatio(ad: TeadsInReadAd, adRatio: TeadsAdRatio) {","    yourViewHeight = adRatio.calculateHeight(for: yourViewWidth)","}"],"syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"Alternatively you can call "},{"type":"codeVoice","code":"adRatio.value(for:)"},{"type":"text","text":" to set multiplier constraint"}]},{"type":"codeListing","code":["func didUpdateRatio(ad: TeadsInReadAd, adRatio: TeadsAdRatio) {","    let multiplier = adRatio.value(for: yourViewWidth)","    \/\/ create constaint with `multiplier and replace it with exisiting one","}"],"syntax":null}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didUpdateRatio(ad:adRatio:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"s:8TeadsSDK0A6InReadV6AdViewV11CoordinatorC14didUpdateRatio2ad0kJ0yAA0acdE0C_AA0aeJ0CtF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":")","kind":"text"}],"title":"didUpdateRatio(ad:adRatio:)","modules":[{"name":"TeadsSDK"}],"platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didupdateratio(ad:adratio:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Called when the Teads SDK needs you to resize your adView the creative inform us of its new ratio"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView":{"title":"TeadsInRead.AdView","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdView","kind":"identifier"}],"navigatorTitle":[{"text":"AdView","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"title":"TeadsInRead.AdView.Coordinator","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator","kind":"symbol","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead":{"navigatorTitle":[{"kind":"identifier","text":"TeadsInRead"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInRead"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","title":"TeadsInRead","url":"\/documentation\/teadssdk\/teadsinread"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didUpdateRatio(ad:adRatio:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didUpdateRatio(ad:adRatio:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called when the Teads SDK needs you to resize your adView the creative inform us of its new ratio"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didupdateratio(ad:adratio:)","kind":"symbol","role":"symbol","title":"didUpdateRatio(ad:adRatio:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"kind":"symbol","url":"\/documentation\/teadssdk\/teadsinreadadview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"type":"topic","role":"symbol","title":"TeadsInReadAdView","navigatorTitle":[{"text":"TeadsInReadAdView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAd"}],"abstract":[{"text":"A TeadsInReadAd represents an InRead ad that will be binded to a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","type":"reference"},{"text":" instance","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAd"}],"type":"topic","role":"symbol","title":"TeadsInReadAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","url":"\/documentation\/teadssdk\/teadsinreadad"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","navigatorTitle":[{"text":"TeadsAdRatio","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadratio","abstract":[{"text":"This class is used to help in resizing a given ad view to a given aspect ratio.","type":"text"}],"title":"TeadsAdRatio","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRatio","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","value":"TeadsInReadAdView","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdView"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title","value":"TeadsInReadAd","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle","value":[{"text":"TeadsInReadAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/title","value":"TeadsAdRatio","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/fragments","value":[{"kind":"identifier","text":"TeadsAdRatio"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/navigatorTitle","value":[{"text":"TeadsAdRatio","kind":"identifier"}],"op":"replace"}]}]}