{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","interfaceLanguage":"swift"},"abstract":[{"text":"The Teads native ad view is responsible to manage a Teads native ad.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/advertiserLabel","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/callToActionButton","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/contentLabel","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/iconImageView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/mediaView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/priceLabel","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/ratingView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/titleLabel"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TeadsNativeAdView","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnativeadview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsnativeadview"]}],"metadata":{"title":"TeadsNativeAdView","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsNativeAdView","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","externalID":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"url":"\/documentation\/teadssdk\/teadsinreadadview","type":"topic","title":"TeadsInReadAdView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TeadsInReadAdView","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsInReadAdView","kind":"identifier"}],"abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearance":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/initWithFrame:":{"role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"kind":"symbol","title":"initWithFrame:","url":"\/documentation\/teadssdk\/teadsnativeadview\/initwithframe:"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"abstract":[{"type":"text","text":"The Teads native ad view is responsible to manage a Teads native ad."}],"url":"\/documentation\/teadssdk\/teadsnativeadview","type":"topic","title":"TeadsNativeAdView","navigatorTitle":[{"text":"TeadsNativeAdView","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdView","kind":"identifier"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/titleLabel":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/titleLabel","url":"\/documentation\/teadssdk\/teadsnativeadview\/titlelabel","abstract":[{"text":"The native ad title label.","type":"text"}],"title":"titleLabel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/initWithCoder:":{"url":"\/documentation\/teadssdk\/teadsnativeadview\/initwithcoder:","type":"topic","title":"initWithCoder:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/initWithCoder:"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/ratingView":{"url":"\/documentation\/teadssdk\/teadsnativeadview\/ratingview","abstract":[{"text":"The native ad rating view.","type":"text"}],"kind":"symbol","title":"ratingView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ratingView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ratingView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/ratingView","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/callToActionButton":{"role":"symbol","navigatorTitle":[{"text":"callToActionButton","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The native ad call to action button."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/callToActionButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callToActionButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"kind":"text","text":"?"}],"kind":"symbol","title":"callToActionButton","url":"\/documentation\/teadssdk\/teadsnativeadview\/calltoactionbutton"},"doc://tv.teads.TeadsSDK.TeadsSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:)":{"url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:)","type":"topic","title":"bind(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"bind:","kind":"identifier"}],"abstract":[{"text":"Call this function to bind a native ad to your native ad view.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:tagBinder:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"text":"TeadsNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tagBinder"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","text":"TagBinderBuilder"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"title":"bind(_:tagBinder:)","navigatorTitle":[{"kind":"identifier","text":"bind:tagBinder:"}],"role":"symbol","url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","abstract":[{"type":"text","text":"Binds the native asset ad views to this native ad using view tags binder"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s8SendableP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/mediaView":{"url":"\/documentation\/teadssdk\/teadsnativeadview\/mediaview","type":"topic","title":"mediaView","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mediaView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsMediaView","kind":"typeIdentifier","text":"TeadsMediaView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"mediaView"}],"abstract":[{"text":"The native ad media view (for images and videos).","type":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/mediaView"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdView":{"role":"symbol","navigatorTitle":[{"text":"TeadsAdView","kind":"identifier"}],"type":"topic","abstract":[{"text":"Root view inherited by ","type":"text"},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","isActive":true},{"type":"text","text":" & "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","isActive":true}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdView"}],"kind":"symbol","title":"TeadsAdView","url":"\/documentation\/teadssdk\/teadsadview"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/contentLabel":{"url":"\/documentation\/teadssdk\/teadsnativeadview\/contentlabel","type":"topic","title":"contentLabel","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"contentLabel","kind":"identifier"}],"abstract":[{"type":"text","text":"The native ad content \/ body \/ description label."}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/contentLabel"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/priceLabel":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"priceLabel"}],"type":"topic","abstract":[{"type":"text","text":"The native ad price label."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/priceLabel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"},{"text":"?","kind":"text"}],"kind":"symbol","title":"priceLabel","url":"\/documentation\/teadssdk\/teadsnativeadview\/pricelabel"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/advertiserLabel":{"url":"\/documentation\/teadssdk\/teadsnativeadview\/advertiserlabel","type":"topic","title":"advertiserLabel","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertiserLabel"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"advertiserLabel"}],"abstract":[{"text":"The native ad advertiser \/ sponsored label.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/advertiserLabel"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/iconImageView":{"url":"\/documentation\/teadssdk\/teadsnativeadview\/iconimageview","type":"topic","title":"iconImageView","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"iconImageView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"iconImageView"}],"abstract":[{"text":"The native ad icon \/ logo image view.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/iconImageView"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"TeadsNativeAdView","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdView"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/advertiserLabel","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/callToActionButton","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/contentLabel","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/iconImageView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/mediaView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/priceLabel","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/ratingView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/titleLabel"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/initWithCoder:","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/initWithFrame:"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"TeadsNativeAdView","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView","text":"TeadsAdView","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","value":"TeadsInReadAdView"},{"op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments"},{"value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","op":"replace"},{"value":"TeadsNativeAdView","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments","value":[{"kind":"identifier","text":"TeadsNativeAdView"}]},{"value":[{"text":"TeadsNativeAdView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle"},{"value":"titleLabel","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1titleLabel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"value":"ratingView","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1ratingView\/title"},{"value":[{"kind":"identifier","text":"ratingView"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1ratingView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1callToActionButton\/title","value":"callToActionButton"},{"value":[{"text":"callToActionButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1callToActionButton\/fragments"},{"value":"bind:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:)\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bind:"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/title","value":"bind:tagBinder:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bind:tagBinder:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/fragments"},{"value":"mediaView","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1mediaView\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1mediaView\/fragments","value":[{"text":"mediaView","kind":"identifier"}],"op":"replace"},{"value":"TeadsAdView","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/title"},{"op":"replace","value":[{"text":"TeadsAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdView"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1contentLabel\/title","op":"replace","value":"contentLabel"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1contentLabel\/fragments","op":"replace","value":[{"text":"contentLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1priceLabel\/title","value":"priceLabel","op":"replace"},{"value":[{"kind":"identifier","text":"priceLabel"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1priceLabel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1advertiserLabel\/title","op":"replace","value":"advertiserLabel"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1advertiserLabel\/fragments","value":[{"text":"advertiserLabel","kind":"identifier"}]},{"op":"replace","value":"iconImageView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1iconImageView\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1iconImageView\/fragments","value":[{"text":"iconImageView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}