{"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didCatchError(ad:error:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didClose(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didCollapsedFromFullscreen(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didExpandedToFullscreen(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didRecordClick(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didRecordImpression(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didTerminate(requestIdentifier:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/willPresentModalView(ad:)"],"title":"Instance Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate"},"abstract":[{"text":"Delegate methods needed to follow Teads ads lifecycle.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsAdDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"TeadsAdDelegate","symbolKind":"protocol","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"TeadsAdDelegate","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@objc(pl)TeadsAdDelegate","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdDelegate"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsaddelegate"]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/didCatchError(ad:error:)":{"url":"\/documentation\/teadssdk\/teadsaddelegate\/didcatcherror(ad:error:)","title":"didCatchError(ad:error:)","abstract":[{"type":"text","text":"Called when the ad has encountered an issue, in this case you need to remove the slot or you will have a blank space."}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didCatchError(ad:error:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCatchError","kind":"identifier"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didCatchErrorWithAd:error:","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/didExpandedToFullscreen(ad:)":{"url":"\/documentation\/teadssdk\/teadsaddelegate\/didexpandedtofullscreen(ad:)","role":"symbol","title":"didExpandedToFullscreen(ad:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"didExpandedToFullscreenWithAd:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didExpandedToFullscreen"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called when an ad is shown in fullscreen."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didExpandedToFullscreen(ad:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/didTerminate(requestIdentifier:)":{"type":"topic","required":true,"url":"\/documentation\/teadssdk\/teadsaddelegate\/didterminate(requestidentifier:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didTerminate","kind":"identifier"},{"kind":"text","text":"("},{"text":"requestIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when an ad is terminated (deinit)"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didTerminate(requestIdentifier:)","role":"symbol","kind":"symbol","title":"didTerminate(requestIdentifier:)","navigatorTitle":[{"kind":"identifier","text":"didTerminateWithRequestIdentifier:"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/didRecordClick(ad:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didRecordClick"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsaddelegate\/didrecordclick(ad:)","navigatorTitle":[{"text":"didRecordClickWithAd:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when Teads has recorded a clickthrough on an ad."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didRecordClick(ad:)","title":"didRecordClick(ad:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/willPresentModalView(ad:)":{"title":"willPresentModalView(ad:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/willPresentModalView(ad:)","abstract":[{"type":"text","text":"Called when an ad wants to present a view controller modally (e.g. safariViewController for call to action or the full screen controller)."}],"type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentModalView"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TeadsAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsaddelegate\/willpresentmodalview(ad:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"willPresentModalViewWithAd:"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate":{"role":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsaddelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads ads lifecycle."}],"title":"TeadsAdDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdDelegate","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate","navigatorTitle":[{"text":"TeadsAdDelegate","kind":"identifier"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/didClose(ad:)":{"url":"\/documentation\/teadssdk\/teadsaddelegate\/didclose(ad:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"didCloseWithAd:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Called when the ad has been close, in this case you need to close the slot or you will have a blank space."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didClose(ad:)","title":"didClose(ad:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/didRecordImpression(ad:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didRecordImpression(ad:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didRecordImpression"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ad"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}],"abstract":[{"text":"Called when the Teads SDK has recorded an impression for an ad.","type":"text"}],"navigatorTitle":[{"text":"didRecordImpressionWithAd:","kind":"identifier"}],"title":"didRecordImpression(ad:)","kind":"symbol","role":"symbol","url":"\/documentation\/teadssdk\/teadsaddelegate\/didrecordimpression(ad:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/didCollapsedFromFullscreen(ad:)":{"url":"\/documentation\/teadssdk\/teadsaddelegate\/didcollapsedfromfullscreen(ad:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCollapsedFromFullscreen"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"didCollapsedFromFullscreen(ad:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didCollapsedFromFullscreen(ad:)","abstract":[{"type":"text","text":"Called when an ad leaves the fullscreen mode."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"didCollapsedFromFullscreenWithAd:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"TeadsAdDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"TeadsAdDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdDelegate","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didCatchError(ad:error:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didClose(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didCollapsedFromFullscreen(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didExpandedToFullscreen(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didRecordClick(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didRecordImpression(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didTerminate(requestIdentifier:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/willPresentModalView(ad:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdDelegate"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didCatchError(ad:error:)\/title","value":"didCatchErrorWithAd:error:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didCatchErrorWithAd:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didCatchError(ad:error:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didExpandedToFullscreen(ad:)\/title","value":"didExpandedToFullscreenWithAd:"},{"value":[{"text":"- ","kind":"text"},{"text":"didExpandedToFullscreenWithAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didExpandedToFullscreen(ad:)\/fragments"},{"op":"replace","value":"didTerminateWithRequestIdentifier:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didTerminate(requestIdentifier:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didTerminate(requestIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTerminateWithRequestIdentifier:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didRecordClick(ad:)\/title","value":"didRecordClickWithAd:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"didRecordClickWithAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didRecordClick(ad:)\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1willPresentModalView(ad:)\/title","op":"replace","value":"willPresentModalViewWithAd:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1willPresentModalView(ad:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willPresentModalViewWithAd:","kind":"identifier"}],"op":"replace"},{"value":"TeadsAdDelegate","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/title"},{"value":[{"text":"TeadsAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/fragments"},{"value":[{"text":"TeadsAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/navigatorTitle"},{"value":"didCloseWithAd:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didClose(ad:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didClose(ad:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didCloseWithAd:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didRecordImpression(ad:)\/title","value":"didRecordImpressionWithAd:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didRecordImpression(ad:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didRecordImpressionWithAd:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didCollapsedFromFullscreen(ad:)\/title","value":"didCollapsedFromFullscreenWithAd:"},{"value":[{"kind":"text","text":"- "},{"text":"didCollapsedFromFullscreenWithAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didCollapsedFromFullscreen(ad:)\/fragments","op":"replace"}]}]}