{"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStartPlayingAudio(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStopPlayingAudio(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didComplete(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didPause(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didPlay(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate"},"abstract":[{"text":"Delegate methods sending informations about Teads ads playback states.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@TeadsSDK@objc(pl)TeadsPlaybackDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}],"role":"symbol","title":"TeadsPlaybackDelegate","modules":[{"name":"TeadsSDK"}],"roleHeading":"Protocol","symbolKind":"protocol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsplaybackdelegate"]},{"paths":["\/documentation\/teadssdk\/teadsplaybackdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}],"abstract":[{"text":"Delegate methods sending informations about Teads ads playback states.","type":"text"}],"title":"TeadsPlaybackDelegate","url":"\/documentation\/teadssdk\/teadsplaybackdelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/adStopPlayingAudio(_:)":{"role":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/adstopplayingaudio(_:)","abstract":[{"type":"text","text":"Called when an ad stops playing audio."}],"title":"adStopPlayingAudio(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adStopPlayingAudio"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"kind":"text","text":")"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStopPlayingAudio(_:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"adStopPlayingAudio:"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/didPlay(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didPlay(_:)","required":true,"navigatorTitle":[{"text":"didPlay:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/didplay(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didPlay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"type":"text","text":"Called when an ad has started or resumed."}],"title":"didPlay(_:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/didPause(_:)":{"abstract":[{"type":"text","text":"Called when an ad has been paused."}],"url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/didpause(_:)","type":"topic","title":"didPause(_:)","navigatorTitle":[{"kind":"identifier","text":"didPause:"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didPause(_:)","required":true,"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didPause","kind":"identifier"},{"kind":"text","text":"("},{"text":"TeadsAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/didComplete(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didComplete"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"didComplete:"}],"kind":"symbol","abstract":[{"type":"text","text":"Called when an ad has ended."}],"required":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didComplete(_:)","role":"symbol","title":"didComplete(_:)","type":"topic","url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/didcomplete(_:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/adStartPlayingAudio(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adStartPlayingAudio","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"adStartPlayingAudio:"}],"kind":"symbol","abstract":[{"type":"text","text":"Called when an ad starts playing audio."}],"required":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStartPlayingAudio(_:)","role":"symbol","type":"topic","title":"adStartPlayingAudio(_:)","url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/adstartplayingaudio(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"TeadsPlaybackDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}]},{"value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStartPlayingAudio(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStopPlayingAudio(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didComplete(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didPause(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didPlay(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPlaybackDelegate","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"TeadsPlaybackDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}]},{"value":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1adStopPlayingAudio(_:)\/title","value":"adStopPlayingAudio:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1adStopPlayingAudio(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"adStopPlayingAudio:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didPlay(_:)\/title","value":"didPlay:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didPlay(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didPlay:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didPause(_:)\/title","value":"didPause:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didPause:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didPause(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didComplete(_:)\/title","value":"didComplete:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didComplete(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didComplete:","kind":"identifier"}]},{"value":"adStartPlayingAudio:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1adStartPlayingAudio(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adStartPlayingAudio:"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1adStartPlayingAudio(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}