{"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementrecommendations\/init(_:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:8TeadsSDK0A26AdPlacementRecommendationsC_8delegateAcA0acdE6Config_p_AA0acD14EventsDelegate_pSgtcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A32AdPlacementRecommendationsConfigP","text":"TeadsAdPlacementRecommendationsConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","title":"init(_:delegate:)","modules":[{"name":"TeadsSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A32AdPlacementRecommendationsConfigP","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendationsConfig","text":"TeadsAdPlacementRecommendationsConfig"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"TeadsAdPlacementProtocol.init(_:delegate:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendations"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendations\/init(_:delegate:)"},"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementRecommendations":{"navigatorTitle":[{"text":"TeadsAdPlacementRecommendations","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementRecommendations","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendations","role":"symbol","type":"topic","title":"TeadsAdPlacementRecommendations","kind":"symbol","abstract":[],"url":"\/documentation\/teadssdk\/teadsadplacementrecommendations"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementRecommendations/init(_:delegate:)":{"title":"init(_:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementRecommendationsConfig","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A32AdPlacementRecommendationsConfigP"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendations\/init(_:delegate:)","url":"\/documentation\/teadssdk\/teadsadplacementrecommendations\/init(_:delegate:)","type":"topic","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementRecommendationsConfig":{"abstract":[{"text":"Protocol for Recommendations placement configuration","type":"text"}],"title":"TeadsAdPlacementRecommendationsConfig","role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementRecommendationsConfig","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendationsConfig","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementrecommendationsconfig","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementRecommendationsConfig","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"abstract":[],"kind":"symbol","title":"TeadsAdPlacementEventsDelegate","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementRecommendations\/title","value":"TeadsAdPlacementRecommendations","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementRecommendations\/fragments","value":[{"text":"TeadsAdPlacementRecommendations","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementRecommendations\/navigatorTitle","value":[{"text":"TeadsAdPlacementRecommendations","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title","value":"TeadsAdPlacementEventsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}