{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/adchoicescomponent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/adchoicescomponent"]}],"kind":"symbol","sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@TeadsSDK@objc(cs)AdChoicesComponent","modules":[{"name":"TeadsSDK"}],"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"AdChoicesComponent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdChoicesComponent"}],"role":"symbol","title":"AdChoicesComponent"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl"],"generated":true,"anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdChoicesComponent"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Teads is partner of DAA "},{"identifier":"https:\/\/youradchoices.com\/participating#CompanyT","type":"reference","isActive":true}]},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"AdChoices component and associated logo is automatically added to ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","isActive":true,"type":"reference"}]}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Native Component containing AdChoices "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","isActive":true,"type":"reference"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent":{"url":"\/documentation\/teadssdk\/adchoicescomponent","navigatorTitle":[{"kind":"identifier","text":"AdChoicesComponent"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","type":"topic","abstract":[{"type":"text","text":"Native Component containing AdChoices "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","isActive":true}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdChoicesComponent"}],"title":"AdChoicesComponent"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent/clickThroughUrl":{"type":"topic","kind":"symbol","title":"clickThroughUrl","url":"\/documentation\/teadssdk\/adchoicescomponent\/clickthroughurl","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickThroughUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"Reach the URL that should be used when the ‘Ad Choices’ button is tapped."},{"type":"text","text":" "},{"type":"text","text":"Common behavior: open a Safari Web Browser with "},{"type":"codeVoice","code":"clickThroughUrl"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OverlayComponent":{"url":"\/documentation\/teadssdk\/overlaycomponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent","role":"symbol","abstract":[{"type":"text","text":"Native overlay component that could be put over playerView such as "},{"type":"strong","inlineContent":[{"type":"text","text":"AdChoices"}]},{"type":"text","text":" or "},{"type":"strong","inlineContent":[{"type":"text","text":"ClickToAction"}]}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverlayComponent","kind":"identifier"}],"title":"OverlayComponent","navigatorTitle":[{"text":"OverlayComponent","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","title":"Swift.Hashable"},"https://youradchoices.com/participating#CompanyT":{"type":"link","identifier":"https:\/\/youradchoices.com\/participating#CompanyT","title":"Digital Advertising Alliance","titleInlineContent":[{"type":"text","text":"Digital Advertising Alliance"}],"url":"https:\/\/youradchoices.com\/participating#CompanyT"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"role":"symbol","title":"TeadsNativeAdView","type":"topic","url":"\/documentation\/teadssdk\/teadsnativeadview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdView","kind":"identifier"}],"abstract":[{"text":"The Teads native ad view is responsible to manage a Teads native ad.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TeadsNativeAdView","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"AdChoicesComponent"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AdChoicesComponent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AdChoicesComponent","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdChoicesComponent","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OverlayComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent","text":"OverlayComponent"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/title","op":"replace","value":"AdChoicesComponent"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/fragments","op":"replace","value":[{"text":"AdChoicesComponent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/navigatorTitle","op":"replace","value":[{"text":"AdChoicesComponent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/title","op":"replace","value":"OverlayComponent"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/fragments","op":"replace","value":[{"text":"OverlayComponent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/navigatorTitle","op":"replace","value":[{"text":"OverlayComponent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title","op":"replace","value":"TeadsNativeAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments","op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle","op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}]}]}]}