{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnativeadrequestsettings"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Alias","role":"symbol","title":"TeadsNativeAdRequestSettings","modules":[{"name":"TeadsSDK"}],"externalID":"s:8TeadsSDK0A23NativeAdRequestSettingsa","symbolKind":"typealias","navigatorTitle":[{"text":"TeadsNativeAdRequestSettings","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdRequestSettings","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"abstract":[{"text":"Convenience closure typealias for ","type":"text"},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)","isActive":true}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdRequestSettings","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdRequestSettings"},{"kind":"text","text":" = "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings","kind":"typeIdentifier","text":"TeadsAdRequestSettings"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"title":"TeadsAdRequestSettings","abstract":[{"text":"Specify which settings you want to set for the related ad request.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdRequestSettings"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadrequestsettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement/requestAd(requestSettings:)":{"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"requestAdWithRequestSettings:"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement\/requestad(requestsettings:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)","type":"topic","title":"requestAd(requestSettings:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23NativeAdRequestSettingsa"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"abstract":[{"text":"Request a native ad on this placement","type":"text"},{"text":" ","type":"text"},{"text":"listen for events by implementing ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","type":"reference","isActive":true}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdRequestSettings":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdRequestSettings"}],"url":"\/documentation\/teadssdk\/teadsnativeadrequestsettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdRequestSettings","type":"topic","title":"TeadsNativeAdRequestSettings","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdRequestSettings"}],"abstract":[{"text":"Convenience closure typealias for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)","type":"reference"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"role":"symbol","title":"TeadsNativeAdPlacementDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","abstract":[{"text":"Delegate methods needed to follow Teads native ad requests flow","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title","op":"replace","value":"TeadsAdRequestSettings"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments","op":"replace","value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1requestAd(requestSettings:)\/title","op":"replace","value":"requestAdWithRequestSettings:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1requestAd(requestSettings:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestAdWithRequestSettings:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title","op":"replace","value":"TeadsNativeAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle","op":"replace","value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}