{"metadata":{"roleHeading":"Protocol","title":"TeadsLogMessageDelegate","navigatorTitle":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@objc(pl)TeadsLogMessageDelegate","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsLogMessageDelegate","kind":"identifier"}],"role":"symbol","symbolKind":"protocol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsLogMessageDelegate","kind":"identifier"}]}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate\/didLogMessage(message:)"],"generated":true,"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate"},"variants":[{"paths":["\/documentation\/teadssdk\/teadslogmessagedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadslogmessagedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherited By","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate"],"kind":"relationships","type":"inheritedBy"},{"title":"Conforming Types","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator"],"kind":"relationships","type":"conformingTypes"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Log delegate enabling you to route every log message written in console into a dedicated area of your choice"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsLogMessageDelegate/didLogMessage(message:)":{"kind":"symbol","title":"didLogMessage(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didLogMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/teadssdk\/teadslogmessagedelegate\/didlogmessage(message:)","navigatorTitle":[{"text":"didLogMessageWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate\/didLogMessage(message:)","type":"topic","abstract":[{"text":"Called each time TeadsSDK triggers a log message","type":"text"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/Coordinator":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"title":"TeadsNative.AdView.Coordinator","url":"\/documentation\/teadssdk\/teadsnative\/adview\/coordinator","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator","abstract":[],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsLogMessageDelegate":{"role":"symbol","kind":"symbol","title":"TeadsLogMessageDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","type":"topic","url":"\/documentation\/teadssdk\/teadslogmessagedelegate","navigatorTitle":[{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"abstract":[{"type":"text","text":"Log delegate enabling you to route every log message written in console into a dedicated area of your choice"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator":{"role":"symbol","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator","kind":"symbol","title":"TeadsInRead.AdView.Coordinator","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"title":"TeadsAdPlacementDelegate","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementdelegate","abstract":[{"type":"text","text":"Root placement delegate methods needed to follow Teads ad requests flow"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"role":"symbol","title":"TeadsNativeAdPlacementDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","abstract":[{"text":"Delegate methods needed to follow Teads native ad requests flow","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","kind":"symbol","title":"TeadsInReadAdPlacementDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","abstract":[{"text":"Delegate methods needed to follow Teads inRead ad requests flow","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"TeadsLogMessageDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate\/didLogMessage(message:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsLogMessageDelegate","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate~1didLogMessage(message:)\/title","op":"replace","value":"didLogMessageWithMessage:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate~1didLogMessage(message:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didLogMessageWithMessage:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/title","op":"replace","value":"TeadsLogMessageDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsLogMessageDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsLogMessageDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/title","op":"replace","value":"TeadsAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title","op":"replace","value":"TeadsNativeAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments","op":"replace","value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","op":"replace","value":"TeadsInReadAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}