{"abstract":[{"type":"text","text":"InRead ad placement to request inRead ads"}],"metadata":{"modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdPlacement","kind":"identifier"}],"title":"TeadsInReadAdPlacement","externalID":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacement","navigatorTitle":[{"text":"TeadsInReadAdPlacement","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsinreadadplacement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsinreadadplacement"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdPlacement","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"TeadsAdPlacement","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacement","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This object is reponsible for performing request and is tied to you PID (placement identifier)"},{"type":"text","text":" "},{"type":"text","text":"In order to create placement, call "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)","isActive":true}]},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"You must own\/retain ","type":"text"},{"code":"TeadsInReadAdPlacement","type":"codeVoice"},{"text":" instance, otherwise ads could not be delivered properly","type":"text"}]}]},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration","isActive":true},{"type":"text","text":" documentation"}],"type":"paragraph"}]}],"kind":"content"}],"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/delegate"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createInReadPlacement(pid:settings:delegate:)":{"url":"\/documentation\/teadssdk\/teads\/createinreadplacement(pid:settings:delegate:)","abstract":[{"text":"Create an inRead ad placement to request inRead ads","type":"text"}],"navigatorTitle":[{"text":"createInReadPlacementWithPid:settings:delegate:","kind":"identifier"}],"role":"symbol","type":"topic","title":"createInReadPlacement(pid:settings:delegate:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createInReadPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"settings","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","text":"TeadsAdPlacementSettings","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate","text":"TeadsInReadAdPlacementDelegate","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacement","text":"TeadsInReadAdPlacement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacement/delegate":{"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/delegate","type":"topic","kind":"symbol","abstract":[{"text":"TeadsInReadAdPlacementDelegate to follow ad placement lifecycle","type":"text"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TeadsInReadAdPlacementDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"text":"?","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacement\/delegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacement/requestAd(requestSettings:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"navigatorTitle":[{"kind":"identifier","text":"requestAdWithRequestSettings:"}],"role":"symbol","url":"\/documentation\/teadssdk\/teadsinreadadplacement\/requestad(requestsettings:)","abstract":[{"text":"Request an InRead ad on this placement","type":"text"},{"text":" ","type":"text"},{"text":"listen for events by implementing ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","type":"reference","isActive":true}],"title":"requestAd(requestSettings:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacement":{"url":"\/documentation\/teadssdk\/teadsadplacement","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacement"}],"type":"topic","role":"symbol","title":"TeadsAdPlacement","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacement"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","kind":"symbol"},"https://support.teads.tv/support/solutions/articles/36000314722-inread-classic-integration":{"url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration","title":"InRead implementation guide","titleInlineContent":[{"text":"InRead implementation guide","type":"text"}],"type":"link"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacement":{"role":"symbol","kind":"symbol","title":"TeadsInReadAdPlacement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacement"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement","type":"topic","abstract":[{"text":"InRead ad placement to request inRead ads","type":"text"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacement","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacement"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","kind":"symbol","title":"TeadsInReadAdPlacementDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","abstract":[{"text":"Delegate methods needed to follow Teads inRead ad requests flow","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TeadsInReadAdPlacement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdPlacement"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsInReadAdPlacement"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/delegate"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdPlacement","kind":"identifier"},{"text":" <","kind":"text"},{"text":"TeadsAdPlacement","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacement"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createInReadPlacement(pid:settings:delegate:)\/title","value":"createInReadPlacementWithPid:settings:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createInReadPlacement(pid:settings:delegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createInReadPlacementWithPid:settings:delegate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1requestAd(requestSettings:)\/title","value":"requestAdWithRequestSettings:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1requestAd(requestSettings:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAdWithRequestSettings:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/title","value":"TeadsAdPlacement"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacement"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/navigatorTitle","value":[{"text":"TeadsAdPlacement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement\/title","value":"TeadsInReadAdPlacement"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdPlacement"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement\/navigatorTitle","value":[{"text":"TeadsInReadAdPlacement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","value":"TeadsInReadAdPlacementDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}