{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewRepresentable.makeUIView(context:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView\/makeUIView(context:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsnative\/mediaview\/makeuiview(context:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","text":"Context"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsMediaView","text":"TeadsMediaView"}],"symbolKind":"method","title":"makeUIView(context:)","role":"symbol","externalID":"s:8TeadsSDK0A6NativeV9MediaViewV10makeUIView7contextAA0adE0C7SwiftUI0G20RepresentableContextVyAEG_tF","modules":[{"name":"TeadsSDK"}],"platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"13.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"13.0","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.0","unavailable":false}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","kind":"typeIdentifier","text":"Context"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsMediaView","kind":"typeIdentifier","text":"TeadsMediaView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView"}],"platforms":["iOS"]}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/MediaView/makeUIView(context:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","kind":"typeIdentifier","text":"Context"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsMediaView","kind":"typeIdentifier","text":"TeadsMediaView"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView\/makeUIView(context:)","abstract":[],"url":"\/documentation\/teadssdk\/teadsnative\/mediaview\/makeuiview(context:)","title":"makeUIView(context:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/MediaView":{"role":"symbol","abstract":[{"type":"text","text":"The MediaView can load either images, videos and VPAID content."}],"url":"\/documentation\/teadssdk\/teadsnative\/mediaview","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaView","kind":"identifier"}],"type":"topic","title":"TeadsNative.MediaView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView","kind":"symbol","navigatorTitle":[{"text":"MediaView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView":{"kind":"symbol","type":"topic","title":"TeadsMediaView","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","navigatorTitle":[{"text":"TeadsMediaView","kind":"identifier"}],"abstract":[{"text":"The TeadsMediaView can load either images, videos and VPAID content.","type":"text"}],"url":"\/documentation\/teadssdk\/teadsmediaview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsMediaView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"url":"\/documentation\/teadssdk\/teadsnative","role":"symbol","title":"TeadsNative","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNative"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsNative"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/title","op":"replace","value":"TeadsMediaView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/fragments","op":"replace","value":[{"text":"TeadsMediaView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsMediaView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}