{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetwork"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNetwork"},"abstract":[{"text":"Connectivity network issue","type":"text"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/aderrorcode\/errornetwork"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/aderrorcode\/errornetwork"]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"AdErrorCodeErrorNetwork","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetwork","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@E@AdErrorCode@AdErrorCodeErrorNetwork","modules":[{"name":"TeadsSDK"}],"title":"AdErrorCode.errorNetwork","role":"symbol"},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","url":"\/documentation\/teadssdk\/aderrorcode","abstract":[{"type":"text","text":"Enumeration of Teads’ error codes."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdErrorCode"}],"kind":"symbol","title":"AdErrorCode","navigatorTitle":[{"kind":"identifier","text":"AdErrorCode"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorNetwork":{"url":"\/documentation\/teadssdk\/aderrorcode\/errornetwork","kind":"symbol","abstract":[{"text":"Connectivity network issue","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorNetwork"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNetwork","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetwork","kind":"identifier"}],"title":"AdErrorCode.errorNetwork","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AdErrorCodeErrorNetwork"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AdErrorCodeErrorNetwork"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"AdErrorCodeErrorNetwork"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/title","value":"AdErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/fragments","value":[{"kind":"identifier","text":"AdErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"AdErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNetwork\/title","value":"AdErrorCodeErrorNetwork"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNetwork\/fragments","value":[{"kind":"identifier","text":"AdErrorCodeErrorNetwork"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}