{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView"]]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIViewRepresentable.dismantleUIView(_:coordinator:)"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismantleUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeAdView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TeadsNativeAdView","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView"},{"text":", ","kind":"text"},{"text":"coordinator","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"_","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Coordinator","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator","preciseIdentifier":"s:8TeadsSDK0A6NativeV6AdViewV11CoordinatorC"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnative\/adview\/dismantleuiview(_:coordinator:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/dismantleUIView(_:coordinator:)"},"metadata":{"externalID":"s:8TeadsSDK0A6NativeV6AdViewV15dismantleUIView_11coordinatoryAA0acdE0C_AE11CoordinatorCy_x_GtFZ","role":"symbol","title":"dismantleUIView(_:coordinator:)","platforms":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"13.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"13.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.0","unavailable":false}],"roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismantleUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsNativeAdView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"coordinator","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Coordinator","preciseIdentifier":"s:8TeadsSDK0A6NativeV6AdViewV11CoordinatorC","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","url":"\/documentation\/teadssdk\/teadsnative","navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"title":"TeadsNative"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/Coordinator":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"url":"\/documentation\/teadssdk\/teadsnative\/adview\/coordinator","role":"symbol","type":"topic","kind":"symbol","title":"TeadsNative.AdView.Coordinator","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinator"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView":{"title":"TeadsNative.AdView","abstract":[{"text":"The AdView is responsible to manage manage a Teads native ad.","type":"text"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdView","kind":"identifier"}],"navigatorTitle":[{"text":"AdView","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnative\/adview","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"kind":"symbol","type":"topic","abstract":[{"text":"The Teads native ad view is responsible to manage a Teads native ad.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdView"}],"title":"TeadsNativeAdView","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdView"}],"url":"\/documentation\/teadssdk\/teadsnativeadview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/dismantleUIView(_:coordinator:)":{"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/dismantleUIView(_:coordinator:)","kind":"symbol","url":"\/documentation\/teadssdk\/teadsnative\/adview\/dismantleuiview(_:coordinator:)","role":"symbol","type":"topic","title":"dismantleUIView(_:coordinator:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismantleUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsNativeAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView"},{"text":", ","kind":"text"},{"text":"coordinator","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Coordinator","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV6AdViewV11CoordinatorC"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title","op":"replace","value":"TeadsNativeAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments","op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle","op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}]}]}]}