{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSwiftUIView"]]},"abstract":[{"type":"text","text":"Initialize with any placement configuration"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementswiftuiview\/init(config:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Placement","preciseIdentifier":"s:8TeadsSDK0A22AdPlacementSwiftUIViewV0D0xmfp"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Config","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementEventsDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"},{"kind":"text","text":"? = nil)"}]}]}],"metadata":{"symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(config:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A22AdPlacementSwiftUIViewV0D0xmfp"},{"text":".","kind":"text"},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"kind":"text","text":"?)"}],"externalID":"s:8TeadsSDK0A22AdPlacementSwiftUIViewV6config8delegateACyxG6ConfigQz_AA0acD14EventsDelegate_pSgtcfc","modules":[{"name":"TeadsSDK"}]},"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSwiftUIView\/init(config:delegate:)","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSwiftUIView/init(config:delegate:)":{"url":"\/documentation\/teadssdk\/teadsadplacementswiftuiview\/init(config:delegate:)","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSwiftUIView\/init(config:delegate:)","abstract":[{"text":"Initialize with any placement configuration","type":"text"}],"title":"init(config:delegate:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A22AdPlacementSwiftUIViewV0D0xmfp"},{"text":".","kind":"text"},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSwiftUIView":{"url":"\/documentation\/teadssdk\/teadsadplacementswiftuiview","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSwiftUIView","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSwiftUIView"}],"role":"symbol","title":"TeadsAdPlacementSwiftUIView","abstract":[{"type":"text","text":"A unified SwiftUI view that can display UIView-based ad placements (Media and Feed)"},{"type":"text","text":" "},{"text":"For MediaNative and Recommendations placements, use their specific SwiftUI views instead","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSwiftUIView"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementProtocol/Config":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"Config"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementprotocol\/config","abstract":[],"type":"topic","title":"Config"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"title":"TeadsAdPlacementEventsDelegate","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title","value":"TeadsAdPlacementEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}