{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewRepresentable.updateUIView(_:context:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView\/updateUIView(_:context:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnative\/mediaview\/updateuiview(_:context:)"]}],"kind":"symbol","metadata":{"modules":[{"name":"TeadsSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUIView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsMediaView","text":"TeadsMediaView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","text":"Context"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","symbolKind":"method","title":"updateUIView(_:context:)","platforms":[{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"externalID":"s:8TeadsSDK0A6NativeV9MediaViewV12updateUIView_7contextyAA0adE0C_7SwiftUI0G20RepresentableContextVyAEGtF","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUIView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsMediaView","text":"TeadsMediaView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","text":"Context"},{"kind":"text","text":")"}]}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsMediaView","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/teadssdk\/teadsmediaview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","role":"symbol","title":"TeadsMediaView","navigatorTitle":[{"text":"TeadsMediaView","kind":"identifier"}],"abstract":[{"type":"text","text":"The TeadsMediaView can load either images, videos and VPAID content."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/MediaView/updateUIView(_:context:)":{"title":"updateUIView(_:context:)","kind":"symbol","url":"\/documentation\/teadssdk\/teadsnative\/mediaview\/updateuiview(_:context:)","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView\/updateUIView(_:context:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsMediaView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsMediaView"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Context","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta"},{"text":")","kind":"text"}],"abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/MediaView":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaView"}],"kind":"symbol","abstract":[{"type":"text","text":"The MediaView can load either images, videos and VPAID content."}],"title":"TeadsNative.MediaView","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaView"}],"url":"\/documentation\/teadssdk\/teadsnative\/mediaview"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"TeadsNative","url":"\/documentation\/teadssdk\/teadsnative","type":"topic","role":"symbol","navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative"}},"variantOverrides":[{"patch":[{"value":"TeadsMediaView","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/title"},{"value":[{"text":"TeadsMediaView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/fragments"},{"value":[{"kind":"identifier","text":"TeadsMediaView"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}