{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTerminate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ad request identifier"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsaddelegate\/didterminate(requestidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsaddelegate\/didterminate(requestidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didTerminate(requestIdentifier:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when an ad is terminated (deinit)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTerminate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":")"}],"title":"didTerminate(requestIdentifier:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(pl)TeadsAdDelegate(im)didTerminateWithRequestIdentifier:","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didTerminateWithRequestIdentifier:"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate/didTerminate(requestIdentifier:)":{"role":"symbol","title":"didTerminate(requestIdentifier:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTerminate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when an ad is terminated (deinit)"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate\/didTerminate(requestIdentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didTerminateWithRequestIdentifier:"}],"url":"\/documentation\/teadssdk\/teadsaddelegate\/didterminate(requestidentifier:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate":{"role":"symbol","title":"TeadsAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdDelegate"}],"abstract":[{"type":"text","text":"Delegate methods needed to follow Teads ads lifecycle."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdDelegate"}],"url":"\/documentation\/teadssdk\/teadsaddelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didTerminateWithRequestIdentifier:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTerminateWithRequestIdentifier:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didTerminateWithRequestIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUUID","preciseIdentifier":"c:objc(cs)NSUUID"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requestIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didTerminate(requestIdentifier:)\/title","value":"didTerminateWithRequestIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate~1didTerminate(requestIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTerminateWithRequestIdentifier:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/title","value":"TeadsAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsAdDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}