{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsmediatedadviewdelegate\/didupdateratio(_:adratio:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsmediatedadviewdelegate\/didupdateratio(_:adratio:)"]}],"metadata":{"symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate(im)didUpdateRatio:adRatio:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"didUpdateRatio:adRatio:"}],"modules":[{"name":"TeadsSDK"}],"title":"didUpdateRatio(_:adRatio:)","role":"symbol","required":true},"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate\/didUpdateRatio(_:adRatio:)","interfaceLanguage":"swift"},"abstract":[{"text":"Called when the ad ratio is udpated. (only for mediation)","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"adView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"adView","content":[{"inlineContent":[{"text":"The adView in which the ad is being played.","type":"text"}],"type":"paragraph"}]},{"name":"adRatio","content":[{"inlineContent":[{"type":"text","text":"The ratio you should use to update your adView height."}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio":{"type":"topic","url":"\/documentation\/teadssdk\/teadsadratio","abstract":[{"type":"text","text":"This class is used to help in resizing a given ad view to a given aspect ratio."}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRatio","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdRatio","kind":"identifier"}],"title":"TeadsAdRatio"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediatedAdViewDelegate/didUpdateRatio(_:adRatio:)":{"navigatorTitle":[{"text":"didUpdateRatio:adRatio:","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsmediatedadviewdelegate\/didupdateratio(_:adratio:)","title":"didUpdateRatio(_:adRatio:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate\/didUpdateRatio(_:adRatio:)","kind":"symbol","abstract":[{"type":"text","text":"Called when the ad ratio is udpated. (only for mediation)"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediatedAdViewDelegate":{"navigatorTitle":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsmediatedadviewdelegate","title":"TeadsMediatedAdViewDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","kind":"symbol","abstract":[{"type":"text","text":"When using mediation adapters on inRead placement you must register your view in order to monitor and perform resize updates"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"didUpdateRatio:adRatio:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didUpdateRatio:adRatio:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didUpdateRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"adView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"adRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio"},{"text":" *) ","kind":"text"},{"text":"adRatio","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The adView in which the ad is being played.","type":"text"}]}],"name":"adView"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ratio you should use to update your adView height."}]}],"name":"adRatio"}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/title","op":"replace","value":"TeadsAdRatio"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdRatio"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdRatio"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate~1didUpdateRatio(_:adRatio:)\/title","op":"replace","value":"didUpdateRatio:adRatio:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate~1didUpdateRatio(_:adRatio:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didUpdateRatio:adRatio:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/title","op":"replace","value":"TeadsMediatedAdViewDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/fragments","op":"replace","value":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}]}]}]}