{"kind":"article","metadata":{"roleHeading":"API Collection","modules":[{"name":"TeadsSDK"}],"title":"Equatable Implementations","role":"collectionGroup"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/teadssdk\/tcfversion\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion\/!=(_:_:)"],"anchor":"Operators"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TCFVersion":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TCFVersion"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TCFVersion","kind":"identifier"}],"url":"\/documentation\/teadssdk\/tcfversion","abstract":[{"type":"text","text":"EU Transparency & Consent Framework versions"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion","role":"symbol","title":"TCFVersion","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TCFVersion/!=(_:_:)":{"kind":"symbol","url":"\/documentation\/teadssdk\/tcfversion\/!=(_:_:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion\/!=(_:_:)","type":"topic","title":"!=(_:_:)","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/title","value":"TCFVersion","op":"replace"},{"op":"replace","value":[{"text":"TCFVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TCFVersion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}