{"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings(im)disableCrashMonitoring","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableCrashMonitoring"},{"kind":"text","text":"()"}],"role":"symbol","title":"disableCrashMonitoring()","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"disableCrashMonitoring"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableCrashMonitoring"},{"kind":"text","text":"()"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"TeadsSDK does not disturb any third party crash handler\/reporter such as Crashlytics"}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/disableCrashMonitoring()","interfaceLanguage":"swift"},"abstract":[{"inlineContent":[{"type":"text","text":"Teads Crash Monitoring"}],"type":"strong"},{"type":"text","text":" is a tool we use to monitor crashes that may occur ONLY IN OUR SDK."},{"type":"text","text":" "},{"type":"text","text":"This tool is really helpful for us and it aims to improve our product continuously."},{"type":"text","text":" "},{"type":"text","text":"Prevent TeadsSDK to automatically handle\/monitor crashes"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/disablecrashmonitoring()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/disablecrashmonitoring()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"title":"TeadsAdPlacementSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","url":"\/documentation\/teadssdk\/teadsadplacementsettings","type":"topic","abstract":[{"type":"text","text":"Specify which settings you want to set for your Teads placement."}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/disableCrashMonitoring()":{"url":"\/documentation\/teadssdk\/teadsadplacementsettings\/disablecrashmonitoring()","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Teads Crash Monitoring"}]},{"type":"text","text":" is a tool we use to monitor crashes that may occur ONLY IN OUR SDK."},{"type":"text","text":" "},{"type":"text","text":"This tool is really helpful for us and it aims to improve our product continuously."},{"type":"text","text":" "},{"type":"text","text":"Prevent TeadsSDK to automatically handle\/monitor crashes"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/disableCrashMonitoring()","navigatorTitle":[{"kind":"identifier","text":"disableCrashMonitoring"}],"kind":"symbol","title":"disableCrashMonitoring()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableCrashMonitoring"},{"kind":"text","text":"()"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"disableCrashMonitoring"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableCrashMonitoring"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"disableCrashMonitoring","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","value":"TeadsAdPlacementSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1disableCrashMonitoring()\/title","value":"disableCrashMonitoring"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableCrashMonitoring"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1disableCrashMonitoring()\/fragments"}]}]}