{"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ContainerComponent"},"abstract":[{"text":"Native container component: represent the overall container of native ad view","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerComponent","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"variants":[{"paths":["\/documentation\/teadssdk\/containercomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/containercomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","title":"ContainerComponent","externalID":"c:@M@TeadsSDK@objc(cs)ContainerComponent","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"ContainerComponent","kind":"identifier"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerComponent","kind":"identifier"}],"roleHeading":"Class"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"abstract":[{"type":"text","text":"Native Root Component"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","title":"CommonComponent","url":"\/documentation\/teadssdk\/commoncomponent","kind":"symbol","navigatorTitle":[{"text":"CommonComponent","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ContainerComponent":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ContainerComponent","kind":"symbol","role":"symbol","title":"ContainerComponent","url":"\/documentation\/teadssdk\/containercomponent","abstract":[{"type":"text","text":"Native container component: represent the overall container of native ad view"}],"navigatorTitle":[{"text":"ContainerComponent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerComponent","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ContainerComponent","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ContainerComponent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ContainerComponent","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerComponent","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"CommonComponent","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"CommonComponent","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title"},{"value":[{"text":"CommonComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments"},{"value":[{"text":"CommonComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle"},{"value":"ContainerComponent","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ContainerComponent\/title"},{"value":[{"kind":"identifier","text":"ContainerComponent"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ContainerComponent\/fragments"},{"value":[{"kind":"identifier","text":"ContainerComponent"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ContainerComponent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}