{"metadata":{"modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverlayComponent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OverlayComponent"}],"externalID":"c:@M@TeadsSDK@objc(cs)OverlayComponent","symbolKind":"class","title":"OverlayComponent","roleHeading":"Class","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverlayComponent","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"name":"Note","type":"aside","content":[{"inlineContent":[{"text":"This component will be considered as friendly obstruction by our Third Party Viewability SDK (","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/iabtechlab.com\/standards\/open-measurement-sdk\/"},{"text":")","type":"text"}],"type":"paragraph"}],"style":"note"}]}],"sections":[],"abstract":[{"text":"Native overlay component that could be put over playerView such as ","type":"text"},{"inlineContent":[{"text":"AdChoices","type":"text"}],"type":"strong"},{"text":" or ","type":"text"},{"inlineContent":[{"text":"ClickToAction","type":"text"}],"type":"strong"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/teadssdk\/overlaycomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/overlaycomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"abstract":[{"type":"text","text":"Native Root Component"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","title":"CommonComponent","url":"\/documentation\/teadssdk\/commoncomponent","kind":"symbol","navigatorTitle":[{"text":"CommonComponent","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent/clickThroughUrl":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","url":"\/documentation\/teadssdk\/adchoicescomponent\/clickthroughurl","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clickThroughUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Reach the URL that should be used when the ‘Ad Choices’ button is tapped."},{"type":"text","text":" "},{"type":"text","text":"Common behavior: open a Safari Web Browser with "},{"type":"codeVoice","code":"clickThroughUrl"}],"title":"clickThroughUrl"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OverlayComponent":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent","navigatorTitle":[{"text":"OverlayComponent","kind":"identifier"}],"abstract":[{"type":"text","text":"Native overlay component that could be put over playerView such as "},{"type":"strong","inlineContent":[{"text":"AdChoices","type":"text"}]},{"type":"text","text":" or "},{"type":"strong","inlineContent":[{"type":"text","text":"ClickToAction"}]}],"kind":"symbol","url":"\/documentation\/teadssdk\/overlaycomponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverlayComponent","kind":"identifier"}],"title":"OverlayComponent","type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Native Component containing AdChoices "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","role":"symbol","url":"\/documentation\/teadssdk\/adchoicescomponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdChoicesComponent","kind":"identifier"}],"title":"AdChoicesComponent","navigatorTitle":[{"text":"AdChoicesComponent","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"},"https://iabtechlab.com/standards/open-measurement-sdk/":{"type":"link","titleInlineContent":[{"text":"Open Measurement","type":"text"}],"title":"Open Measurement","identifier":"https:\/\/iabtechlab.com\/standards\/open-measurement-sdk\/","url":"https:\/\/iabtechlab.com\/standards\/open-measurement-sdk\/"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OverlayComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OverlayComponent","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OverlayComponent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent"],"type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent"],"type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OverlayComponent"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","kind":"typeIdentifier","text":"CommonComponent"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title","value":"CommonComponent"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments","value":[{"kind":"identifier","text":"CommonComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle","value":[{"kind":"identifier","text":"CommonComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/title","value":"OverlayComponent"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/fragments","value":[{"text":"OverlayComponent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/navigatorTitle","value":[{"text":"OverlayComponent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/title","value":"AdChoicesComponent"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/fragments","value":[{"text":"AdChoicesComponent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/navigatorTitle","value":[{"text":"AdChoicesComponent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}