{"variants":[{"paths":["\/documentation\/teadssdk\/teadsmediaview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsmediaview"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediaView"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement it to render media component content using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/bind(component:)"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent"}],"type":"paragraph"}]}]}],"kind":"content"}],"metadata":{"roleHeading":"Class","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsMediaView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsMediaView","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsMediaView","kind":"identifier"}],"title":"TeadsMediaView","symbolKind":"class"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView"},"abstract":[{"text":"The TeadsMediaView can load either images, videos and VPAID content.","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/init(frame:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/init(videoComponent:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/mediaScale","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/placeholderImage"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/bind(component:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/layoutSubviews()"],"anchor":"Instance-Methods","generated":true}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/VideoComponent":{"kind":"symbol","navigatorTitle":[{"text":"VideoComponent","kind":"identifier"}],"url":"\/documentation\/teadssdk\/videocomponent","title":"VideoComponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoComponent","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent","abstract":[{"text":"Native video component containing media content","type":"text"}],"type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView/placeholderImage":{"kind":"symbol","abstract":[{"type":"text","text":"Image placeholder"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/placeholderImage","title":"placeholderImage","url":"\/documentation\/teadssdk\/teadsmediaview\/placeholderimage","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView/init(frame:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/init(frame:)","url":"\/documentation\/teadssdk\/teadsmediaview\/init(frame:)","role":"symbol","title":"init(frame:)","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView/layoutSubviews()":{"abstract":[],"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsmediaview\/layoutsubviews()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/layoutSubviews()","title":"layoutSubviews()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageComponent","kind":"identifier"}],"url":"\/documentation\/teadssdk\/imagecomponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","abstract":[{"text":"Native image component containing image url","type":"text"}],"navigatorTitle":[{"text":"ImageComponent","kind":"identifier"}],"title":"ImageComponent","role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView/bind(component:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","kind":"typeIdentifier","text":"CommonComponent"},{"kind":"text","text":"?)"}],"abstract":[{"text":"map your UIKit element to TeadsSDK logic,","type":"text"},{"text":" ","type":"text"},{"text":"this ensures visibility measurement is monitored and click behaviors are well handled","type":"text"}],"navigatorTitle":[{"text":"bindWithComponent:","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/bind(component:)","title":"bind(component:)","type":"topic","url":"\/documentation\/teadssdk\/teadsmediaview\/bind(component:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s8SendableP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsMediaView","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/teadssdk\/teadsmediaview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","role":"symbol","title":"TeadsMediaView","navigatorTitle":[{"text":"TeadsMediaView","kind":"identifier"}],"abstract":[{"type":"text","text":"The TeadsMediaView can load either images, videos and VPAID content."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView/init(videoComponent:)":{"abstract":[{"text":"When dealing with VideoComponent, it needs to be rendered using TeadsMediaView","type":"text"}],"title":"init(videoComponent:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"videoComponent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)VideoComponent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithVideoComponent:","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsmediaview\/init(videocomponent:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/init(videoComponent:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView/mediaScale":{"type":"topic","title":"mediaScale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaScale"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@E@MediaScale","kind":"typeIdentifier","text":"MediaScale"}],"abstract":[{"type":"text","text":"A value describing the native ad media scale that is being used."}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/mediaScale","role":"symbol","url":"\/documentation\/teadssdk\/teadsmediaview\/mediascale"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"TeadsMediaView","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"TeadsMediaView"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"TeadsMediaView"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/bind(component:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/init(frame:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/init(videoComponent:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/layoutSubviews()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsMediaView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"VideoComponent","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/title"},{"value":[{"text":"VideoComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/fragments"},{"value":[{"text":"VideoComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/navigatorTitle"},{"value":"initWithFrame:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1init(frame:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1init(frame:)\/fragments"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1layoutSubviews()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1layoutSubviews()\/fragments"},{"value":"ImageComponent","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/title"},{"value":[{"text":"ImageComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/fragments"},{"value":[{"kind":"identifier","text":"ImageComponent"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/navigatorTitle"},{"value":"bindWithComponent:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1bind(component:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"bindWithComponent:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1bind(component:)\/fragments"},{"value":"TeadsMediaView","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/title"},{"value":[{"text":"TeadsMediaView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/fragments"},{"value":[{"kind":"identifier","text":"TeadsMediaView"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/navigatorTitle"},{"value":"initWithVideoComponent:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1init(videoComponent:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVideoComponent:"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1init(videoComponent:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}