{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate\/didUpdateRatio(_:adRatio:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsmediatedadviewdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsmediatedadviewdelegate"]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"title":"TeadsMediatedAdViewDelegate","externalID":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"modules":[{"name":"TeadsSDK"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol"},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"When using mediation adapters on inRead placement you must register your view in order to monitor and perform resize updates"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediatedAdViewDelegate/didUpdateRatio(_:adRatio:)":{"navigatorTitle":[{"text":"didUpdateRatio:adRatio:","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsmediatedadviewdelegate\/didupdateratio(_:adratio:)","title":"didUpdateRatio(_:adRatio:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate\/didUpdateRatio(_:adRatio:)","kind":"symbol","abstract":[{"type":"text","text":"Called when the ad ratio is udpated. (only for mediation)"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediatedAdViewDelegate":{"navigatorTitle":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsmediatedadviewdelegate","title":"TeadsMediatedAdViewDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","kind":"symbol","abstract":[{"type":"text","text":"When using mediation adapters on inRead placement you must register your view in order to monitor and perform resize updates"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"TeadsMediatedAdViewDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate\/didUpdateRatio(_:adRatio:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"didUpdateRatio:adRatio:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate~1didUpdateRatio(_:adRatio:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didUpdateRatio:adRatio:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate~1didUpdateRatio(_:adRatio:)\/fragments"},{"value":"TeadsMediatedAdViewDelegate","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/title"},{"value":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/fragments"},{"value":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}