{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView","role":"symbol","modules":[{"name":"TeadsSDK"}],"title":"TeadsInReadAdView","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdView","kind":"identifier"}],"symbolKind":"class"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(bind:frame:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(coder:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(frame:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/bind(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/didMoveToWindow()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/layoutSubviews()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/willMove(toWindow:)"],"generated":true,"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsinreadadview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsinreadadview"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/init(coder:)":{"abstract":[],"url":"\/documentation\/teadssdk\/teadsinreadadview\/init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(coder:)","role":"symbol","title":"init(coder:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/layoutSubviews()":{"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/teadssdk\/teadsinreadadview\/layoutsubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/layoutSubviews()","role":"symbol","title":"layoutSubviews()","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/init(bind:frame:)":{"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(bind:frame:)","url":"\/documentation\/teadssdk\/teadsinreadadview\/init(bind:frame:)","title":"init(bind:frame:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd","text":"TeadsInReadAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"abstract":[{"text":"Init TeadsInReadAdView by prodiving the ad to bind.","type":"text"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/bind(_:)":{"navigatorTitle":[{"kind":"identifier","text":"bind:"}],"url":"\/documentation\/teadssdk\/teadsinreadadview\/bind(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TeadsInReadAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/bind(_:)","role":"symbol","title":"bind(_:)","abstract":[{"text":"Call this to bind an inRead ad to your inRead ad view.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/willMove(toWindow:)":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/willMove(toWindow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier","text":"UIWindow"},{"kind":"text","text":"?)"}],"role":"symbol","title":"willMove(toWindow:)","url":"\/documentation\/teadssdk\/teadsinreadadview\/willmove(towindow:)","navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}],"type":"topic","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/didMoveToWindow()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"kind":"symbol","title":"didMoveToWindow()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/didMoveToWindow()","type":"topic","abstract":[],"url":"\/documentation\/teadssdk\/teadsinreadadview\/didmovetowindow()"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"abstract":[{"text":"The Teads inRead ad view is responsible to manage a Teads inRead ad.","type":"text"}],"title":"TeadsInReadAdView","role":"symbol","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdView"}],"url":"\/documentation\/teadssdk\/teadsinreadadview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdView":{"role":"symbol","url":"\/documentation\/teadssdk\/teadsadview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdView"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdView"}],"kind":"symbol","title":"TeadsAdView","abstract":[{"type":"text","text":"Root view inherited by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"},{"type":"text","text":" & "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","type":"topic","url":"\/documentation\/teadssdk\/teadsnativeadview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdView"}],"title":"TeadsNativeAdView","abstract":[{"type":"text","text":"The Teads native ad view is responsible to manage a Teads native ad."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/init(frame:)":{"url":"\/documentation\/teadssdk\/teadsinreadadview\/init(frame:)","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(frame:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"TeadsInReadAdView","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsInReadAdView"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/bind(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/didMoveToWindow()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(coder:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(frame:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/layoutSubviews()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/willMove(toWindow:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView","text":"TeadsAdView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdView"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithCoder:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1init(coder:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1init(coder:)\/fragments","op":"replace"},{"value":"layoutSubviews","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1layoutSubviews()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1layoutSubviews()\/fragments","op":"replace"},{"value":"bind:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1bind(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bind:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1bind(_:)\/fragments","op":"replace"},{"value":"willMoveToWindow:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1willMove(toWindow:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToWindow:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1willMove(toWindow:)\/fragments","op":"replace"},{"value":"didMoveToWindow","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1didMoveToWindow()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1didMoveToWindow()\/fragments","op":"replace"},{"value":"TeadsInReadAdView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","op":"replace"},{"value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsInReadAdView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","op":"replace"},{"value":"TeadsAdView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/title","op":"replace"},{"value":[{"text":"TeadsAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/fragments","op":"replace"},{"value":[{"text":"TeadsAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/navigatorTitle","op":"replace"},{"value":"TeadsNativeAdView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title","op":"replace"},{"value":[{"text":"TeadsNativeAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments","op":"replace"},{"value":[{"text":"TeadsNativeAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle","op":"replace"},{"value":"initWithFrame:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1init(frame:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView~1init(frame:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}