{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clicked","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"title":"TeadsAdPlacementEventName.clicked","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName@TeadsAdPlacementEventNameClicked","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clicked","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventNameClicked"}]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementeventname\/clicked"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementeventname\/clicked"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/clicked"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/clicked":{"title":"TeadsAdPlacementEventName.clicked","abstract":[],"url":"\/documentation\/teadssdk\/teadsadplacementeventname\/clicked","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/clicked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clicked"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventNameClicked"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName":{"navigatorTitle":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"abstract":[],"type":"topic","title":"TeadsAdPlacementEventName","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"TeadsAdPlacementEventNameClicked"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameClicked"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"TeadsAdPlacementEventNameClicked","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1clicked\/title","value":"TeadsAdPlacementEventNameClicked"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1clicked\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameClicked"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/title","value":"TeadsAdPlacementEventName"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementEventName"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementEventName"}]}]}]}