{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/rendered"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendered","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rendered"}],"role":"symbol","symbolKind":"case","title":"TeadsAdPlacementEventName.rendered","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventNameRendered"}],"roleHeading":"Case","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName@TeadsAdPlacementEventNameRendered"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementeventname\/rendered"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementeventname\/rendered"]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName":{"navigatorTitle":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"abstract":[],"type":"topic","title":"TeadsAdPlacementEventName","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/rendered":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rendered"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/rendered","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventNameRendered"}],"abstract":[],"title":"TeadsAdPlacementEventName.rendered","type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/rendered","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"TeadsAdPlacementEventNameRendered"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementEventNameRendered","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"TeadsAdPlacementEventNameRendered","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/title","op":"replace","value":"TeadsAdPlacementEventName"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1rendered\/title","op":"replace","value":"TeadsAdPlacementEventNameRendered"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1rendered\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameRendered"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}