{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startPlayAudio","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"title":"TeadsAdPlacementEventName.startPlayAudio","externalID":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName@TeadsAdPlacementEventNameStartPlayAudio","symbolKind":"case","roleHeading":"Case","role":"symbol","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startPlayAudio","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventNameStartPlayAudio"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementeventname\/startplayaudio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementeventname\/startplayaudio"]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/startPlayAudio","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/startPlayAudio":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/startPlayAudio","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/startplayaudio","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startPlayAudio","kind":"identifier"}],"abstract":[],"title":"TeadsAdPlacementEventName.startPlayAudio","role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementEventNameStartPlayAudio","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName":{"navigatorTitle":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"abstract":[],"type":"topic","title":"TeadsAdPlacementEventName","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"TeadsAdPlacementEventNameStartPlayAudio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameStartPlayAudio"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"TeadsAdPlacementEventNameStartPlayAudio","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1startPlayAudio\/title","op":"replace","value":"TeadsAdPlacementEventNameStartPlayAudio"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1startPlayAudio\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameStartPlayAudio"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/title","op":"replace","value":"TeadsAdPlacementEventName"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventName"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}