{"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init(build:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init(from:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/adPlacementSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/adRequestSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/hasSubscribedToAdResizing","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/mediaScale"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/addExtras(_:for:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableBatteryMonitoring()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableCrashMonitoring()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableLocation()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableMediaPreload()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableTeadsAudioSessionManagement()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableDebug()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableLightEndScreen()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableValidationMode()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/encode(to:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/pageUrl(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/registerAdView(_:delegate:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setGppConsent(consent:sectionIds:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setIntegration(type:version:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setMediaScale(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setUsPrivacy(consent:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeAdResizeDelegate(_:forAdView:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeToAdResizing()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/toDictionary()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)"],"generated":true,"anchor":"Instance-Methods"},{"anchor":"Type-Aliases","title":"Type Aliases","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/BuildTeadsAdapterSettings"]},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/integrationTypeKey","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/integrationVersionKey","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/prebidStandaloneKey"],"anchor":"Type-Properties","title":"Type Properties","generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/instance(from:)"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/Se","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SE","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TeadsAdapterSettings","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","modules":[{"name":"TeadsSDK"}],"title":"TeadsAdapterSettings","role":"symbol","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Settings used to load Teads’ mediation adapter ads"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TeadsAdapterSettings","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"Specify which setting you want to set for the related mediation request."},{"type":"text","text":" "},{"type":"text","text":"Those settings will be persisted for the ad lifecycle only."}],"type":"paragraph"},{"inlineContent":[{"text":"Only relevant when using  adapter such as","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314767-inread-google-ad-manager-and-admob-mediation"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000357700-inread-applovin-mediation","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314771-smart-adserver-mediation-inread","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/3600031477136000459748","isActive":true}]}]}],"type":"unorderedList"}],"kind":"content"}],"seeAlsoSections":[{"title":"Settings","anchor":"Settings","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings"],"generated":true}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings"]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/disableLocation()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableLocation"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadaptersettings\/disablelocation()","navigatorTitle":[{"text":"disableLocation","kind":"identifier"}],"title":"disableLocation()","abstract":[],"deprecated":true,"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableLocation()","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/toDictionary()":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/toDictionary()","url":"\/documentation\/teadssdk\/teadsadaptersettings\/todictionary()","navigatorTitle":[{"kind":"identifier","text":"toDictionaryAndReturnError:"}],"kind":"symbol","abstract":[{"type":"text","text":"Return a dictionary representation of the current TeadsAdSettings object."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toDictionary"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"title":"toDictionary()","role":"symbol","type":"topic"},"https://support.teads.tv/support/solutions/articles/36000314767-inread-google-ad-manager-and-admob-mediation":{"title":"AdMob","titleInlineContent":[{"type":"text","text":"AdMob"}],"url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314767-inread-google-ad-manager-and-admob-mediation","type":"link","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314767-inread-google-ad-manager-and-admob-mediation"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/setMediaScale(_:)":{"title":"setMediaScale(_:)","navigatorTitle":[{"kind":"identifier","text":"setMediaScale:"}],"type":"topic","abstract":[{"type":"text","text":"Set the native media view scale."}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/setmediascale(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMediaScale"},{"text":"(","kind":"text"},{"text":"MediaScale","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@MediaScale"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setMediaScale(_:)","kind":"symbol","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject","title":"NSObject"},"https://support.teads.tv/support/solutions/articles/36000357700-inread-applovin-mediation":{"title":"AppLovin","titleInlineContent":[{"type":"text","text":"AppLovin"}],"url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000357700-inread-applovin-mediation","type":"link","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000357700-inread-applovin-mediation"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/enableValidationMode()":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableValidationMode()","navigatorTitle":[{"kind":"identifier","text":"enableValidationMode"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadaptersettings\/enablevalidationmode()","title":"enableValidationMode()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableValidationMode"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"The Teads inApp Validation tool is the best way to ensure all basic features and prerequisites are correctly implemented."},{"type":"text","text":" "},{"type":"text","text":"It is also useful during integration iterations."}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/init()":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init()","url":"\/documentation\/teadssdk\/teadsadaptersettings\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/Se":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/pageUrl(_:)":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/pageUrl(_:)","navigatorTitle":[{"kind":"identifier","text":"pageUrl:"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadaptersettings\/pageurl(_:)","title":"pageUrl(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pageUrl","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Set the publisher http page url that matches the content where Teads Ad will be loaded."}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/disableTeadsAudioSessionManagement()":{"kind":"symbol","navigatorTitle":[{"text":"disableTeadsAudioSessionManagement","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/disableteadsaudiosessionmanagement()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disableTeadsAudioSessionManagement"},{"text":"()","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"By default, the Teads SDK handles the audio session by setting its category to ambient."},{"text":" ","type":"text"},{"text":"This means that all the audio played by other apps will be simply mixed with the ad sound.","type":"text"}],"type":"topic","title":"disableTeadsAudioSessionManagement()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableTeadsAudioSessionManagement()"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/enableDebug()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableDebug"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableDebug()","url":"\/documentation\/teadssdk\/teadsadaptersettings\/enabledebug()","title":"enableDebug()","abstract":[{"type":"text","text":"Enable all TeadsSDK Log for debugging purpose"}],"navigatorTitle":[{"kind":"identifier","text":"enableDebug"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/instance(from:)":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/instance(from:)","title":"instance(from:)","navigatorTitle":[{"text":"instanceFrom:error:","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/instance(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instance"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings"}],"type":"topic","abstract":[{"type":"text","text":"Create an instance from "},{"code":"[AnyHashable: Any]","type":"codeVoice"}]},"https://support.teads.tv/support/solutions/articles/3600031477136000459748":{"type":"link","titleInlineContent":[{"text":"Prebid","type":"text"}],"url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/3600031477136000459748","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/3600031477136000459748","title":"Prebid"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/prebidStandaloneKey":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/prebidstandalonekey","title":"prebidStandaloneKey","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/prebidStandaloneKey","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prebidStandaloneKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/init(from:)":{"role":"symbol","title":"init(from:)","url":"\/documentation\/teadssdk\/teadsadaptersettings\/init(from:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init(from:)","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/setIntegration(type:version:)":{"abstract":[{"type":"text","text":"Specify integration type and version"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIntegration"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdapterIntegrationType","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"version","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","title":"setIntegration(type:version:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setIntegrationWithType:version:"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setIntegration(type:version:)","url":"\/documentation\/teadssdk\/teadsadaptersettings\/setintegration(type:version:)","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"url":"\/documentation\/teadssdk\/teadsadrequestsettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdRequestSettings"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"kind":"symbol","abstract":[{"text":"Specify which settings you want to set for the related ad request.","type":"text"}],"role":"symbol","title":"TeadsAdRequestSettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/disableBatteryMonitoring()":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableBatteryMonitoring()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableBatteryMonitoring"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/disablebatterymonitoring()","abstract":[{"type":"text","text":"Prevent to automatically set UIDevice.current.isBatteryMonitoringEnabled"}],"title":"disableBatteryMonitoring()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"disableBatteryMonitoring","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)":{"abstract":[{"text":"In order to follow the IAB specifications for GDPR, please fill the following parameters with attention.","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","type":"topic","url":"\/documentation\/teadssdk\/teadsadaptersettings\/userconsent(subjecttogdpr:consent:tcfversion:cmpsdkid:)","navigatorTitle":[{"kind":"identifier","text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:"}],"kind":"symbol","title":"userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userConsent"},{"text":"(","kind":"text"},{"text":"subjectToGDPR","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"consent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"tcfVersion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TCFVersion","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cmpSdkID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/disableCrashMonitoring()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableCrashMonitoring"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableCrashMonitoring()","url":"\/documentation\/teadssdk\/teadsadaptersettings\/disablecrashmonitoring()","title":"disableCrashMonitoring()","abstract":[{"inlineContent":[{"type":"text","text":"Teads Crash Monitoring"}],"type":"strong"},{"type":"text","text":" is a tool we use to monitor crashes that may occur ONLY IN OUR SDK."},{"type":"text","text":" "},{"text":"This tool is really helpful for us and it aims to improve our product continuously.","type":"text"},{"type":"text","text":" "},{"text":"Prevent TeadsSDK to automatically handle\/monitor crashes","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"disableCrashMonitoring"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/hasSubscribedToAdResizing":{"kind":"symbol","type":"topic","title":"hasSubscribedToAdResizing","abstract":[{"type":"text","text":"Return true if the placement has subscribed to ad resizing."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/hasSubscribedToAdResizing","url":"\/documentation\/teadssdk\/teadsadaptersettings\/hassubscribedtoadresizing","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasSubscribedToAdResizing","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"https://support.teads.tv/support/solutions/articles/36000314771-smart-adserver-mediation-inread":{"type":"link","titleInlineContent":[{"type":"text","text":"Smart Ad Server"}],"url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314771-smart-adserver-mediation-inread","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314771-smart-adserver-mediation-inread","title":"Smart Ad Server"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/subscribeToAdResizing()":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subscribeToAdResizing"},{"text":"()","kind":"text"}],"abstract":[{"text":"Convenient way to specify ability to resize in settings","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/subscribetoadresizing()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeToAdResizing()","title":"subscribeToAdResizing()","navigatorTitle":[{"kind":"identifier","text":"subscribeToAdResizing"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/disableMediaPreload()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableMediaPreload","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadaptersettings\/disablemediapreload()","deprecated":true,"navigatorTitle":[{"text":"disableMediaPreload","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableMediaPreload()","abstract":[{"text":"To improve performances and user experience, media such as videos or images are preloaded.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This setting prevents TeadsSDK from automatically preloading media."}],"title":"disableMediaPreload()","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","title":"TeadsAdPlacementSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementsettings","kind":"symbol","abstract":[{"text":"Specify which settings you want to set for your Teads placement.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/enableLightEndScreen()":{"kind":"symbol","navigatorTitle":[{"text":"enableLightEndScreen","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/enablelightendscreen()","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableLightEndScreen","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","abstract":[],"type":"topic","title":"enableLightEndScreen()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableLightEndScreen()"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/setUsPrivacy(consent:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setUsPrivacy(consent:)","url":"\/documentation\/teadssdk\/teadsadaptersettings\/setusprivacy(consent:)","navigatorTitle":[{"text":"setUsPrivacyWithConsent:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"In order to follow the IAB specifications for CCPA, please fill the following parameters with attention.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUsPrivacy","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"consent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"setUsPrivacy(consent:)","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/addExtras(_:for:)":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/addextras(_:for:)","title":"addExtras(_:for:)","navigatorTitle":[{"kind":"identifier","text":"addExtras:for:"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/addExtras(_:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addExtras","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"abstract":[{"text":"Add extra informations to settings.","type":"text"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/init(build:)":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/init(build:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBuild:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"build"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A15AdapterSettingsC05BuildacD0a","text":"BuildTeadsAdapterSettings"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Instance settings builder"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init(build:)","title":"init(build:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/adPlacementSettings":{"role":"symbol","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings\/adplacementsettings","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adPlacementSettings"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","text":"TeadsAdPlacementSettings","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/adPlacementSettings","abstract":[{"text":"Placement settings (internal use only)","type":"text"}],"title":"adPlacementSettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/integrationTypeKey":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/integrationTypeKey","url":"\/documentation\/teadssdk\/teadsadaptersettings\/integrationtypekey","abstract":[{"type":"text","text":"Mediation key to monitor mediation adadpters"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"integrationTypeKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"integrationTypeKey"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/integrationVersionKey":{"kind":"symbol","abstract":[{"text":"Version of adapter key to monitor mediation adadpters","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/integrationversionkey","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/integrationVersionKey","type":"topic","title":"integrationVersionKey","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"integrationVersionKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/subscribeAdResizeDelegate(_:forAdView:)":{"title":"subscribeAdResizeDelegate(_:forAdView:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"subscribeAdResizeDelegate:forAdView:error:"}],"deprecated":true,"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings\/subscribeadresizedelegate(_:foradview:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeAdResizeDelegate(_:forAdView:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"subscribeAdResizeDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"TeadsMediatedAdViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forAdView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/SE":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/mediaScale":{"title":"mediaScale","navigatorTitle":[{"text":"mediaScale","kind":"identifier"}],"type":"topic","abstract":[{"text":"A value describing the native ad media scale that is being used.","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/mediascale","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaScale"},{"kind":"text","text":": "},{"text":"MediaScale","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@MediaScale"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/mediaScale","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/registerAdView(_:delegate:)":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/registeradview(_:delegate:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/registerAdView(_:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerAdView"},{"kind":"text","text":"("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate","text":"TeadsMediatedAdViewDelegate"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerAdView:delegate:"}],"kind":"symbol","abstract":[{"text":"Register the ad view in case of mediation adapter.","type":"text"}],"role":"symbol","title":"registerAdView(_:delegate:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/BuildTeadsAdapterSettings":{"role":"symbol","title":"TeadsAdapterSettings.BuildTeadsAdapterSettings","url":"\/documentation\/teadssdk\/teadsadaptersettings\/buildteadsadaptersettings","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"BuildTeadsAdapterSettings","kind":"identifier"}],"navigatorTitle":[{"text":"BuildTeadsAdapterSettings","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/BuildTeadsAdapterSettings","abstract":[{"type":"text","text":"Convenience closure typealias for "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","isActive":true}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/encode(to:)":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/encode(to:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/encode(to:)","title":"encode(to:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"navigatorTitle":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings","type":"topic","title":"TeadsAdapterSettings","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/adRequestSettings":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/adRequestSettings","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Request settings (internal use only)"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"adRequestSettings","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TeadsAdRequestSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings"}],"title":"adRequestSettings","url":"\/documentation\/teadssdk\/teadsadaptersettings\/adrequestsettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/setGppConsent(consent:sectionIds:)":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setGppConsent(consent:sectionIds:)","navigatorTitle":[{"kind":"identifier","text":"setGppConsentWithConsent:sectionIds:"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadaptersettings\/setgppconsent(consent:sectionids:)","title":"setGppConsent(consent:sectionIds:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setGppConsent","kind":"identifier"},{"kind":"text","text":"("},{"text":"consent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sectionIds"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"In order to follow the IAB specifications for GPP, please fill the following parameters with attention."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"TeadsAdapterSettings","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/mediaScale"]},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/addExtras(_:for:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableBatteryMonitoring()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableCrashMonitoring()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableLocation()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableMediaPreload()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableTeadsAudioSessionManagement()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableDebug()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableLightEndScreen()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableValidationMode()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init(build:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/pageUrl(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/registerAdView(_:delegate:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setGppConsent(consent:sectionIds:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setIntegration(type:version:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setMediaScale(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setUsPrivacy(consent:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeAdResizeDelegate(_:forAdView:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeToAdResizing()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/toDictionary()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/instance(from:)"],"anchor":"Type-Methods"}],"path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"Settings","anchor":"Settings","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings"],"generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdapterSettings"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableLocation()\/title","value":"disableLocation"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableLocation"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableLocation()\/fragments"},{"op":"replace","value":"toDictionaryAndReturnError:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1toDictionary()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"toDictionaryAndReturnError:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1toDictionary()\/fragments"},{"op":"replace","value":"setMediaScale:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setMediaScale(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"setMediaScale:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setMediaScale(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableValidationMode()\/title","value":"enableValidationMode"},{"value":[{"kind":"text","text":"- "},{"text":"enableValidationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableValidationMode()\/fragments"},{"value":"init","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1init()\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1pageUrl(_:)\/title","op":"replace","value":"pageUrl:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pageUrl:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1pageUrl(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableTeadsAudioSessionManagement()\/title","value":"disableTeadsAudioSessionManagement"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableTeadsAudioSessionManagement()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disableTeadsAudioSessionManagement","kind":"identifier"}]},{"value":"enableDebug","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableDebug()\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableDebug()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"enableDebug","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1instance(from:)\/title","op":"replace","value":"instanceFrom:error:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"instanceFrom:error:"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1instance(from:)\/fragments"},{"value":"setIntegrationWithType:version:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setIntegration(type:version:)\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setIntegration(type:version:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setIntegrationWithType:version:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title","value":"TeadsAdRequestSettings","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments"},{"op":"replace","value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/navigatorTitle"},{"op":"replace","value":"disableBatteryMonitoring","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableBatteryMonitoring()\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableBatteryMonitoring()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disableBatteryMonitoring","kind":"identifier"}]},{"op":"replace","value":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableCrashMonitoring()\/title","op":"replace","value":"disableCrashMonitoring"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableCrashMonitoring()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"disableCrashMonitoring"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1subscribeToAdResizing()\/title","value":"subscribeToAdResizing"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribeToAdResizing"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1subscribeToAdResizing()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableMediaPreload()\/title","value":"disableMediaPreload"},{"value":[{"kind":"text","text":"- "},{"text":"disableMediaPreload","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableMediaPreload()\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","op":"replace","value":"TeadsAdPlacementSettings"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments"},{"value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableLightEndScreen()\/title","value":"enableLightEndScreen"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableLightEndScreen()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"enableLightEndScreen","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setUsPrivacy(consent:)\/title","value":"setUsPrivacyWithConsent:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setUsPrivacy(consent:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setUsPrivacyWithConsent:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1addExtras(_:for:)\/title","op":"replace","value":"addExtras:for:"},{"value":[{"text":"- ","kind":"text"},{"text":"addExtras:for:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1addExtras(_:for:)\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1init(build:)\/title","value":"initWithBuild:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1init(build:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBuild:","kind":"identifier"}],"op":"replace"},{"value":"subscribeAdResizeDelegate:forAdView:error:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1subscribeAdResizeDelegate(_:forAdView:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribeAdResizeDelegate:forAdView:error:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1subscribeAdResizeDelegate(_:forAdView:)\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1mediaScale\/title","op":"replace","value":"mediaScale"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1mediaScale\/fragments","op":"replace","value":[{"text":"mediaScale","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1registerAdView(_:delegate:)\/title","value":"registerAdView:delegate:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1registerAdView(_:delegate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerAdView:delegate:"}]},{"value":"TeadsAdapterSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setGppConsent(consent:sectionIds:)\/title","value":"setGppConsentWithConsent:sectionIds:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setGppConsentWithConsent:sectionIds:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setGppConsent(consent:sectionIds:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}