{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInReadPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","text":"TeadsAdPlacementSettings"},{"kind":"text","text":" = TeadsAdPlacementSettings(), "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate","text":"TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacement","text":"TeadsInReadAdPlacement"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"pid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Your Teads placement identifier for "},{"type":"strong","inlineContent":[{"type":"text","text":"inRead"}]},{"type":"text","text":" ads"}]}]},{"name":"settings","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The placement’s related settings you want to apply"}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"TeadsInReadAdPlacementDelegate to follow ad placement lifecycle"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"TeadsInReadAdPlacement instance, this instance must be owned\/retained"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You must own\/retain "},{"type":"codeVoice","code":"TeadsInReadAdPlacement"},{"type":"text","text":" instance, otherwise ads could not be delivered properly: you can free placement instance on       "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate\/didReceiveAd(ad:adRatio:)"},{"type":"text","text":" or  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/didFailToReceiveAd(reason:)"}]}],"type":"aside","name":"Important"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration"},{"type":"text","text":" documentation"}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teads\/createinreadplacement(pid:settings:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teads\/createinreadplacement(pid:settings:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create an inRead ad placement to request inRead ads"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInReadPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TeadsInReadAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacement"},{"kind":"text","text":"?"}],"title":"createInReadPlacement(pid:settings:delegate:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)Teads(cm)createInReadPlacementWithPid:settings:delegate:","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createInReadPlacementWithPid:settings:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"seeAlsoSections":[{"title":"Create Ad Placements","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createNativePlacement(pid:settings:delegate:)"],"generated":true}],"references":{"https://support.teads.tv/support/solutions/articles/36000314722-inread-classic-integration":{"title":"InRead implementation guide","titleInlineContent":[{"type":"text","text":"InRead implementation guide"}],"type":"link","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration","url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate/didReceiveAd(ad:adRatio:)":{"navigatorTitle":[{"kind":"identifier","text":"didReceiveAdWithAd:adRatio:"}],"role":"symbol","title":"didReceiveAd(ad:adRatio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the Teads SDK has received an ad for you to display"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate\/didReceiveAd(ad:adRatio:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate\/didreceivead(ad:adratio:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createInReadPlacement(pid:settings:delegate:)":{"role":"symbol","title":"createInReadPlacement(pid:settings:delegate:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInReadPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TeadsInReadAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacement"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Create an inRead ad placement to request inRead ads"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createInReadPlacementWithPid:settings:delegate:"}],"url":"\/documentation\/teadssdk\/teads\/createinreadplacement(pid:settings:delegate:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate/didFailToReceiveAd(reason:)":{"navigatorTitle":[{"kind":"identifier","text":"didFailToReceiveAdWithReason:"}],"role":"symbol","title":"didFailToReceiveAd(reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdFailReason","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/didFailToReceiveAd(reason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementdelegate\/didfailtoreceivead(reason:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"role":"symbol","title":"TeadsAdPlacementSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"abstract":[{"type":"text","text":"Specify which settings you want to set for your Teads placement."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"url":"\/documentation\/teadssdk\/teadsadplacementsettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacement":{"role":"symbol","title":"TeadsInReadAdPlacement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacement"}],"abstract":[{"type":"text","text":"InRead ad placement to request inRead ads"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacement"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacement"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createNativePlacement(pid:settings:delegate:)":{"role":"symbol","title":"createNativePlacement(pid:settings:delegate:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNativePlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Create a native ad placement to request native ads"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createNativePlacement(pid:settings:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teads\/createnativeplacement(pid:settings:delegate:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","title":"TeadsInReadAdPlacementDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"abstract":[{"type":"text","text":"Delegate methods needed to follow Teads inRead ad requests flow"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createInReadPlacementWithPid:settings:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createInReadPlacementWithPid:settings:delegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"id<TeadsInReadAdPlacement>","preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsInReadAdPlacement"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createInReadPlacementWithPid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pid"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","text":"TeadsAdPlacementSettings"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"settings"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<TeadsInReadAdPlacementDelegate>","preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate~1didReceiveAd(ad:adRatio:)\/title","value":"didReceiveAdWithAd:adRatio:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate~1didReceiveAd(ad:adRatio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveAdWithAd:adRatio:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createInReadPlacement(pid:settings:delegate:)\/title","value":"createInReadPlacementWithPid:settings:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createInReadPlacement(pid:settings:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createInReadPlacementWithPid:settings:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1didFailToReceiveAd(reason:)\/title","value":"didFailToReceiveAdWithReason:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1didFailToReceiveAd(reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFailToReceiveAdWithReason:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","value":"TeadsAdPlacementSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement\/title","value":"TeadsInReadAdPlacement"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdPlacement"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","value":"TeadsInReadAdPlacementDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}