{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/Se","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","variants":[{"paths":["\/documentation\/teadssdk\/obrecommendationresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/obrecommendationresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBRecommendationResponse","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/init(from:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/error","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/recommendations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/request","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/settings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/viewabilityActions"]}],"metadata":{"roleHeading":"Class","title":"OBRecommendationResponse","externalID":"c:@M@TeadsSDK@objc(cs)OBRecommendationResponse","role":"symbol","navigatorTitle":[{"text":"OBRecommendationResponse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBRecommendationResponse","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"TeadsSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/Se"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse/viewabilityActions":{"abstract":[],"title":"viewabilityActions","url":"\/documentation\/teadssdk\/obrecommendationresponse\/viewabilityactions","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewabilityActions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBViewabilityActions","kind":"typeIdentifier","text":"OBViewabilityActions"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/viewabilityActions","navigatorTitle":[{"kind":"identifier","text":"viewabilityActions"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse":{"navigatorTitle":[{"kind":"identifier","text":"OBRecommendationResponse"}],"title":"OBRecommendationResponse","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBRecommendationResponse"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse","url":"\/documentation\/teadssdk\/obrecommendationresponse","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse/init(from:)":{"title":"init(from:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/init(from:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/teadssdk\/obrecommendationresponse\/init(from:)","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse/recommendations":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/recommendations","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recommendations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"OBRecommendation","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBRecommendation"},{"kind":"text","text":"]"}],"role":"symbol","title":"recommendations","url":"\/documentation\/teadssdk\/obrecommendationresponse\/recommendations","navigatorTitle":[{"kind":"identifier","text":"recommendations"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse/error":{"title":"error","url":"\/documentation\/teadssdk\/obrecommendationresponse\/error","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/error","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBError","text":"OBError","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"error","kind":"identifier"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse/request":{"kind":"symbol","abstract":[],"url":"\/documentation\/teadssdk\/obrecommendationresponse\/request","navigatorTitle":[{"text":"request","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/request","role":"symbol","title":"request","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse/settings":{"navigatorTitle":[{"kind":"identifier","text":"settings"}],"title":"settings","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/settings","url":"\/documentation\/teadssdk\/obrecommendationresponse\/settings","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OBRecommendationResponse","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OBRecommendationResponse"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OBRecommendationResponse"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/error","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/recommendations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/request","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/settings","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/viewabilityActions"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBRecommendationResponse"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"viewabilityActions","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1viewabilityActions\/title"},{"value":[{"text":"viewabilityActions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1viewabilityActions\/fragments"},{"value":"OBRecommendationResponse","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/title"},{"value":[{"kind":"identifier","text":"OBRecommendationResponse"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/fragments"},{"value":[{"kind":"identifier","text":"OBRecommendationResponse"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/navigatorTitle"},{"value":"recommendations","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1recommendations\/title"},{"value":[{"kind":"identifier","text":"recommendations"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1recommendations\/fragments"},{"value":"error","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1error\/title"},{"value":[{"text":"error","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1error\/fragments"},{"value":"request","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1request\/title"},{"value":[{"text":"request","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1request\/fragments"},{"value":"settings","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1settings\/title"},{"value":[{"text":"settings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1settings\/fragments"}]}]}