{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView\/init(coder:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView\/init(frame:)"],"title":"Initializers","generated":true,"anchor":"Initializers"}],"abstract":[{"type":"text","text":"Root view inherited by "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","type":"reference","isActive":true},{"type":"text","text":" & "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","type":"reference","isActive":true}],"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s16SendableMetatypeP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdView"}],"roleHeading":"Class","role":"symbol","title":"TeadsAdView","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdView","modules":[{"name":"TeadsSDK"}],"symbolKind":"class","navigatorTitle":[{"text":"TeadsAdView","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdView"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Do not instanciate it by yourself, you should instanciate childs"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadview"]}],"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearance":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdView":{"type":"topic","abstract":[{"type":"text","text":"Root view inherited by "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","isActive":true},{"type":"text","text":" & "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","isActive":true}],"kind":"symbol","title":"TeadsAdView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdView","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdView","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)UIView":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdView/init(coder:)":{"type":"topic","abstract":[],"kind":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/teadssdk\/teadsadview\/init(coder:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView\/init(coder:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","type":"topic","title":"TeadsInReadAdView","url":"\/documentation\/teadssdk\/teadsinreadadview","kind":"symbol","abstract":[{"text":"The Teads inRead ad view is responsible to manage a Teads inRead ad.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://tv.teads.TeadsSDK.TeadsSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIUtilities.UICoordinateSpace"},"doc://tv.teads.TeadsSDK.TeadsSDK/s8SendableP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s16SendableMetatypeP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdView/init(frame:)":{"title":"init(frame:)","url":"\/documentation\/teadssdk\/teadsadview\/init(frame:)","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView\/init(frame:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"kind":"symbol","type":"topic","abstract":[{"text":"The Teads native ad view is responsible to manage a Teads native ad.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdView"}],"title":"TeadsNativeAdView","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdView"}],"url":"\/documentation\/teadssdk\/teadsnativeadview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"TeadsAdView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdView"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdView"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView\/init(coder:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdView\/init(frame:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView"],"type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView"],"type":"inheritedBy"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/title","op":"replace","value":"TeadsAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/fragments","op":"replace","value":[{"text":"TeadsAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdView"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView~1init(coder:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","op":"replace","value":"TeadsInReadAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView~1init(frame:)\/title","op":"replace","value":"initWithFrame:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdView~1init(frame:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title","op":"replace","value":"TeadsNativeAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments","op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdView"}]}]}]}