{"abstract":[{"type":"text","text":"Native ad placement to request native ads"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"metadata":{"role":"symbol","externalID":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"title":"TeadsNativeAdPlacement","symbolKind":"protocol","roleHeading":"Protocol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacement"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacement","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","text":"TeadsAdPlacement"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"From instance reponsible for performing request and is tied to you PID (placement identifier)"},{"type":"text","text":" "},{"type":"text","text":"In order to create placement, call "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createNativePlacement(pid:settings:delegate:)","isActive":true}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You must own\/retain "},{"type":"codeVoice","code":"TeadsNativeAdPlacement"},{"type":"text","text":" instance, otherwise ads could not be delivered properly"}]}],"style":"important","name":"Important","type":"aside"},{"content":[{"inlineContent":[{"type":"text","text":"See "},{"isActive":true,"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314757-native-ad-classic-integration","type":"reference"},{"type":"text","text":" documentation"}],"type":"paragraph"}],"style":"note","name":"Note","type":"aside"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnativeadplacement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsnativeadplacement"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/delegate"],"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)"],"generated":true}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement/requestAd(requestSettings:)":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)","role":"symbol","navigatorTitle":[{"text":"requestAdWithRequestSettings:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsNativeAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23NativeAdRequestSettingsa","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"}],"title":"requestAd(requestSettings:)","kind":"symbol","url":"\/documentation\/teadssdk\/teadsnativeadplacement\/requestad(requestsettings:)","required":true,"abstract":[{"text":"Request a native ad on this placement","type":"text"},{"text":" ","type":"text"},{"text":"listen for events by implementing ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","isActive":true,"type":"reference"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacement":{"type":"topic","title":"TeadsAdPlacement","url":"\/documentation\/teadssdk\/teadsadplacement","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacement","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"TeadsAdPlacement","kind":"identifier"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"title":"TeadsNativeAdPlacementDelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads native ad requests flow"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement":{"abstract":[{"text":"Native ad placement to request native ads","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement","title":"TeadsNativeAdPlacement","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement\/delegate","required":true,"title":"delegate","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/delegate","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"text":"TeadsNativeAdPlacementDelegate to follow ad placement lifecycle","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createNativePlacement(pid:settings:delegate:)":{"kind":"symbol","abstract":[{"text":"Create a native ad placement to request native ads","type":"text"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createNativePlacement(pid:settings:delegate:)","role":"symbol","title":"createNativePlacement(pid:settings:delegate:)","url":"\/documentation\/teadssdk\/teads\/createnativeplacement(pid:settings:delegate:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createNativePlacement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"settings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"TeadsNativeAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"https://support.teads.tv/support/solutions/articles/36000314757-native-ad-classic-integration":{"type":"link","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314757-native-ad-classic-integration","titleInlineContent":[{"type":"text","text":"Native implementation guide"}],"title":"Native implementation guide","url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314757-native-ad-classic-integration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"TeadsNativeAdPlacement","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/delegate"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacement"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacement","kind":"typeIdentifier","text":"TeadsAdPlacement","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"requestAdWithRequestSettings:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1requestAd(requestSettings:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"requestAdWithRequestSettings:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1requestAd(requestSettings:)\/fragments","op":"replace"},{"value":"TeadsAdPlacement","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/title","op":"replace"},{"value":[{"text":"TeadsAdPlacement","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdPlacement"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/navigatorTitle","op":"replace"},{"value":"TeadsNativeAdPlacementDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle","op":"replace"},{"value":"TeadsNativeAdPlacement","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/navigatorTitle","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1delegate\/title","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1delegate\/fragments","op":"replace"}]}]}