{"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"TeadsSDK"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementMedia","title":"TeadsAdPlacementMedia","navigatorTitle":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"roleHeading":"Class"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8CopyableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(_:delegate:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:delegate:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:enableValidationMode:delegate:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/contentView"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/loadAd()"],"anchor":"Instance-Methods"},{"title":"Type Aliases","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/ViewType"],"anchor":"Type-Aliases"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsAdPlacementDelegate-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsAdPlacementIdentifiable-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsInReadAdPlacementDelegate-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsUIViewPlacement-Implementations"],"anchor":"Default-Implementations"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/TeadsAdPlacementDelegate-Implementations":{"title":"TeadsAdPlacementDelegate Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsAdPlacementDelegate-Implementations","abstract":[],"url":"\/documentation\/teadssdk\/teadsadplacementmedia\/teadsadplacementdelegate-implementations","kind":"article"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/init(_:delegate:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(_:delegate:)","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/init(_:delegate:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A22AdPlacementMediaConfigV","text":"TeadsAdPlacementMediaConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate"},{"kind":"text","text":"?)"}],"title":"init(_:delegate:)","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementIdentifiable":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable","url":"\/documentation\/teadssdk\/teadsadplacementidentifiable","title":"TeadsAdPlacementIdentifiable","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"abstract":[],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsLogMessageDelegate":{"url":"\/documentation\/teadssdk\/teadslogmessagedelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"Log delegate enabling you to route every log message written in console into a dedicated area of your choice"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","title":"TeadsLogMessageDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementProtocol":{"role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementProtocol"}],"url":"\/documentation\/teadssdk\/teadsadplacementprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementProtocol"}],"title":"TeadsAdPlacementProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/ViewType":{"type":"topic","role":"symbol","abstract":[{"text":"The specific UIView type this placement returns","type":"text"},{"text":" ","type":"text"},{"text":"Must be a subclass or composition that includes UIView","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/ViewType","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewType","kind":"identifier"}],"kind":"symbol","title":"TeadsAdPlacementMedia.ViewType","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/viewtype","navigatorTitle":[{"text":"ViewType","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate":{"type":"topic","navigatorTitle":[{"text":"TeadsAdPlacementDelegate","kind":"identifier"}],"role":"symbol","title":"TeadsAdPlacementDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementDelegate","kind":"identifier"}],"abstract":[{"text":"Root placement delegate methods needed to follow Teads ad requests flow","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","url":"\/documentation\/teadssdk\/teadsadplacementdelegate","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/init(pid:articleUrl:enableValidationMode:delegate:)":{"url":"\/documentation\/teadssdk\/teadsadplacementmedia\/init(pid:articleurl:enablevalidationmode:delegate:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:enableValidationMode:delegate:)","title":"init(pid:articleUrl:enableValidationMode:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"articleUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"enableValidationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithPid:articleUrl:enableValidationMode:delegate:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/TeadsInReadAdPlacementDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsInReadAdPlacementDelegate-Implementations","title":"TeadsInReadAdPlacementDelegate Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/teadsinreadadplacementdelegate-implementations","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/TeadsAdPlacementIdentifiable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsAdPlacementIdentifiable-Implementations","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/teadsadplacementidentifiable-implementations","type":"topic","role":"collectionGroup","title":"TeadsAdPlacementIdentifiable Implementations"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"kind":"symbol","title":"TeadsAdPlacementMedia","url":"\/documentation\/teadssdk\/teadsadplacementmedia","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads inRead ad requests flow"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","title":"TeadsInReadAdPlacementDelegate","type":"topic","navigatorTitle":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/contentView":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A24AdPlacementContainerViewC","text":"TeadsAdPlacementContainerView","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView","text":"TeadsInReadAdView","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","title":"contentView","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/contentView","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/contentview","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/TeadsUIViewPlacement-Implementations":{"url":"\/documentation\/teadssdk\/teadsadplacementmedia\/teadsuiviewplacement-implementations","title":"TeadsUIViewPlacement Implementations","role":"collectionGroup","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsUIViewPlacement-Implementations","abstract":[],"type":"topic","kind":"article"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsUIViewPlacement":{"abstract":[{"type":"text","text":"Protocol for ad placements that return UIView-based content from loadAd()"}],"kind":"symbol","title":"TeadsUIViewPlacement","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsUIViewPlacement"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsUIViewPlacement"}],"type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teadsuiviewplacement"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/init(pid:articleUrl:delegate:)":{"title":"init(pid:articleUrl:delegate:)","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:delegate:)","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/init(pid:articleurl:delegate:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"articleUrl"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithPid:articleUrl:delegate:","kind":"identifier"}],"abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/s8CopyableP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/loadAd()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"navigatorTitle":[{"text":"loadAdAndReturnError:","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/loadAd()","type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/loadad()","title":"loadAd()","kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"TeadsAdPlacementMedia"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:delegate:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:enableValidationMode:delegate:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/loadAd()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsAdPlacementDelegate-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsAdPlacementIdentifiable-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsInReadAdPlacementDelegate-Implementations"],"anchor":"Default-Implementations"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/title","op":"replace","value":"TeadsAdPlacementIdentifiable"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementIdentifiable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/title","op":"replace","value":"TeadsLogMessageDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/fragments","op":"replace","value":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/navigatorTitle","op":"replace","value":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/title","op":"replace","value":"TeadsAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1init(pid:articleUrl:enableValidationMode:delegate:)\/title","op":"replace","value":"initWithPid:articleUrl:enableValidationMode:delegate:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1init(pid:articleUrl:enableValidationMode:delegate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPid:articleUrl:enableValidationMode:delegate:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title","op":"replace","value":"TeadsAdPlacementMedia"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","op":"replace","value":"TeadsInReadAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle","op":"replace","value":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1init(pid:articleUrl:delegate:)\/title","op":"replace","value":"initWithPid:articleUrl:delegate:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1init(pid:articleUrl:delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPid:articleUrl:delegate:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1loadAd()\/title","op":"replace","value":"loadAdAndReturnError:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1loadAd()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAdAndReturnError:"}]}]}]}