{"variants":[{"paths":["\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/adopportunitytrackerview(trackerview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/adOpportunityTrackerView(trackerView:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view that will monitor your inventory","type":"text"}]}],"name":"trackerView"}],"kind":"parameters"}],"metadata":{"roleHeading":"Instance Method","platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"13.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"13.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.0"}],"role":"symbol","symbolKind":"method","modules":[{"name":"TeadsSDK"}],"externalID":"s:8TeadsSDK0A6InReadV6AdViewV11CoordinatorC020adOpportunityTrackerF007trackerF0yAA0aeijF0C_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adOpportunityTrackerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackerView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView"},{"text":")","kind":"text"}],"title":"adOpportunityTrackerView(trackerView:)"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/adOpportunityTrackerView(trackerView:)":{"role":"symbol","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/adopportunitytrackerview(trackerview:)","abstract":[{"text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/adOpportunityTrackerView(trackerView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","kind":"typeIdentifier","text":"TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"title":"adOpportunityTrackerView(trackerView:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView":{"type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AdView","kind":"identifier"}],"title":"TeadsInRead.AdView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView","url":"\/documentation\/teadssdk\/teadsinread\/adview","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead":{"url":"\/documentation\/teadssdk\/teadsinread","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","title":"TeadsInRead","navigatorTitle":[{"text":"TeadsInRead","kind":"identifier"}],"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInRead","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinator"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"title":"TeadsInRead.AdView.Coordinator","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","navigatorTitle":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","title":"TeadsAdOpportunityTrackerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"abstract":[{"type":"text","text":"adOpportunity is a key metrics to evaluate the performance of your inventory."},{"type":"text","text":" "},{"type":"text","text":"It builds the visibility score of your placement in publisher dashboards."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TeadsAdOpportunityTrackerView","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title"},{"value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments"},{"value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle"}]}]}