{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinator"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"platforms":[{"name":"iOS","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false}],"roleHeading":"Class","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"title":"TeadsInRead.AdView.Coordinator","externalID":"s:8TeadsSDK0A6InReadV6AdViewV11CoordinatorC"},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/adOpportunityTrackerView(trackerView:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/adStartPlayingAudio(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/adStopPlayingAudio(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didCatchError(ad:error:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didClose(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didCollapsedFromFullscreen(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didComplete(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didExpandedToFullscreen(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didFailToReceiveAd(reason:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didLogMessage(message:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didPause(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didPlay(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didReceiveAd(ad:adRatio:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didRecordClick(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didRecordImpression(ad:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didUpdateRatio(ad:adRatio:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/willPresentModalView(ad:)"],"generated":true,"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsinread\/adview\/coordinator"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIViewRepresentable.Coordinator","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate"],"kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didRecordClick(ad:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier","text":"TeadsAd"},{"kind":"text","text":")"}],"title":"didRecordClick(ad:)","kind":"symbol","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didrecordclick(ad:)","abstract":[{"text":"Called when Teads has recorded a clickthrough on an ad.","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didRecordClick(ad:)","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"title":"TeadsInRead.AdView.Coordinator","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator","kind":"symbol","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate","abstract":[{"type":"text","text":"Delegate methods sending informations about Teads ads playback states."}],"url":"\/documentation\/teadssdk\/teadsplaybackdelegate","kind":"symbol","title":"TeadsPlaybackDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/adStartPlayingAudio(_:)":{"title":"adStartPlayingAudio(_:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/adStartPlayingAudio(_:)","abstract":[{"type":"text","text":"Called when an ad starts playing audio."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStartPlayingAudio","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/adstartplayingaudio(_:)","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didExpandedToFullscreen(ad:)":{"role":"symbol","type":"topic","title":"didExpandedToFullscreen(ad:)","abstract":[{"text":"Called when an ad is shown in fullscreen.","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didExpandedToFullscreen(ad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didExpandedToFullscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd"},{"kind":"text","text":")"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didexpandedtofullscreen(ad:)","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didReceiveAd(ad:adRatio:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didReceiveAd(ad:adRatio:)","title":"didReceiveAd(ad:adRatio:)","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didreceivead(ad:adratio:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Called when the Teads SDK has received an ad for you to display","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceiveAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd","text":"TeadsInReadAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsLogMessageDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","abstract":[{"text":"Log delegate enabling you to route every log message written in console into a dedicated area of your choice","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"role":"symbol","type":"topic","title":"TeadsLogMessageDelegate","kind":"symbol","url":"\/documentation\/teadssdk\/teadslogmessagedelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdDelegate","kind":"symbol","url":"\/documentation\/teadssdk\/teadsaddelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads ads lifecycle."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdDelegate"}],"type":"topic","title":"TeadsAdDelegate","navigatorTitle":[{"kind":"identifier","text":"TeadsAdDelegate"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didCatchError(ad:error:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCatchError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"didCatchError(ad:error:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didCatchError(ad:error:)","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didcatcherror(ad:error:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Called when the ad has encountered an issue, in this case you need to remove the slot or you will have a blank space."}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didRecordImpression(ad:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd"},{"kind":"text","text":")"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didRecordImpression(ad:)","title":"didRecordImpression(ad:)","abstract":[{"type":"text","text":"Called when the Teads SDK has recorded an impression for an ad."}],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didrecordimpression(ad:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didUpdateRatio(ad:adRatio:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didUpdateRatio(ad:adRatio:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called when the Teads SDK needs you to resize your adView the creative inform us of its new ratio"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didupdateratio(ad:adratio:)","kind":"symbol","role":"symbol","title":"didUpdateRatio(ad:adRatio:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didCollapsedFromFullscreen(ad:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCollapsedFromFullscreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Called when an ad leaves the fullscreen mode.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didCollapsedFromFullscreen(ad:)","title":"didCollapsedFromFullscreen(ad:)","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didcollapsedfromfullscreen(ad:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/adOpportunityTrackerView(trackerView:)":{"abstract":[{"text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory.","type":"text"}],"title":"adOpportunityTrackerView(trackerView:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/adOpportunityTrackerView(trackerView:)","role":"symbol","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/adopportunitytrackerview(trackerview:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adOpportunityTrackerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackerView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView"},{"text":")","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead":{"navigatorTitle":[{"kind":"identifier","text":"TeadsInRead"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInRead"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","title":"TeadsInRead","url":"\/documentation\/teadssdk\/teadsinread"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didPause(_:)":{"abstract":[{"text":"Called when an ad has been paused.","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didPause(_:)","role":"symbol","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didpause(_:)","type":"topic","title":"didPause(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPause"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier","text":"TeadsAd"},{"kind":"text","text":")"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didComplete(_:)":{"title":"didComplete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didComplete"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier","text":"TeadsAd"},{"kind":"text","text":")"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didcomplete(_:)","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didComplete(_:)","type":"topic","abstract":[{"text":"Called when an ad has ended.","type":"text"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView":{"title":"TeadsInRead.AdView","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdView","kind":"identifier"}],"navigatorTitle":[{"text":"AdView","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","navigatorTitle":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}],"title":"TeadsInReadAdPlacementDelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads inRead ad requests flow"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didFailToReceiveAd(reason:)":{"kind":"symbol","abstract":[{"type":"text","text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter"}],"type":"topic","title":"didFailToReceiveAd(reason:)","role":"symbol","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didfailtoreceivead(reason:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFailToReceiveAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason","text":"AdFailReason","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didFailToReceiveAd(reason:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/adStopPlayingAudio(_:)":{"kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/adstopplayingaudio(_:)","abstract":[{"type":"text","text":"Called when an ad stops playing audio."}],"title":"adStopPlayingAudio(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStopPlayingAudio","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/adStopPlayingAudio(_:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didClose(ad:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didClose(ad:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didclose(ad:)","title":"didClose(ad:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Called when the ad has been close, in this case you need to close the slot or you will have a blank space."}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate":{"kind":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementDelegate","kind":"identifier"}],"title":"TeadsAdPlacementDelegate","abstract":[{"text":"Root placement delegate methods needed to follow Teads ad requests flow","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadplacementdelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementDelegate","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didLogMessage(message:)":{"title":"didLogMessage(message:)","abstract":[{"type":"text","text":"Called each time TeadsSDK triggers a log message"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didLogMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didlogmessage(message:)","kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didLogMessage(message:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/willPresentModalView(ad:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when an ad wants to present a view controller modally (e.g. safariViewController for call to action or the full screen controller)."}],"title":"willPresentModalView(ad:)","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/willpresentmodalview(ad:)","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/willPresentModalView(ad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPresentModalView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator/didPlay(_:)":{"type":"topic","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator\/didplay(_:)","title":"didPlay(_:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator\/didPlay(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didPlay","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Called when an ad has started or resumed.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/title","value":"TeadsPlaybackDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/fragments","value":[{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/title","value":"TeadsLogMessageDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/fragments","value":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/navigatorTitle","value":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/title","value":"TeadsAdDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/fragments","value":[{"text":"TeadsAdDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdDelegate\/navigatorTitle","value":[{"text":"TeadsAdDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","value":"TeadsInReadAdPlacementDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/title","value":"TeadsAdPlacementDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"op":"replace"}]}]}