{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIViewRepresentable.updateUIView(_:context:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView","text":"TeadsInReadAdView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","text":"Context","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsInReadAdView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Context","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false}],"modules":[{"name":"TeadsSDK"}],"symbolKind":"method","title":"updateUIView(_:context:)","role":"symbol","roleHeading":"Instance Method","externalID":"s:8TeadsSDK0A6InReadV6AdViewV12updateUIView_7contextyAA0acdeF0C_7SwiftUI0H20RepresentableContextVyAEGtF"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/updateUIView(_:context:)"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsinread\/adview\/updateuiview(_:context:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/updateUIView(_:context:)":{"title":"updateUIView(_:context:)","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/updateUIView(_:context:)","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/teadssdk\/teadsinread\/adview\/updateuiview(_:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUIView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TeadsInReadAdView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Context","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta"},{"kind":"text","text":")"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead":{"navigatorTitle":[{"kind":"identifier","text":"TeadsInRead"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInRead"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","title":"TeadsInRead","url":"\/documentation\/teadssdk\/teadsinread"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView":{"title":"TeadsInRead.AdView","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdView","kind":"identifier"}],"navigatorTitle":[{"text":"AdView","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsinread\/adview","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"kind":"symbol","url":"\/documentation\/teadssdk\/teadsinreadadview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"type":"topic","role":"symbol","title":"TeadsInReadAdView","navigatorTitle":[{"text":"TeadsInReadAdView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","value":"TeadsInReadAdView","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsInReadAdView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}