{"metadata":{"symbolKind":"init","title":"init(placement:nativeAdViewHeight:content:)","role":"symbol","externalID":"s:8TeadsSDK0A6NativeV6AdViewV9placement06nativedE6Height7contentAEy_xG7SwiftUI7BindingVyAA0acD9Placement_pSgG_ALy14CoreFoundation7CGFloatVGxAA0acD0Cctcfc","modules":[{"name":"TeadsSDK"}],"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"placement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"text":"TeadsNativeAdPlacement","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement"},{"text":"?>, ","kind":"text"},{"text":"nativeAdViewHeight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":">, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TeadsNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd"},{"text":") -> ","kind":"text"},{"text":"Content","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV6AdViewV7Contentxmfp"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"placement","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","text":"TeadsNativeAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement","kind":"typeIdentifier"},{"text":"?>, ","kind":"text"},{"text":"nativeAdViewHeight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:7SwiftUI11ViewBuilderV","text":"ViewBuilder","kind":"attribute"},{"text":" ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","text":"TeadsNativeAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A6NativeV6AdViewV7Contentxmfp","text":"Content","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"placement","content":[{"inlineContent":[{"text":"Binding native placement","type":"text"}],"type":"paragraph"}]},{"name":"nativeAdViewHeight","content":[{"type":"paragraph","inlineContent":[{"text":"Height of the ad to apply to the overall view","type":"text"}]}]},{"name":"content","content":[{"inlineContent":[{"text":"A view that describes the purpose natve ad.","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Teads Native ad constructor","type":"text"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/init(placement:nativeAdViewHeight:content:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsnative\/adview\/init(placement:nativeadviewheight:content:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView":{"navigatorTitle":[{"kind":"identifier","text":"AdView"}],"title":"TeadsNative.AdView","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdView"}],"abstract":[{"type":"text","text":"The AdView is responsible to manage manage a Teads native ad."}],"url":"\/documentation\/teadssdk\/teadsnative\/adview","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/init(placement:nativeAdViewHeight:content:)":{"abstract":[{"text":"Teads Native ad constructor","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/init(placement:nativeAdViewHeight:content:)","title":"init(placement:nativeAdViewHeight:content:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"placement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement","text":"TeadsNativeAdPlacement"},{"kind":"text","text":"?>, "},{"kind":"externalParam","text":"nativeAdViewHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nativeAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV6AdViewV7Contentxmfp","text":"Content"},{"kind":"text","text":")"}],"url":"\/documentation\/teadssdk\/teadsnative\/adview\/init(placement:nativeadviewheight:content:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"url":"\/documentation\/teadssdk\/teadsnativead","abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"type":"topic","title":"TeadsNativeAd","kind":"symbol","navigatorTitle":[{"text":"TeadsNativeAd","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","title":"TeadsNative","url":"\/documentation\/teadssdk\/teadsnative","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement":{"title":"TeadsNativeAdPlacement","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","navigatorTitle":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement","kind":"symbol","abstract":[{"text":"Native ad placement to request native ads","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TeadsNativeAd","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title"},{"value":[{"kind":"identifier","text":"TeadsNativeAd"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments"},{"value":[{"text":"TeadsNativeAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"},{"value":"TeadsNativeAdPlacement","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/title"},{"value":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/fragments"},{"value":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/navigatorTitle"}]}]}