{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent\/loadImage(async:success:failure:)","interfaceLanguage":"swift"},"abstract":[{"text":"Loads Image data content asynchronously depending on the needs","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"async","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"text":"success","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"failure","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"async","content":[{"inlineContent":[{"type":"text","text":"Default value is true, image data loading will be performed asynchronously (very recommanded) otherwise the loading is performed synchronously (thread blocking)"}],"type":"paragraph"}]},{"name":"success","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Closure will be called once image data has been successfully loaded"}]}]},{"name":"failure","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Failure will be called when image loading has failed: can fail for multiple reasong connectivity, resource unavailable, …"}]}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"name":"Warning","style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Specifying ","type":"text"},{"type":"codeVoice","code":"async"},{"text":" parameter to false will block thread execution","type":"text"}]}]},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"We strongly encourage to use this method to retrieve content and associate with "},{"type":"codeVoice","code":"UIImageView"}],"type":"paragraph"}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent"]]},"variants":[{"paths":["\/documentation\/teadssdk\/imagecomponent\/loadimage(async:success:failure:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/imagecomponent\/loadimage(async:success:failure:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"loadImageWithAsync:success:failure:","kind":"identifier"}],"title":"loadImage(async:success:failure:)","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"async","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"success","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"failure","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@TeadsSDK@objc(cs)ImageComponent(im)loadImageWithAsync:success:failure:","modules":[{"name":"TeadsSDK"}]},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent":{"abstract":[{"text":"Native image component containing image url","type":"text"}],"url":"\/documentation\/teadssdk\/imagecomponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","kind":"symbol","navigatorTitle":[{"text":"ImageComponent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageComponent","kind":"identifier"}],"type":"topic","title":"ImageComponent","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent/loadImage(async:success:failure:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent\/loadImage(async:success:failure:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"async","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"success","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"failure","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/teadssdk\/imagecomponent\/loadimage(async:success:failure:)","type":"topic","title":"loadImage(async:success:failure:)","kind":"symbol","navigatorTitle":[{"text":"loadImageWithAsync:success:failure:","kind":"identifier"}],"abstract":[{"text":"Loads Image data content asynchronously depending on the needs","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"loadImageWithAsync:success:failure:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadImageWithAsync:success:failure:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadImageWithAsync:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"success:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"success","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"failure:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"failure","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Default value is true, image data loading will be performed asynchronously (very recommanded) otherwise the loading is performed synchronously (thread blocking)"}],"type":"paragraph"}],"name":"async"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Closure will be called once image data has been successfully loaded"}]}],"name":"success"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Failure will be called when image loading has failed: can fail for multiple reasong connectivity, resource unavailable, …","type":"text"}]}],"name":"failure"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/title","op":"replace","value":"ImageComponent"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/fragments","op":"replace","value":[{"text":"ImageComponent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ImageComponent"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent~1loadImage(async:success:failure:)\/title","op":"replace","value":"loadImageWithAsync:success:failure:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent~1loadImage(async:success:failure:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadImageWithAsync:success:failure:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}