{"variants":[{"paths":["\/documentation\/teadssdk\/imagecomponent\/loadimage()"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"TeadsSDK"}],"externalID":"s:8TeadsSDK14ImageComponentC04loadC0So7UIImageCyYaKF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"}],"role":"symbol","title":"loadImage()","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"13.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"13.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"13.0","beta":false}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent\/loadImage()"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent"]]},"abstract":[{"type":"text","text":"Loads image data asynchronously using async\/await concurrency instead of closures"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadImage","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}]}],"kind":"declarations"},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"UIImage data representation when succeed to load","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"A loading error when failting to get resource for multiple reasons such as connectivity, unavailable resources","type":"text"}]}],"type":"aside"}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent":{"abstract":[{"text":"Native image component containing image url","type":"text"}],"url":"\/documentation\/teadssdk\/imagecomponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","kind":"symbol","navigatorTitle":[{"text":"ImageComponent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageComponent","kind":"identifier"}],"type":"topic","title":"ImageComponent","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent/loadImage()":{"kind":"symbol","title":"loadImage()","role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent\/loadImage()","abstract":[{"text":"Loads image data asynchronously using async\/await concurrency instead of closures","type":"text"}],"url":"\/documentation\/teadssdk\/imagecomponent\/loadimage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/title","value":"ImageComponent"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/fragments","value":[{"kind":"identifier","text":"ImageComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/navigatorTitle","value":[{"text":"ImageComponent","kind":"identifier"}]}]}]}