{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The default value for "},{"type":"text","text":"TeadsAdRatio"},{"type":"text","text":" "},{"type":"text","text":"note:"},{"type":"text","text":" "},{"type":"text","text":"usually 16:9 HDTV aspect ratio"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio"]]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadratio\/default_"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Property","role":"symbol","symbolKind":"property","fragments":[{"text":"default_","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio(cpy)default_","title":"default_","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"default_"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio\/default_","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"default","kind":"identifier"},{"text":") ","kind":"text"},{"text":"TeadsAdRatio","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":" * ","kind":"text"},{"text":"default_","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio":{"title":"TeadsAdRatio","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","url":"\/documentation\/teadssdk\/teadsadratio","abstract":[{"text":"This class is used to help in resizing a given ad view to a given aspect ratio.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdRatio"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdRatio"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio/default_":{"abstract":[{"text":"The default value for ","type":"text"},{"text":"TeadsAdRatio","type":"text"},{"text":" ","type":"text"},{"text":"note:","type":"text"},{"text":" ","type":"text"},{"text":"usually 16:9 HDTV aspect ratio","type":"text"}],"type":"topic","fragments":[{"kind":"identifier","text":"default_"}],"url":"\/documentation\/teadssdk\/teadsadratio\/default_","kind":"symbol","title":"default_","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio\/default_","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"TeadsAdRatio","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/title","op":"replace"},{"value":[{"text":"TeadsAdRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/fragments","op":"replace"},{"value":[{"text":"TeadsAdRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}