{"abstract":[{"type":"text","text":"Teads’ AdChoices element"}],"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnativead\/adchoices"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsnativead\/adchoices"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adChoices"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","kind":"typeIdentifier","text":"AdChoicesComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdChoicesComponent"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","type":"reference"},{"type":"text","text":" property represents advertiser’s url"}],"type":"paragraph"}]}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd(py)adChoices","role":"symbol","roleHeading":"Instance Property","title":"adChoices","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"adChoices","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adChoices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdChoicesComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdChoicesComponent"},{"kind":"text","text":"?"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/adChoices","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent":{"title":"AdChoicesComponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdChoicesComponent","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AdChoicesComponent","kind":"identifier"}],"url":"\/documentation\/teadssdk\/adchoicescomponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","abstract":[{"type":"text","text":"Native Component containing AdChoices "},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd/adChoices":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/adChoices","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adChoices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdChoicesComponent","text":"AdChoicesComponent"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"adChoices","kind":"identifier"}],"abstract":[{"type":"text","text":"Teads’ AdChoices element"}],"url":"\/documentation\/teadssdk\/teadsnativead\/adchoices","title":"adChoices"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent/clickThroughUrl":{"title":"clickThroughUrl","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clickThroughUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"role":"symbol","kind":"symbol","url":"\/documentation\/teadssdk\/adchoicescomponent\/clickthroughurl","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","abstract":[{"text":"Reach the URL that should be used when the ‘Ad Choices’ button is tapped.","type":"text"},{"text":" ","type":"text"},{"text":"Common behavior: open a Safari Web Browser with ","type":"text"},{"type":"codeVoice","code":"clickThroughUrl"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"url":"\/documentation\/teadssdk\/teadsnativead","abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"type":"topic","title":"TeadsNativeAd","kind":"symbol","navigatorTitle":[{"text":"TeadsNativeAd","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"adChoices"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"adChoices","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdChoicesComponent","text":"AdChoicesComponent","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent"},{"text":" * ","kind":"text"},{"text":"adChoices","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/title","value":"AdChoicesComponent"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/fragments","value":[{"text":"AdChoicesComponent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/navigatorTitle","value":[{"kind":"identifier","text":"AdChoicesComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd~1adChoices\/title","value":"adChoices"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd~1adChoices\/fragments","value":[{"text":"adChoices","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title","value":"TeadsNativeAd"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments","value":[{"text":"TeadsNativeAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsNativeAd"}]}]}]}