{"abstract":[{"text":"Main image element of ad, usually corresponds to main media content","type":"text"},{"text":" ","type":"text"},{"text":"Large image preview for the ad","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)ImageComponent","text":"ImageComponent"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent\/url","isActive":true},{"type":"text","text":" property"}],"type":"paragraph"}]},{"name":"Note","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can call "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent\/loadImage(async:success:failure:)","type":"reference","isActive":true},{"type":"text","text":" to get "},{"type":"codeVoice","code":"UImage"}]}]}],"kind":"content"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)ImageComponent","text":"ImageComponent"},{"kind":"text","text":"?"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"image"}],"modules":[{"name":"TeadsSDK"}],"title":"image","externalID":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd(py)image","role":"symbol","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnativead\/image"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsnativead\/image"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/image"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd/image":{"title":"image","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)ImageComponent","kind":"typeIdentifier","text":"ImageComponent"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"image"}],"abstract":[{"text":"Main image element of ad, usually corresponds to main media content","type":"text"},{"text":" ","type":"text"},{"text":"Large image preview for the ad","type":"text"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsnativead\/image"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent/loadImage(async:success:failure:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent\/loadImage(async:success:failure:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"async","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"success","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"failure","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/teadssdk\/imagecomponent\/loadimage(async:success:failure:)","type":"topic","title":"loadImage(async:success:failure:)","kind":"symbol","navigatorTitle":[{"text":"loadImageWithAsync:success:failure:","kind":"identifier"}],"abstract":[{"text":"Loads Image data content asynchronously depending on the needs","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent":{"abstract":[{"text":"Native image component containing image url","type":"text"}],"url":"\/documentation\/teadssdk\/imagecomponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","kind":"symbol","navigatorTitle":[{"text":"ImageComponent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageComponent","kind":"identifier"}],"type":"topic","title":"ImageComponent","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent/url":{"abstract":[{"type":"text","text":"image URL"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent\/url","role":"symbol","url":"\/documentation\/teadssdk\/imagecomponent\/url","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"title":"url","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"url":"\/documentation\/teadssdk\/teadsnativead","abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"type":"topic","title":"TeadsNativeAd","kind":"symbol","navigatorTitle":[{"text":"TeadsNativeAd","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"image","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"image"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)ImageComponent","text":"ImageComponent","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent"},{"text":" * ","kind":"text"},{"text":"image","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"image","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd~1image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"image"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd~1image\/fragments"},{"op":"replace","value":"loadImageWithAsync:success:failure:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent~1loadImage(async:success:failure:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadImageWithAsync:success:failure:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent~1loadImage(async:success:failure:)\/fragments"},{"op":"replace","value":"ImageComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/title"},{"op":"replace","value":[{"text":"ImageComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/fragments"},{"op":"replace","value":[{"text":"ImageComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/navigatorTitle"},{"op":"replace","value":"TeadsNativeAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments"},{"op":"replace","value":[{"text":"TeadsNativeAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"}]}]}