{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadapterintegrationtype\/admob"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType"]]},"metadata":{"symbolKind":"property","modules":[{"name":"TeadsSDK"}],"roleHeading":"Type Property","externalID":"s:8TeadsSDK0A22AdapterIntegrationTypeC5adMobACvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adMob","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TeadsAdapterIntegrationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType"}],"title":"adMob","role":"symbol"},"abstract":[{"text":"AdMob\/GAM mediation value to monitor adapter integration ","type":"text"},{"type":"codeVoice","code":"TeadsAdMobAdapter"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType\/adMob","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adMob","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TeadsAdapterIntegrationType","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"content":[{"inlineContent":[{"type":"text","text":"Adapters internal purpose only"}],"type":"paragraph"}],"style":"important","name":"Important","type":"aside"}]}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType/adMob":{"title":"adMob","type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType\/adMob","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"adMob"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType","kind":"typeIdentifier","text":"TeadsAdapterIntegrationType"}],"abstract":[{"type":"text","text":"AdMob\/GAM mediation value to monitor adapter integration "},{"type":"codeVoice","code":"TeadsAdMobAdapter"}],"url":"\/documentation\/teadssdk\/teadsadapterintegrationtype\/admob"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType":{"title":"TeadsAdapterIntegrationType","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterIntegrationType"}],"abstract":[{"type":"text","text":"Never create your own TeadsAdapterIntegrationType directly. Use one of the predefined standard values."}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","url":"\/documentation\/teadssdk\/teadsadapterintegrationtype","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterIntegrationType"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/title","value":"TeadsAdapterIntegrationType"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/fragments","value":[{"kind":"identifier","text":"TeadsAdapterIntegrationType"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdapterIntegrationType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}