{"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate\/adPlacement(_:didEmitEvent:data:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adPlacement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TeadsAdPlacementIdentifiable","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didEmitEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementEventName","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adPlacement:didEmitEvent:data:"}],"modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate(im)adPlacement:didEmitEvent:data:","roleHeading":"Instance Method","title":"adPlacement(_:didEmitEvent:data:)","required":true,"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"placement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable","text":"TeadsAdPlacementIdentifiable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didEmitEvent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName","text":"TeadsAdPlacementEventName","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementeventsdelegate\/adplacement(_:didemitevent:data:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementeventsdelegate\/adplacement(_:didemitevent:data:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate/adPlacement(_:didEmitEvent:data:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adPlacement:didEmitEvent:data:"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate\/adPlacement(_:didEmitEvent:data:)","title":"adPlacement(_:didEmitEvent:data:)","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate\/adplacement(_:didemitevent:data:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable","text":"TeadsAdPlacementIdentifiable","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"didEmitEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName","text":"TeadsAdPlacementEventName","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"type":"topic","required":true},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"abstract":[],"kind":"symbol","title":"TeadsAdPlacementEventsDelegate","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementIdentifiable":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable","url":"\/documentation\/teadssdk\/teadsadplacementidentifiable","title":"TeadsAdPlacementIdentifiable","type":"topic","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName":{"role":"symbol","kind":"symbol","title":"TeadsAdPlacementEventName","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventName"}],"type":"topic","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName","url":"\/documentation\/teadssdk\/teadsadplacementeventname","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventName"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"adPlacement:didEmitEvent:data:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adPlacement:didEmitEvent:data:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adPlacement:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable","text":"id<TeadsAdPlacementIdentifiable>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"placement","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didEmitEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName","text":"TeadsAdPlacementEventName","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"data:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"adPlacement:didEmitEvent:data:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate~1adPlacement(_:didEmitEvent:data:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"adPlacement:didEmitEvent:data:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate~1adPlacement(_:didEmitEvent:data:)\/fragments","op":"replace"},{"value":"TeadsAdPlacementEventsDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/title","value":"TeadsAdPlacementIdentifiable"},{"value":[{"text":"TeadsAdPlacementIdentifiable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/fragments"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/navigatorTitle"},{"value":"TeadsAdPlacementEventName","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/title"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementEventName"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/fragments"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementEventName"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/navigatorTitle"}]}]}