{"metadata":{"symbolKind":"init","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(cs)OBError(im)initWithType:message:code:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorType","text":"OBErrorType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OBErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorCode"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithType:message:code:","kind":"identifier"}],"title":"init(type:message:code:)","roleHeading":"Initializer","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/teadssdk\/oberror\/init(type:message:code:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/oberror\/init(type:message:code:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError\/init(type:message:code:)"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType","text":"OBErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorType"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode","text":"OBErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorCode"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBError":{"abstract":[],"navigatorTitle":[{"text":"OBError","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/teadssdk\/oberror","title":"OBError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBError","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBError/init(type:message:code:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError\/init(type:message:code:)","abstract":[],"title":"init(type:message:code:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorType","text":"OBErrorType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorCode","text":"OBErrorCode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithType:message:code:"}],"url":"\/documentation\/teadssdk\/oberror\/init(type:message:code:)","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType","title":"OBErrorType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"OBErrorType"}],"url":"\/documentation\/teadssdk\/oberrortype","kind":"symbol","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorCode":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OBErrorCode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBErrorCode"}],"title":"OBErrorCode","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/oberrorcode"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithType:message:code:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:message:code:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorType","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType","kind":"typeIdentifier","text":"OBErrorType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"code:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorCode","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode","kind":"typeIdentifier","text":"OBErrorCode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"code"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OBError","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/title"},{"value":[{"kind":"identifier","text":"OBError"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/fragments"},{"value":[{"text":"OBError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/navigatorTitle"},{"value":"initWithType:message:code:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError~1init(type:message:code:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:message:code:"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError~1init(type:message:code:)\/fragments"},{"value":"OBErrorType","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType\/title"},{"value":[{"kind":"identifier","text":"OBErrorType"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType\/fragments"},{"value":[{"text":"OBErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType\/navigatorTitle"},{"value":"OBErrorCode","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/title"},{"value":[{"text":"OBErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/fragments"},{"value":[{"text":"OBErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}