{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/oberror\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"TeadsSDK","relatedModules":["Swift"]}],"title":"localizedDescription","symbolKind":"property","role":"symbol","extendedModule":"Swift","roleHeading":"Instance Property","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::c:@M@TeadsSDK@objc(cs)OBError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"8.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"8.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"8.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.10"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"9.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"watchOS","introducedAt":"2.0"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError\/localizedDescription"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Error.localizedDescription"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBError/localizedDescription":{"title":"localizedDescription","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError\/localizedDescription","url":"\/documentation\/teadssdk\/oberror\/localizeddescription","role":"symbol","type":"topic","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBError":{"abstract":[],"navigatorTitle":[{"text":"OBError","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/teadssdk\/oberror","title":"OBError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBError","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/title","op":"replace","value":"OBError"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/fragments","op":"replace","value":[{"text":"OBError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/navigatorTitle","op":"replace","value":[{"text":"OBError","kind":"identifier"}]}]}]}