{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/didReceiveAd(_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"TeadsSDK"}],"symbolKind":"method","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false}],"title":"didReceiveAd(_:)","externalID":"s:8TeadsSDK0A6InReadV6AdViewV010didReceiveE0yAEyAA0aE5RatioCcF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceiveAd","kind":"identifier"},{"text":"((","kind":"text"},{"text":"TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"TeadsInRead","preciseIdentifier":"s:8TeadsSDK0A6InReadV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"AdView","preciseIdentifier":"s:8TeadsSDK0A6InReadV6AdViewV","kind":"typeIdentifier"}]},"abstract":[{"text":"Called when the Teads SDK has received an ad for you to display","type":"text"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsinread\/adview\/didreceivead(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceiveAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"closure","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","text":"TeadsInRead","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6InReadV"},{"text":".","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView","text":"AdView","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6InReadV6AdViewV"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Declare a state variable"}]},{"code":["@State private var slotHeight: CGFloat = 0.0"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"slotHeight"},{"type":"text","text":" must be applied to the overall View"}]},{"code":["TeadsInRead.AdView(placement: $inReadAdPlacement) {","\/\/...","}",".frame(height: slotHeight)"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"When it called it is the right place to update your view ratio. A basic implementation may look litke this:"}]},{"code":["didReceiveAd { _, adRatio in","    slotHeight = adRatio.calculateHeight(for: rect.size.width)","}"],"type":"codeListing","syntax":null}],"kind":"content"}],"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead":{"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInRead","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsinread","navigatorTitle":[{"text":"TeadsInRead","kind":"identifier"}],"title":"TeadsInRead"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/didReceiveAd(_:)":{"type":"topic","url":"\/documentation\/teadssdk\/teadsinread\/adview\/didreceivead(_:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/didReceiveAd(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceiveAd","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A6InReadV","text":"TeadsInRead","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A6InReadV6AdViewV","text":"AdView","kind":"typeIdentifier"}],"title":"didReceiveAd(_:)","kind":"symbol","abstract":[{"text":"Called when the Teads SDK has received an ad for you to display","type":"text"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView":{"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView","abstract":[],"url":"\/documentation\/teadssdk\/teadsinread\/adview","type":"topic","title":"TeadsInRead.AdView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdView"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdView"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio":{"type":"topic","url":"\/documentation\/teadssdk\/teadsadratio","abstract":[{"type":"text","text":"This class is used to help in resizing a given ad view to a given aspect ratio."}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRatio","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdRatio","kind":"identifier"}],"title":"TeadsAdRatio"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/title","value":"TeadsAdRatio","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/fragments","value":[{"text":"TeadsAdRatio","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/navigatorTitle","value":[{"text":"TeadsAdRatio","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}