{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/makeUIView(context:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIViewRepresentable.makeUIView(context:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnative\/adview\/makeuiview(context:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","kind":"typeIdentifier","text":"Context"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView","kind":"typeIdentifier","text":"TeadsNativeAdView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Context","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta"},{"text":") -> ","kind":"text"},{"text":"TeadsNativeAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView"}],"title":"makeUIView(context:)","role":"symbol","externalID":"s:8TeadsSDK0A6NativeV6AdViewV10makeUIView7contextAA0acdE0C7SwiftUI0G20RepresentableContextVyAEy_xGG_tF","modules":[{"name":"TeadsSDK"}],"symbolKind":"method","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"13.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"13.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.0"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"url":"\/documentation\/teadssdk\/teadsnative","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNative"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsNative"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","abstract":[],"type":"topic","role":"symbol","title":"TeadsNative","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"navigatorTitle":[{"text":"TeadsNativeAdView","kind":"identifier"}],"title":"TeadsNativeAdView","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","abstract":[{"text":"The Teads native ad view is responsible to manage a Teads native ad.","type":"text"}],"url":"\/documentation\/teadssdk\/teadsnativeadview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView":{"type":"topic","navigatorTitle":[{"text":"AdView","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView","title":"TeadsNative.AdView","url":"\/documentation\/teadssdk\/teadsnative\/adview","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdView","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The AdView is responsible to manage manage a Teads native ad."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/makeUIView(context:)":{"type":"topic","kind":"symbol","role":"symbol","title":"makeUIView(context:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","kind":"typeIdentifier","text":"Context"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView","kind":"typeIdentifier","text":"TeadsNativeAdView"}],"url":"\/documentation\/teadssdk\/teadsnative\/adview\/makeuiview(context:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/makeUIView(context:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title","op":"replace","value":"TeadsNativeAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments","op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}