{"variants":[{"paths":["\/documentation\/teadssdk\/teadsnativeadplacementdelegate\/didreceivead(ad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsnativeadplacementdelegate\/didreceivead(ad:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didReceiveAd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd"},{"kind":"text","text":")"}],"externalID":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate(im)didReceiveAdWithAd:","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didReceiveAdWithAd:"}],"roleHeading":"Instance Method","title":"didReceiveAd(ad:)"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceiveAd"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsNativeAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The teadsAd object"}]}]}]}],"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate\/didReceiveAd(ad:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the Teads SDK has received an ad for you to display"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"type":"topic","navigatorTitle":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"kind":"symbol","title":"TeadsNativeAdPlacementDelegate","url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads native ad requests flow"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate/didReceiveAd(ad:)":{"kind":"symbol","navigatorTitle":[{"text":"didReceiveAdWithAd:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceiveAd"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd"},{"text":")","kind":"text"}],"type":"topic","title":"didReceiveAd(ad:)","abstract":[{"type":"text","text":"Called when the Teads SDK has received an ad for you to display"}],"required":true,"url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate\/didreceivead(ad:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate\/didReceiveAd(ad:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsnativead","title":"TeadsNativeAd","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAd"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"didReceiveAdWithAd:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didReceiveAdWithAd:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"didReceiveAdWithAd:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","text":"TeadsNativeAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ad","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":{"parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"text":"The teadsAd object","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"TeadsNativeAdPlacementDelegate","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title"},{"op":"replace","value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments"},{"op":"replace","value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate~1didReceiveAd(ad:)\/title","value":"didReceiveAdWithAd:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate~1didReceiveAd(ad:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveAdWithAd:"}],"op":"replace"},{"value":"TeadsNativeAd","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments","value":[{"text":"TeadsNativeAd","kind":"identifier"}]},{"op":"replace","value":[{"text":"TeadsNativeAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"}]}]}