{"metadata":{"modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Property","title":"recommendations","externalID":"c:@M@TeadsSDK@objc(cs)OBRecommendationResponse(py)recommendations","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"recommendations"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recommendations"},{"kind":"text","text":": ["},{"text":"OBRecommendation","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBRecommendation"},{"text":"]","kind":"text"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/teadssdk\/obrecommendationresponse\/recommendations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/obrecommendationresponse\/recommendations"]}],"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/recommendations","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recommendations"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBRecommendation","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation","text":"OBRecommendation"},{"kind":"text","text":"]"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendation":{"type":"topic","title":"OBRecommendation","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation","url":"\/documentation\/teadssdk\/obrecommendation","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBRecommendation","kind":"identifier"}],"navigatorTitle":[{"text":"OBRecommendation","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse":{"url":"\/documentation\/teadssdk\/obrecommendationresponse","navigatorTitle":[{"kind":"identifier","text":"OBRecommendationResponse"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBRecommendationResponse"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse","title":"OBRecommendationResponse","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse/recommendations":{"url":"\/documentation\/teadssdk\/obrecommendationresponse\/recommendations","navigatorTitle":[{"text":"recommendations","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/recommendations","title":"recommendations","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recommendations","kind":"identifier"},{"text":": [","kind":"text"},{"text":"OBRecommendation","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBRecommendation","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recommendations"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"recommendations","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<OBRecommendation *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recommendations"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/title","value":"OBRecommendation"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/fragments","value":[{"kind":"identifier","text":"OBRecommendation"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/navigatorTitle","value":[{"kind":"identifier","text":"OBRecommendation"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/title","value":"OBRecommendationResponse"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/fragments","value":[{"text":"OBRecommendationResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/navigatorTitle","value":[{"kind":"identifier","text":"OBRecommendationResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1recommendations\/title","value":"recommendations"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1recommendations\/fragments","value":[{"text":"recommendations","kind":"identifier"}]}]}]}