{"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"viewabilityActions"}],"modules":[{"name":"TeadsSDK"}],"title":"viewabilityActions","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewabilityActions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBViewabilityActions","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBViewabilityActions"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:@M@TeadsSDK@objc(cs)OBRecommendationResponse(py)viewabilityActions"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/viewabilityActions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewabilityActions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBViewabilityActions","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBViewabilityActions","text":"OBViewabilityActions"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/obrecommendationresponse\/viewabilityactions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/obrecommendationresponse\/viewabilityactions"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse/viewabilityActions":{"title":"viewabilityActions","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewabilityActions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBViewabilityActions","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBViewabilityActions"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"viewabilityActions","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse\/viewabilityActions","role":"symbol","abstract":[],"url":"\/documentation\/teadssdk\/obrecommendationresponse\/viewabilityactions","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendationResponse":{"url":"\/documentation\/teadssdk\/obrecommendationresponse","navigatorTitle":[{"kind":"identifier","text":"OBRecommendationResponse"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBRecommendationResponse"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendationResponse","title":"OBRecommendationResponse","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBViewabilityActions":{"type":"topic","url":"\/documentation\/teadssdk\/obviewabilityactions","navigatorTitle":[{"text":"OBViewabilityActions","kind":"identifier"}],"title":"OBViewabilityActions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBViewabilityActions","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBViewabilityActions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"viewabilityActions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"viewabilityActions","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBViewabilityActions","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBViewabilityActions","text":"OBViewabilityActions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"viewabilityActions"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1viewabilityActions\/title","value":"viewabilityActions"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse~1viewabilityActions\/fragments","value":[{"text":"viewabilityActions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/title","value":"OBRecommendationResponse"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/fragments","value":[{"text":"OBRecommendationResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendationResponse\/navigatorTitle","value":[{"kind":"identifier","text":"OBRecommendationResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBViewabilityActions\/title","value":"OBViewabilityActions"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBViewabilityActions\/fragments","value":[{"text":"OBViewabilityActions","kind":"identifier"}]},{"op":"replace","value":[{"text":"OBViewabilityActions","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBViewabilityActions\/navigatorTitle"}]}]}