{"abstract":[{"text":"Called when an ad has been paused.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"TeadsSDK"}],"title":"didPause(_:)","role":"symbol","externalID":"c:@M@TeadsSDK@objc(pl)TeadsPlaybackDelegate(im)didPause:","required":true,"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didPause","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didPause:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didPause(_:)"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didPause","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ad"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","text":"TeadsAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"ad","content":[{"inlineContent":[{"type":"text","text":"The ad that has been paused."}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/teadssdk\/teadsplaybackdelegate\/didpause(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsplaybackdelegate\/didpause(_:)"]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd":{"navigatorTitle":[{"text":"TeadsAd","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAd"}],"kind":"symbol","type":"topic","abstract":[{"text":"Root Ad Object inherited by ","type":"text"},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","isActive":true},{"type":"text","text":" & "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"}],"url":"\/documentation\/teadssdk\/teadsad","title":"TeadsAd"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"title":"TeadsNativeAd","url":"\/documentation\/teadssdk\/teadsnativead","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAd"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsNativeAd","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate":{"title":"TeadsPlaybackDelegate","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsplaybackdelegate","abstract":[{"type":"text","text":"Delegate methods sending informations about Teads ads playback states."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"navigatorTitle":[{"text":"TeadsInReadAd","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAd"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A TeadsInReadAd represents an InRead ad that will be binded to a "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","isActive":true,"type":"reference"},{"type":"text","text":" instance"}],"url":"\/documentation\/teadssdk\/teadsinreadad","title":"TeadsInReadAd"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/didPause(_:)":{"title":"didPause(_:)","kind":"symbol","required":true,"type":"topic","role":"symbol","navigatorTitle":[{"text":"didPause:","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didPause(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPause"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/didpause(_:)","abstract":[{"type":"text","text":"Called when an ad has been paused."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"didPause:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didPause:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didPause:"},{"text":"(","kind":"text"},{"text":"TeadsAd","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ad"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"text":"The ad that has been paused.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/title","op":"replace","value":"TeadsAd"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/fragments","value":[{"kind":"identifier","text":"TeadsAd"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/navigatorTitle","op":"replace","value":[{"text":"TeadsAd","kind":"identifier"}]},{"value":"TeadsNativeAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments","op":"replace","value":[{"text":"TeadsNativeAd","kind":"identifier"}]},{"value":[{"text":"TeadsNativeAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/title","value":"TeadsPlaybackDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsPlaybackDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title","op":"replace","value":"TeadsInReadAd"},{"value":[{"kind":"identifier","text":"TeadsInReadAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments","op":"replace"},{"value":[{"text":"TeadsInReadAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle"},{"value":"didPause:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didPause(_:)\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didPause(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didPause:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}