{"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"TeadsAdPlacementSettingsProtocol.enableLightEndScreen()","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/enableLightEndScreen()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableLightEndScreen","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"metadata":{"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings(im)enableLightEndScreen","platforms":[],"navigatorTitle":[{"text":"enableLightEndScreen","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"title":"enableLightEndScreen()","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableLightEndScreen","kind":"identifier"},{"kind":"text","text":"()"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Won't be used in any newer SDK versions."}]}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/enablelightendscreen()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/enablelightendscreen()"]}],"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/enableLightEndScreen()":{"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementsettings\/enablelightendscreen()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/enableLightEndScreen()","type":"topic","navigatorTitle":[{"text":"enableLightEndScreen","kind":"identifier"}],"deprecated":true,"title":"enableLightEndScreen()","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"enableLightEndScreen","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"title":"TeadsAdPlacementSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementsettings","abstract":[{"text":"Specify which settings you want to set for your Teads placement.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"enableLightEndScreen"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"enableLightEndScreen"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"enableLightEndScreen","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1enableLightEndScreen()\/title","value":"enableLightEndScreen"},{"value":[{"text":"- ","kind":"text"},{"text":"enableLightEndScreen","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1enableLightEndScreen()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","op":"replace","value":"TeadsAdPlacementSettings"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments"},{"value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}