{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/pluginReactNative","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Plugin value react native to monitor.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/pluginreactnative"]}],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginReactNative"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"s:8TeadsSDK0A19AdPlacementSettingsC17pluginReactNativeSSvpZ","modules":[{"name":"TeadsSDK"}],"roleHeading":"Type Property","title":"pluginReactNative"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pluginReactNative"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"name":"Note","content":[{"inlineContent":[{"text":"Internal purpose only.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"}],"kind":"content"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/pluginReactNative":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/pluginReactNative","kind":"symbol","type":"topic","title":"pluginReactNative","url":"\/documentation\/teadssdk\/teadsadplacementsettings\/pluginreactnative","abstract":[{"type":"text","text":"Plugin value react native to monitor."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"pluginReactNative","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"title":"TeadsAdPlacementSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementsettings","abstract":[{"text":"Specify which settings you want to set for your Teads placement.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TeadsAdPlacementSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"op":"replace"}]}]}