{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"metadata":{"modules":[{"name":"TeadsSDK"}],"title":"userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userConsent","kind":"identifier"},{"kind":"text","text":"("},{"text":"subjectToGDPR","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"consent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"tcfVersion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion","text":"TCFVersion","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cmpSdkID"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings(im)userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","role":"symbol","navigatorTitle":[{"text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","kind":"identifier"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userConsent","kind":"identifier"},{"kind":"text","text":"("},{"text":"subjectToGDPR","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"consent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tcfVersion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion","text":"TCFVersion","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion"},{"kind":"text","text":" = .v2, "},{"text":"cmpSdkID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":" = 0)"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"subjectToGDPR","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"\"1\""},{"type":"text","text":" if the traffic or the publisher is in the EEA (European Economic Area), "},{"code":"\"0\"","type":"codeVoice"},{"type":"text","text":" if it is not, "},{"type":"codeVoice","code":"\"null\""},{"type":"text","text":" if it’s unknown."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Which vendors and purposes did the user give consent for."}]}],"name":"consent"},{"name":"tcfVersion","content":[{"inlineContent":[{"type":"text","text":"Transparency and Consent Framework version."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Consent Manager Platform unique identifier.","type":"text"}]}],"name":"cmpSdkID"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"If you use a ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/iabeurope.eu\/tcf-for-cmps\/"},{"type":"text","text":", you can skip this step: CMP will store those parameters into "},{"type":"codeVoice","code":"UserDefaults"},{"text":", TeadSDK will automatically retrieve these values. ","type":"text"},{"type":"reference","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md","isActive":true},{"type":"text","text":" IAB documentation."}]}]}]}],"abstract":[{"text":"In order to follow the IAB specifications for GDPR, please fill the following parameters with attention.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/userconsent(subjecttogdpr:consent:tcfversion:cmpsdkid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/userconsent(subjecttogdpr:consent:tcfversion:cmpsdkid:)"]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TCFVersion":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TCFVersion"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TCFVersion","kind":"identifier"}],"url":"\/documentation\/teadssdk\/tcfversion","abstract":[{"type":"text","text":"EU Transparency & Consent Framework versions"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion","role":"symbol","title":"TCFVersion","kind":"symbol"},"https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md":{"identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md","type":"link","titleInlineContent":[{"text":"GDPR Transparency and Consent Framework ","type":"text"}],"title":"GDPR Transparency and Consent Framework ","url":"https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md"},"https://iabeurope.eu/tcf-for-cmps/":{"identifier":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","type":"link","titleInlineContent":[{"text":"CMP","type":"text"}],"title":"CMP","url":"https:\/\/iabeurope.eu\/tcf-for-cmps\/"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)":{"abstract":[{"text":"In order to follow the IAB specifications for GDPR, please fill the following parameters with attention.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userConsent"},{"kind":"text","text":"("},{"text":"subjectToGDPR","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"consent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"tcfVersion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion","text":"TCFVersion"},{"kind":"text","text":", "},{"text":"cmpSdkID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadplacementsettings\/userconsent(subjecttogdpr:consent:tcfversion:cmpsdkid:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"title":"TeadsAdPlacementSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementsettings","abstract":[{"text":"Specify which settings you want to set for your Teads placement.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userConsentWithSubjectToGDPR:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"subjectToGDPR"},{"text":" ","kind":"text"},{"text":"consent:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"consent","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tcfVersion:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion","text":"TCFVersion"},{"kind":"text","text":") "},{"text":"tcfVersion","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cmpSdkID:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cmpSdkID"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"\"1\""},{"type":"text","text":" if the traffic or the publisher is in the EEA (European Economic Area), "},{"type":"codeVoice","code":"\"0\""},{"type":"text","text":" if it is not, "},{"type":"codeVoice","code":"\"null\""},{"text":" if it’s unknown.","type":"text"}],"type":"paragraph"}],"name":"subjectToGDPR"},{"name":"consent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Which vendors and purposes did the user give consent for."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Transparency and Consent Framework version."}],"type":"paragraph"}],"name":"tcfVersion"},{"content":[{"inlineContent":[{"type":"text","text":"Consent Manager Platform unique identifier."}],"type":"paragraph"}],"name":"cmpSdkID"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/title","value":"TCFVersion"},{"value":[{"kind":"identifier","text":"TCFVersion"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/navigatorTitle","value":[{"text":"TCFVersion","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","value":"TeadsAdPlacementSettings"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"op":"replace"}]}]}