{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadopportunitytrackerview\/removefromsuperview()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadopportunitytrackerview\/removefromsuperview()"]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView"]]},"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/removeFromSuperview()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeFromSuperview","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFromSuperview"},{"kind":"text","text":"()"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView(im)removeFromSuperview","symbolKind":"method","title":"removeFromSuperview()","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"removeFromSuperview"}]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"kind":"symbol","abstract":[{"text":"adOpportunity is a key metrics to evaluate the performance of your inventory.","type":"text"},{"text":" ","type":"text"},{"text":"It builds the visibility score of your placement in publisher dashboards.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","type":"topic","navigatorTitle":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","title":"TeadsAdOpportunityTrackerView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView/removeFromSuperview()":{"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview\/removefromsuperview()","title":"removeFromSuperview()","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFromSuperview"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"text":"removeFromSuperview","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/removeFromSuperview()","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"removeFromSuperview","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFromSuperview"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeFromSuperview"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"TeadsAdOpportunityTrackerView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title"},{"op":"replace","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments"},{"op":"replace","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle"},{"op":"replace","value":"removeFromSuperview","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1removeFromSuperview()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeFromSuperview","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1removeFromSuperview()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}