{"abstract":[{"type":"text","text":"Convenience closure typealias for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BuildTeadsAdapterSettings","kind":"identifier"},{"text":" = (","kind":"text"},{"text":"TeadsAdapterSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/buildteadsadaptersettings"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/BuildTeadsAdapterSettings","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"BuildTeadsAdapterSettings"}],"externalID":"s:8TeadsSDK0A15AdapterSettingsC05BuildacD0a","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuildTeadsAdapterSettings"}],"title":"TeadsAdapterSettings.BuildTeadsAdapterSettings","symbolKind":"typealias","roleHeading":"Type Alias","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/BuildTeadsAdapterSettings":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BuildTeadsAdapterSettings","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"BuildTeadsAdapterSettings","kind":"identifier"}],"abstract":[{"text":"Convenience closure typealias for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","type":"reference"}],"title":"TeadsAdapterSettings.BuildTeadsAdapterSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/BuildTeadsAdapterSettings","role":"symbol","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings\/buildteadsadaptersettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"url":"\/documentation\/teadssdk\/teadsadaptersettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterSettings"}],"kind":"symbol","role":"symbol","title":"TeadsAdapterSettings","type":"topic","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"TeadsAdapterSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title"},{"op":"replace","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"op":"replace","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}