{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","interfaceLanguage":"swift"},"metadata":{"title":"userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","role":"symbol","navigatorTitle":[{"text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"subjectToGDPR","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"consent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"tcfVersion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TCFVersion","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion"},{"text":", ","kind":"text"},{"text":"cmpSdkID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/userconsent(subjecttogdpr:consent:tcfversion:cmpsdkid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/userconsent(subjecttogdpr:consent:tcfversion:cmpsdkid:)"]}],"sections":[],"abstract":[{"type":"text","text":"In order to follow the IAB specifications for GDPR, please fill the following parameters with attention."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"subjectToGDPR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tcfVersion"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion","kind":"typeIdentifier","text":"TCFVersion","preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion"},{"kind":"text","text":" = .v2, "},{"kind":"externalParam","text":"cmpSdkID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 0)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"\"1\""},{"type":"text","text":" if the traffic or the publisher is in the EEA (European Economic Area), "},{"type":"codeVoice","code":"\"0\""},{"type":"text","text":" if it is not, "},{"type":"codeVoice","code":"\"null\""},{"type":"text","text":" if it’s unknown."}]}],"name":"subjectToGDPR"},{"content":[{"inlineContent":[{"text":"Which vendors and purposes did the user give consent for.","type":"text"}],"type":"paragraph"}],"name":"consent"},{"content":[{"inlineContent":[{"type":"text","text":"Transparency and Consent Framework version."}],"type":"paragraph"}],"name":"tcfVersion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Consent Manager Platform unique identifier.","type":"text"}]}],"name":"cmpSdkID"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"style":"note","content":[{"inlineContent":[{"type":"text","text":"If you use a "},{"type":"reference","identifier":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","isActive":true},{"type":"text","text":", you can skip this step: CMP will store those parameters into "},{"type":"codeVoice","code":"UserDefaults"},{"type":"text","text":", TeadSDK will automatically retrieve these values. "},{"type":"reference","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md","isActive":true},{"type":"text","text":" IAB documentation."}],"type":"paragraph"}],"type":"aside","name":"Note"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TCFVersion":{"title":"TCFVersion","type":"topic","url":"\/documentation\/teadssdk\/tcfversion","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TCFVersion"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion","kind":"symbol","abstract":[{"text":"EU Transparency & Consent Framework versions","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TCFVersion"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"url":"\/documentation\/teadssdk\/teadsadaptersettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterSettings"}],"kind":"symbol","role":"symbol","title":"TeadsAdapterSettings","type":"topic","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}]},"https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md":{"url":"https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md","title":"GDPR Transparency and Consent Framework ","type":"link","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md","titleInlineContent":[{"text":"GDPR Transparency and Consent Framework ","type":"text"}]},"https://iabeurope.eu/tcf-for-cmps/":{"url":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","title":"CMP","type":"link","identifier":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","titleInlineContent":[{"type":"text","text":"CMP"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","title":"userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/userconsent(subjecttogdpr:consent:tcfversion:cmpsdkid:)","abstract":[{"text":"In order to follow the IAB specifications for GDPR, please fill the following parameters with attention.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"subjectToGDPR","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"consent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"tcfVersion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TCFVersion","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion"},{"text":", ","kind":"text"},{"text":"cmpSdkID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"userConsentWithSubjectToGDPR:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"subjectToGDPR"},{"kind":"text","text":" "},{"kind":"identifier","text":"consent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"consent"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcfVersion:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TCFVersion","preciseIdentifier":"c:@M@TeadsSDK@E@TCFVersion","text":"TCFVersion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tcfVersion"},{"kind":"text","text":" "},{"kind":"identifier","text":"cmpSdkID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cmpSdkID"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"subjectToGDPR","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"\"1\""},{"type":"text","text":" if the traffic or the publisher is in the EEA (European Economic Area), "},{"type":"codeVoice","code":"\"0\""},{"type":"text","text":" if it is not, "},{"type":"codeVoice","code":"\"null\""},{"type":"text","text":" if it’s unknown."}],"type":"paragraph"}]},{"name":"consent","content":[{"type":"paragraph","inlineContent":[{"text":"Which vendors and purposes did the user give consent for.","type":"text"}]}]},{"name":"tcfVersion","content":[{"inlineContent":[{"type":"text","text":"Transparency and Consent Framework version."}],"type":"paragraph"}]},{"name":"cmpSdkID","content":[{"inlineContent":[{"type":"text","text":"Consent Manager Platform unique identifier."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/title","value":"TCFVersion","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/fragments","value":[{"kind":"identifier","text":"TCFVersion"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TCFVersion\/navigatorTitle","value":[{"text":"TCFVersion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)\/title","value":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1userConsent(subjectToGDPR:consent:tcfVersion:cmpSdkID:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userConsentWithSubjectToGDPR:consent:tcfVersion:cmpSdkID:"}],"op":"replace"}]}]}