{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendations\/placementType"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"TeadsAdPlacementIdentifiable.placementType"},{"type":"text","text":"."}],"metadata":{"extendedModule":"TeadsSDK","navigatorTitle":[{"text":"placementType","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placementType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementType","text":"TeadsAdPlacementType","kind":"typeIdentifier"}],"modules":[{"name":"TeadsSDK"}],"title":"placementType","role":"symbol","roleHeading":"Instance Property","externalID":"c:@CM@TeadsSDK@objc(cs)TeadsAdPlacementRecommendations(py)placementType"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendations"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placementType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementType","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementType","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementrecommendations\/placementtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementrecommendations\/placementtype"]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementRecommendations":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementRecommendations"}],"role":"symbol","kind":"symbol","type":"topic","title":"TeadsAdPlacementRecommendations","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementRecommendations"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendations","url":"\/documentation\/teadssdk\/teadsadplacementrecommendations"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementRecommendations/placementType":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placementType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementType","text":"TeadsAdPlacementType"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementRecommendations\/placementType","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementrecommendations\/placementtype","type":"topic","title":"placementType","navigatorTitle":[{"kind":"identifier","text":"placementType"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementType":{"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementtype","role":"symbol","title":"TeadsAdPlacementType","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementType","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdPlacementType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"placementType","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"placementType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementType","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementType","kind":"typeIdentifier","text":"TeadsAdPlacementType"},{"kind":"text","text":" "},{"kind":"identifier","text":"placementType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TeadsAdPlacementRecommendations","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementRecommendations\/title"},{"value":[{"text":"TeadsAdPlacementRecommendations","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementRecommendations\/fragments"},{"value":[{"text":"TeadsAdPlacementRecommendations","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementRecommendations\/navigatorTitle"},{"value":"placementType","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementRecommendations~1placementType\/title"},{"value":[{"text":"placementType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementRecommendations~1placementType\/fragments"},{"value":"TeadsAdPlacementType","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementType\/title"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementType"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementType\/fragments"},{"value":[{"text":"TeadsAdPlacementType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}