{"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"TeadsSDK"}],"externalID":"s:8TeadsSDK0A15AdapterSettingsC011adPlacementD0AA0a2AdfD0Cvp","roleHeading":"Instance Property","title":"adPlacementSettings","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlacementSettings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/adPlacementSettings"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlacementSettings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","text":"TeadsAdPlacementSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"kind":"symbol","abstract":[{"text":"Placement settings (internal use only)","type":"text"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/adplacementsettings"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"url":"\/documentation\/teadssdk\/teadsadplacementsettings","title":"TeadsAdPlacementSettings","type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"abstract":[{"text":"Specify which settings you want to set for your Teads placement.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/adPlacementSettings":{"type":"topic","title":"adPlacementSettings","url":"\/documentation\/teadssdk\/teadsadaptersettings\/adplacementsettings","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/adPlacementSettings","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlacementSettings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","text":"TeadsAdPlacementSettings","kind":"typeIdentifier"}],"abstract":[{"text":"Placement settings (internal use only)","type":"text"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"title":"TeadsAdapterSettings","type":"topic","navigatorTitle":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","value":"TeadsAdPlacementSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}]}]}]}