{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/adfailreason\/localizeddescription"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason\/Error-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Error.localizedDescription"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"role":"symbol","platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"8.0"},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false},{"beta":false,"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"10.10"},{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false},{"beta":false,"name":"watchOS","deprecated":false,"introducedAt":"2.0","unavailable":false}],"extendedModule":"Swift","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"localizedDescription","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::c:@M@TeadsSDK@objc(cs)AdFailReason","modules":[{"name":"TeadsSDK","relatedModules":["Swift"]}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason\/localizedDescription","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason":{"navigatorTitle":[{"text":"AdFailReason","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","url":"\/documentation\/teadssdk\/adfailreason","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Error returned when ad request has failed. The failure is usually due to network"},{"text":" ","type":"text"},{"text":"connectivity or ad availablility (i.e., no fill).","type":"text"}],"role":"symbol","title":"AdFailReason","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdFailReason","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason/Error-Implementations":{"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason\/Error-Implementations","type":"topic","url":"\/documentation\/teadssdk\/adfailreason\/error-implementations","role":"collectionGroup","kind":"article","title":"Error Implementations"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason/localizedDescription":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason\/localizedDescription","role":"symbol","title":"localizedDescription","type":"topic","url":"\/documentation\/teadssdk\/adfailreason\/localizeddescription"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/title","value":"AdFailReason"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/fragments","value":[{"text":"AdFailReason","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/navigatorTitle","op":"replace","value":[{"text":"AdFailReason","kind":"identifier"}]}]}]}