{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TagBinderBuilder"}],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Class","modules":[{"name":"TeadsSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TagBinderBuilder","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","navigatorTitle":[{"text":"TagBinderBuilder","kind":"identifier"}],"symbolKind":"class","title":"TagBinderBuilder","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"]}],"sections":[],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/advertiserLabelTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/callToActionButtonTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/contentLabelTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/iconImageViewTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/mediaViewTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/priceLabelTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/ratingViewTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/titleLabelTag"],"generated":true,"title":"Instance Properties"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/teadssdk\/tagbinderbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/tagbinderbuilder"]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","interfaceLanguage":"swift"},"abstract":[{"text":"This builder allows you to bind UI elements programmatically using ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","type":"reference","isActive":true}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/advertiserLabelTag":{"type":"topic","role":"symbol","kind":"symbol","title":"advertiserLabelTag","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"advertiserLabelTag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/advertiserLabelTag","abstract":[{"text":"A non-zero tag for advertiser label view to be rendered. The maximum length will be 25 characters.","type":"text"}],"url":"\/documentation\/teadssdk\/tagbinderbuilder\/advertiserlabeltag","navigatorTitle":[{"text":"advertiserLabelTag","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/callToActionButtonTag":{"navigatorTitle":[{"text":"callToActionButtonTag","kind":"identifier"}],"abstract":[{"type":"text","text":"A non-zero tag for call to action button view to be rendered. The maximum length will be 15 characters."}],"title":"callToActionButtonTag","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/callToActionButtonTag","url":"\/documentation\/teadssdk\/tagbinderbuilder\/calltoactionbuttontag","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callToActionButtonTag","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder":{"type":"topic","role":"symbol","kind":"symbol","title":"TagBinderBuilder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TagBinderBuilder","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","abstract":[{"type":"text","text":"This builder allows you to bind UI elements programmatically using "},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","type":"reference"}],"url":"\/documentation\/teadssdk\/tagbinderbuilder","navigatorTitle":[{"text":"TagBinderBuilder","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/mediaViewTag":{"type":"topic","role":"symbol","kind":"symbol","title":"mediaViewTag","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mediaViewTag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/mediaViewTag","abstract":[{"type":"text","text":"A non-zero tag for media content view to be rendered."}],"url":"\/documentation\/teadssdk\/tagbinderbuilder\/mediaviewtag","navigatorTitle":[{"text":"mediaViewTag","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/ratingViewTag":{"navigatorTitle":[{"text":"ratingViewTag","kind":"identifier"}],"abstract":[{"text":"A non-zero tag for star rating content view to be rendered.","type":"text"}],"title":"ratingViewTag","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/ratingViewTag","url":"\/documentation\/teadssdk\/tagbinderbuilder\/ratingviewtag","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ratingViewTag","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/iconImageViewTag":{"type":"topic","role":"symbol","kind":"symbol","title":"iconImageViewTag","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconImageViewTag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/iconImageViewTag","abstract":[{"type":"text","text":"A non-zero tag for icon image view to be rendered."}],"url":"\/documentation\/teadssdk\/tagbinderbuilder\/iconimageviewtag","navigatorTitle":[{"text":"iconImageViewTag","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/contentLabelTag":{"navigatorTitle":[{"text":"contentLabelTag","kind":"identifier"}],"abstract":[{"text":"A non-zero tag for content \/ body \/ description label view to be rendered. The maximum length will be 150 characters.","type":"text"}],"title":"contentLabelTag","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/contentLabelTag","url":"\/documentation\/teadssdk\/tagbinderbuilder\/contentlabeltag","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contentLabelTag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:tagBinder:)":{"navigatorTitle":[{"kind":"identifier","text":"bind:tagBinder:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bind"},{"text":"(","kind":"text"},{"text":"TeadsNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd"},{"text":", ","kind":"text"},{"text":"tagBinder","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","text":"TagBinderBuilder","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"bind(_:tagBinder:)","role":"symbol","url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)","abstract":[{"text":"Binds the native asset ad views to this native ad using view tags binder","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/priceLabelTag":{"type":"topic","role":"symbol","kind":"symbol","title":"priceLabelTag","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"priceLabelTag","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/priceLabelTag","abstract":[{"text":"A non-zero tag for price content view to be rendered.","type":"text"}],"url":"\/documentation\/teadssdk\/tagbinderbuilder\/pricelabeltag","navigatorTitle":[{"text":"priceLabelTag","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/titleLabelTag":{"navigatorTitle":[{"text":"titleLabelTag","kind":"identifier"}],"abstract":[{"text":"A non-zero tag for the title label view to be rendered. The maximum length will be 50 characters.","type":"text"}],"title":"titleLabelTag","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/titleLabelTag","url":"\/documentation\/teadssdk\/tagbinderbuilder\/titlelabeltag","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleLabelTag"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TagBinderBuilder"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"TagBinderBuilder","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"TagBinderBuilder","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/advertiserLabelTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/callToActionButtonTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/contentLabelTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/iconImageViewTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/mediaViewTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/priceLabelTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/ratingViewTag","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/titleLabelTag"],"generated":true,"title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TagBinderBuilder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1advertiserLabelTag\/title","op":"replace","value":"advertiserLabelTag"},{"op":"replace","value":[{"text":"advertiserLabelTag","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1advertiserLabelTag\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1callToActionButtonTag\/title","value":"callToActionButtonTag","op":"replace"},{"value":[{"kind":"identifier","text":"callToActionButtonTag"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1callToActionButtonTag\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/title","value":"TagBinderBuilder","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/fragments","value":[{"kind":"identifier","text":"TagBinderBuilder"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/navigatorTitle","op":"replace","value":[{"text":"TagBinderBuilder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1mediaViewTag\/title","value":"mediaViewTag"},{"op":"replace","value":[{"text":"mediaViewTag","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1mediaViewTag\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1ratingViewTag\/title","op":"replace","value":"ratingViewTag"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1ratingViewTag\/fragments","op":"replace","value":[{"kind":"identifier","text":"ratingViewTag"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1iconImageViewTag\/title","value":"iconImageViewTag"},{"op":"replace","value":[{"text":"iconImageViewTag","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1iconImageViewTag\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1contentLabelTag\/title","value":"contentLabelTag"},{"value":[{"kind":"identifier","text":"contentLabelTag"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1contentLabelTag\/fragments","op":"replace"},{"value":"bind:tagBinder:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"bind:tagBinder:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1priceLabelTag\/title","value":"priceLabelTag"},{"value":[{"text":"priceLabelTag","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1priceLabelTag\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1titleLabelTag\/title","value":"titleLabelTag"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1titleLabelTag\/fragments","value":[{"text":"titleLabelTag","kind":"identifier"}],"op":"replace"}]}]}