{"sections":[],"metadata":{"title":"TeadsAdOpportunityTrackerView","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","symbolKind":"class","modules":[{"name":"TeadsSDK"}],"role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"It is mandatory to implement it, a bad visibility measurement will impact your placement fill rate.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"To do so: add this view just above your slot, when visibility is tracked, this view will be removed from superview automaically"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadopportunitytrackerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadopportunitytrackerview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"adOpportunity is a key metrics to evaluate the performance of your inventory."},{"text":" ","type":"text"},{"text":"It builds the visibility score of your placement in publisher dashboards.","type":"text"}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/init(frame:)"],"title":"Initializers","generated":true},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/requestIdentifier"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/removeFromSuperview()"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","abstract":[{"text":"adOpportunity is a key metrics to evaluate the performance of your inventory.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It builds the visibility score of your placement in publisher dashboards."}],"navigatorTitle":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","role":"symbol","type":"topic","kind":"symbol","title":"TeadsAdOpportunityTrackerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSCoding","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearance","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView/removeFromSuperview()":{"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview\/removefromsuperview()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/removeFromSuperview()","role":"symbol","kind":"symbol","abstract":[],"title":"removeFromSuperview()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeFromSuperview","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"removeFromSuperview","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)UIView":{"title":"UIView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView/init(frame:)":{"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview\/init(frame:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/init(frame:)","role":"symbol","title":"init(frame:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView/requestIdentifier":{"abstract":[{"text":"Request identifier allows you to match the returned value from placement.requestAd call","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requestIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"?","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview\/requestidentifier","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/requestIdentifier","type":"topic","title":"requestIdentifier","navigatorTitle":[{"kind":"identifier","text":"requestIdentifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"TeadsAdOpportunityTrackerView","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/requestIdentifier"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/init(frame:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/removeFromSuperview()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)UIView"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title","value":"TeadsAdOpportunityTrackerView","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"op":"replace"},{"value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1removeFromSuperview()\/title","value":"removeFromSuperview","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1removeFromSuperview()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeFromSuperview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1init(frame:)\/title","value":"initWithFrame:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1init(frame:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1requestIdentifier\/title","value":"requestIdentifier"},{"value":[{"text":"requestIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1requestIdentifier\/fragments","op":"replace"}]}]}