{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/adfailreason\/errorcode"]}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"externalID":"s:8TeadsSDK12AdFailReasonC9errorCodeSivp","role":"symbol","roleHeading":"Instance Property","title":"errorCode","modules":[{"name":"TeadsSDK"}],"extendedModule":"TeadsSDK"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason\/errorCode"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomNSError.errorCode","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdFailReason"}],"kind":"symbol","url":"\/documentation\/teadssdk\/adfailreason","navigatorTitle":[{"kind":"identifier","text":"AdFailReason"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","type":"topic","abstract":[{"type":"text","text":"Error returned when ad request has failed. The failure is usually due to network"},{"type":"text","text":" "},{"type":"text","text":"connectivity or ad availablility (i.e., no fill)."}],"title":"AdFailReason"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason/errorCode":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason\/errorCode","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"\/documentation\/teadssdk\/adfailreason\/errorcode","type":"topic","title":"errorCode","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"AdFailReason","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/title"},{"op":"replace","value":[{"text":"AdFailReason","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AdFailReason"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}