{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didComplete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ad","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","kind":"typeIdentifier","text":"TeadsAd"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"text":"The ad that has ended.","type":"text"}]}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate"]]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didComplete(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsplaybackdelegate\/didcomplete(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsplaybackdelegate\/didcomplete(_:)"]}],"metadata":{"externalID":"c:@M@TeadsSDK@objc(pl)TeadsPlaybackDelegate(im)didComplete:","navigatorTitle":[{"kind":"identifier","text":"didComplete:"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"didComplete(_:)","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didComplete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Called when an ad has ended.","type":"text"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/didComplete(_:)":{"url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/didcomplete(_:)","title":"didComplete(_:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/didComplete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didComplete"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TeadsAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"didComplete:"}],"abstract":[{"type":"text","text":"Called when an ad has ended."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAd"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAd"}],"type":"topic","abstract":[{"text":"A TeadsInReadAd represents an InRead ad that will be binded to a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"},{"text":" instance","type":"text"}],"title":"TeadsInReadAd","url":"\/documentation\/teadssdk\/teadsinreadad","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAd"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","url":"\/documentation\/teadssdk\/teadsnativead","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAd"}],"title":"TeadsNativeAd","abstract":[{"type":"text","text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate methods sending informations about Teads ads playback states.","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate","type":"topic","title":"TeadsPlaybackDelegate","url":"\/documentation\/teadssdk\/teadsplaybackdelegate","kind":"symbol","navigatorTitle":[{"text":"TeadsPlaybackDelegate","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd":{"navigatorTitle":[{"text":"TeadsAd","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAd","kind":"identifier"}],"kind":"symbol","title":"TeadsAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","abstract":[{"type":"text","text":"Root Ad Object inherited by "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","isActive":true},{"type":"text","text":" & "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","isActive":true}],"type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teadsad"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"didComplete:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didComplete:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didComplete:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","text":"TeadsAd","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ad","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"ad","content":[{"inlineContent":[{"type":"text","text":"The ad that has ended."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"didComplete:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didComplete(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didComplete:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1didComplete(_:)\/fragments"},{"value":"TeadsInReadAd","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title"},{"value":[{"kind":"identifier","text":"TeadsInReadAd"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments"},{"value":[{"text":"TeadsInReadAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle"},{"value":"TeadsNativeAd","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title"},{"value":[{"text":"TeadsNativeAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments"},{"value":[{"kind":"identifier","text":"TeadsNativeAd"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"},{"value":"TeadsPlaybackDelegate","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/title"},{"value":[{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/fragments"},{"value":[{"text":"TeadsPlaybackDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate\/navigatorTitle"},{"value":"TeadsAd","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/title"},{"value":[{"text":"TeadsAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/fragments"},{"value":[{"text":"TeadsAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}