{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/init(videoComponent:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"videoComponent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)VideoComponent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"When dealing with VideoComponent, it needs to be rendered using TeadsMediaView","type":"text"}],"metadata":{"symbolKind":"init","role":"symbol","title":"init(videoComponent:)","roleHeading":"Initializer","modules":[{"name":"TeadsSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoComponent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)VideoComponent","kind":"typeIdentifier","text":"VideoComponent"},{"kind":"text","text":")"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsMediaView(im)initWithVideoComponent:","navigatorTitle":[{"kind":"identifier","text":"initWithVideoComponent:"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsmediaview\/init(videocomponent:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsmediaview\/init(videocomponent:)"]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView/init(videoComponent:)":{"url":"\/documentation\/teadssdk\/teadsmediaview\/init(videocomponent:)","title":"init(videoComponent:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"When dealing with VideoComponent, it needs to be rendered using TeadsMediaView"}],"navigatorTitle":[{"text":"initWithVideoComponent:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)VideoComponent","text":"VideoComponent"},{"kind":"text","text":")"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/init(videoComponent:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView":{"navigatorTitle":[{"kind":"identifier","text":"TeadsMediaView"}],"title":"TeadsMediaView","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","url":"\/documentation\/teadssdk\/teadsmediaview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediaView"}],"abstract":[{"type":"text","text":"The TeadsMediaView can load either images, videos and VPAID content."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/VideoComponent":{"navigatorTitle":[{"kind":"identifier","text":"VideoComponent"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoComponent"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Native video component containing media content"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent","title":"VideoComponent","url":"\/documentation\/teadssdk\/videocomponent"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithVideoComponent:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVideoComponent:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithVideoComponent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoComponent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)VideoComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent"},{"text":" *) ","kind":"text"},{"text":"videoComponent","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithVideoComponent:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1init(videoComponent:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithVideoComponent:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1init(videoComponent:)\/fragments","op":"replace"},{"value":"TeadsMediaView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/title","op":"replace"},{"value":[{"text":"TeadsMediaView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsMediaView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/navigatorTitle","op":"replace"},{"value":"VideoComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/title","op":"replace"},{"value":[{"text":"VideoComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"VideoComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/navigatorTitle","op":"replace"}]}]}