{"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/disabledApp","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorAdRequest","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorBadResponse","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorInternal","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNetwork","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNoSlot","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNotFilled","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorUserIdMissing","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorVastError"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/Equatable-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SY"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"metadata":{"symbolKind":"enum","role":"symbol","modules":[{"name":"TeadsSDK"}],"roleHeading":"Enumeration","title":"AdErrorCode","externalID":"c:@M@TeadsSDK@E@AdErrorCode","navigatorTitle":[{"kind":"identifier","text":"AdErrorCode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdErrorCode"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enumeration of Teads’ error codes."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdErrorCode"}]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Error code is part of the "},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","type":"reference"},{"type":"text","text":" object returned through placement delegate "},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/didFailToReceiveAd(reason:)","type":"reference"},{"type":"text","text":" "},{"type":"text","text":"You can switch over it in order to adapt logic regarding error case"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/teadssdk\/aderrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/aderrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorUserIdMissing":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorUserIdMissing"}],"navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorUserIdMissing"}],"abstract":[{"text":"Placement Identifier is missing","type":"text"}],"url":"\/documentation\/teadssdk\/aderrorcode\/erroruseridmissing","title":"AdErrorCode.errorUserIdMissing","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorUserIdMissing","type":"topic","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/Equatable-Implementations":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/Equatable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/teadssdk\/aderrorcode\/equatable-implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate/didFailToReceiveAd(reason:)":{"navigatorTitle":[{"text":"didFailToReceiveAdWithReason:","kind":"identifier"}],"title":"didFailToReceiveAd(reason:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFailToReceiveAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason","text":"AdFailReason","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsadplacementdelegate\/didfailtoreceivead(reason:)","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/didFailToReceiveAd(reason:)","type":"topic","required":true,"abstract":[{"text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/teadssdk\/aderrorcode\/rawrepresentable-implementations","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdFailReason"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","navigatorTitle":[{"kind":"identifier","text":"AdFailReason"}],"title":"AdFailReason","url":"\/documentation\/teadssdk\/adfailreason","abstract":[{"text":"Error returned when ad request has failed. The failure is usually due to network","type":"text"},{"text":" ","type":"text"},{"text":"connectivity or ad availablility (i.e., no fill).","type":"text"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorInternal":{"abstract":[{"type":"text","text":"Internal error"}],"title":"AdErrorCode.errorInternal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorInternal"}],"url":"\/documentation\/teadssdk\/aderrorcode\/errorinternal","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorInternal","navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorInternal"}],"kind":"symbol","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorNoSlot":{"navigatorTitle":[{"text":"AdErrorCodeErrorNoSlot","kind":"identifier"}],"url":"\/documentation\/teadssdk\/aderrorcode\/errornoslot","abstract":[{"text":"When no slot exists for ad","type":"text"}],"title":"AdErrorCode.errorNoSlot","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNoSlot","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNoSlot"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorNotFilled":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNotFilled","type":"topic","title":"AdErrorCode.errorNotFilled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNotFilled"}],"url":"\/documentation\/teadssdk\/aderrorcode\/errornotfilled","abstract":[{"text":"AdServer does not responds with an ad","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AdErrorCodeErrorNotFilled","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorVastError":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorVastError","abstract":[{"type":"text","text":"VAST error"}],"url":"\/documentation\/teadssdk\/aderrorcode\/errorvasterror","type":"topic","title":"AdErrorCode.errorVastError","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorVastError"}],"navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorVastError"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/disabledApp":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabledApp","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeDisabledApp"}],"abstract":[{"type":"text","text":"App (bundle identifier) has been disabled on purpose"}],"title":"AdErrorCode.disabledApp","url":"\/documentation\/teadssdk\/aderrorcode\/disabledapp","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/disabledApp"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorNetwork":{"title":"AdErrorCode.errorNetwork","url":"\/documentation\/teadssdk\/aderrorcode\/errornetwork","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNetwork","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetwork"}],"navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorNetwork"}],"abstract":[{"type":"text","text":"Connectivity network issue"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorBadResponse":{"abstract":[{"type":"text","text":"Ad parsing error"}],"type":"topic","title":"AdErrorCode.errorBadResponse","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorBadResponse","kind":"symbol","url":"\/documentation\/teadssdk\/aderrorcode\/errorbadresponse","navigatorTitle":[{"text":"AdErrorCodeErrorBadResponse","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorBadResponse","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SY"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode":{"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","title":"AdErrorCode","abstract":[{"text":"Enumeration of Teads’ error codes.","type":"text"}],"role":"symbol","url":"\/documentation\/teadssdk\/aderrorcode","navigatorTitle":[{"kind":"identifier","text":"AdErrorCode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdErrorCode"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/init(rawValue:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/init(rawValue:)","abstract":[],"type":"topic","title":"init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/teadssdk\/aderrorcode\/init(rawvalue:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorAdRequest":{"title":"AdErrorCode.errorAdRequest","url":"\/documentation\/teadssdk\/aderrorcode\/erroradrequest","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AdErrorCodeErrorAdRequest","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorAdRequest","abstract":[{"type":"text","text":"Ad Request has returned an error"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorAdRequest","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AdErrorCode","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AdErrorCode"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"AdErrorCode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/disabledApp","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorAdRequest","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorBadResponse","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorInternal","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNetwork","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNoSlot","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNotFilled","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorUserIdMissing","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorVastError"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdErrorCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AdErrorCodeErrorUserIdMissing","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorUserIdMissing\/title"},{"op":"replace","value":[{"text":"AdErrorCodeErrorUserIdMissing","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorUserIdMissing\/fragments"},{"op":"replace","value":"didFailToReceiveAdWithReason:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1didFailToReceiveAd(reason:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFailToReceiveAdWithReason:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1didFailToReceiveAd(reason:)\/fragments"},{"op":"replace","value":"AdFailReason","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AdFailReason"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/fragments"},{"op":"replace","value":[{"text":"AdFailReason","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/navigatorTitle"},{"op":"replace","value":"AdErrorCodeErrorInternal","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorInternal\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AdErrorCodeErrorInternal"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorInternal\/fragments"},{"op":"replace","value":"AdErrorCodeErrorNoSlot","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNoSlot\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AdErrorCodeErrorNoSlot"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNoSlot\/fragments"},{"op":"replace","value":"AdErrorCodeErrorNotFilled","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNotFilled\/title"},{"op":"replace","value":[{"text":"AdErrorCodeErrorNotFilled","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNotFilled\/fragments"},{"op":"replace","value":"AdErrorCodeErrorVastError","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorVastError\/title"},{"op":"replace","value":[{"text":"AdErrorCodeErrorVastError","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorVastError\/fragments"},{"op":"replace","value":"AdErrorCodeDisabledApp","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1disabledApp\/title"},{"op":"replace","value":[{"text":"AdErrorCodeDisabledApp","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1disabledApp\/fragments"},{"op":"replace","value":"AdErrorCodeErrorNetwork","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNetwork\/title"},{"op":"replace","value":[{"text":"AdErrorCodeErrorNetwork","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNetwork\/fragments"},{"op":"replace","value":"AdErrorCodeErrorBadResponse","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorBadResponse\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AdErrorCodeErrorBadResponse"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorBadResponse\/fragments"},{"op":"replace","value":"AdErrorCode","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AdErrorCode"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AdErrorCode"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/navigatorTitle"},{"op":"replace","value":"AdErrorCodeErrorAdRequest","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorAdRequest\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AdErrorCodeErrorAdRequest"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorAdRequest\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}