{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/obdisclosure"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/obdisclosure"]}],"sections":[],"metadata":{"symbolKind":"class","externalID":"c:@M@TeadsSDK@objc(cs)OBDisclosure","role":"symbol","title":"OBDisclosure","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBDisclosure","kind":"identifier"}],"navigatorTitle":[{"text":"OBDisclosure","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}]},"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/init(from:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/init(imageUrl:clickUrl:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/clickUrl","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/imageUrl"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBDisclosure"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/Se","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBDisclosure/clickUrl":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/clickUrl","navigatorTitle":[{"kind":"identifier","text":"clickUrl"}],"role":"symbol","title":"clickUrl","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","url":"\/documentation\/teadssdk\/obdisclosure\/clickurl"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBDisclosure/init(from:)":{"role":"symbol","url":"\/documentation\/teadssdk\/obdisclosure\/init(from:)","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/init(from:)","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/Se","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBDisclosure/imageUrl":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/imageUrl","type":"topic","url":"\/documentation\/teadssdk\/obdisclosure\/imageurl","role":"symbol","kind":"symbol","title":"imageUrl","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageUrl","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"imageUrl","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBDisclosure":{"role":"symbol","url":"\/documentation\/teadssdk\/obdisclosure","title":"OBDisclosure","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBDisclosure","kind":"identifier"}],"navigatorTitle":[{"text":"OBDisclosure","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBDisclosure/init(imageUrl:clickUrl:)":{"abstract":[],"role":"symbol","title":"init(imageUrl:clickUrl:)","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/init(imageUrl:clickUrl:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"clickUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageUrl:clickUrl:"}],"url":"\/documentation\/teadssdk\/obdisclosure\/init(imageurl:clickurl:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OBDisclosure","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"OBDisclosure","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OBDisclosure"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/clickUrl","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/imageUrl"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBDisclosure\/init(imageUrl:clickUrl:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBDisclosure","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"clickUrl","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure~1clickUrl\/title","op":"replace"},{"value":[{"kind":"identifier","text":"clickUrl"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure~1clickUrl\/fragments"},{"value":"imageUrl","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure~1imageUrl\/title"},{"value":[{"kind":"identifier","text":"imageUrl"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure~1imageUrl\/fragments"},{"value":"OBDisclosure","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure\/title"},{"value":[{"text":"OBDisclosure","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure\/fragments"},{"value":[{"kind":"identifier","text":"OBDisclosure"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure\/navigatorTitle"},{"value":"initWithImageUrl:clickUrl:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure~1init(imageUrl:clickUrl:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageUrl:clickUrl:"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBDisclosure~1init(imageUrl:clickUrl:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}