{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsuiviewplacement"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsUIViewPlacement"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol","text":"TeadsAdPlacementProtocol"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol constrains SwiftUI components to only work with placements that return"},{"type":"text","text":" "},{"type":"text","text":"UIView instances. It uses associated type refinement to maintain type safety while"},{"type":"text","text":" "},{"type":"text","text":"accommodating different UIView compositions (e.g., UIView, UIView & DarkModeTogglable)."}]},{"type":"paragraph","inlineContent":[{"text":"Usage:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"type":"codeVoice","code":"TeadsAdPlacementSwiftUIView"},{"text":" for placements conforming to this protocol","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Implement custom SwiftUI views for MediaNative placements (see demo app examples)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement custom SwiftUI views for Recommendations placements (see demo app examples)"}]}]}]}]}],"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsUIViewPlacement","kind":"identifier"}],"externalID":"s:8TeadsSDK0A15UIViewPlacementP","roleHeading":"Protocol","title":"TeadsUIViewPlacement","navigatorTitle":[{"text":"TeadsUIViewPlacement","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"symbolKind":"protocol"},"topicSections":[{"generated":true,"title":"Associated Types","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement\/ViewType"],"anchor":"Associated-Types"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement\/uiViewResult"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementFeed","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"],"type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"sections":[],"abstract":[{"text":"Protocol for ad placements that return UIView-based content from loadAd()","type":"text"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsUIViewPlacement/uiViewResult":{"type":"topic","role":"symbol","defaultImplementations":1,"url":"\/documentation\/teadssdk\/teadsuiviewplacement\/uiviewresult","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement\/uiViewResult","kind":"symbol","required":true,"title":"uiViewResult","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiViewResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewType","preciseIdentifier":"s:8TeadsSDK0A15UIViewPlacementP8ViewTypeQa"}],"abstract":[{"text":"Returns the UIView result from loadAd() with proper typing","type":"text"},{"text":" ","type":"text"},{"text":"This provides compile-time type safety for UIView-based placements","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementFeed":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementFeed"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementFeed","url":"\/documentation\/teadssdk\/teadsadplacementfeed","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementFeed"}],"title":"TeadsAdPlacementFeed","type":"topic","role":"symbol","kind":"symbol","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsUIViewPlacement/ViewType":{"url":"\/documentation\/teadssdk\/teadsuiviewplacement\/viewtype","abstract":[{"type":"text","text":"The specific UIView type this placement returns"},{"type":"text","text":" "},{"type":"text","text":"Must be a subclass or composition that includes UIView"}],"type":"topic","fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement\/ViewType","title":"ViewType"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"title":"TeadsAdPlacementMedia","url":"\/documentation\/teadssdk\/teadsadplacementmedia","type":"topic","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementProtocol":{"type":"topic","title":"TeadsAdPlacementProtocol","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementprotocol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdPlacementProtocol","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsUIViewPlacement":{"title":"TeadsUIViewPlacement","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement","navigatorTitle":[{"text":"TeadsUIViewPlacement","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for ad placements that return UIView-based content from loadAd()"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsUIViewPlacement","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsuiviewplacement","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementFeed\/title","op":"replace","value":"TeadsAdPlacementFeed"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementFeed\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementFeed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementFeed\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacementFeed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title","op":"replace","value":"TeadsAdPlacementMedia"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]}]}]}