{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"TeadsPrivacy","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPrivacy","kind":"identifier"}],"role":"symbol","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"TeadsPrivacy","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsPrivacy","roleHeading":"Class"},"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprApplies","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentString","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentStringV1","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentStringV2","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppApplies","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppSections","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppString","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/hasGDPRConsentForTeads","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/hasOptedOutOfSale","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/idfaString","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/idfaTrackingAuthorized","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/isCMPPresent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/usPrivacyString"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/clearAllCustomSettings()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/clearCustomIDFAConsent()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/requestIDFAPermission(completion:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRApplies(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentString(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentStringV1(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentStringV2(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGPPSections(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGPPString(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setIDFAConsent(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setUSPrivacyString(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/shared"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPrivacy","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsprivacy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsprivacy"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setGDPRConsentStringV1(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setGDPRConsentStringV1"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"title":"setGDPRConsentStringV1(_:)","role":"symbol","url":"\/documentation\/teadssdk\/teadsprivacy\/setgdprconsentstringv1(_:)","kind":"symbol","abstract":[{"text":"Set custom GDPR TCF v1 consent string from host app","type":"text"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentStringV1(_:)","navigatorTitle":[{"kind":"identifier","text":"setGDPRConsentStringV1:"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/clearCustomIDFAConsent()":{"title":"clearCustomIDFAConsent()","navigatorTitle":[{"text":"clearCustomIDFAConsent","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearCustomIDFAConsent","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/clearCustomIDFAConsent()","abstract":[{"text":"Clear custom IDFA consent to use system value","type":"text"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsprivacy\/clearcustomidfaconsent()","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/hasOptedOutOfSale":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasOptedOutOfSale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/hasOptedOutOfSale","navigatorTitle":[{"text":"hasOptedOutOfSale","kind":"identifier"}],"role":"symbol","title":"hasOptedOutOfSale","abstract":[{"type":"text","text":"Check if user has opted out of sale under CCPA"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/hasoptedoutofsale"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/requestIDFAPermission(completion:)":{"title":"requestIDFAPermission(completion:)","abstract":[{"type":"text","text":"Request IDFA permission (iOS 14+)"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestIDFAPermission","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/requestIDFAPermission(completion:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"requestIDFAPermissionWithCompletion:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/requestidfapermission(completion:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/usPrivacyString":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"usPrivacyString"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/usprivacystring","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"usPrivacyString"}],"title":"usPrivacyString","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/usPrivacyString","abstract":[{"text":"Get US Privacy string (prefers custom value over system)","type":"text"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/idfaString":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/idfaString","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"idfaString"}],"title":"idfaString","url":"\/documentation\/teadssdk\/teadsprivacy\/idfastring","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idfaString","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Get IDFA string if tracking is authorized"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/gdprConsentString":{"type":"topic","abstract":[{"text":"Get GDPR consent string (prefers custom value over system)","type":"text"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/gdprconsentstring","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentString","title":"gdprConsentString","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gdprConsentString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"gdprConsentString"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/hasGDPRConsentForTeads":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasGDPRConsentForTeads","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Check if user has given consent for Teads (Vendor ID 132)","type":"text"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/hasgdprconsentforteads","title":"hasGDPRConsentForTeads","navigatorTitle":[{"text":"hasGDPRConsentForTeads","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/hasGDPRConsentForTeads"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setIDFAConsent(_:)":{"title":"setIDFAConsent(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setIDFAConsent","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Set custom IDFA consent from host app"}],"navigatorTitle":[{"text":"setIDFAConsent:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setIDFAConsent(_:)","url":"\/documentation\/teadssdk\/teadsprivacy\/setidfaconsent(_:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy":{"type":"topic","title":"TeadsPrivacy","abstract":[],"url":"\/documentation\/teadssdk\/teadsprivacy","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsPrivacy"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsPrivacy"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/shared":{"navigatorTitle":[{"text":"shared","kind":"identifier"}],"title":"shared","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsPrivacy","text":"TeadsPrivacy","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/teadssdk\/teadsprivacy\/shared"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setGDPRApplies(_:)":{"navigatorTitle":[{"text":"setGDPRApplies:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"setGDPRApplies(_:)","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRApplies(_:)","url":"\/documentation\/teadssdk\/teadsprivacy\/setgdprapplies(_:)","abstract":[{"type":"text","text":"Set whether GDPR applies from host app"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGDPRApplies","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/gdprConsentStringV1":{"navigatorTitle":[{"text":"gdprConsentStringV1","kind":"identifier"}],"kind":"symbol","type":"topic","title":"gdprConsentStringV1","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentStringV1","abstract":[{"type":"text","text":"Get GDPR TCF v1 consent string (prefers custom value over system)"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/gdprconsentstringv1","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gdprConsentStringV1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/idfaTrackingAuthorized":{"navigatorTitle":[{"text":"idfaTrackingAuthorized","kind":"identifier"}],"title":"idfaTrackingAuthorized","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/idfaTrackingAuthorized","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idfaTrackingAuthorized","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Check IDFA tracking authorization status (prefers custom value over system)"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/idfatrackingauthorized"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/clearAllCustomSettings()":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Clear all custom privacy settings to use system values"}],"navigatorTitle":[{"text":"clearAllCustomSettings","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/clearallcustomsettings()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/clearAllCustomSettings()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearAllCustomSettings","kind":"identifier"},{"text":"()","kind":"text"}],"title":"clearAllCustomSettings()","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/gppApplies":{"abstract":[{"text":"Check if GPP applies (has GPP string)","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"gppApplies"}],"type":"topic","title":"gppApplies","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gppApplies","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppApplies","url":"\/documentation\/teadssdk\/teadsprivacy\/gppapplies"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/gdprConsentStringV2":{"navigatorTitle":[{"text":"gdprConsentStringV2","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gdprConsentStringV2","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/gdprconsentstringv2","type":"topic","abstract":[{"type":"text","text":"Get GDPR TCF v2 consent string (prefers custom value over system)"}],"title":"gdprConsentStringV2","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentStringV2","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/gppString":{"abstract":[{"type":"text","text":"Get GPP string (prefers custom value over system)"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppString","url":"\/documentation\/teadssdk\/teadsprivacy\/gppstring","title":"gppString","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gppString","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"gppString","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setUSPrivacyString(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Set custom US Privacy string from host app"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setUSPrivacyString(_:)","navigatorTitle":[{"text":"setUSPrivacyString:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/setusprivacystring(_:)","title":"setUSPrivacyString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUSPrivacyString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setGDPRConsentStringV2(_:)":{"abstract":[{"type":"text","text":"Set custom GDPR TCF v2 consent string from host app"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentStringV2(_:)","url":"\/documentation\/teadssdk\/teadsprivacy\/setgdprconsentstringv2(_:)","title":"setGDPRConsentStringV2(_:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGDPRConsentStringV2","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"setGDPRConsentStringV2:","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/gppSections":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gppSections"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"Get GPP sections (prefers custom value over system)"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppSections","title":"gppSections","role":"symbol","url":"\/documentation\/teadssdk\/teadsprivacy\/gppsections","navigatorTitle":[{"kind":"identifier","text":"gppSections"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/gdprApplies":{"type":"topic","abstract":[{"type":"text","text":"Check if GDPR applies (prefers custom value over system)"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gdprApplies","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprApplies","role":"symbol","title":"gdprApplies","url":"\/documentation\/teadssdk\/teadsprivacy\/gdprapplies","navigatorTitle":[{"kind":"identifier","text":"gdprApplies"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setGPPString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGPPString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/setgppstring(_:)","title":"setGPPString(_:)","abstract":[{"type":"text","text":"Set custom GPP string from host app"}],"role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGPPString(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setGPPString:"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/isCMPPresent":{"kind":"symbol","title":"isCMPPresent","abstract":[{"type":"text","text":"Check if CMP is present"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/iscmppresent","role":"symbol","navigatorTitle":[{"text":"isCMPPresent","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/isCMPPresent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCMPPresent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setGPPSections(_:)":{"abstract":[{"text":"Set custom GPP sections from host app","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGPPSections(_:)","url":"\/documentation\/teadssdk\/teadsprivacy\/setgppsections(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGPPSections","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"setGPPSections(_:)","navigatorTitle":[{"text":"setGPPSections:","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setGDPRConsentString(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGDPRConsentString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Set custom GDPR consent string from host app","type":"text"}],"navigatorTitle":[{"text":"setGDPRConsentString:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/setgdprconsentstring(_:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentString(_:)","type":"topic","role":"symbol","title":"setGDPRConsentString(_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"TeadsPrivacy"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsPrivacy"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsPrivacy"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprApplies","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentString","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentStringV1","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gdprConsentStringV2","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppApplies","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppSections","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/gppString","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/hasGDPRConsentForTeads","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/hasOptedOutOfSale","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/idfaString","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/idfaTrackingAuthorized","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/isCMPPresent","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/usPrivacyString"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/clearAllCustomSettings()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/clearCustomIDFAConsent()","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/requestIDFAPermission(completion:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRApplies(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentString(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentStringV1(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGDPRConsentStringV2(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGPPSections(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setGPPString(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setIDFAConsent(_:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setUSPrivacyString(_:)"]},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/shared"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsPrivacy"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGDPRConsentStringV1(_:)\/title","op":"replace","value":"setGDPRConsentStringV1:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGDPRConsentStringV1(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setGDPRConsentStringV1:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1clearCustomIDFAConsent()\/title","op":"replace","value":"clearCustomIDFAConsent"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1clearCustomIDFAConsent()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"clearCustomIDFAConsent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1hasOptedOutOfSale\/title","op":"replace","value":"hasOptedOutOfSale"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1hasOptedOutOfSale\/fragments","op":"replace","value":[{"text":"hasOptedOutOfSale","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1requestIDFAPermission(completion:)\/title","op":"replace","value":"requestIDFAPermissionWithCompletion:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1requestIDFAPermission(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestIDFAPermissionWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1usPrivacyString\/title","op":"replace","value":"usPrivacyString"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1usPrivacyString\/fragments","op":"replace","value":[{"text":"usPrivacyString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1idfaString\/title","op":"replace","value":"idfaString"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1idfaString\/fragments","op":"replace","value":[{"kind":"identifier","text":"idfaString"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gdprConsentString\/title","op":"replace","value":"gdprConsentString"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gdprConsentString\/fragments","op":"replace","value":[{"text":"gdprConsentString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1hasGDPRConsentForTeads\/title","op":"replace","value":"hasGDPRConsentForTeads"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1hasGDPRConsentForTeads\/fragments","op":"replace","value":[{"kind":"identifier","text":"hasGDPRConsentForTeads"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setIDFAConsent(_:)\/title","op":"replace","value":"setIDFAConsent:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setIDFAConsent(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setIDFAConsent:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy\/title","op":"replace","value":"TeadsPrivacy"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsPrivacy"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy\/navigatorTitle","op":"replace","value":[{"text":"TeadsPrivacy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1shared\/title","op":"replace","value":"shared"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1shared\/fragments","op":"replace","value":[{"text":"shared","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGDPRApplies(_:)\/title","op":"replace","value":"setGDPRApplies:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGDPRApplies(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setGDPRApplies:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gdprConsentStringV1\/title","op":"replace","value":"gdprConsentStringV1"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gdprConsentStringV1\/fragments","op":"replace","value":[{"text":"gdprConsentStringV1","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1idfaTrackingAuthorized\/title","op":"replace","value":"idfaTrackingAuthorized"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1idfaTrackingAuthorized\/fragments","op":"replace","value":[{"text":"idfaTrackingAuthorized","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1clearAllCustomSettings()\/title","op":"replace","value":"clearAllCustomSettings"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1clearAllCustomSettings()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearAllCustomSettings"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gppApplies\/title","op":"replace","value":"gppApplies"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gppApplies\/fragments","op":"replace","value":[{"kind":"identifier","text":"gppApplies"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gdprConsentStringV2\/title","op":"replace","value":"gdprConsentStringV2"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gdprConsentStringV2\/fragments","op":"replace","value":[{"text":"gdprConsentStringV2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gppString\/title","op":"replace","value":"gppString"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gppString\/fragments","op":"replace","value":[{"text":"gppString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setUSPrivacyString(_:)\/title","op":"replace","value":"setUSPrivacyString:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setUSPrivacyString(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUSPrivacyString:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGDPRConsentStringV2(_:)\/title","op":"replace","value":"setGDPRConsentStringV2:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGDPRConsentStringV2(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setGDPRConsentStringV2:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gppSections\/title","op":"replace","value":"gppSections"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gppSections\/fragments","op":"replace","value":[{"text":"gppSections","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gdprApplies\/title","op":"replace","value":"gdprApplies"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1gdprApplies\/fragments","op":"replace","value":[{"text":"gdprApplies","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGPPString(_:)\/title","op":"replace","value":"setGPPString:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGPPString(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setGPPString:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1isCMPPresent\/title","op":"replace","value":"isCMPPresent"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1isCMPPresent\/fragments","op":"replace","value":[{"text":"isCMPPresent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGPPSections(_:)\/title","op":"replace","value":"setGPPSections:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGPPSections(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setGPPSections:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGDPRConsentString(_:)\/title","op":"replace","value":"setGDPRConsentString:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setGDPRConsentString(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setGDPRConsentString:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}