{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teads\/init"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/init"},"metadata":{"role":"symbol","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(cs)Teads(im)init","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/init":{"abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/teadssdk\/teads\/init","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/init","type":"topic","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads":{"kind":"symbol","title":"Teads","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","type":"topic","navigatorTitle":[{"text":"Teads","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"Teads","type":"codeVoice"},{"text":" class defines the main entry point to start implementing TeadsSDK.","type":"text"}],"url":"\/documentation\/teadssdk\/teads","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Teads"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/title","value":"Teads","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/fragments","op":"replace","value":[{"text":"Teads","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"Teads"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/navigatorTitle"}]}]}