{"sections":[],"metadata":{"title":"MediaScale.scaleAspectFill","role":"symbol","modules":[{"name":"TeadsSDK"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@TeadsSDK@E@MediaScale@MediaScaleScaleAspectFill","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scaleAspectFill"}],"navigatorTitle":[{"text":"MediaScaleScaleAspectFill","kind":"identifier"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFill","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/teadssdk\/mediascale\/scaleaspectfill"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/mediascale\/scaleaspectfill"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Contents scaled to fill with fixed aspect. some portion of content may be clipped."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"scaleAspectFill","kind":"identifier"}]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Behaviour is similar to "},{"type":"codeVoice","code":"UIView.ContentMode.scaleToFill"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaScale"}],"abstract":[{"type":"text","text":"A flag used to determine how TeadsMediaView lays out its content when its bounds change."}],"navigatorTitle":[{"kind":"identifier","text":"MediaScale"}],"url":"\/documentation\/teadssdk\/mediascale","kind":"symbol","role":"symbol","title":"MediaScale"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale/scaleAspectFill":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"scaleAspectFill","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFill","abstract":[{"text":"Contents scaled to fill with fixed aspect. some portion of content may be clipped.","type":"text"}],"role":"symbol","title":"MediaScale.scaleAspectFill","navigatorTitle":[{"text":"MediaScaleScaleAspectFill","kind":"identifier"}],"url":"\/documentation\/teadssdk\/mediascale\/scaleaspectfill","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MediaScaleScaleAspectFill"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MediaScaleScaleAspectFill"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MediaScaleScaleAspectFill","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/title","value":"MediaScale","op":"replace"},{"value":[{"text":"MediaScale","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/navigatorTitle","value":[{"text":"MediaScale","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MediaScaleScaleAspectFill","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale~1scaleAspectFill\/title"},{"op":"replace","value":[{"text":"MediaScaleScaleAspectFill","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale~1scaleAspectFill\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}