{"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGppConsent","kind":"identifier"},{"kind":"text","text":"("},{"text":"consent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sectionIds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings(im)setGppConsentWithConsent:sectionIds:","title":"setGppConsent(consent:sectionIds:)","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setGppConsentWithConsent:sectionIds:"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setGppConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"consent"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sectionIds"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Which vendors and purposes did the user give consent for."}]}],"name":"consent"},{"name":"sectionIds","content":[{"inlineContent":[{"type":"text","text":"List of the applicable section ids."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you use a "},{"type":"reference","identifier":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","isActive":true},{"text":", you can skip this step: CMP will store those parameters into ","type":"text"},{"code":"UserDefaults","type":"codeVoice"},{"type":"text","text":", TeadSDK will automatically retrieve these values. "},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md"},{"text":" IAB documentation.","type":"text"}]}],"type":"aside"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/setGppConsent(consent:sectionIds:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/setgppconsent(consent:sectionids:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/setgppconsent(consent:sectionids:)"]}],"abstract":[{"type":"text","text":"In order to follow the IAB specifications for GDPR, please fill the following parameters with attention."}],"references":{"https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md":{"title":"Global Privacy Platform ","url":"https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md","type":"link","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md","titleInlineContent":[{"type":"text","text":"Global Privacy Platform "}]},"https://iabeurope.eu/tcf-for-cmps/":{"title":"CMP","url":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","type":"link","identifier":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","titleInlineContent":[{"text":"CMP","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/setGppConsent(consent:sectionIds:)":{"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementsettings\/setgppconsent(consent:sectionids:)","navigatorTitle":[{"kind":"identifier","text":"setGppConsentWithConsent:sectionIds:"}],"abstract":[{"text":"In order to follow the IAB specifications for GDPR, please fill the following parameters with attention.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setGppConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"consent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sectionIds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/setGppConsent(consent:sectionIds:)","title":"setGppConsent(consent:sectionIds:)","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","title":"TeadsAdPlacementSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementsettings","kind":"symbol","abstract":[{"text":"Specify which settings you want to set for your Teads placement.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"setGppConsentWithConsent:sectionIds:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setGppConsentWithConsent:sectionIds:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setGppConsentWithConsent:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"consent"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionIds:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sectionIds"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"consent","content":[{"inlineContent":[{"type":"text","text":"Which vendors and purposes did the user give consent for."}],"type":"paragraph"}]},{"name":"sectionIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List of the applicable section ids."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1setGppConsent(consent:sectionIds:)\/title","value":"setGppConsentWithConsent:sectionIds:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setGppConsentWithConsent:sectionIds:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1setGppConsent(consent:sectionIds:)\/fragments","op":"replace"},{"op":"replace","value":"TeadsAdPlacementSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]}]}]}