{"metadata":{"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings(im)setUsPrivacyWithConsent:","symbolKind":"method","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUsPrivacy"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"consent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol","title":"setUsPrivacy(consent:)","navigatorTitle":[{"text":"setUsPrivacyWithConsent:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setUsPrivacy"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"consent"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"consent","content":[{"inlineContent":[{"text":"The CCPA consent string.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"If you use a Content Management Platform, you can skip this step: CMP will store those parameters into "},{"type":"codeVoice","code":"UserDefaults"},{"text":", TeadSDK will automatically retrieve consent value. ","type":"text"},{"type":"reference","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md","isActive":true},{"type":"text","text":" IAB documentation."}],"type":"paragraph"}],"name":"Note","style":"note"}]}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/setusprivacy(consent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/setusprivacy(consent:)"]}],"abstract":[{"text":"In order to follow the IAB specifications for CCPA, please fill the following parameters with attention.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/setUsPrivacy(consent:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","title":"TeadsAdPlacementSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementsettings","kind":"symbol","abstract":[{"text":"Specify which settings you want to set for your Teads placement.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/setUsPrivacy(consent:)":{"role":"symbol","type":"topic","title":"setUsPrivacy(consent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUsPrivacy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"consent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setUsPrivacyWithConsent:","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/setUsPrivacy(consent:)","abstract":[{"text":"In order to follow the IAB specifications for CCPA, please fill the following parameters with attention.","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadplacementsettings\/setusprivacy(consent:)","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md":{"type":"link","url":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md","title":"CCPA","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md","titleInlineContent":[{"type":"text","text":"CCPA"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setUsPrivacyWithConsent:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setUsPrivacyWithConsent:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setUsPrivacyWithConsent:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"consent"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The CCPA consent string."}]}],"name":"consent"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","op":"replace","value":"TeadsAdPlacementSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1setUsPrivacy(consent:)\/title","value":"setUsPrivacyWithConsent:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1setUsPrivacy(consent:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setUsPrivacyWithConsent:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}