{"abstract":[{"type":"text","text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"]]},"metadata":{"role":"symbol","extendedModule":"TeadsSDK","title":"adOpportunityTrackerView(trackerView:)","externalID":"c:@CM@TeadsSDK@objc(cs)TeadsAdPlacementMedia(im)adOpportunityTrackerViewWithTrackerView:","symbolKind":"method","modules":[{"name":"TeadsSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdOpportunityTrackerView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"trackerView","content":[{"type":"paragraph","inlineContent":[{"text":"The view that will monitor your inventory","type":"text"}]}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/adOpportunityTrackerView(trackerView:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/adopportunitytrackerview(trackerview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/adopportunitytrackerview(trackerview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","kind":"symbol","abstract":[{"text":"adOpportunity is a key metrics to evaluate the performance of your inventory.","type":"text"},{"text":" ","type":"text"},{"text":"It builds the visibility score of your placement in publisher dashboards.","type":"text"}],"navigatorTitle":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"title":"TeadsAdOpportunityTrackerView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"title":"TeadsAdPlacementMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementmedia","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","abstract":[],"role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/adOpportunityTrackerView(trackerView:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/adOpportunityTrackerView(trackerView:)","type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/adopportunitytrackerview(trackerview:)","navigatorTitle":[{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"title":"adOpportunityTrackerView(trackerView:)","abstract":[{"type":"text","text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory."}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adOpportunityTrackerViewWithTrackerView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"trackerView","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"trackerView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view that will monitor your inventory"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title","value":"TeadsAdOpportunityTrackerView"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title","value":"TeadsAdPlacementMedia"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1adOpportunityTrackerView(trackerView:)\/title","value":"adOpportunityTrackerViewWithTrackerView:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1adOpportunityTrackerView(trackerView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}