{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"]]},"sections":[],"abstract":[{"text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter","type":"text"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/didFailToReceiveAd(reason:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:@CM@TeadsSDK@objc(cs)TeadsAdPlacementMedia(im)didFailToReceiveAdWithReason:","extendedModule":"TeadsSDK","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFailToReceiveAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdFailReason","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didFailToReceiveAdWithReason:","kind":"identifier"}],"title":"didFailToReceiveAd(reason:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/didfailtoreceivead(reason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/didfailtoreceivead(reason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","text":"AdFailReason"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"reason","content":[{"inlineContent":[{"text":"An object that contains the fail reason","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason":{"title":"AdFailReason","kind":"symbol","abstract":[{"type":"text","text":"Error returned when ad request has failed. The failure is usually due to network"},{"type":"text","text":" "},{"type":"text","text":"connectivity or ad availablility (i.e., no fill)."}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","navigatorTitle":[{"text":"AdFailReason","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdFailReason"}],"url":"\/documentation\/teadssdk\/adfailreason","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"title":"TeadsAdPlacementMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementmedia","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","abstract":[],"role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/didFailToReceiveAd(reason:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason","kind":"typeIdentifier","text":"AdFailReason"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter","type":"text"}],"title":"didFailToReceiveAd(reason:)","navigatorTitle":[{"kind":"identifier","text":"didFailToReceiveAdWithReason:"}],"url":"\/documentation\/teadssdk\/teadsadplacementmedia\/didfailtoreceivead(reason:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/didFailToReceiveAd(reason:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"didFailToReceiveAdWithReason:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didFailToReceiveAdWithReason:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didFailToReceiveAdWithReason:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AdFailReason","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"An object that contains the fail reason","type":"text"}],"type":"paragraph"}],"name":"reason"}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/title","value":"AdFailReason","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/fragments","value":[{"text":"AdFailReason","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"AdFailReason","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/navigatorTitle"},{"op":"replace","value":"TeadsAdPlacementMedia","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle"},{"op":"replace","value":"didFailToReceiveAdWithReason:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1didFailToReceiveAd(reason:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didFailToReceiveAdWithReason:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1didFailToReceiveAd(reason:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}