{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadapterintegrationtype\/prebid"]}],"abstract":[{"type":"text","text":"Prebid plugin value to monitor official PrebidMobileSDK integration"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prebid"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","text":"TeadsAdapterIntegrationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Adapters internal purpose only"}]}],"style":"important","type":"aside"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType\/prebid","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"prebid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdapterIntegrationType","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType"}],"externalID":"s:8TeadsSDK0A22AdapterIntegrationTypeC6prebidACvpZ","role":"symbol","title":"prebid","modules":[{"name":"TeadsSDK"}]},"sections":[],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType":{"abstract":[{"type":"text","text":"Never create your own TeadsAdapterIntegrationType directly. Use one of the predefined standard values."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"type":"topic","title":"TeadsAdapterIntegrationType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterIntegrationType"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","url":"\/documentation\/teadssdk\/teadsadapterintegrationtype","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType/prebid":{"url":"\/documentation\/teadssdk\/teadsadapterintegrationtype\/prebid","title":"prebid","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType\/prebid","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prebid"},{"text":": ","kind":"text"},{"text":"TeadsAdapterIntegrationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType"}],"abstract":[{"type":"text","text":"Prebid plugin value to monitor official PrebidMobileSDK integration"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/title","op":"replace","value":"TeadsAdapterIntegrationType"},{"value":[{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdapterIntegrationType"}]}]}]}