{"variants":[{"paths":["\/documentation\/teadssdk\/teadsadopportunitytrackerview\/requestidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadopportunitytrackerview\/requestidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Request identifier allows you to match the returned value from placement.requestAd call","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/requestIdentifier"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"? { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":"?"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView(py)requestIdentifier","navigatorTitle":[{"text":"requestIdentifier","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"title":"requestIdentifier","symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"role":"symbol","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","abstract":[{"text":"adOpportunity is a key metrics to evaluate the performance of your inventory.","type":"text"},{"text":" ","type":"text"},{"text":"It builds the visibility score of your placement in publisher dashboards.","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","title":"TeadsAdOpportunityTrackerView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView/requestIdentifier":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"text":"Request identifier allows you to match the returned value from placement.requestAd call","type":"text"}],"title":"requestIdentifier","role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView\/requestIdentifier","navigatorTitle":[{"kind":"identifier","text":"requestIdentifier"}],"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview\/requestidentifier"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"requestIdentifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"requestIdentifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID"},{"kind":"text","text":" * "},{"kind":"identifier","text":"requestIdentifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title","op":"replace","value":"TeadsAdOpportunityTrackerView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments","op":"replace","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1requestIdentifier\/title","op":"replace","value":"requestIdentifier"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView~1requestIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"requestIdentifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}