{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView"]]},"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/layoutSubviews()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsmediaview\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsmediaview\/layoutsubviews()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsMediaView(im)layoutSubviews","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"modules":[{"name":"TeadsSDK"}]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView/layoutSubviews()":{"url":"\/documentation\/teadssdk\/teadsmediaview\/layoutsubviews()","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView\/layoutSubviews()","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"role":"symbol","title":"layoutSubviews()"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView":{"kind":"symbol","navigatorTitle":[{"text":"TeadsMediaView","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The TeadsMediaView can load either images, videos and VPAID content.","type":"text"}],"url":"\/documentation\/teadssdk\/teadsmediaview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsMediaView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","title":"TeadsMediaView"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"layoutSubviews","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1layoutSubviews()\/title","value":"layoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/title","value":"TeadsMediaView","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/fragments","value":[{"kind":"identifier","text":"TeadsMediaView"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsMediaView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}