{"sections":[],"metadata":{"roleHeading":"Instance Method","title":"teadsAdPlacement(config:delegate:)","externalID":"s:7SwiftUI4ViewP8TeadsSDKE16teadsAdPlacement6config8delegateQr6ConfigQyd___AD0dgH14EventsDelegate_pSgtAD0d6UIViewH0Rd__lF::SYNTHESIZED::s:8TeadsSDK0A6NativeV9MediaViewV","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"teadsAdPlacement","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Placement","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP8TeadsSDKE16teadsAdPlacement6config8delegateQr6ConfigQyd___AD0dgH14EventsDelegate_pSgtAD0d6UIViewH0Rd__lFQO0H0qd__mfp"},{"text":".","kind":"text"},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"extendedModule":"SwiftUICore","modules":[{"name":"TeadsSDK","relatedModules":["SwiftUICore"]}],"role":"symbol","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"teadsAdPlacement","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Placement","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","preciseIdentifier":"s:7SwiftUI4ViewP8TeadsSDKE16teadsAdPlacement6config8delegateQr6ConfigQyd___AD0dgH14EventsDelegate_pSgtAD0d6UIViewH0Rd__lFQO0H0qd__mfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Config","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placement","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"TeadsUIViewPlacement","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement","preciseIdentifier":"s:8TeadsSDK0A15UIViewPlacementP","kind":"typeIdentifier"},{"text":"\n","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView"]]},"abstract":[{"text":"Add a Teads Ad Placement to the view using generic configuration","type":"text"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView\/teadsAdPlacement(config:delegate:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnative\/mediaview\/teadsadplacement(config:delegate:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"abstract":[],"url":"\/documentation\/teadssdk\/teadsnative","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","title":"TeadsNative","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"title":"TeadsAdPlacementEventsDelegate","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsUIViewPlacement":{"title":"TeadsUIViewPlacement","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement","navigatorTitle":[{"text":"TeadsUIViewPlacement","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for ad placements that return UIView-based content from loadAd()"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsUIViewPlacement","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsuiviewplacement","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementProtocol/Config":{"role":"symbol","required":true,"type":"topic","fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Config","kind":"identifier"}],"abstract":[],"url":"\/documentation\/teadssdk\/teadsadplacementprotocol\/config","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config","title":"Config","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/MediaView":{"title":"TeadsNative.MediaView","role":"symbol","url":"\/documentation\/teadssdk\/teadsnative\/mediaview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MediaView"}],"abstract":[{"type":"text","text":"The MediaView can load either images, videos and VPAID content."}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/MediaView/teadsAdPlacement(config:delegate:)":{"title":"teadsAdPlacement(config:delegate:)","abstract":[{"type":"text","text":"Add a Teads Ad Placement to the view using generic configuration"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"teadsAdPlacement","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Placement","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP8TeadsSDKE16teadsAdPlacement6config8delegateQr6ConfigQyd___AD0dgH14EventsDelegate_pSgtAD0d6UIViewH0Rd__lFQO0H0qd__mfp"},{"text":".","kind":"text"},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"url":"\/documentation\/teadssdk\/teadsnative\/mediaview\/teadsadplacement(config:delegate:)","role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView\/teadsAdPlacement(config:delegate:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title","value":"TeadsAdPlacementEventsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"op":"replace"}]}]}