{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads native ad requests flow"}],"metadata":{"modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate","navigatorTitle":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","title":"TeadsNativeAdPlacementDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"symbolKind":"protocol"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate"],"kind":"relationships","type":"inheritsFrom"}],"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnativeadplacementdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsnativeadplacementdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate\/didReceiveAd(ad:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"},{"kind":"text","text":" : "},{"text":"TeadsAdPlacementDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementDelegate","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"title":"TeadsAdPlacementDelegate","abstract":[{"text":"Root placement delegate methods needed to follow Teads ad requests flow","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadplacementdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsAdPlacementDelegate","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","kind":"symbol","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"type":"topic","navigatorTitle":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"kind":"symbol","title":"TeadsNativeAdPlacementDelegate","url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads native ad requests flow"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsLogMessageDelegate":{"title":"TeadsLogMessageDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsLogMessageDelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"url":"\/documentation\/teadssdk\/teadslogmessagedelegate","kind":"symbol","navigatorTitle":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}],"abstract":[{"text":"Log delegate enabling you to route every log message written in console into a dedicated area of your choice","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate/didReceiveAd(ad:)":{"kind":"symbol","navigatorTitle":[{"text":"didReceiveAdWithAd:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceiveAd"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd"},{"text":")","kind":"text"}],"type":"topic","title":"didReceiveAd(ad:)","abstract":[{"type":"text","text":"Called when the Teads SDK has received an ad for you to display"}],"required":true,"url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate\/didreceivead(ad:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate\/didReceiveAd(ad:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TeadsNativeAdPlacementDelegate"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate\/didReceiveAd(ad:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementDelegate","kind":"typeIdentifier","text":"TeadsAdPlacementDelegate"},{"kind":"text","text":">"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/title","value":"TeadsAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/navigatorTitle","value":[{"text":"TeadsAdPlacementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title","op":"replace","value":"TeadsNativeAdPlacementDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}]},{"op":"replace","value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle"},{"value":"TeadsLogMessageDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsLogMessageDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsLogMessageDelegate\/navigatorTitle","op":"replace","value":[{"text":"TeadsLogMessageDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate~1didReceiveAd(ad:)\/title","value":"didReceiveAdWithAd:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate~1didReceiveAd(ad:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didReceiveAdWithAd:","kind":"identifier"}]}]}]}