{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/teadssdk\/teadsinreadadplacementdelegate\/didupdateratio(ad:adratio:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsinreadadplacementdelegate\/didupdateratio(ad:adratio:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdRatio","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The teadsAd object","type":"text"}],"type":"paragraph"}],"name":"ad"},{"content":[{"inlineContent":[{"type":"text","text":"An object that will help you display the ad correctly"}],"type":"paragraph"}],"name":"adRatio"}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When it called it is the right place to update your view ratio. A basic implementation may look litke this:"}]},{"type":"codeListing","code":["func didUpdateRatio(ad: TeadsInReadAd, adRatio: TeadsAdRatio) {","    yourViewHeight = adRatio.calculateHeight(for: yourViewWidth)","}"],"syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"Alternatively you can call "},{"type":"codeVoice","code":"adRatio.value(for:)"},{"type":"text","text":" to set multiplier constraint"}]},{"type":"codeListing","code":["func didUpdateRatio(ad: TeadsInReadAd, adRatio: TeadsAdRatio) {","    let multiplier = adRatio.value(for: yourViewWidth)","    \/\/ create constaint with `multiplier and replace it with exisiting one","}"],"syntax":null}],"kind":"content"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate\/didUpdateRatio(ad:adRatio:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateRatio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate(im)didUpdateRatioWithAd:adRatio:","navigatorTitle":[{"text":"didUpdateRatioWithAd:adRatio:","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"required":true,"title":"didUpdateRatio(ad:adRatio:)","symbolKind":"method"},"abstract":[{"text":"Called when the Teads SDK needs you to resize your adView the creative inform us of its new ratio","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdView"}],"url":"\/documentation\/teadssdk\/teadsinreadadview","kind":"symbol","title":"TeadsInReadAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"}],"abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"url":"\/documentation\/teadssdk\/teadsinreadad","type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","abstract":[{"type":"text","text":"A TeadsInReadAd represents an InRead ad that will be binded to a "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","isActive":true,"type":"reference"},{"type":"text","text":" instance"}],"title":"TeadsInReadAd","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAd","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TeadsInReadAd","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","kind":"symbol","title":"TeadsInReadAdPlacementDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","abstract":[{"text":"Delegate methods needed to follow Teads inRead ad requests flow","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate/didUpdateRatio(ad:adRatio:)":{"title":"didUpdateRatio(ad:adRatio:)","abstract":[{"text":"Called when the Teads SDK needs you to resize your adView the creative inform us of its new ratio","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate\/didUpdateRatio(ad:adRatio:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didUpdateRatioWithAd:adRatio:","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate\/didupdateratio(ad:adratio:)","required":true,"role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdRatio"}],"url":"\/documentation\/teadssdk\/teadsadratio","type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","navigatorTitle":[{"kind":"identifier","text":"TeadsAdRatio"}],"abstract":[{"text":"This class is used to help in resizing a given ad view to a given aspect ratio.","type":"text"}],"title":"TeadsAdRatio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"didUpdateRatioWithAd:adRatio:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didUpdateRatioWithAd:adRatio:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didUpdateRatioWithAd:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","text":"TeadsInReadAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"text":" *) ","kind":"text"},{"text":"ad","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"adRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":" *) ","kind":"text"},{"text":"adRatio","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"ad","content":[{"inlineContent":[{"text":"The teadsAd object","type":"text"}],"type":"paragraph"}]},{"name":"adRatio","content":[{"type":"paragraph","inlineContent":[{"text":"An object that will help you display the ad correctly","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","value":"TeadsInReadAdView","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdView"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title","value":"TeadsInReadAd","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments","value":[{"text":"TeadsInReadAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsInReadAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","value":"TeadsInReadAdPlacementDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle","value":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate~1didUpdateRatio(ad:adRatio:)\/title","value":"didUpdateRatioWithAd:adRatio:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate~1didUpdateRatio(ad:adRatio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateRatioWithAd:adRatio:"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/title","value":"TeadsAdRatio","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/fragments","value":[{"text":"TeadsAdRatio","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/navigatorTitle","value":[{"text":"TeadsAdRatio","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}