{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"binding"},{"kind":"text","text":" "},{"kind":"internalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OverlayComponent","text":"OverlayComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdChoicesView(im)initWithBinding:","title":"init(binding:)","role":"symbol","navigatorTitle":[{"text":"initWithBinding:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"binding","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OverlayComponent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OverlayComponent"},{"text":"?)","kind":"text"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdChoicesView\/init(binding:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadchoicesview\/init(binding:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadchoicesview\/init(binding:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdChoicesView"]]},"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdChoicesView/init(binding:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdChoicesView\/init(binding:)","title":"init(binding:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"binding","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OverlayComponent","kind":"typeIdentifier","text":"OverlayComponent"},{"kind":"text","text":"?)"}],"url":"\/documentation\/teadssdk\/teadsadchoicesview\/init(binding:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBinding:"}],"abstract":[],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdChoicesView":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdChoicesView","url":"\/documentation\/teadssdk\/teadsadchoicesview","role":"symbol","title":"TeadsAdChoicesView","abstract":[{"type":"text","text":"The Teads AdChoices view is responsible to render the optionView or AdChoices view."}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdChoicesView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdChoicesView"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OverlayComponent":{"type":"topic","title":"OverlayComponent","url":"\/documentation\/teadssdk\/overlaycomponent","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OverlayComponent","kind":"identifier"}],"abstract":[{"type":"text","text":"Native overlay component that could be put over playerView such as "},{"inlineContent":[{"text":"AdChoices","type":"text"}],"type":"strong"},{"type":"text","text":" or "},{"inlineContent":[{"text":"ClickToAction","type":"text"}],"type":"strong"}],"navigatorTitle":[{"text":"OverlayComponent","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithBinding:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBinding:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBinding:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OverlayComponent","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OverlayComponent","text":"OverlayComponent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"component"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithBinding:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdChoicesView~1init(binding:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBinding:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdChoicesView~1init(binding:)\/fragments"},{"op":"replace","value":"TeadsAdChoicesView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdChoicesView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdChoicesView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdChoicesView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdChoicesView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdChoicesView\/navigatorTitle"},{"op":"replace","value":"OverlayComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/title"},{"op":"replace","value":[{"text":"OverlayComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/fragments"},{"op":"replace","value":[{"text":"OverlayComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OverlayComponent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}