{"seeAlsoSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)"],"title":"Request Ads over placements","generated":true,"anchor":"Request-Ads-over-placements"}],"metadata":{"title":"requestAd(requestSettings:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A23NativeAdRequestSettingsa","text":"TeadsNativeAdRequestSettings"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"}],"required":true,"externalID":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement(im)requestAdWithRequestSettings:","modules":[{"name":"TeadsSDK"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"requestAdWithRequestSettings:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdRequestSettings","text":"TeadsNativeAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23NativeAdRequestSettingsa"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"}]}],"kind":"declarations"},{"parameters":[{"name":"requestSettings","content":[{"type":"paragraph","inlineContent":[{"text":"Settings ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdRequestSettings","type":"reference"},{"text":" to tweak your needs","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique request identifier, this identifier will be the same value of TeadsNativeAd requestIdentifier property"}]}],"kind":"content"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/delegate","type":"reference","isActive":true},{"text":" property must be set to perform ad request, otherwise didReceiveAd will not be triggered","type":"text"}]}],"type":"aside","style":"note","name":"Requires"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)"},"kind":"symbol","abstract":[{"text":"Request a native ad on this placement","type":"text"},{"text":" ","type":"text"},{"text":"listen for events by implementing ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","isActive":true,"type":"reference"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnativeadplacement\/requestad(requestsettings:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsnativeadplacement\/requestad(requestsettings:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"url":"\/documentation\/teadssdk\/teadsadrequestsettings","type":"topic","title":"TeadsAdRequestSettings","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRequestSettings","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","navigatorTitle":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"abstract":[{"text":"Specify which settings you want to set for the related ad request.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement/delegate":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/delegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"title":"delegate","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement\/delegate","abstract":[{"type":"text","text":"TeadsNativeAdPlacementDelegate to follow ad placement lifecycle"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","navigatorTitle":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}],"title":"TeadsInReadAdPlacementDelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads inRead ad requests flow"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdRequestSettings":{"title":"TeadsNativeAdRequestSettings","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdRequestSettings"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdRequestSettings"}],"url":"\/documentation\/teadssdk\/teadsnativeadrequestsettings","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdRequestSettings","abstract":[{"text":"Convenience closure typealias for ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)","isActive":true,"type":"reference"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement/requestAd(requestSettings:)":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/requestAd(requestSettings:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestAdWithRequestSettings:"}],"title":"requestAd(requestSettings:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23NativeAdRequestSettingsa"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement\/requestad(requestsettings:)","abstract":[{"type":"text","text":"Request a native ad on this placement"},{"type":"text","text":" "},{"type":"text","text":"listen for events by implementing "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","type":"reference","isActive":true}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"title":"TeadsNativeAdPlacement","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement","abstract":[{"text":"Native ad placement to request native ads","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacement/requestAd(requestSettings:)":{"abstract":[{"text":"Request an InRead ad on this placement","type":"text"},{"text":" ","type":"text"},{"text":"listen for events by implementing ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","type":"reference"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsinreadadplacement\/requestad(requestsettings:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)","required":true,"type":"topic","title":"requestAd(requestSettings:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAdRequestSettings","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa"},{"text":") -> ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"}],"navigatorTitle":[{"text":"requestAdWithRequestSettings:","kind":"identifier"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"title":"TeadsNativeAdPlacementDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads native ad requests flow"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"requestAdWithRequestSettings:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"requestAdWithRequestSettings:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"anchor":"Request-Ads-over-placements","title":"Request Ads over placements","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSUUID","preciseIdentifier":"c:objc(cs)NSUUID"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"requestAdWithRequestSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","text":"TeadsAdRequestSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requestSettings"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Settings "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdRequestSettings","isActive":true},{"type":"text","text":" to tweak your needs"}],"type":"paragraph"}],"name":"requestSettings"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"A unique request identifier, this identifier will be the same value of TeadsNativeAd requestIdentifier property"}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"TeadsAdRequestSettings","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title"},{"value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments"},{"value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/navigatorTitle"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1delegate\/title"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1delegate\/fragments"},{"value":"TeadsInReadAdPlacementDelegate","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title"},{"value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments"},{"value":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle"},{"value":"requestAdWithRequestSettings:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1requestAd(requestSettings:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"requestAdWithRequestSettings:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1requestAd(requestSettings:)\/fragments"},{"value":"TeadsNativeAdPlacement","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/title"},{"value":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/fragments"},{"value":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/navigatorTitle"},{"value":"requestAdWithRequestSettings:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1requestAd(requestSettings:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAdWithRequestSettings:"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1requestAd(requestSettings:)\/fragments"},{"value":"TeadsNativeAdPlacementDelegate","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title"},{"value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments"},{"value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle"}]}]}