{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/disablecrashmonitoring()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/disablecrashmonitoring()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"inlineContent":[{"text":"Teads Crash Monitoring","type":"text"}],"type":"strong"},{"type":"text","text":" is a tool we use to monitor crashes that may occur ONLY IN OUR SDK."},{"text":" ","type":"text"},{"type":"text","text":"This tool is really helpful for us and it aims to improve our product continuously."},{"text":" ","type":"text"},{"type":"text","text":"Prevent TeadsSDK to automatically handle\/monitor crashes"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableCrashMonitoring()"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disableCrashMonitoring"},{"text":"()","kind":"text"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)disableCrashMonitoring","title":"disableCrashMonitoring()","symbolKind":"method","role":"symbol","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"disableCrashMonitoring"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"disableCrashMonitoring","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"content":[{"inlineContent":[{"type":"text","text":"TeadsSDK does not disturb any third party crash handler\/reporter such as Crashlytics"}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"}],"kind":"content"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"navigatorTitle":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings","type":"topic","title":"TeadsAdapterSettings","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/disableCrashMonitoring()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableCrashMonitoring"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableCrashMonitoring()","url":"\/documentation\/teadssdk\/teadsadaptersettings\/disablecrashmonitoring()","title":"disableCrashMonitoring()","abstract":[{"inlineContent":[{"type":"text","text":"Teads Crash Monitoring"}],"type":"strong"},{"type":"text","text":" is a tool we use to monitor crashes that may occur ONLY IN OUR SDK."},{"type":"text","text":" "},{"text":"This tool is really helpful for us and it aims to improve our product continuously.","type":"text"},{"type":"text","text":" "},{"text":"Prevent TeadsSDK to automatically handle\/monitor crashes","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"disableCrashMonitoring"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"disableCrashMonitoring","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"disableCrashMonitoring","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"disableCrashMonitoring","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"TeadsAdapterSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableCrashMonitoring()\/title","value":"disableCrashMonitoring","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"disableCrashMonitoring","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableCrashMonitoring()\/fragments","op":"replace"}]}]}