{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableDebug"},{"text":"()","kind":"text"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)enableDebug","title":"enableDebug()","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enableDebug"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Enable all TeadsSDK Log for debugging purpose","type":"text"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableDebug()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableDebug"},{"text":"()","kind":"text"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"content":[{"inlineContent":[{"text":"Remember to remove this setting when you are going in production","type":"text"}],"type":"paragraph"}],"name":"Warning","style":"warning","type":"aside"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/enabledebug()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/enabledebug()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/enableDebug()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableDebug"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableDebug()","url":"\/documentation\/teadssdk\/teadsadaptersettings\/enabledebug()","title":"enableDebug()","abstract":[{"type":"text","text":"Enable all TeadsSDK Log for debugging purpose"}],"navigatorTitle":[{"kind":"identifier","text":"enableDebug"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"navigatorTitle":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings","type":"topic","title":"TeadsAdapterSettings","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"enableDebug","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"enableDebug","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"enableDebug","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"enableDebug","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableDebug()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableDebug()\/fragments","value":[{"kind":"text","text":"- "},{"text":"enableDebug","kind":"identifier"}]},{"value":"TeadsAdapterSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}