{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"advertiserLabelTag","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"advertiserLabelTag","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder(py)advertiserLabelTag","role":"symbol","title":"advertiserLabelTag","symbolKind":"property","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/teadssdk\/tagbinderbuilder\/advertiserlabeltag"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/tagbinderbuilder\/advertiserlabeltag"]}],"abstract":[{"type":"text","text":"A non-zero tag for advertiser label view to be rendered. The maximum length will be 25 characters."}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/advertiserLabelTag","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertiserLabelTag"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"UIView element should be a "},{"code":"UILabel","type":"codeVoice"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder":{"role":"symbol","navigatorTitle":[{"text":"TagBinderBuilder","kind":"identifier"}],"url":"\/documentation\/teadssdk\/tagbinderbuilder","title":"TagBinderBuilder","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TagBinderBuilder","kind":"identifier"}],"abstract":[{"text":"This builder allows you to bind UI elements programmatically using ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","isActive":true,"type":"reference"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/advertiserLabelTag":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"advertiserLabelTag"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[{"text":"A non-zero tag for advertiser label view to be rendered. The maximum length will be 25 characters.","type":"text"}],"url":"\/documentation\/teadssdk\/tagbinderbuilder\/advertiserlabeltag","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/advertiserLabelTag","navigatorTitle":[{"text":"advertiserLabelTag","kind":"identifier"}],"type":"topic","role":"symbol","title":"advertiserLabelTag"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:tagBinder:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bind:tagBinder:"}],"url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)","title":"bind(_:tagBinder:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tagBinder"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","text":"TagBinderBuilder"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Binds the native asset ad views to this native ad using view tags binder","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"advertiserLabelTag","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"advertiserLabelTag","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertiserLabelTag"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/title","op":"replace","value":"TagBinderBuilder"},{"value":[{"text":"TagBinderBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TagBinderBuilder"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/navigatorTitle"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1advertiserLabelTag\/title","op":"replace","value":"advertiserLabelTag"},{"value":[{"kind":"identifier","text":"advertiserLabelTag"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1advertiserLabelTag\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/title","value":"bind:tagBinder:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"bind:tagBinder:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/fragments"}]}]}