{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder"]]},"abstract":[{"type":"text","text":"A non-zero tag for star rating content view to be rendered."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ratingViewTag","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/ratingViewTag","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/teadssdk\/tagbinderbuilder\/ratingviewtag"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/tagbinderbuilder\/ratingviewtag"]}],"sections":[],"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"ratingViewTag","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ratingViewTag","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"externalID":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder(py)ratingViewTag","roleHeading":"Instance Property","title":"ratingViewTag"},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/ratingViewTag":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/ratingViewTag","url":"\/documentation\/teadssdk\/tagbinderbuilder\/ratingviewtag","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ratingViewTag"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","title":"ratingViewTag","navigatorTitle":[{"text":"ratingViewTag","kind":"identifier"}],"abstract":[{"text":"A non-zero tag for star rating content view to be rendered.","type":"text"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:tagBinder:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bind:tagBinder:"}],"url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)","title":"bind(_:tagBinder:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tagBinder"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","text":"TagBinderBuilder"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Binds the native asset ad views to this native ad using view tags binder","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder":{"role":"symbol","navigatorTitle":[{"text":"TagBinderBuilder","kind":"identifier"}],"url":"\/documentation\/teadssdk\/tagbinderbuilder","title":"TagBinderBuilder","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TagBinderBuilder","kind":"identifier"}],"abstract":[{"text":"This builder allows you to bind UI elements programmatically using ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","isActive":true,"type":"reference"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ratingViewTag"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"ratingViewTag","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"text":"ratingViewTag","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ratingViewTag","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1ratingViewTag\/title"},{"value":[{"text":"ratingViewTag","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1ratingViewTag\/fragments","op":"replace"},{"value":"bind:tagBinder:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bind:tagBinder:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/title","value":"TagBinderBuilder","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/fragments","value":[{"text":"TagBinderBuilder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/navigatorTitle","value":[{"text":"TagBinderBuilder","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}