{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/Image"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/swiftuicore\/image\/init(component:default:)"]}],"abstract":[{"type":"text","text":"if default value is not provided and component does not contains image, init will fail by returning a nil value, this will ensure Image UI element is not displayed"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/Image\/init(component:default:)"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)ImageComponent"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"default"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"s:7SwiftUI5ImageV"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","role":"symbol","platforms":[{"introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"}],"title":"init(component:default:)","extendedModule":"SwiftUICore","externalID":"s:7SwiftUI5ImageV8TeadsSDKE9component7defaultACSgAD0C9ComponentCSg_AGtcfc","modules":[{"relatedModules":["SwiftUICore"],"name":"TeadsSDK"}],"symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","text":"ImageComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)ImageComponent","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"default","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"defaultImage","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"s:7SwiftUI5ImageV","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore":{"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore","url":"\/documentation\/teadssdk\/swiftuicore","kind":"symbol","title":"SwiftUICore","type":"topic","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"abstract":[],"url":"\/documentation\/teadssdk\/swiftuicore\/image","type":"topic","title":"Image","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/Image","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/ImageComponent":{"abstract":[{"text":"Native image component containing image url","type":"text"}],"url":"\/documentation\/teadssdk\/imagecomponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/ImageComponent","kind":"symbol","navigatorTitle":[{"text":"ImageComponent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageComponent","kind":"identifier"}],"type":"topic","title":"ImageComponent","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore/Image/init(component:default:)":{"abstract":[{"type":"text","text":"if default value is not provided and component does not contains image, init will fail by returning a nil value, this will ensure Image UI element is not displayed"}],"url":"\/documentation\/teadssdk\/swiftuicore\/image\/init(component:default:)","type":"topic","title":"init(component:default:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)ImageComponent","text":"ImageComponent","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"default","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/Image\/init(component:default:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"ImageComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/fragments","op":"replace","value":[{"kind":"identifier","text":"ImageComponent"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1ImageComponent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ImageComponent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}