{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"smart"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType","kind":"typeIdentifier","text":"TeadsAdapterIntegrationType"}],"roleHeading":"Type Property","symbolKind":"property","role":"symbol","externalID":"s:8TeadsSDK0A22AdapterIntegrationTypeC5smartACvpZ","modules":[{"name":"TeadsSDK"}],"title":"smart"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadapterintegrationtype\/smart"]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType\/smart","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"smart"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType","text":"TeadsAdapterIntegrationType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"aside","name":"Important","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Adapters internal purpose only"}]}]}],"kind":"content"}],"abstract":[{"text":"Smart  Ad Server mediation value to monitor integration adapter ","type":"text"},{"code":"TeadsSmartAdapter","type":"codeVoice"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType/smart":{"type":"topic","abstract":[{"type":"text","text":"Smart  Ad Server mediation value to monitor integration adapter "},{"code":"TeadsSmartAdapter","type":"codeVoice"}],"title":"smart","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"smart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType","text":"TeadsAdapterIntegrationType"}],"role":"symbol","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadapterintegrationtype\/smart","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType\/smart"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"title":"TeadsAdapterIntegrationType","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","type":"topic","navigatorTitle":[{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadapterintegrationtype","abstract":[{"text":"Never create your own TeadsAdapterIntegrationType directly. Use one of the predefined standard values.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TeadsAdapterIntegrationType","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/title"},{"value":[{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/fragments"},{"value":[{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/navigatorTitle"}]}]}