{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation\/image","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBImageInfo","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBImageInfo","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBImageInfo","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@TeadsSDK@objc(cs)OBRecommendation(py)image","title":"image","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBImageInfo","kind":"typeIdentifier","text":"OBImageInfo"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"role":"symbol","modules":[{"name":"TeadsSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/obrecommendation\/image"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/obrecommendation\/image"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBImageInfo":{"navigatorTitle":[{"text":"OBImageInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBImageInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBImageInfo","title":"OBImageInfo","url":"\/documentation\/teadssdk\/obimageinfo"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendation/image":{"abstract":[],"type":"topic","url":"\/documentation\/teadssdk\/obrecommendation\/image","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation\/image","title":"image","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBImageInfo","text":"OBImageInfo","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendation":{"navigatorTitle":[{"kind":"identifier","text":"OBRecommendation"}],"url":"\/documentation\/teadssdk\/obrecommendation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBRecommendation"}],"title":"OBRecommendation","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation","kind":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"image","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"image","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OBImageInfo","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBImageInfo","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBImageInfo"},{"text":" * ","kind":"text"},{"text":"image","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OBImageInfo","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBImageInfo\/title"},{"op":"replace","value":[{"text":"OBImageInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBImageInfo\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OBImageInfo"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBImageInfo\/navigatorTitle"},{"op":"replace","value":"image","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation~1image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"image"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation~1image\/fragments"},{"op":"replace","value":"OBRecommendation","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OBRecommendation"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/fragments"},{"op":"replace","value":[{"text":"OBRecommendation","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}