{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdOpportunityTrackerView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"TeadsSDK"}],"title":"adOpportunityTrackerView(trackerView:)","symbolKind":"method","required":true,"roleHeading":"Instance Method","externalID":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementDelegate(im)adOpportunityTrackerViewWithTrackerView:"},"sections":[],"abstract":[{"text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/adOpportunityTrackerView(trackerView:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"trackerView","content":[{"inlineContent":[{"type":"text","text":"The view that will monitor your inventory"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementdelegate\/adopportunitytrackerview(trackerview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementdelegate\/adopportunitytrackerview(trackerview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate/adOpportunityTrackerView(trackerView:)":{"abstract":[{"type":"text","text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory."}],"kind":"symbol","navigatorTitle":[{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadplacementdelegate\/adopportunitytrackerview(trackerview:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adOpportunityTrackerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackerView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/adOpportunityTrackerView(trackerView:)","role":"symbol","title":"adOpportunityTrackerView(trackerView:)","required":true,"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","kind":"symbol","abstract":[{"type":"text","text":"adOpportunity is a key metrics to evaluate the performance of your inventory."},{"type":"text","text":" "},{"type":"text","text":"It builds the visibility score of your placement in publisher dashboards."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","navigatorTitle":[{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"title":"TeadsAdOpportunityTrackerView","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate":{"abstract":[{"text":"Root placement delegate methods needed to follow Teads ad requests flow","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsadplacementdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate","role":"symbol","title":"TeadsAdPlacementDelegate","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"adOpportunityTrackerViewWithTrackerView:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView"},{"text":" *) ","kind":"text"},{"text":"trackerView","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view that will monitor your inventory","type":"text"}]}],"name":"trackerView"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"adOpportunityTrackerViewWithTrackerView:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1adOpportunityTrackerView(trackerView:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1adOpportunityTrackerView(trackerView:)\/fragments"},{"op":"replace","value":"TeadsAdOpportunityTrackerView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle"},{"op":"replace","value":"TeadsAdPlacementDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}