{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickThroughUrl"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"TeadsSDK"}],"externalID":"s:8TeadsSDK18AdChoicesComponentC15clickThroughUrl10Foundation3URLVvp","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"clickThroughUrl","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","title":"clickThroughUrl"},"abstract":[{"text":"Reach the URL that should be used when the ‘Ad Choices’ button is tapped.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Common behavior: open a Safari Web Browser with "},{"type":"codeVoice","code":"clickThroughUrl"}],"variants":[{"paths":["\/documentation\/teadssdk\/adchoicescomponent\/clickthroughurl"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl"},"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent/clickThroughUrl":{"url":"\/documentation\/teadssdk\/adchoicescomponent\/clickthroughurl","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickThroughUrl"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","abstract":[{"type":"text","text":"Reach the URL that should be used when the ‘Ad Choices’ button is tapped."},{"text":" ","type":"text"},{"text":"Common behavior: open a Safari Web Browser with ","type":"text"},{"code":"clickThroughUrl","type":"codeVoice"}],"role":"symbol","title":"clickThroughUrl","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdChoicesComponent":{"title":"AdChoicesComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent","type":"topic","url":"\/documentation\/teadssdk\/adchoicescomponent","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdChoicesComponent"}],"abstract":[{"type":"text","text":"Native Component containing AdChoices "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdChoicesComponent\/clickThroughUrl","isActive":true,"type":"reference"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdChoicesComponent"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/title","value":"AdChoicesComponent"},{"value":[{"text":"AdChoicesComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/fragments"},{"value":[{"kind":"identifier","text":"AdChoicesComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdChoicesComponent\/navigatorTitle","op":"replace"}]}]}