{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdOpportunityTrackerView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0"},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0"}],"role":"symbol","title":"adOpportunityTrackerView(trackerView:)","symbolKind":"method","modules":[{"name":"TeadsSDK"}],"externalID":"s:8TeadsSDK0A6NativeV6AdViewV11CoordinatorC020adOpportunityTrackerE007trackerE0yAA0adhiE0C_tF"},"abstract":[{"type":"text","text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"trackerView","content":[{"type":"paragraph","inlineContent":[{"text":"The view that will monitor your inventory","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnative\/adview\/coordinator\/adopportunitytrackerview(trackerview:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator\/adOpportunityTrackerView(trackerView:)"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"title":"TeadsNative","url":"\/documentation\/teadssdk\/teadsnative","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","kind":"symbol","abstract":[{"text":"adOpportunity is a key metrics to evaluate the performance of your inventory.","type":"text"},{"text":" ","type":"text"},{"text":"It builds the visibility score of your placement in publisher dashboards.","type":"text"}],"navigatorTitle":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"title":"TeadsAdOpportunityTrackerView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView":{"abstract":[{"type":"text","text":"The AdView is responsible to manage manage a Teads native ad."}],"kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsnative\/adview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdView"}],"navigatorTitle":[{"kind":"identifier","text":"AdView"}],"title":"TeadsNative.AdView","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/Coordinator":{"title":"TeadsNative.AdView.Coordinator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator","url":"\/documentation\/teadssdk\/teadsnative\/adview\/coordinator","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/Coordinator/adOpportunityTrackerView(trackerView:)":{"title":"adOpportunityTrackerView(trackerView:)","url":"\/documentation\/teadssdk\/teadsnative\/adview\/coordinator\/adopportunitytrackerview(trackerview:)","kind":"symbol","role":"symbol","abstract":[{"text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adOpportunityTrackerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackerView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/Coordinator\/adOpportunityTrackerView(trackerView:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TeadsAdOpportunityTrackerView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdOpportunityTrackerView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments"},{"op":"replace","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle"}]}]}