{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableMediaPreload"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/disablemediapreload()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/disablemediapreload()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/disableMediaPreload()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"To improve performances and user experience, media such as videos or images are preloaded."},{"type":"text","text":" "},{"type":"text","text":"This setting prevents TeadsSDK from automatically preloading media."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"disableMediaPreload"}],"role":"symbol","title":"disableMediaPreload()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableMediaPreload"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings(im)disableMediaPreload","modules":[{"name":"TeadsSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is not used anymore and will be removed in a future version of the SDK"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/disableMediaPreload()":{"deprecated":true,"role":"symbol","title":"disableMediaPreload()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableMediaPreload"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"To improve performances and user experience, media such as videos or images are preloaded."},{"type":"text","text":" "},{"type":"text","text":"This setting prevents TeadsSDK from automatically preloading media."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/disableMediaPreload()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableMediaPreload"}],"url":"\/documentation\/teadssdk\/teadsadplacementsettings\/disablemediapreload()"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"role":"symbol","title":"TeadsAdPlacementSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"abstract":[{"type":"text","text":"Specify which settings you want to set for your Teads placement."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"url":"\/documentation\/teadssdk\/teadsadplacementsettings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"disableMediaPreload"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableMediaPreload"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"disableMediaPreload"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1disableMediaPreload()\/title","value":"disableMediaPreload"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1disableMediaPreload()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableMediaPreload"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","value":"TeadsAdPlacementSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}