{"abstract":[{"type":"text","text":"Sponsored may contain the brand name of the sponsor \/ advertiser."}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sponsored","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","text":"CommonComponent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd(py)sponsored","title":"sponsored","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"sponsored","kind":"identifier"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/sponsored","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sponsored","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent\/text","isActive":true},{"text":" String property represents brand name value","type":"text"}]}],"style":"note","type":"aside","name":"Note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnativead\/sponsored"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsnativead\/sponsored"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsnativead","title":"TeadsNativeAd","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAd"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"title":"CommonComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CommonComponent"}],"navigatorTitle":[{"text":"CommonComponent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/commoncomponent","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Native Root Component"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd/sponsored":{"kind":"symbol","title":"sponsored","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/sponsored","abstract":[{"text":"Sponsored may contain the brand name of the sponsor \/ advertiser.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sponsored","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","text":"CommonComponent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sponsored","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativead\/sponsored","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent/text":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent\/text","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/teadssdk\/commoncomponent\/text","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"text"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sponsored","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"sponsored","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","kind":"typeIdentifier","text":"CommonComponent"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sponsored"},{"kind":"text","text":";"}]}]}},{"value":"TeadsNativeAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments","op":"replace","value":[{"text":"TeadsNativeAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsNativeAd"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title","value":"CommonComponent"},{"value":[{"text":"CommonComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments"},{"op":"replace","value":[{"text":"CommonComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle"},{"value":"sponsored","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd~1sponsored\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd~1sponsored\/fragments","value":[{"kind":"identifier","text":"sponsored"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}