{"metadata":{"role":"symbol","title":"enableValidationMode()","navigatorTitle":[{"text":"enableValidationMode","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableValidationMode","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)enableValidationMode"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"enableValidationMode","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Remember to remove this setting when you are going in production.","type":"text"}]}],"style":"warning","name":"Warning"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Follow "},{"type":"reference","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314783-validation-tool","isActive":true}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"abstract":[{"text":"The Teads inApp Validation tool is the best way to ensure all basic features and prerequisites are correctly implemented.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It is also useful during integration iterations."}],"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableValidationMode()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/enablevalidationmode()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/enablevalidationmode()"]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/enableValidationMode()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableValidationMode"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableValidationMode"},{"kind":"text","text":"()"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/enablevalidationmode()","abstract":[{"type":"text","text":"The Teads inApp Validation tool is the best way to ensure all basic features and prerequisites are correctly implemented."},{"type":"text","text":" "},{"type":"text","text":"It is also useful during integration iterations."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/enableValidationMode()","role":"symbol","title":"enableValidationMode()","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"type":"topic","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","title":"TeadsAdapterSettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterSettings"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings","role":"symbol"},"https://support.teads.tv/support/solutions/articles/36000314783-validation-tool":{"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314783-validation-tool","type":"link","titleInlineContent":[{"text":"validate your integration documentation","type":"text"}],"title":"validate your integration documentation","url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314783-validation-tool"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"enableValidationMode","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"enableValidationMode","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"enableValidationMode","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"enableValidationMode","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableValidationMode()\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1enableValidationMode()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"enableValidationMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TeadsAdapterSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}]},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}