{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setGppConsent(consent:sectionIds:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setGppConsent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"sectionIds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"consent","content":[{"inlineContent":[{"text":"Which vendors and purposes did the user give consent for.","type":"text"}],"type":"paragraph"}]},{"name":"sectionIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List of the applicable section ids."}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"If you use a "},{"isActive":true,"type":"reference","identifier":"https:\/\/iabeurope.eu\/tcf-for-cmps\/"},{"type":"text","text":", you can skip this step: CMP will store those parameters into "},{"code":"UserDefaults","type":"codeVoice"},{"type":"text","text":", TeadSDK will automatically retrieve these values. "},{"type":"reference","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md","isActive":true},{"type":"text","text":" IAB documentation."}],"type":"paragraph"}],"type":"aside","style":"note"}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/setgppconsent(consent:sectionids:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/setgppconsent(consent:sectionids:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setGppConsent"},{"text":"(","kind":"text"},{"text":"consent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sectionIds"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setGppConsentWithConsent:sectionIds:"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)setGppConsentWithConsent:sectionIds:","role":"symbol","title":"setGppConsent(consent:sectionIds:)","symbolKind":"method","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"In order to follow the IAB specifications for GPP, please fill the following parameters with attention."}],"references":{"https://iabeurope.eu/tcf-for-cmps/":{"identifier":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","title":"CMP","url":"https:\/\/iabeurope.eu\/tcf-for-cmps\/","type":"link","titleInlineContent":[{"type":"text","text":"CMP"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md":{"identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md","title":"Global Privacy Platform ","type":"link","titleInlineContent":[{"type":"text","text":"Global Privacy Platform "}],"url":"https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"type":"topic","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","title":"TeadsAdapterSettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterSettings"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/setGppConsent(consent:sectionIds:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setGppConsentWithConsent:sectionIds:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setGppConsent"},{"text":"(","kind":"text"},{"text":"consent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sectionIds"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/setgppconsent(consent:sectionids:)","abstract":[{"type":"text","text":"In order to follow the IAB specifications for GPP, please fill the following parameters with attention."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setGppConsent(consent:sectionIds:)","role":"symbol","title":"setGppConsent(consent:sectionIds:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"setGppConsentWithConsent:sectionIds:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setGppConsentWithConsent:sectionIds:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"setGppConsentWithConsent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"consent","kind":"internalParam"},{"kind":"text","text":" "},{"text":"sectionIds:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sectionIds"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"consent","content":[{"type":"paragraph","inlineContent":[{"text":"Which vendors and purposes did the user give consent for.","type":"text"}]}]},{"name":"sectionIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List of the applicable section ids."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"TeadsAdapterSettings","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}]},{"value":"setGppConsentWithConsent:sectionIds:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setGppConsent(consent:sectionIds:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"setGppConsentWithConsent:sectionIds:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setGppConsent(consent:sectionIds:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}