{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeToAdResizing()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/subscribetoadresizing()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/subscribetoadresizing()"]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"subscribeToAdResizing","kind":"identifier"}],"title":"subscribeToAdResizing()","role":"symbol","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)subscribeToAdResizing","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribeToAdResizing"},{"text":"()","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subscribeToAdResizing","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Convenient way to specify ability to resize in settings"}],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/subscribeToAdResizing()":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Convenient way to specify ability to resize in settings"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeToAdResizing()","title":"subscribeToAdResizing()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribeToAdResizing"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"subscribeToAdResizing","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/subscribetoadresizing()"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"type":"topic","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","title":"TeadsAdapterSettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterSettings"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"subscribeToAdResizing"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribeToAdResizing"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"subscribeToAdResizing"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1subscribeToAdResizing()\/title","value":"subscribeToAdResizing"},{"value":[{"text":"- ","kind":"text"},{"text":"subscribeToAdResizing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1subscribeToAdResizing()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings"},{"value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","op":"replace"},{"op":"replace","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle"}]}]}