{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadapterintegrationtype\/reactnative"]}],"abstract":[{"text":"React-Native plugin value to monitor integration","type":"text"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType"]]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType\/reactNative","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"reactNative","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TeadsAdapterIntegrationType","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"name":"Important","style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Adapters internal purpose only","type":"text"}]}]}],"kind":"content"}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reactNative"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType","text":"TeadsAdapterIntegrationType","kind":"typeIdentifier"}],"externalID":"s:8TeadsSDK0A22AdapterIntegrationTypeC11reactNativeACvpZ","role":"symbol","roleHeading":"Type Property","modules":[{"name":"TeadsSDK"}],"title":"reactNative"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType":{"role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType","kind":"symbol","title":"TeadsAdapterIntegrationType","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsAdapterIntegrationType","kind":"identifier"}],"abstract":[{"type":"text","text":"Never create your own TeadsAdapterIntegrationType directly. Use one of the predefined standard values."}],"url":"\/documentation\/teadssdk\/teadsadapterintegrationtype","navigatorTitle":[{"text":"TeadsAdapterIntegrationType","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterIntegrationType/reactNative":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterIntegrationType\/reactNative","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"reactNative","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdapterIntegrationType","text":"TeadsAdapterIntegrationType"}],"url":"\/documentation\/teadssdk\/teadsadapterintegrationtype\/reactnative","abstract":[{"text":"React-Native plugin value to monitor integration","type":"text"}],"role":"symbol","title":"reactNative"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/title","value":"TeadsAdapterIntegrationType","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdapterIntegrationType"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdapterIntegrationType"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterIntegrationType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}