{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableBatteryMonitoring","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Prevent to automatically set UIDevice.current.isBatteryMonitoringEnabled"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"metadata":{"navigatorTitle":[{"text":"disableBatteryMonitoring","kind":"identifier"}],"role":"symbol","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings(im)disableBatteryMonitoring","title":"disableBatteryMonitoring()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableBatteryMonitoring","kind":"identifier"},{"text":"()","kind":"text"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/disableBatteryMonitoring()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/disablebatterymonitoring()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/disablebatterymonitoring()"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"url":"\/documentation\/teadssdk\/teadsadplacementsettings","type":"topic","title":"TeadsAdPlacementSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Specify which settings you want to set for your Teads placement."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/disableBatteryMonitoring()":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/disableBatteryMonitoring()","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"disableBatteryMonitoring","kind":"identifier"}],"title":"disableBatteryMonitoring()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"disableBatteryMonitoring","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"text":"Prevent to automatically set UIDevice.current.isBatteryMonitoringEnabled","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadplacementsettings\/disablebatterymonitoring()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"disableBatteryMonitoring","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disableBatteryMonitoring","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"disableBatteryMonitoring","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","op":"replace","value":"TeadsAdPlacementSettings"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1disableBatteryMonitoring()\/title","op":"replace","value":"disableBatteryMonitoring"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableBatteryMonitoring"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings~1disableBatteryMonitoring()\/fragments"}]}]}