{"abstract":[{"text":"Plugin value flutter to monitor.","type":"text"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementsettings\/pluginflutter"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/pluginFlutter","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"pluginFlutter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Internal purpose only.","type":"text"}]}],"name":"Note","style":"note"}],"kind":"content"}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pluginFlutter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","modules":[{"name":"TeadsSDK"}],"role":"symbol","externalID":"s:8TeadsSDK0A19AdPlacementSettingsC13pluginFlutterSSvpZ","title":"pluginFlutter","roleHeading":"Type Property"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"url":"\/documentation\/teadssdk\/teadsadplacementsettings","type":"topic","title":"TeadsAdPlacementSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Specify which settings you want to set for your Teads placement."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings/pluginFlutter":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"pluginFlutter","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/teadssdk\/teadsadplacementsettings\/pluginflutter","type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings\/pluginFlutter","abstract":[{"type":"text","text":"Plugin value flutter to monitor."}],"title":"pluginFlutter","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","value":"TeadsAdPlacementSettings"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}