{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView"]]},"metadata":{"modules":[{"name":"TeadsSDK"}],"symbolKind":"method","externalID":"s:8TeadsSDK0A6NativeV6AdViewV12updateUIView_7contextyAA0acdE0C_7SwiftUI0G20RepresentableContextVyAEy_xGGtF","title":"updateUIView(_:context:)","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0"},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUIView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView","kind":"typeIdentifier","text":"TeadsNativeAdView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","kind":"typeIdentifier","text":"Context"},{"kind":"text","text":")"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","text":"TeadsNativeAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Context","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnative\/adview\/updateuiview(_:context:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/updateUIView(_:context:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIViewRepresentable.updateUIView(_:context:)","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView","type":"topic","url":"\/documentation\/teadssdk\/teadsnativeadview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdView"}],"title":"TeadsNativeAdView","abstract":[{"type":"text","text":"The Teads native ad view is responsible to manage a Teads native ad."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"TeadsNative","url":"\/documentation\/teadssdk\/teadsnative","type":"topic","role":"symbol","navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView":{"url":"\/documentation\/teadssdk\/teadsnative\/adview","title":"TeadsNative.AdView","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView","kind":"symbol","abstract":[{"type":"text","text":"The AdView is responsible to manage manage a Teads native ad."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdView"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdView"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/updateUIView(_:context:)":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUIView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAdView","text":"TeadsNativeAdView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta","text":"Context"},{"kind":"text","text":")"}],"title":"updateUIView(_:context:)","url":"\/documentation\/teadssdk\/teadsnative\/adview\/updateuiview(_:context:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/updateUIView(_:context:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"TeadsNativeAdView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/title"},{"op":"replace","value":[{"text":"TeadsNativeAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}