{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createPlacement(with:delegate:)"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPlacement","kind":"identifier"},{"text":"<","kind":"text"},{"text":"PlacementType","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PlacementType","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A0C15createPlacement4with8delegatexSg6ConfigQz_AA0a2AdD14EventsDelegate_pSgtAA0ahD8ProtocolRzlFZ0D4TypeL_xmfp"},{"text":".","kind":"text"},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"},{"text":"? = nil) -> ","kind":"text"},{"text":"PlacementType","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A0C15createPlacement4with8delegatexSg6ConfigQz_AA0a2AdD14EventsDelegate_pSgtAA0ahD8ProtocolRzlFZ0D4TypeL_xmfp"},{"text":"? ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlacementType","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"TeadsAdPlacementProtocol","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPlacement"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"PlacementType"},{"kind":"text","text":">("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A0C15createPlacement4with8delegatexSg6ConfigQz_AA0a2AdD14EventsDelegate_pSgtAA0ahD8ProtocolRzlFZ0D4TypeL_xmfp","text":"PlacementType"},{"text":".","kind":"text"},{"text":"Config","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"PlacementType","preciseIdentifier":"s:8TeadsSDK0A0C15createPlacement4with8delegatexSg6ConfigQz_AA0a2AdD14EventsDelegate_pSgtAA0ahD8ProtocolRzlFZ0D4TypeL_xmfp","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:8TeadsSDK0A0C15createPlacement4with8delegatexSg6ConfigQz_AA0a2AdD14EventsDelegate_pSgtAA0ahD8ProtocolRzlFZ","roleHeading":"Type Method","modules":[{"name":"TeadsSDK"}],"extendedModule":"TeadsSDK","title":"createPlacement(with:delegate:)"},"variants":[{"paths":["\/documentation\/teadssdk\/teads\/createplacement(with:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementProtocol":{"type":"topic","title":"TeadsAdPlacementProtocol","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementprotocol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdPlacementProtocol","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"title":"TeadsAdPlacementEventsDelegate","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createPlacement(with:delegate:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPlacement","kind":"identifier"},{"text":"<","kind":"text"},{"text":"PlacementType","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A0C15createPlacement4with8delegatexSg6ConfigQz_AA0a2AdD14EventsDelegate_pSgtAA0ahD8ProtocolRzlFZ0D4TypeL_xmfp","text":"PlacementType","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa","text":"Config","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A0C15createPlacement4with8delegatexSg6ConfigQz_AA0a2AdD14EventsDelegate_pSgtAA0ahD8ProtocolRzlFZ0D4TypeL_xmfp","text":"PlacementType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createPlacement(with:delegate:)","title":"createPlacement(with:delegate:)","url":"\/documentation\/teadssdk\/teads\/createplacement(with:delegate:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementProtocol/Config":{"role":"symbol","required":true,"type":"topic","fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Config","kind":"identifier"}],"abstract":[],"url":"\/documentation\/teadssdk\/teadsadplacementprotocol\/config","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config","title":"Config","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads":{"kind":"symbol","title":"Teads","url":"\/documentation\/teadssdk\/teads","abstract":[{"text":"The ","type":"text"},{"code":"Teads","type":"codeVoice"},{"text":" class defines the main entry point to start implementing TeadsSDK.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Teads"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","navigatorTitle":[{"kind":"identifier","text":"Teads"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title","value":"TeadsAdPlacementEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/title","value":"Teads"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/fragments","value":[{"text":"Teads","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/navigatorTitle","value":[{"text":"Teads","kind":"identifier"}]}]}]}