{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads"]]},"sections":[],"abstract":[{"text":"Specifies the wrapper framework type and version used to integrate the Teads SDK.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrapperFrameworkInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrapperFrameworkInfo","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for native iOS integration (default)."},{"type":"text","text":" "},{"type":"text","text":"Set this property only when using Flutter or React Native as a wrapper framework."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Default value","type":"text"}]},{"type":"text","text":": "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" (native iOS integration)"}]},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"For Flutter integration","type":"text"}],"type":"strong"},{"text":":","type":"text"}]},{"type":"codeListing","code":["Teads.wrapperFrameworkInfo = WrapperFrameworkInfo.flutter(\"1.0.0\")"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"For React Native integration","type":"text"}],"type":"strong"},{"text":":","type":"text"}]},{"type":"codeListing","code":["Teads.wrapperFrameworkInfo = WrapperFrameworkInfo.reactNative(\"1.0.0\")"],"syntax":"swift"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"This property should be set only if the publisher uses Flutter or React Native"},{"type":"text","text":" "},{"type":"text","text":"as a wrapper to the SDK. For native iOS integration, keep it as "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"Note","style":"note"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo"}]}],"name":"See Also","style":"note"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/FrameworkType","isActive":true}]}],"name":"See Also","style":"note"}],"kind":"content"}],"metadata":{"title":"wrapperFrameworkInfo","navigatorTitle":[{"text":"wrapperFrameworkInfo","kind":"identifier"}],"roleHeading":"Type Property","externalID":"c:@M@TeadsSDK@objc(cs)Teads(cpy)wrapperFrameworkInfo","role":"symbol","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrapperFrameworkInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrapperFrameworkInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo"},{"text":"?","kind":"text"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teads\/wrapperframeworkinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teads\/wrapperframeworkinfo"]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/wrapperFrameworkInfo","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads":{"kind":"symbol","title":"Teads","url":"\/documentation\/teadssdk\/teads","abstract":[{"text":"The ","type":"text"},{"code":"Teads","type":"codeVoice"},{"text":" class defines the main entry point to start implementing TeadsSDK.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Teads"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","navigatorTitle":[{"kind":"identifier","text":"Teads"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/FrameworkType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FrameworkType","kind":"identifier"}],"type":"topic","title":"FrameworkType","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/FrameworkType","navigatorTitle":[{"text":"FrameworkType","kind":"identifier"}],"url":"\/documentation\/teadssdk\/frameworktype","abstract":[{"text":"Represents the type of wrapper framework used for SDK integration.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/wrapperFrameworkInfo":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/wrapperFrameworkInfo","url":"\/documentation\/teadssdk\/teads\/wrapperframeworkinfo","title":"wrapperFrameworkInfo","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrapperFrameworkInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo","text":"WrapperFrameworkInfo"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"wrapperFrameworkInfo"}],"kind":"symbol","abstract":[{"text":"Specifies the wrapper framework type and version used to integrate the Teads SDK.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/WrapperFrameworkInfo":{"role":"symbol","title":"WrapperFrameworkInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrapperFrameworkInfo"}],"url":"\/documentation\/teadssdk\/wrapperframeworkinfo","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrapperFrameworkInfo"}],"abstract":[{"type":"text","text":"Represents wrapper framework integration information for the Teads SDK."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"wrapperFrameworkInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"wrapperFrameworkInfo","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo","kind":"typeIdentifier","text":"WrapperFrameworkInfo","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"wrapperFrameworkInfo"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/title","value":"Teads"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/fragments","value":[{"kind":"identifier","text":"Teads"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/navigatorTitle","value":[{"kind":"identifier","text":"Teads"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1FrameworkType\/title","value":"FrameworkType"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1FrameworkType\/fragments","value":[{"kind":"identifier","text":"FrameworkType"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1FrameworkType\/navigatorTitle","value":[{"kind":"identifier","text":"FrameworkType"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1wrapperFrameworkInfo\/title","value":"wrapperFrameworkInfo"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1wrapperFrameworkInfo\/fragments","value":[{"text":"wrapperFrameworkInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/title","value":"WrapperFrameworkInfo"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/fragments","value":[{"text":"WrapperFrameworkInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/navigatorTitle","value":[{"kind":"identifier","text":"WrapperFrameworkInfo"}]}]}]}