{"sections":[],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable\/placementType","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placementType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementType","text":"TeadsAdPlacementType","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"placementType"}],"symbolKind":"property","required":true,"modules":[{"name":"TeadsSDK"}],"title":"placementType","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placementType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementType","kind":"typeIdentifier","text":"TeadsAdPlacementType"}],"role":"symbol","externalID":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable(py)placementType"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementidentifiable\/placementtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementidentifiable\/placementtype"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementType":{"abstract":[],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementtype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementType"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementType"}],"title":"TeadsAdPlacementType","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementType"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementIdentifiable/placementType":{"url":"\/documentation\/teadssdk\/teadsadplacementidentifiable\/placementtype","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable\/placementType","title":"placementType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placementType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementType","text":"TeadsAdPlacementType","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","required":true,"navigatorTitle":[{"text":"placementType","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementIdentifiable":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable","url":"\/documentation\/teadssdk\/teadsadplacementidentifiable","title":"TeadsAdPlacementIdentifiable","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"placementType","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"placementType"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementType","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementType","kind":"typeIdentifier","text":"TeadsAdPlacementType"},{"kind":"text","text":" "},{"kind":"identifier","text":"placementType"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"TeadsAdPlacementType","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementType"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementType\/fragments","op":"replace"},{"value":[{"text":"TeadsAdPlacementType","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementType\/navigatorTitle","op":"replace"},{"value":"placementType","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable~1placementType\/title","op":"replace"},{"value":[{"text":"placementType","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable~1placementType\/fragments","op":"replace"},{"value":"TeadsAdPlacementIdentifiable","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/fragments","op":"replace"},{"value":[{"text":"TeadsAdPlacementIdentifiable","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}