{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd\/adRatio"},"sections":[],"abstract":[{"type":"text","text":"adRatio to correctly display ad"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"}],"navigatorTitle":[{"kind":"identifier","text":"adRatio"}],"symbolKind":"property","externalID":"c:@CM@TeadsSDK@objc(cs)TeadsInReadAd(py)adRatio","modules":[{"name":"TeadsSDK"}],"extendedModule":"TeadsSDK","roleHeading":"Instance Property","role":"symbol","title":"adRatio"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsinreadad\/adratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsinreadad\/adratio"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call  "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio\/calculateHeight(for:)","isActive":true},{"type":"text","text":" to obtain optimal height to better fit ad size"}]}]}],"kind":"content"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","navigatorTitle":[{"text":"TeadsAdRatio","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadratio","abstract":[{"text":"This class is used to help in resizing a given ad view to a given aspect ratio.","type":"text"}],"title":"TeadsAdRatio","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRatio","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd/adRatio":{"abstract":[{"text":"adRatio to correctly display ad","type":"text"}],"url":"\/documentation\/teadssdk\/teadsinreadad\/adratio","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd\/adRatio","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"adRatio","kind":"identifier"}],"title":"adRatio"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio/calculateHeight(for:)":{"navigatorTitle":[{"kind":"identifier","text":"calculateHeightForWidth:"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio\/calculateHeight(for:)","abstract":[{"type":"text","text":"Compute the best height for your TeadsInReadAdView with the given width."}],"title":"calculateHeight(for:)","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsadratio\/calculateheight(for:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateHeight"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAd"}],"abstract":[{"text":"A TeadsInReadAd represents an InRead ad that will be binded to a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","type":"reference"},{"text":" instance","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAd"}],"type":"topic","role":"symbol","title":"TeadsInReadAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","url":"\/documentation\/teadssdk\/teadsinreadad"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"kind":"symbol","url":"\/documentation\/teadssdk\/teadsinreadadview","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"type":"topic","role":"symbol","title":"TeadsInReadAdView","navigatorTitle":[{"text":"TeadsInReadAdView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"adRatio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"adRatio","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"TeadsAdRatio","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":" * ","kind":"text"},{"text":"adRatio","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/title","op":"replace","value":"TeadsAdRatio"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/fragments","op":"replace","value":[{"text":"TeadsAdRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd~1adRatio\/title","op":"replace","value":"adRatio"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd~1adRatio\/fragments","op":"replace","value":[{"text":"adRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio~1calculateHeight(for:)\/title","op":"replace","value":"calculateHeightForWidth:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio~1calculateHeight(for:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"calculateHeightForWidth:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title","op":"replace","value":"TeadsInReadAd"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments","op":"replace","value":[{"text":"TeadsInReadAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle","op":"replace","value":[{"text":"TeadsInReadAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","op":"replace","value":"TeadsInReadAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}