{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"build"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/BuildTeadsAdapterSettings","preciseIdentifier":"s:8TeadsSDK0A15AdapterSettingsC05BuildacD0a","text":"BuildTeadsAdapterSettings"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"build","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"closure to tune settings"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/init(build:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/init(build:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init(build:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Instance settings builder"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"build"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BuildTeadsAdapterSettings","preciseIdentifier":"s:8TeadsSDK0A15AdapterSettingsC05BuildacD0a"},{"kind":"text","text":")"}],"title":"init(build:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)initWithBuild:","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBuild:"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/init(build:)":{"role":"symbol","title":"init(build:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"build"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BuildTeadsAdapterSettings","preciseIdentifier":"s:8TeadsSDK0A15AdapterSettingsC05BuildacD0a"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instance settings builder"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/init(build:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBuild:"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/init(build:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"role":"symbol","title":"TeadsAdapterSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterSettings"}],"abstract":[{"type":"text","text":"Settings used to load Teads’ mediation adapter ads"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/BuildTeadsAdapterSettings":{"role":"symbol","title":"TeadsAdapterSettings.BuildTeadsAdapterSettings","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuildTeadsAdapterSettings"}],"abstract":[{"type":"text","text":"Convenience closure typealias for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/BuildTeadsAdapterSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BuildTeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/buildteadsadaptersettings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBuild:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBuild:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBuild:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(TeadsAdapterSettings *)","preciseIdentifier":"c:BFv(#*$@M@TeadsSDK@objc(cs)TeadsAdapterSettings)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"build"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1init(build:)\/title","value":"initWithBuild:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1init(build:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBuild:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}