{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/delegate","interfaceLanguage":"swift"},"abstract":[{"text":"TeadsNativeAdPlacementDelegate to follow ad placement lifecycle","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement"]]},"metadata":{"modules":[{"name":"TeadsSDK"}],"required":true,"title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate","kind":"typeIdentifier","text":"TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"?"}],"externalID":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement(py)delegate","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","text":"TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnativeadplacement\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsnativeadplacement\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement":{"abstract":[{"text":"Native ad placement to request native ads","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement","title":"TeadsNativeAdPlacement","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"title":"TeadsNativeAdPlacementDelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads native ad requests flow"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement\/delegate","required":true,"title":"delegate","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement\/delegate","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"text":"TeadsNativeAdPlacementDelegate to follow ad placement lifecycle","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"delegate","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<TeadsNativeAdPlacementDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"TeadsNativeAdPlacement","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/navigatorTitle"},{"op":"replace","value":"TeadsNativeAdPlacementDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments"},{"op":"replace","value":[{"text":"TeadsNativeAdPlacementDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1delegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement~1delegate\/fragments"}]}]}