{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disableTeadsAudioSessionManagement"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"disableTeadsAudioSessionManagement"}],"title":"disableTeadsAudioSessionManagement()","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)disableTeadsAudioSessionManagement","modules":[{"name":"TeadsSDK"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableTeadsAudioSessionManagement()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"abstract":[{"text":"By default, the Teads SDK handles the audio session by setting its category to ambient.","type":"text"},{"text":" ","type":"text"},{"text":"This means that all the audio played by other apps will be simply mixed with the ad sound.","type":"text"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/disableteadsaudiosessionmanagement()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/disableteadsaudiosessionmanagement()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"disableTeadsAudioSessionManagement","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"content":[{"inlineContent":[{"type":"text","text":"If you chose to handle the audio session by yourself you need to call "},{"type":"codeVoice","code":"disableTeadsAudioSessionManagement"},{"text":" and implement  ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStartPlayingAudio(_:)"},{"text":" & ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStopPlayingAudio(_:)"}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/disableTeadsAudioSessionManagement()":{"abstract":[{"type":"text","text":"By default, the Teads SDK handles the audio session by setting its category to ambient."},{"text":" ","type":"text"},{"type":"text","text":"This means that all the audio played by other apps will be simply mixed with the ad sound."}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings\/disableteadsaudiosessionmanagement()","title":"disableTeadsAudioSessionManagement()","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableTeadsAudioSessionManagement()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disableTeadsAudioSessionManagement"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableTeadsAudioSessionManagement"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/adStartPlayingAudio(_:)":{"abstract":[{"type":"text","text":"Called when an ad starts playing audio."}],"url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/adstartplayingaudio(_:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStartPlayingAudio(_:)","type":"topic","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adStartPlayingAudio:"}],"title":"adStartPlayingAudio(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStartPlayingAudio","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"role":"symbol","title":"TeadsAdapterSettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPlaybackDelegate/adStopPlayingAudio(_:)":{"kind":"symbol","title":"adStopPlayingAudio(_:)","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPlaybackDelegate\/adStopPlayingAudio(_:)","type":"topic","navigatorTitle":[{"text":"adStopPlayingAudio:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when an ad stops playing audio."}],"url":"\/documentation\/teadssdk\/teadsplaybackdelegate\/adstopplayingaudio(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStopPlayingAudio","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAd","text":"TeadsAd","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"disableTeadsAudioSessionManagement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disableTeadsAudioSessionManagement","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"disableTeadsAudioSessionManagement"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableTeadsAudioSessionManagement()\/title","value":"disableTeadsAudioSessionManagement"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableTeadsAudioSessionManagement()\/fragments","value":[{"kind":"text","text":"- "},{"text":"disableTeadsAudioSessionManagement","kind":"identifier"}]},{"value":"adStartPlayingAudio:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1adStartPlayingAudio(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1adStartPlayingAudio(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adStartPlayingAudio:"}]},{"value":"TeadsAdapterSettings","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title"},{"value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1adStopPlayingAudio(_:)\/title","value":"adStopPlayingAudio:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPlaybackDelegate~1adStopPlayingAudio(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adStopPlayingAudio:"}],"op":"replace"}]}]}