{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Property","externalID":"s:8TeadsSDK0A15AdapterSettingsC25hasSubscribedToAdResizingSbvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasSubscribedToAdResizing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","title":"hasSubscribedToAdResizing","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/hasSubscribedToAdResizing"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/hassubscribedtoadresizing"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Return true if the placement has subscribed to ad resizing."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasSubscribedToAdResizing"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"role":"symbol","title":"TeadsAdapterSettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/hasSubscribedToAdResizing":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/hassubscribedtoadresizing","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/hasSubscribedToAdResizing","role":"symbol","title":"hasSubscribedToAdResizing","abstract":[{"text":"Return true if the placement has subscribed to ad resizing.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasSubscribedToAdResizing"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings"},{"value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}]}]}]}