{"abstract":[{"type":"text","text":"Version of adapter key to monitor mediation adadpters"}],"metadata":{"title":"integrationVersionKey","role":"symbol","modules":[{"name":"TeadsSDK"}],"symbolKind":"property","roleHeading":"Type Property","externalID":"s:8TeadsSDK0A15AdapterSettingsC21integrationVersionKeySSvpZ","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"integrationVersionKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/integrationversionkey"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"integrationVersionKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"name":"Note","style":"note","content":[{"inlineContent":[{"type":"text","text":"Adapters internal purpose only"}],"type":"paragraph"}],"type":"aside"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/integrationVersionKey","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"kind":"symbol","sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"role":"symbol","title":"TeadsAdapterSettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/integrationVersionKey":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/integrationversionkey","title":"integrationVersionKey","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"integrationVersionKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/integrationVersionKey","abstract":[{"text":"Version of adapter key to monitor mediation adadpters","type":"text"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}]}]}]}