{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"subscribeAdResizeDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"TeadsMediatedAdViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAdView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"subscribeAdResizeDelegate:forAdView:error:"}],"role":"symbol","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)subscribeAdResizeDelegate:forAdView:error:","title":"subscribeAdResizeDelegate(_:forAdView:)","platforms":[]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"subscribeAdResizeDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","text":"TeadsMediatedAdViewDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forAdView"},{"text":" ","kind":"text"},{"text":"adView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeAdResizeDelegate(_:forAdView:)"},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/subscribeadresizedelegate(_:foradview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/subscribeadresizedelegate(_:foradview:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/subscribeAdResizeDelegate(_:forAdView:)":{"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/subscribeAdResizeDelegate(_:forAdView:)","navigatorTitle":[{"text":"subscribeAdResizeDelegate:forAdView:error:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/subscribeadresizedelegate(_:foradview:)","role":"symbol","deprecated":true,"type":"topic","kind":"symbol","title":"subscribeAdResizeDelegate(_:forAdView:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"subscribeAdResizeDelegate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate","text":"TeadsMediatedAdViewDelegate"},{"kind":"text","text":", "},{"text":"forAdView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","kind":"symbol","type":"topic","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediatedAdViewDelegate":{"title":"TeadsMediatedAdViewDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","abstract":[{"text":"When using mediation adapters on inRead placement you must register your view in order to monitor and perform resize updates","type":"text"}],"url":"\/documentation\/teadssdk\/teadsmediatedadviewdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"navigatorTitle":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"role":"symbol","title":"TeadsAdapterSettings","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"subscribeAdResizeDelegate:forAdView:error:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribeAdResizeDelegate:forAdView:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"subscribeAdResizeDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<TeadsMediatedAdViewDelegate>","preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forAdView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"adView"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1subscribeAdResizeDelegate(_:forAdView:)\/title","value":"subscribeAdResizeDelegate:forAdView:error:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1subscribeAdResizeDelegate(_:forAdView:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"subscribeAdResizeDelegate:forAdView:error:","kind":"identifier"}],"op":"replace"},{"value":"TeadsMediatedAdViewDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/fragments","op":"replace","value":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}]},{"value":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings"},{"value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","op":"replace"}]}]}