{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/Text\/init(component:default:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?<"},{"kind":"genericParameter","text":"S"},{"kind":"text","text":">("},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","text":"CommonComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"default"},{"kind":"text","text":" "},{"kind":"internalParam","text":"defaultText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV8TeadsSDKE9component7defaultACSgAD15CommonComponentCSg_xSgtcSyRzlufc1SL_xmfp","text":"S"},{"kind":"text","text":"? = nil) "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"S"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sy","text":"StringProtocol"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"s:7SwiftUI4TextV8TeadsSDKE9component7defaultACSgAD15CommonComponentCSg_xSgtcSyRzlufc","extendedModule":"SwiftUICore","fragments":[{"text":"init","kind":"identifier"},{"text":"?<","kind":"text"},{"text":"S","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonComponent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"},{"text":"?, ","kind":"text"},{"text":"default","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"S","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV8TeadsSDKE9component7defaultACSgAD15CommonComponentCSg_xSgtcSyRzlufc1SL_xmfp"},{"text":"?)","kind":"text"}],"symbolKind":"init","roleHeading":"Initializer","modules":[{"relatedModules":["SwiftUICore"],"name":"TeadsSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"13.0","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.0","deprecated":false}],"title":"init(component:default:)"},"abstract":[{"text":"if default value is not provided and component does not contains text value, init will fail by returning a nil value, this will ensure Text UI element is not displayed","type":"text"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/swiftuicore\/text\/init(component:default:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/Text"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore/Text/init(component:default:)":{"type":"topic","kind":"symbol","title":"init(component:default:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?<","kind":"text"},{"text":"S","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonComponent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"},{"text":"?, ","kind":"text"},{"text":"default","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"S","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV8TeadsSDKE9component7defaultACSgAD15CommonComponentCSg_xSgtcSyRzlufc1SL_xmfp"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/Text\/init(component:default:)","abstract":[{"text":"if default value is not provided and component does not contains text value, init will fail by returning a nil value, this will ensure Text UI element is not displayed","type":"text"}],"url":"\/documentation\/teadssdk\/swiftuicore\/text\/init(component:default:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore/Text":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4TextV","text":"Text","kind":"identifier"}],"title":"Text","abstract":[],"url":"\/documentation\/teadssdk\/swiftuicore\/text","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore\/Text","role":"symbol","navigatorTitle":[{"text":"Text","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","url":"\/documentation\/teadssdk\/commoncomponent","abstract":[{"text":"Native Root Component","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonComponent"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"kind":"symbol","title":"CommonComponent","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/SwiftUICore":{"type":"topic","abstract":[],"title":"SwiftUICore","kind":"symbol","role":"collection","url":"\/documentation\/teadssdk\/swiftuicore","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/SwiftUICore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title","value":"CommonComponent"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments","value":[{"text":"CommonComponent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle","value":[{"text":"CommonComponent","kind":"identifier"}]}]}]}