{"metadata":{"modules":[{"name":"TeadsSDK"}],"roleHeading":"Enumeration","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"MediaScale"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaScale","kind":"identifier"}],"title":"MediaScale","externalID":"c:@M@TeadsSDK@E@MediaScale"},"abstract":[{"type":"text","text":"A flag used to determine how TeadsMediaView lays out its content when its bounds change."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/mediascale"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/mediascale"]}],"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/Se","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SE","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaScale"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFill","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFit"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/Equatable-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale/scaleAspectFit":{"navigatorTitle":[{"kind":"identifier","text":"MediaScaleScaleAspectFit"}],"url":"\/documentation\/teadssdk\/mediascale\/scaleaspectfit","type":"topic","kind":"symbol","abstract":[{"text":"Contents scaled to fit with fixed aspect. remainder is transparent.","type":"text"}],"title":"MediaScale.scaleAspectFit","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleAspectFit"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFit"},"doc://tv.teads.TeadsSDK.TeadsSDK/Se":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SY":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale/Equatable-Implementations":{"url":"\/documentation\/teadssdk\/mediascale\/equatable-implementations","type":"topic","kind":"article","abstract":[],"title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/Equatable-Implementations"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale":{"abstract":[{"text":"A flag used to determine how TeadsMediaView lays out its content when its bounds change.","type":"text"}],"kind":"symbol","type":"topic","title":"MediaScale","url":"\/documentation\/teadssdk\/mediascale","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaScale"}],"navigatorTitle":[{"kind":"identifier","text":"MediaScale"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale"},"doc://tv.teads.TeadsSDK.TeadsSDK/SE":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale/scaleAspectFill":{"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFill","title":"MediaScale.scaleAspectFill","url":"\/documentation\/teadssdk\/mediascale\/scaleaspectfill","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleAspectFill"}],"type":"topic","kind":"symbol","abstract":[{"text":"Contents scaled to fill with fixed aspect. some portion of content may be clipped.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MediaScaleScaleAspectFill"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale/RawRepresentable-Implementations":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/RawRepresentable-Implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/teadssdk\/mediascale\/rawrepresentable-implementations","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale/init(rawValue:)":{"url":"\/documentation\/teadssdk\/mediascale\/init(rawvalue:)","type":"topic","kind":"symbol","abstract":[],"title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/init(rawValue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"MediaScale"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MediaScale","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MediaScale"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFill","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale\/scaleAspectFit"],"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaScale","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale~1scaleAspectFit\/title","op":"replace","value":"MediaScaleScaleAspectFit"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale~1scaleAspectFit\/fragments","op":"replace","value":[{"kind":"identifier","text":"MediaScaleScaleAspectFit"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/title","op":"replace","value":"MediaScale"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/fragments","op":"replace","value":[{"text":"MediaScale","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/navigatorTitle","op":"replace","value":[{"text":"MediaScale","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale~1scaleAspectFill\/title","op":"replace","value":"MediaScaleScaleAspectFill"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale~1scaleAspectFill\/fragments","op":"replace","value":[{"kind":"identifier","text":"MediaScaleScaleAspectFill"}]}]}]}