{"variants":[{"paths":["\/documentation\/teadssdk\/oberrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/oberrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"sections":[],"metadata":{"externalID":"c:@M@TeadsSDK@E@OBErrorType","roleHeading":"Enumeration","title":"OBErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBErrorType"}],"modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"OBErrorType","kind":"identifier"}],"symbolKind":"enum","role":"symbol"},"topicSections":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/generic","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/native","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/network","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/zeroRecommendations"]},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/Equatable-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SY","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s16SendableMetatypeP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBErrorType"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType/native":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/native","type":"topic","kind":"symbol","role":"symbol","title":"OBErrorType.native","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"}],"url":"\/documentation\/teadssdk\/oberrortype\/native","abstract":[],"navigatorTitle":[{"text":"OBErrorTypeNative","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType/network":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"}],"title":"OBErrorType.network","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"OBErrorTypeNetwork","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/oberrortype\/network","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/network"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s8SendableP":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://tv.teads.TeadsSDK.TeadsSDK/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://tv.teads.TeadsSDK.TeadsSDK/SY":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/teadssdk\/oberrortype\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType","title":"OBErrorType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"OBErrorType"}],"url":"\/documentation\/teadssdk\/oberrortype","kind":"symbol","abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType/generic":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generic","kind":"identifier"}],"title":"OBErrorType.generic","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"OBErrorTypeGeneric","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/oberrortype\/generic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/generic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/teadssdk\/oberrortype\/rawrepresentable-implementations","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/RawRepresentable-Implementations"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType/zeroRecommendations":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zeroRecommendations"}],"title":"OBErrorType.zeroRecommendations","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OBErrorTypeZeroRecommendations"}],"kind":"symbol","url":"\/documentation\/teadssdk\/oberrortype\/zerorecommendations","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/zeroRecommendations"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorType/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/Equatable-Implementations","abstract":[],"type":"topic","url":"\/documentation\/teadssdk\/oberrortype\/equatable-implementations","kind":"article","title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OBErrorType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OBErrorType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"OBErrorType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/generic","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/native","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/network","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorType\/zeroRecommendations"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBErrorType","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OBErrorTypeNative","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType~1native\/title"},{"op":"replace","value":[{"text":"OBErrorTypeNative","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType~1native\/fragments"},{"op":"replace","value":"OBErrorTypeNetwork","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType~1network\/title"},{"op":"replace","value":[{"text":"OBErrorTypeNetwork","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType~1network\/fragments"},{"op":"replace","value":"OBErrorType","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OBErrorType"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType\/fragments"},{"op":"replace","value":[{"text":"OBErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType\/navigatorTitle"},{"op":"replace","value":"OBErrorTypeGeneric","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType~1generic\/title"},{"op":"replace","value":[{"text":"OBErrorTypeGeneric","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType~1generic\/fragments"},{"op":"replace","value":"OBErrorTypeZeroRecommendations","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType~1zeroRecommendations\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OBErrorTypeZeroRecommendations"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorType~1zeroRecommendations\/fragments"}]}]}