{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"metadata":{"roleHeading":"Class","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAd","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAd","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAd"}],"symbolKind":"class","title":"TeadsAd","role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Root Ad Object inherited by "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","isActive":true},{"type":"text","text":" & "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","isActive":true}],"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/delegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/playbackDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/requestIdentifier"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsad"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsad"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAd"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","title":"Swift.Equatable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","title":"Swift.Hashable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd":{"navigatorTitle":[{"text":"TeadsAd","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAd","kind":"identifier"}],"kind":"symbol","title":"TeadsAd","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd","abstract":[{"type":"text","text":"Root Ad Object inherited by "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","isActive":true},{"type":"text","text":" & "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","isActive":true}],"type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teadsad"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAd"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","url":"\/documentation\/teadssdk\/teadsnativead","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAd"}],"title":"TeadsNativeAd","abstract":[{"type":"text","text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAd"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAd"}],"type":"topic","abstract":[{"text":"A TeadsInReadAd represents an InRead ad that will be binded to a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"},{"text":" instance","type":"text"}],"title":"TeadsInReadAd","url":"\/documentation\/teadssdk\/teadsinreadad","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","role":"symbol","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject","title":"NSObject"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd/delegate":{"abstract":[{"type":"text","text":"Optional delegate object that receives state changes notifications from TeadsAd."},{"type":"text","text":" "},{"type":"text","text":"Usually this is a "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"."}],"type":"topic","title":"delegate","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/delegate","url":"\/documentation\/teadssdk\/teadsad\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TeadsAdDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdDelegate"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdView"}],"type":"topic","abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"url":"\/documentation\/teadssdk\/teadsinreadadview","kind":"symbol","role":"symbol","title":"TeadsInReadAdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd/requestIdentifier":{"abstract":[{"type":"text","text":"Request identifier allows you to match the returned value from "},{"type":"codeVoice","code":"placement.requestAd"},{"type":"text","text":" \/ "},{"type":"codeVoice","code":"placement.loadAd"},{"type":"text","text":" call"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/requestIdentifier","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"requestIdentifier","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsad\/requestidentifier","title":"requestIdentifier"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAd/playbackDelegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TeadsPlaybackDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsPlaybackDelegate"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/playbackDelegate","title":"playbackDelegate","url":"\/documentation\/teadssdk\/teadsad\/playbackdelegate","abstract":[{"text":"Optional delegate object that receives playback lifecycle changes notifications from TeadsAd.","type":"text"},{"text":" ","type":"text"},{"text":"Usually this is a ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"text":"playbackDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"TeadsAd","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"TeadsAd","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAd"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/delegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/playbackDelegate","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAd\/requestIdentifier"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAd","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/title","op":"replace","value":"TeadsAd"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/fragments","value":[{"kind":"identifier","text":"TeadsAd"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAd"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title","value":"TeadsNativeAd"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"},{"op":"replace","value":"TeadsInReadAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd~1delegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd~1delegate\/fragments"},{"op":"replace","value":"TeadsInReadAdView","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title"},{"op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdView"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle"},{"op":"replace","value":"requestIdentifier","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd~1requestIdentifier\/title"},{"op":"replace","value":[{"text":"requestIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd~1requestIdentifier\/fragments"},{"op":"replace","value":"playbackDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd~1playbackDelegate\/title"},{"op":"replace","value":[{"text":"playbackDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAd~1playbackDelegate\/fragments"}]}]}