{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"role":"symbol","title":"TeadsAdPlacementEventsDelegate","symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementeventsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementeventsdelegate"]}],"sections":[],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate\/adPlacement(_:didEmitEvent:data:)"],"generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"abstract":[],"kind":"symbol","title":"TeadsAdPlacementEventsDelegate","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementViewModel":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementViewModel","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel","abstract":[{"text":"View model that manages the state and behavior of Teads ad placements in SwiftUI","type":"text"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementviewmodel","title":"TeadsAdPlacementViewModel","kind":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementViewModel","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate/adPlacement(_:didEmitEvent:data:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adPlacement:didEmitEvent:data:"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate\/adPlacement(_:didEmitEvent:data:)","title":"adPlacement(_:didEmitEvent:data:)","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate\/adplacement(_:didemitevent:data:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable","text":"TeadsAdPlacementIdentifiable","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"didEmitEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName","text":"TeadsAdPlacementEventName","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"type":"topic","required":true},"doc://tv.teads.TeadsSDK.TeadsSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"TeadsAdPlacementEventsDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate\/adPlacement(_:didEmitEvent:data:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/objc(pl)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title","op":"replace","value":"TeadsAdPlacementEventsDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments","op":"replace","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate~1adPlacement(_:didEmitEvent:data:)\/title","op":"replace","value":"adPlacement:didEmitEvent:data:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate~1adPlacement(_:didEmitEvent:data:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"adPlacement:didEmitEvent:data:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}