{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventName","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/clicked","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/clickedOrganic","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/complete","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/failed","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/heightUpdated","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/loaded","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/pause","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/play","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/ready","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/rendered","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/startPlayAudio","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/stopPlayAudio","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/viewed"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/description","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/identifier"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/Equatable-Implementations","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s12CaseIterableP","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementeventname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementeventname"]}],"metadata":{"navigatorTitle":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"role":"symbol","title":"TeadsAdPlacementEventName","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"roleHeading":"Enumeration"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/init(rawValue:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/init(rawValue:)","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/init(rawvalue:)","abstract":[],"kind":"symbol","title":"init(rawValue:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/identifier":{"abstract":[{"type":"text","text":"Event identifier string"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/teadssdk\/teadsadplacementeventname\/identifier","title":"identifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/identifier","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/clickedOrganic":{"title":"TeadsAdPlacementEventName.clickedOrganic","navigatorTitle":[{"text":"TeadsAdPlacementEventNameClickedOrganic","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/clickedOrganic","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clickedOrganic","kind":"identifier"}],"role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/clickedorganic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/startPlayAudio":{"role":"symbol","title":"TeadsAdPlacementEventName.startPlayAudio","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/startplayaudio","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startPlayAudio","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdPlacementEventNameStartPlayAudio","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/startPlayAudio"},"doc://tv.teads.TeadsSDK.TeadsSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SY"},"doc://tv.teads.TeadsSDK.TeadsSDK/s12CaseIterableP":{"title":"Swift.CaseIterable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/s12CaseIterableP","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SQ"},"doc://tv.teads.TeadsSDK.TeadsSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/SH","type":"unresolvable"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/failed":{"url":"\/documentation\/teadssdk\/teadsadplacementeventname\/failed","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/failed","title":"TeadsAdPlacementEventName.failed","navigatorTitle":[{"text":"TeadsAdPlacementEventNameFailed","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/stopPlayAudio":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/stopPlayAudio","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/stopplayaudio","title":"TeadsAdPlacementEventName.stopPlayAudio","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopPlayAudio","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdPlacementEventNameStopPlayAudio","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/ready":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/ready","navigatorTitle":[{"text":"TeadsAdPlacementEventNameReady","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ready","kind":"identifier"}],"title":"TeadsAdPlacementEventName.ready","kind":"symbol","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/ready"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/equatable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/Equatable-Implementations","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/heightUpdated":{"navigatorTitle":[{"text":"TeadsAdPlacementEventNameHeightUpdated","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/heightUpdated","kind":"symbol","title":"TeadsAdPlacementEventName.heightUpdated","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/heightupdated","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightUpdated"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/rendered":{"kind":"symbol","title":"TeadsAdPlacementEventName.rendered","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/rendered","abstract":[],"type":"topic","navigatorTitle":[{"text":"TeadsAdPlacementEventNameRendered","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadplacementeventname\/rendered","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rendered"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/complete":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/complete","navigatorTitle":[{"text":"TeadsAdPlacementEventNameComplete","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"}],"url":"\/documentation\/teadssdk\/teadsadplacementeventname\/complete","role":"symbol","title":"TeadsAdPlacementEventName.complete"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/pause":{"kind":"symbol","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/pause","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/pause","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventNamePause"}],"title":"TeadsAdPlacementEventName.pause"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/description":{"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/description","role":"symbol","abstract":[],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/viewed":{"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/viewed","role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementEventNameViewed","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/viewed","title":"TeadsAdPlacementEventName.viewed","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewed","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/play":{"type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/play","navigatorTitle":[{"text":"TeadsAdPlacementEventNamePlay","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"TeadsAdPlacementEventName.play","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadplacementeventname\/play"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/RawRepresentable-Implementations":{"url":"\/documentation\/teadssdk\/teadsadplacementeventname\/rawrepresentable-implementations","kind":"article","type":"topic","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/RawRepresentable-Implementations","role":"collectionGroup"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName":{"role":"symbol","kind":"symbol","title":"TeadsAdPlacementEventName","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventName"}],"type":"topic","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName","url":"\/documentation\/teadssdk\/teadsadplacementeventname","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventName"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/clicked":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clicked","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdPlacementEventNameClicked","kind":"identifier"}],"title":"TeadsAdPlacementEventName.clicked","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname\/clicked","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/clicked"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName/loaded":{"url":"\/documentation\/teadssdk\/teadsadplacementeventname\/loaded","kind":"symbol","type":"topic","title":"TeadsAdPlacementEventName.loaded","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/loaded","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loaded","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdPlacementEventNameLoaded","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"TeadsAdPlacementEventName","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/clicked","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/clickedOrganic","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/complete","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/failed","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/heightUpdated","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/loaded","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/pause","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/play","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/ready","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/rendered","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/startPlayAudio","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/stopPlayAudio","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName\/viewed"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventName"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"TeadsAdPlacementEventNameClickedOrganic","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1clickedOrganic\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameClickedOrganic"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1clickedOrganic\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameStartPlayAudio","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1startPlayAudio\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameStartPlayAudio"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1startPlayAudio\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameFailed","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1failed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameFailed"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1failed\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameStopPlayAudio","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1stopPlayAudio\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameStopPlayAudio"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1stopPlayAudio\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameReady","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1ready\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventNameReady","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1ready\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameHeightUpdated","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1heightUpdated\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameHeightUpdated"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1heightUpdated\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameRendered","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1rendered\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventNameRendered","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1rendered\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameComplete","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1complete\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameComplete"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1complete\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNamePause","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1pause\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNamePause"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1pause\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameViewed","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1viewed\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventNameViewed","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1viewed\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNamePlay","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1play\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNamePlay"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1play\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventName","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventName"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/navigatorTitle"},{"op":"replace","value":"TeadsAdPlacementEventNameClicked","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1clicked\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventNameClicked","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1clicked\/fragments"},{"op":"replace","value":"TeadsAdPlacementEventNameLoaded","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1loaded\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventNameLoaded"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName~1loaded\/fragments"}]}]}