{"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPrebidPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","kind":"typeIdentifier","text":"TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate","text":"TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsPrebidAdPlacement","text":"TeadsPrebidAdPlacement"},{"kind":"text","text":"?"}],"externalID":"c:@M@TeadsSDK@objc(cs)Teads(cm)createPrebidPlacementWithSettings:delegate:","role":"symbol","title":"createPrebidPlacement(settings:delegate:)","modules":[{"name":"TeadsSDK"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"createPrebidPlacementWithSettings:delegate:"}]},"variants":[{"paths":["\/documentation\/teadssdk\/teads\/createprebidplacement(settings:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teads\/createprebidplacement(settings:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Create an  inRead ad placement to request load Prebid ad response"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createPrebidPlacement(settings:delegate:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPrebidPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"settings","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","kind":"typeIdentifier"},{"text":" = TeadsAdPlacementSettings(), ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate","text":"TeadsInReadAdPlacementDelegate","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsPrebidAdPlacement","text":"TeadsPrebidAdPlacement"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The placement’s related settings you want to apply","type":"text"}],"type":"paragraph"}],"name":"settings"},{"content":[{"type":"paragraph","inlineContent":[{"text":"TeadsInReadAdPlacementDelegate to follow ad placement lifecycle","type":"text"}]}],"name":"delegate"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"TeadsInReadAdPlacement instance, this instance must be owned\/retained"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"name":"Important","type":"aside","style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"You must own\/retain ","type":"text"},{"code":"TeadsInReadAdPlacement","type":"codeVoice"},{"text":" instance, otherwise ads could not be delivered properly: you can free placement instance on       ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate\/didReceiveAd(ad:adRatio:)","isActive":true,"type":"reference"},{"text":" or  ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/didFailToReceiveAd(reason:)","isActive":true,"type":"reference"}]}]},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration"},{"text":" documentation","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate/didFailToReceiveAd(reason:)":{"title":"didFailToReceiveAd(reason:)","navigatorTitle":[{"kind":"identifier","text":"didFailToReceiveAdWithReason:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdFailReason","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementdelegate\/didfailtoreceivead(reason:)","required":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/didFailToReceiveAd(reason:)","kind":"symbol","role":"symbol","abstract":[{"text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createPrebidPlacement(settings:delegate:)":{"url":"\/documentation\/teadssdk\/teads\/createprebidplacement(settings:delegate:)","navigatorTitle":[{"kind":"identifier","text":"createPrebidPlacementWithSettings:delegate:"}],"type":"topic","role":"symbol","title":"createPrebidPlacement(settings:delegate:)","abstract":[{"type":"text","text":"Create an  inRead ad placement to request load Prebid ad response"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPrebidPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TeadsPrebidAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsPrebidAdPlacement"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createPrebidPlacement(settings:delegate:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate/didReceiveAd(ad:adRatio:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didReceiveAdWithAd:adRatio:"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate\/didreceivead(ad:adratio:)","kind":"symbol","title":"didReceiveAd(ad:adRatio:)","required":true,"abstract":[{"type":"text","text":"Called when the Teads SDK has received an ad for you to display"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate\/didReceiveAd(ad:adRatio:)"},"https://support.teads.tv/support/solutions/articles/36000314722-inread-classic-integration":{"url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration","type":"link","title":"InRead implementation guide","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314722-inread-classic-integration","titleInlineContent":[{"type":"text","text":"InRead implementation guide"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","kind":"symbol","title":"TeadsAdPlacementSettings","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"url":"\/documentation\/teadssdk\/teadsadplacementsettings","abstract":[{"text":"Specify which settings you want to set for your Teads placement.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","kind":"symbol","title":"TeadsInReadAdPlacementDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","abstract":[{"text":"Delegate methods needed to follow Teads inRead ad requests flow","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads":{"kind":"symbol","url":"\/documentation\/teadssdk\/teads","type":"topic","navigatorTitle":[{"text":"Teads","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Teads","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","title":"Teads","abstract":[{"text":"The ","type":"text"},{"code":"Teads","type":"codeVoice"},{"text":" class defines the main entry point to start implementing TeadsSDK.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement":{"title":"TeadsPrebidAdPlacement","abstract":[{"text":"\/ Prebid ad placement to load inRead ads from Prebid winning bid","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement","kind":"symbol","url":"\/documentation\/teadssdk\/teadsprebidadplacement"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createPrebidPlacementWithSettings:delegate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createPrebidPlacementWithSettings:delegate:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsPrebidAdPlacement","text":"id<TeadsPrebidAdPlacement>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createPrebidPlacementWithSettings:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","text":"TeadsAdPlacementSettings","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"settings","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate","text":"id<TeadsInReadAdPlacementDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The placement’s related settings you want to apply","type":"text"}],"type":"paragraph"}],"name":"settings"},{"content":[{"inlineContent":[{"type":"text","text":"TeadsInReadAdPlacementDelegate to follow ad placement lifecycle"}],"type":"paragraph"}],"name":"delegate"}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"TeadsInReadAdPlacement instance, this instance must be owned\/retained","type":"text"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1didFailToReceiveAd(reason:)\/title","op":"replace","value":"didFailToReceiveAdWithReason:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1didFailToReceiveAd(reason:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFailToReceiveAdWithReason:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createPrebidPlacement(settings:delegate:)\/title","op":"replace","value":"createPrebidPlacementWithSettings:delegate:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createPrebidPlacement(settings:delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createPrebidPlacementWithSettings:delegate:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate~1didReceiveAd(ad:adRatio:)\/title","op":"replace","value":"didReceiveAdWithAd:adRatio:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate~1didReceiveAd(ad:adRatio:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveAdWithAd:adRatio:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","op":"replace","value":"TeadsAdPlacementSettings"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","op":"replace","value":"TeadsInReadAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","op":"replace","value":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/title","op":"replace","value":"Teads"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/fragments","op":"replace","value":[{"kind":"identifier","text":"Teads"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/navigatorTitle","op":"replace","value":[{"text":"Teads","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/title","op":"replace","value":"TeadsPrebidAdPlacement"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/fragments","op":"replace","value":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsPrebidAdPlacement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}