{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/teadssdk\/obrecommendation\/origurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/obrecommendation\/origurl"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation\/origUrl"},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origUrl","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(cs)OBRecommendation(py)origUrl","title":"origUrl","navigatorTitle":[{"kind":"identifier","text":"origUrl"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendation/origUrl":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation\/origUrl","url":"\/documentation\/teadssdk\/obrecommendation\/origurl","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"origUrl"}],"title":"origUrl","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendation":{"role":"symbol","title":"OBRecommendation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBRecommendation"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation","navigatorTitle":[{"kind":"identifier","text":"OBRecommendation"}],"abstract":[],"url":"\/documentation\/teadssdk\/obrecommendation","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"origUrl","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"origUrl"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"origUrl","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"origUrl","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation~1origUrl\/title"},{"value":[{"text":"origUrl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation~1origUrl\/fragments"},{"value":"OBRecommendation","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/title"},{"value":[{"kind":"identifier","text":"OBRecommendation"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/fragments"},{"value":[{"kind":"identifier","text":"OBRecommendation"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/navigatorTitle"}]}]}