{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldDisplayDisclosureIcon","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation\/shouldDisplayDisclosureIcon()","interfaceLanguage":"swift"},"metadata":{"title":"shouldDisplayDisclosureIcon()","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"shouldDisplayDisclosureIcon"}],"externalID":"c:@M@TeadsSDK@objc(cs)OBRecommendation(im)shouldDisplayDisclosureIcon","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldDisplayDisclosureIcon","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/teadssdk\/obrecommendation\/shoulddisplaydisclosureicon()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/obrecommendation\/shoulddisplaydisclosureicon()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendation/shouldDisplayDisclosureIcon()":{"url":"\/documentation\/teadssdk\/obrecommendation\/shoulddisplaydisclosureicon()","abstract":[],"navigatorTitle":[{"text":"shouldDisplayDisclosureIcon","kind":"identifier"}],"title":"shouldDisplayDisclosureIcon()","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation\/shouldDisplayDisclosureIcon()","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldDisplayDisclosureIcon","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBRecommendation":{"role":"symbol","title":"OBRecommendation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBRecommendation"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBRecommendation","navigatorTitle":[{"kind":"identifier","text":"OBRecommendation"}],"abstract":[],"url":"\/documentation\/teadssdk\/obrecommendation","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"shouldDisplayDisclosureIcon"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldDisplayDisclosureIcon"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"shouldDisplayDisclosureIcon"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation~1shouldDisplayDisclosureIcon()\/title","op":"replace","value":"shouldDisplayDisclosureIcon"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation~1shouldDisplayDisclosureIcon()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldDisplayDisclosureIcon"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/title","op":"replace","value":"OBRecommendation"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/fragments","op":"replace","value":[{"text":"OBRecommendation","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"OBRecommendation"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBRecommendation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}