{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rawUrlString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"urlString","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The content related page URL."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Setting this value can significally improve fill-rate since contextual data can be inferred from the content behing url."},{"type":"text","text":" "},{"type":"text","text":"It’s perfectly suitable for news app or retail app as most of the app content is also available on a website: it allows us to have a more detailed brand safety article by article."},{"type":"text","text":" "},{"type":"text","text":"For non-news apps, this setting is optional."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadrequestsettings\/pageurl(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadrequestsettings\/pageurl(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/pageUrl(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the publisher http page url that matches the content where Teads Ad will be loaded."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageUrl"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"pageUrl(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings(im)pageUrl:","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"pageUrl:"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings/pageUrl(_:)":{"role":"symbol","title":"pageUrl(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageUrl"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set the publisher http page url that matches the content where Teads Ad will be loaded."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/pageUrl(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageUrl:"}],"url":"\/documentation\/teadssdk\/teadsadrequestsettings\/pageurl(_:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"role":"symbol","title":"TeadsAdRequestSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdRequestSettings"}],"abstract":[{"type":"text","text":"Specify which settings you want to set for the related ad request."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"url":"\/documentation\/teadssdk\/teadsadrequestsettings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pageUrl:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageUrl:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"pageUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawUrlString"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings~1pageUrl(_:)\/title","value":"pageUrl:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings~1pageUrl(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageUrl:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title","value":"TeadsAdRequestSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}