{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel\/adPlacement(_:didEmitEvent:data:)"},"metadata":{"symbolKind":"method","title":"adPlacement(_:didEmitEvent:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adPlacement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable","text":"TeadsAdPlacementIdentifiable"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didEmitEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName","text":"TeadsAdPlacementEventName"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"TeadsSDK"}],"externalID":"s:8TeadsSDK0A20AdPlacementViewModelC02adD0_12didEmitEvent4datayAA0acD12Identifiable_pSg_AA0acdJ4NameOSDySSypGSgtF"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"TeadsAdPlacementEventsDelegate.adPlacement(_:didEmitEvent:data:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"placement","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementIdentifiable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"didEmitEvent","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventName","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementviewmodel\/adplacement(_:didemitevent:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventName":{"navigatorTitle":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"abstract":[],"type":"topic","title":"TeadsAdPlacementEventName","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventName","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventname"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementViewModel/adPlacement(_:didEmitEvent:data:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsAdPlacementIdentifiable","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementIdentifiable","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"didEmitEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventName","preciseIdentifier":"c:@M@TeadsSDK@E@TeadsAdPlacementEventName","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"url":"\/documentation\/teadssdk\/teadsadplacementviewmodel\/adplacement(_:didemitevent:data:)","title":"adPlacement(_:didEmitEvent:data:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel\/adPlacement(_:didEmitEvent:data:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementIdentifiable":{"title":"TeadsAdPlacementIdentifiable","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementIdentifiable","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementIdentifiable","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadplacementidentifiable","role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementIdentifiable","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementViewModel":{"title":"TeadsAdPlacementViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdPlacementViewModel"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementViewModel"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementviewmodel","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel","abstract":[{"type":"text","text":"View model that manages the state and behavior of Teads ad placements in SwiftUI"}]}},"variantOverrides":[{"patch":[{"value":"TeadsAdPlacementEventName","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/title"},{"value":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/fragments"},{"value":[{"text":"TeadsAdPlacementEventName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventName\/navigatorTitle"},{"value":"TeadsAdPlacementIdentifiable","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/title"},{"value":[{"kind":"identifier","text":"TeadsAdPlacementIdentifiable"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/fragments"},{"value":[{"text":"TeadsAdPlacementIdentifiable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementIdentifiable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}