{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsFluentProtocol\/didFailToReceiveAd(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsFluentProtocol"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"closure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"AdFailReason","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"didFailToReceiveAd(_:)","roleHeading":"Instance Method","symbolKind":"method","externalID":"s:8TeadsSDK0A14FluentProtocolP18didFailToReceiveAdyxyAA0iF6ReasonCcF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAd"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason","text":"AdFailReason"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"required":true,"modules":[{"name":"TeadsSDK"}]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsfluentprotocol\/didfailtoreceivead(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdFailReason":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdFailReason"}],"kind":"symbol","url":"\/documentation\/teadssdk\/adfailreason","navigatorTitle":[{"kind":"identifier","text":"AdFailReason"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdFailReason","type":"topic","abstract":[{"type":"text","text":"Error returned when ad request has failed. The failure is usually due to network"},{"type":"text","text":" "},{"type":"text","text":"connectivity or ad availablility (i.e., no fill)."}],"title":"AdFailReason"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsFluentProtocol":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsFluentProtocol","kind":"symbol","abstract":[{"text":"Fluent Interface for SwifUI implementation","type":"text"}],"url":"\/documentation\/teadssdk\/teadsfluentprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsFluentProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsFluentProtocol","kind":"identifier"}],"title":"TeadsFluentProtocol","type":"topic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsFluentProtocol/didFailToReceiveAd(_:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFailToReceiveAd","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason","text":"AdFailReason","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"abstract":[{"text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter","type":"text"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsFluentProtocol\/didFailToReceiveAd(_:)","url":"\/documentation\/teadssdk\/teadsfluentprotocol\/didfailtoreceivead(_:)","kind":"symbol","title":"didFailToReceiveAd(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/title","value":"AdFailReason","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/fragments","value":[{"text":"AdFailReason","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdFailReason\/navigatorTitle","value":[{"kind":"identifier","text":"AdFailReason"}],"op":"replace"}]}]}