{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"]]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(bind:frame:)","interfaceLanguage":"swift"},"abstract":[{"text":"Init TeadsInReadAdView by prodiving the ad to bind.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"bind","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ad","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","text":"TeadsInReadAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" = .zero)"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"ad","content":[{"inlineContent":[{"type":"text","text":"The ad that should be binded to the ad view."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Optional frame rect definition, default value is CGRect.zero","type":"text"}],"type":"paragraph"}],"name":"frame"}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Adding and positioning view inside your interface is your responsibility. We strongly advise you to use iOS AutoLayout feature.","type":"text"}],"type":"paragraph"}],"name":"Note","type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsinreadadview\/init(bind:frame:)"]}],"metadata":{"title":"init(bind:frame:)","modules":[{"name":"TeadsSDK"}],"role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd","text":"TeadsInReadAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"s:8TeadsSDK0A12InReadAdViewC4bind5frameAcA0acdE0C_So6CGRectVtcfc"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView/init(bind:frame:)":{"title":"init(bind:frame:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView\/init(bind:frame:)","url":"\/documentation\/teadssdk\/teadsinreadadview\/init(bind:frame:)","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Init TeadsInReadAdView by prodiving the ad to bind.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","type":"topic","title":"TeadsInReadAdView","url":"\/documentation\/teadssdk\/teadsinreadadview","kind":"symbol","abstract":[{"text":"The Teads inRead ad view is responsible to manage a Teads inRead ad.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdView"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAd":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAd","type":"topic","abstract":[{"type":"text","text":"A TeadsInReadAd represents an InRead ad that will be binded to a "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","isActive":true},{"type":"text","text":" instance"}],"url":"\/documentation\/teadssdk\/teadsinreadad","kind":"symbol","title":"TeadsInReadAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAd","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsInReadAd","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","op":"replace","value":"TeadsInReadAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdView"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/title","op":"replace","value":"TeadsInReadAd"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAd"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAd\/navigatorTitle","op":"replace","value":[{"text":"TeadsInReadAd","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}