{"metadata":{"title":"OBErrorCode.generic","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@E@OBErrorCode@OBErrorCodeGeneric","navigatorTitle":[{"text":"OBErrorCodeGeneric","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generic","kind":"identifier"}],"roleHeading":"Case","role":"symbol","symbolKind":"case"},"variants":[{"paths":["\/documentation\/teadssdk\/oberrorcode\/generic"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/oberrorcode\/generic"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode\/generic"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"generic"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorCode/generic":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode\/generic","navigatorTitle":[{"text":"OBErrorCodeGeneric","kind":"identifier"}],"type":"topic","abstract":[],"title":"OBErrorCode.generic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generic","kind":"identifier"}],"url":"\/documentation\/teadssdk\/oberrorcode\/generic","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorCode":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBErrorCode","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode","navigatorTitle":[{"text":"OBErrorCode","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/teadssdk\/oberrorcode","title":"OBErrorCode"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OBErrorCodeGeneric","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OBErrorCodeGeneric","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OBErrorCodeGeneric"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OBErrorCodeGeneric","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode~1generic\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode~1generic\/fragments","op":"replace","value":[{"text":"OBErrorCodeGeneric","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/title","op":"replace","value":"OBErrorCode"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"OBErrorCode"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/navigatorTitle","op":"replace","value":[{"text":"OBErrorCode","kind":"identifier"}]}]}]}