{"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"OBErrorCodeInvalidParameters","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"TeadsSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidParameters","kind":"identifier"}],"externalID":"c:@M@TeadsSDK@E@OBErrorCode@OBErrorCodeInvalidParameters","title":"OBErrorCode.invalidParameters"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidParameters","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/oberrorcode\/invalidparameters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/oberrorcode\/invalidparameters"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode\/invalidParameters"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorCode/invalidParameters":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidParameters","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode\/invalidParameters","navigatorTitle":[{"text":"OBErrorCodeInvalidParameters","kind":"identifier"}],"url":"\/documentation\/teadssdk\/oberrorcode\/invalidparameters","title":"OBErrorCode.invalidParameters","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorCode":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBErrorCode","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode","navigatorTitle":[{"text":"OBErrorCode","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/teadssdk\/oberrorcode","title":"OBErrorCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OBErrorCodeInvalidParameters"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OBErrorCodeInvalidParameters","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OBErrorCodeInvalidParameters","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode~1invalidParameters\/title","value":"OBErrorCodeInvalidParameters"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode~1invalidParameters\/fragments","value":[{"text":"OBErrorCodeInvalidParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/title","value":"OBErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/fragments","value":[{"text":"OBErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/navigatorTitle","value":[{"text":"OBErrorCode","kind":"identifier"}]}]}]}