{"abstract":[{"type":"text","text":"Ad’s main content \/ body"},{"type":"text","text":" "},{"type":"text","text":"Descriptive text associated with the product or service being advertised"}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd(py)content","symbolKind":"property","navigatorTitle":[{"text":"content","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"title":"content","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","text":"CommonComponent"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonComponent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent\/text","isActive":true,"type":"reference"},{"text":" String property reprensent large description of ad","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Note"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnativead\/content"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsnativead\/content"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/content"},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"kind":"symbol","url":"\/documentation\/teadssdk\/commoncomponent","role":"symbol","abstract":[{"type":"text","text":"Native Root Component"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommonComponent"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"title":"CommonComponent"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"role":"symbol","url":"\/documentation\/teadssdk\/teadsnativead","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAd"}],"abstract":[{"text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable","type":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAd"}],"title":"TeadsNativeAd","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd/content":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/content","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"content"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"},{"kind":"text","text":"?"}],"title":"content","abstract":[{"type":"text","text":"Ad’s main content \/ body"},{"text":" ","type":"text"},{"text":"Descriptive text associated with the product or service being advertised","type":"text"}],"url":"\/documentation\/teadssdk\/teadsnativead\/content"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent/text":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent\/text","url":"\/documentation\/teadssdk\/commoncomponent\/text","abstract":[],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"text"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"content","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"content"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CommonComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"content","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"CommonComponent","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CommonComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CommonComponent"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle"},{"op":"replace","value":"TeadsNativeAd","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title"},{"op":"replace","value":[{"text":"TeadsNativeAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsNativeAd"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"},{"op":"replace","value":"content","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd~1content\/title"},{"op":"replace","value":[{"kind":"identifier","text":"content"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd~1content\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}