{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuildTeadsAdRequestSettings"},{"kind":"text","text":" = ("},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","text":"TeadsAdRequestSettings","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadrequestsettings\/buildteadsadrequestsettings"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"typealias","role":"symbol","externalID":"s:8TeadsSDK0A17AdRequestSettingsC05BuildacdE0a","title":"TeadsAdRequestSettings.BuildTeadsAdRequestSettings","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuildTeadsAdRequestSettings"}],"navigatorTitle":[{"text":"BuildTeadsAdRequestSettings","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"roleHeading":"Type Alias"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/BuildTeadsAdRequestSettings"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings"]]},"abstract":[{"text":"Convenience closure typealias for ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","type":"reference","isActive":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings/BuildTeadsAdRequestSettings":{"navigatorTitle":[{"text":"BuildTeadsAdRequestSettings","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadrequestsettings\/buildteadsadrequestsettings","title":"TeadsAdRequestSettings.BuildTeadsAdRequestSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/BuildTeadsAdRequestSettings","abstract":[{"type":"text","text":"Convenience closure typealias for "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","isActive":true}],"type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BuildTeadsAdRequestSettings","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"url":"\/documentation\/teadssdk\/teadsadrequestsettings","title":"TeadsAdRequestSettings","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRequestSettings","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","abstract":[{"text":"Specify which settings you want to set for the related ad request.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title","value":"TeadsAdRequestSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments","value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/navigatorTitle","value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}]}]}]}