{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/dismantleUIView(inReadAdView:coordinator:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"dismantleUIView(inReadAdView:coordinator:)","externalID":"s:8TeadsSDK0A6InReadV6AdViewV15dismantleUIView02indeF011coordinatoryAA0acdeF0C_AE11CoordinatorCtFZ","modules":[{"name":"TeadsSDK"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","platforms":[{"beta":false,"introducedAt":"13.0","name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"13.0","name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"13.0","name":"Mac Catalyst","unavailable":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismantleUIView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inReadAdView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"coordinator"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A6InReadV6AdViewV11CoordinatorC","text":"Coordinator","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsinread\/adview\/dismantleuiview(inreadadview:coordinator:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismantleUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inReadAdView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView","text":"TeadsInReadAdView","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView"},{"text":", ","kind":"text"},{"text":"coordinator","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"_","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8TeadsSDK0A6InReadV6AdViewV11CoordinatorC","text":"Coordinator","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead":{"title":"TeadsInRead","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInRead"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsinread","navigatorTitle":[{"kind":"identifier","text":"TeadsInRead"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView":{"type":"topic","url":"\/documentation\/teadssdk\/teadsinread\/adview","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView","title":"TeadsInRead.AdView","navigatorTitle":[{"text":"AdView","kind":"identifier"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdView":{"navigatorTitle":[{"text":"TeadsInReadAdView","kind":"identifier"}],"title":"TeadsInReadAdView","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdView","role":"symbol","url":"\/documentation\/teadssdk\/teadsinreadadview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsInReadAdView","kind":"identifier"}],"abstract":[{"type":"text","text":"The Teads inRead ad view is responsible to manage a Teads inRead ad."}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/dismantleUIView(inReadAdView:coordinator:)":{"title":"dismantleUIView(inReadAdView:coordinator:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismantleUIView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inReadAdView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsInReadAdView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"coordinator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Coordinator","preciseIdentifier":"s:8TeadsSDK0A6InReadV6AdViewV11CoordinatorC"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","url":"\/documentation\/teadssdk\/teadsinread\/adview\/dismantleuiview(inreadadview:coordinator:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/dismantleUIView(inReadAdView:coordinator:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInRead/AdView/Coordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInRead\/AdView\/Coordinator","url":"\/documentation\/teadssdk\/teadsinread\/adview\/coordinator","role":"symbol","title":"TeadsInRead.AdView.Coordinator","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/title","op":"replace","value":"TeadsInReadAdView"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/fragments","op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdView\/navigatorTitle","op":"replace","value":[{"text":"TeadsInReadAdView","kind":"identifier"}]}]}]}