{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"You should call it when view like Call to Action button is tapped"},{"type":"text","text":" "},{"type":"text","text":"This will open link on SFSafariViewController or open directly an app depending on the link itself"}],"metadata":{"role":"symbol","externalID":"c:@M@TeadsSDK@objc(cs)CommonComponent(im)didTapView","symbolKind":"method","modules":[{"name":"TeadsSDK"}],"title":"didTapView()","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"didTapView"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapView"},{"kind":"text","text":"()"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didTapView","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent\/didTapView()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/teadssdk\/commoncomponent\/didtapview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/commoncomponent\/didtapview()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","url":"\/documentation\/teadssdk\/commoncomponent","abstract":[{"text":"Native Root Component","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonComponent"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"kind":"symbol","title":"CommonComponent","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent/didTapView()":{"navigatorTitle":[{"kind":"identifier","text":"didTapView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent\/didTapView()","type":"topic","role":"symbol","kind":"symbol","title":"didTapView()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didTapView","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"You should call it when view like Call to Action button is tapped"},{"type":"text","text":" "},{"type":"text","text":"This will open link on SFSafariViewController or open directly an app depending on the link itself"}],"url":"\/documentation\/teadssdk\/commoncomponent\/didtapview()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didTapView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didTapView","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didTapView","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title","value":"CommonComponent"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments","value":[{"kind":"identifier","text":"CommonComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle","value":[{"text":"CommonComponent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent~1didTapView()\/title","value":"didTapView"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent~1didTapView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}