{"sections":[],"abstract":[{"text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementmedianative\/adopportunitytrackerview(trackerview:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadplacementmedianative\/adopportunitytrackerview(trackerview:)"]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/adOpportunityTrackerView(trackerView:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative"]]},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@CM@TeadsSDK@objc(cs)TeadsAdPlacementMediaNative(im)adOpportunityTrackerViewWithTrackerView:","navigatorTitle":[{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}],"extendedModule":"TeadsSDK","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adOpportunityTrackerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackerView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"adOpportunityTrackerView(trackerView:)","role":"symbol","modules":[{"name":"TeadsSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adOpportunityTrackerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackerView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view that will monitor your inventory"}],"type":"paragraph"}],"name":"trackerView"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMediaNative/adOpportunityTrackerView(trackerView:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/adOpportunityTrackerView(trackerView:)","kind":"symbol","abstract":[{"text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory.","type":"text"}],"role":"symbol","type":"topic","title":"adOpportunityTrackerView(trackerView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}],"url":"\/documentation\/teadssdk\/teadsadplacementmedianative\/adopportunitytrackerview(trackerview:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdOpportunityTrackerView":{"role":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","navigatorTitle":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadopportunitytrackerview","title":"TeadsAdOpportunityTrackerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}],"abstract":[{"type":"text","text":"adOpportunity is a key metrics to evaluate the performance of your inventory."},{"type":"text","text":" "},{"type":"text","text":"It builds the visibility score of your placement in publisher dashboards."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMediaNative":{"url":"\/documentation\/teadssdk\/teadsadplacementmedianative","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementMediaNative","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative","abstract":[],"title":"TeadsAdPlacementMediaNative","navigatorTitle":[{"text":"TeadsAdPlacementMediaNative","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adOpportunityTrackerViewWithTrackerView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsAdOpportunityTrackerView","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdOpportunityTrackerView","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"trackerView","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The view that will monitor your inventory","type":"text"}],"type":"paragraph"}],"name":"trackerView"}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative~1adOpportunityTrackerView(trackerView:)\/title","value":"adOpportunityTrackerViewWithTrackerView:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative~1adOpportunityTrackerView(trackerView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/title","value":"TeadsAdOpportunityTrackerView"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/fragments","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdOpportunityTrackerView\/navigatorTitle","value":[{"text":"TeadsAdOpportunityTrackerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative\/title","value":"TeadsAdPlacementMediaNative"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative\/fragments","value":[{"text":"TeadsAdPlacementMediaNative","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative\/navigatorTitle","value":[{"text":"TeadsAdPlacementMediaNative","kind":"identifier"}]}]}]}