{"sections":[],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"API Collection","modules":[{"name":"TeadsSDK"}],"title":"TeadsAdPlacementDelegate Implementations","role":"collectionGroup"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/TeadsAdPlacementDelegate-Implementations"},"topicSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/adOpportunityTrackerView(trackerView:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/didFailToReceiveAd(reason:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementmedianative\/teadsadplacementdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementmedianative\/teadsadplacementdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMediaNative":{"url":"\/documentation\/teadssdk\/teadsadplacementmedianative","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementMediaNative","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative","abstract":[],"title":"TeadsAdPlacementMediaNative","navigatorTitle":[{"text":"TeadsAdPlacementMediaNative","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMediaNative/adOpportunityTrackerView(trackerView:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/adOpportunityTrackerView(trackerView:)","kind":"symbol","abstract":[{"text":"Called when the Teads SDK has a tracker view to provide you. You have to place it where your ad slot is. It will be used to help monitor your inventory.","type":"text"}],"role":"symbol","type":"topic","title":"adOpportunityTrackerView(trackerView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adOpportunityTrackerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdOpportunityTrackerView","text":"TeadsAdOpportunityTrackerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"adOpportunityTrackerViewWithTrackerView:"}],"url":"\/documentation\/teadssdk\/teadsadplacementmedianative\/adopportunitytrackerview(trackerview:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMediaNative/didFailToReceiveAd(reason:)":{"title":"didFailToReceiveAd(reason:)","navigatorTitle":[{"text":"didFailToReceiveAdWithReason:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFailToReceiveAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdFailReason","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementmedianative\/didfailtoreceivead(reason:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/didFailToReceiveAd(reason:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/adOpportunityTrackerView(trackerView:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMediaNative\/didFailToReceiveAd(reason:)"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative\/title","value":"TeadsAdPlacementMediaNative"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementMediaNative"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementMediaNative"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative~1adOpportunityTrackerView(trackerView:)\/title","value":"adOpportunityTrackerViewWithTrackerView:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative~1adOpportunityTrackerView(trackerView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adOpportunityTrackerViewWithTrackerView:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative~1didFailToReceiveAd(reason:)\/title","value":"didFailToReceiveAdWithReason:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMediaNative~1didFailToReceiveAd(reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didFailToReceiveAdWithReason:","kind":"identifier"}]}]}]}