{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorUserIdMissing","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorUserIdMissing"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/aderrorcode\/erroruseridmissing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/aderrorcode\/erroruseridmissing"]}],"kind":"symbol","abstract":[{"text":"Placement Identifier is missing","type":"text"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorUserIdMissing"}],"navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorUserIdMissing"}],"role":"symbol","modules":[{"name":"TeadsSDK"}],"title":"AdErrorCode.errorUserIdMissing","roleHeading":"Case","externalID":"c:@M@TeadsSDK@E@AdErrorCode@AdErrorCodeErrorUserIdMissing"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorUserIdMissing":{"navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorUserIdMissing"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorUserIdMissing","url":"\/documentation\/teadssdk\/aderrorcode\/erroruseridmissing","type":"topic","kind":"symbol","abstract":[{"text":"Placement Identifier is missing","type":"text"}],"role":"symbol","title":"AdErrorCode.errorUserIdMissing","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorUserIdMissing","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode":{"navigatorTitle":[{"text":"AdErrorCode","kind":"identifier"}],"url":"\/documentation\/teadssdk\/aderrorcode","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enumeration of Teads’ error codes."}],"role":"symbol","title":"AdErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdErrorCode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"AdErrorCodeErrorUserIdMissing","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"AdErrorCodeErrorUserIdMissing","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AdErrorCodeErrorUserIdMissing"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorUserIdMissing\/title","value":"AdErrorCodeErrorUserIdMissing","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorUserIdMissing\/fragments","value":[{"text":"AdErrorCodeErrorUserIdMissing","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AdErrorCode","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/title"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"AdErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/navigatorTitle","value":[{"text":"AdErrorCode","kind":"identifier"}]}]}]}