{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Initialize with generic placement configuration","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementviewmodel\/init(config:delegate:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","preciseIdentifier":"s:8TeadsSDK0A20AdPlacementViewModelC0D0xmfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Config","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel\/init(config:delegate:)"},"metadata":{"modules":[{"name":"TeadsSDK"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8TeadsSDK0A20AdPlacementViewModelC0D0xmfp","kind":"typeIdentifier","text":"Placement"},{"kind":"text","text":"."},{"preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa","kind":"typeIdentifier","text":"Config"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"externalID":"s:8TeadsSDK0A20AdPlacementViewModelC6config8delegateACyxG6ConfigQz_AA0acD14EventsDelegate_pSgtcfc","title":"init(config:delegate:)"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementViewModel/init(config:delegate:)":{"abstract":[{"text":"Initialize with generic placement configuration","type":"text"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementviewmodel\/init(config:delegate:)","role":"symbol","kind":"symbol","title":"init(config:delegate:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel\/init(config:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A20AdPlacementViewModelC0D0xmfp"},{"text":".","kind":"text"},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"text":"?)","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementProtocol/Config":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"Config"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementprotocol\/config","abstract":[],"type":"topic","title":"Config"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementViewModel":{"url":"\/documentation\/teadssdk\/teadsadplacementviewmodel","navigatorTitle":[{"text":"TeadsAdPlacementViewModel","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementViewModel","kind":"identifier"}],"type":"topic","abstract":[{"text":"View model that manages the state and behavior of Teads ad placements in SwiftUI","type":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementViewModel","title":"TeadsAdPlacementViewModel"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"title":"TeadsAdPlacementEventsDelegate","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title","value":"TeadsAdPlacementEventsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"op":"replace"}]}]}