{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/uikit\/uibutton\/bind(component:)"]}],"metadata":{"externalID":"c:@CM@TeadsSDK@@objc(cs)UIButton(im)bindWithComponent:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonComponent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"},{"text":"?)","kind":"text"}],"title":"bind(component:)","modules":[{"name":"TeadsSDK","relatedModules":["UIKit"]}],"roleHeading":"Instance Method","symbolKind":"method","extendedModule":"UIKit","role":"symbol"},"abstract":[{"type":"text","text":"map your UIKit element to TeadsSDK logic,"},{"type":"text","text":" "},{"type":"text","text":"this ensures visibility measurement is monitored and click behaviors are well handled"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"component","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent","kind":"typeIdentifier","text":"CommonComponent"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Object holding text, image or video depending on his subtype","type":"text"}]}],"name":"component"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/UIKit","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/UIKit\/UIButton"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/UIKit\/UIButton\/bind(component:)","interfaceLanguage":"swift"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/CommonComponent":{"kind":"symbol","url":"\/documentation\/teadssdk\/commoncomponent","role":"symbol","abstract":[{"type":"text","text":"Native Root Component"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommonComponent"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/CommonComponent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonComponent"}],"title":"CommonComponent"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/UIKit/UIButton":{"kind":"symbol","url":"\/documentation\/teadssdk\/uikit\/uibutton","title":"UIButton","abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/UIKit\/UIButton","navigatorTitle":[{"kind":"identifier","text":"UIButton"}],"role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/UIKit":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/UIKit","url":"\/documentation\/teadssdk\/uikit","title":"UIKit","abstract":[],"type":"topic","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/UIKit/UIButton/bind(component:)":{"role":"symbol","kind":"symbol","title":"bind(component:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonComponent","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)CommonComponent"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/UIKit\/UIButton\/bind(component:)","type":"topic","url":"\/documentation\/teadssdk\/uikit\/uibutton\/bind(component:)","abstract":[{"type":"text","text":"map your UIKit element to TeadsSDK logic,"},{"type":"text","text":" "},{"type":"text","text":"this ensures visibility measurement is monitored and click behaviors are well handled"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/title","value":"CommonComponent"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/fragments","value":[{"text":"CommonComponent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1CommonComponent\/navigatorTitle","value":[{"kind":"identifier","text":"CommonComponent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}