{"abstract":[{"text":"The Teads inApp Validation tool is the best way to ensure all basic features and prerequisites are correctly implemented.","type":"text"},{"text":" ","type":"text"},{"text":"It is also useful during integration iterations.","type":"text"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/enableValidationMode()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableValidationMode","kind":"identifier"},{"text":"()","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Each time you upgrade TeadsSDK versions, you should perfom a validation pass to ensure integration is set correctly."}],"type":"paragraph"},{"style":"warning","content":[{"inlineContent":[{"type":"text","text":"Remember to remove this setting when you are going in production."}],"type":"paragraph"}],"type":"aside","name":"Warning"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Follow "},{"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314783-validation-tool","type":"reference","isActive":true}]}],"type":"aside","name":"Note"}]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadrequestsettings\/enablevalidationmode()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadrequestsettings\/enablevalidationmode()"]}],"metadata":{"modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"enableValidationMode"}],"role":"symbol","title":"enableValidationMode()","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings(im)enableValidationMode","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableValidationMode","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"https://support.teads.tv/support/solutions/articles/36000314783-validation-tool":{"titleInlineContent":[{"text":"validate your integration documentation","type":"text"}],"type":"link","title":"validate your integration documentation","url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314783-validation-tool","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314783-validation-tool"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"url":"\/documentation\/teadssdk\/teadsadrequestsettings","type":"topic","title":"TeadsAdRequestSettings","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdRequestSettings","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","navigatorTitle":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"abstract":[{"text":"Specify which settings you want to set for the related ad request.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings/enableValidationMode()":{"kind":"symbol","title":"enableValidationMode()","abstract":[{"text":"The Teads inApp Validation tool is the best way to ensure all basic features and prerequisites are correctly implemented.","type":"text"},{"text":" ","type":"text"},{"text":"It is also useful during integration iterations.","type":"text"}],"url":"\/documentation\/teadssdk\/teadsadrequestsettings\/enablevalidationmode()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableValidationMode","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/enableValidationMode()","role":"symbol","navigatorTitle":[{"text":"enableValidationMode","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"enableValidationMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"enableValidationMode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"enableValidationMode","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title","value":"TeadsAdRequestSettings","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments","value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings~1enableValidationMode()\/title","value":"enableValidationMode","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings~1enableValidationMode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableValidationMode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}