{"abstract":[{"type":"text","text":"Creates a WrapperFrameworkInfo for Flutter integration."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo\/flutter(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/wrapperframeworkinfo\/flutter(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/wrapperframeworkinfo\/flutter(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flutter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flutterVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo","text":"WrapperFrameworkInfo"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The version of the Flutter package","type":"text"}],"type":"paragraph"}],"name":"flutterVersion"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A WrapperFrameworkInfo instance for Flutter","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"method","title":"flutter(_:)","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flutter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"WrapperFrameworkInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo"}],"modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"flutter:"}],"externalID":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo(cm)flutter:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/WrapperFrameworkInfo/flutter(_:)":{"navigatorTitle":[{"kind":"identifier","text":"flutter:"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo\/flutter(_:)","url":"\/documentation\/teadssdk\/wrapperframeworkinfo\/flutter(_:)","type":"topic","abstract":[{"text":"Creates a WrapperFrameworkInfo for Flutter integration.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flutter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo","text":"WrapperFrameworkInfo"}],"title":"flutter(_:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/WrapperFrameworkInfo":{"abstract":[{"text":"Represents wrapper framework integration information for the Teads SDK.","type":"text"}],"url":"\/documentation\/teadssdk\/wrapperframeworkinfo","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrapperFrameworkInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrapperFrameworkInfo","kind":"identifier"}],"kind":"symbol","title":"WrapperFrameworkInfo"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"flutter:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flutter:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","text":"WrapperFrameworkInfo","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"flutter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"flutterVersion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"flutterVersion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The version of the Flutter package"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A WrapperFrameworkInfo instance for Flutter"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo~1flutter(_:)\/title","value":"flutter:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo~1flutter(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flutter:"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/title","value":"WrapperFrameworkInfo","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/fragments","value":[{"text":"WrapperFrameworkInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/navigatorTitle","value":[{"kind":"identifier","text":"WrapperFrameworkInfo"}],"op":"replace"}]}]}