{"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reactNative","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo","text":"WrapperFrameworkInfo","kind":"typeIdentifier"}],"title":"reactNative(_:)","externalID":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo(cm)reactNative:","roleHeading":"Type Method","symbolKind":"method","role":"symbol","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"text":"reactNative:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo\/reactNative(_:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reactNative"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"reactNativeVersion"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"WrapperFrameworkInfo","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"reactNativeVersion","content":[{"inlineContent":[{"text":"The version of the React Native package","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A WrapperFrameworkInfo instance for React Native","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo"]]},"kind":"symbol","abstract":[{"type":"text","text":"Creates a WrapperFrameworkInfo for React Native integration."}],"variants":[{"paths":["\/documentation\/teadssdk\/wrapperframeworkinfo\/reactnative(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/wrapperframeworkinfo\/reactnative(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/WrapperFrameworkInfo":{"abstract":[{"text":"Represents wrapper framework integration information for the Teads SDK.","type":"text"}],"url":"\/documentation\/teadssdk\/wrapperframeworkinfo","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrapperFrameworkInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrapperFrameworkInfo","kind":"identifier"}],"kind":"symbol","title":"WrapperFrameworkInfo"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/WrapperFrameworkInfo/reactNative(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reactNative","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"WrapperFrameworkInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo"}],"kind":"symbol","abstract":[{"text":"Creates a WrapperFrameworkInfo for React Native integration.","type":"text"}],"type":"topic","url":"\/documentation\/teadssdk\/wrapperframeworkinfo\/reactnative(_:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo\/reactNative(_:)","title":"reactNative(_:)","role":"symbol","navigatorTitle":[{"text":"reactNative:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"reactNative:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"reactNative:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"WrapperFrameworkInfo","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo"},{"text":" *) ","kind":"text"},{"text":"reactNative:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reactNativeVersion","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The version of the React Native package","type":"text"}]}],"name":"reactNativeVersion"}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A WrapperFrameworkInfo instance for React Native"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/title","value":"WrapperFrameworkInfo"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/fragments","value":[{"text":"WrapperFrameworkInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/navigatorTitle","value":[{"text":"WrapperFrameworkInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo~1reactNative(_:)\/title","value":"reactNative:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo~1reactNative(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"reactNative:","kind":"identifier"}]}]}]}