{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo"]]},"metadata":{"symbolKind":"property","externalID":"c:@M@TeadsSDK@objc(cs)WrapperFrameworkInfo(py)version","modules":[{"name":"TeadsSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"version","kind":"identifier"}],"title":"version"},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo\/version","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The version of the wrapper framework integration"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/teadssdk\/wrapperframeworkinfo\/version"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/wrapperframeworkinfo\/version"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/WrapperFrameworkInfo":{"abstract":[{"text":"Represents wrapper framework integration information for the Teads SDK.","type":"text"}],"url":"\/documentation\/teadssdk\/wrapperframeworkinfo","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrapperFrameworkInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrapperFrameworkInfo","kind":"identifier"}],"kind":"symbol","title":"WrapperFrameworkInfo"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/WrapperFrameworkInfo/version":{"type":"topic","title":"version","abstract":[{"text":"The version of the wrapper framework integration","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"version"}],"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/WrapperFrameworkInfo\/version","url":"\/documentation\/teadssdk\/wrapperframeworkinfo\/version"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"version","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"version","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"version","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"WrapperFrameworkInfo","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/fragments","value":[{"text":"WrapperFrameworkInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo\/navigatorTitle","value":[{"text":"WrapperFrameworkInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo~1version\/title","value":"version"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1WrapperFrameworkInfo~1version\/fragments","value":[{"kind":"identifier","text":"version"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}