{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/aderrorcode\/errornoslot"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/aderrorcode\/errornoslot"]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNoSlot","interfaceLanguage":"swift"},"abstract":[{"text":"When no slot exists for ad","type":"text"}],"kind":"symbol","metadata":{"roleHeading":"Case","title":"AdErrorCode.errorNoSlot","externalID":"c:@M@TeadsSDK@E@AdErrorCode@AdErrorCodeErrorNoSlot","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNoSlot"}],"modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorNoSlot"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNoSlot","kind":"identifier"}]}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode":{"url":"\/documentation\/teadssdk\/aderrorcode","title":"AdErrorCode","navigatorTitle":[{"kind":"identifier","text":"AdErrorCode"}],"kind":"symbol","abstract":[{"type":"text","text":"Enumeration of Teads’ error codes."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdErrorCode"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorNoSlot":{"title":"AdErrorCode.errorNoSlot","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/aderrorcode\/errornoslot","navigatorTitle":[{"kind":"identifier","text":"AdErrorCodeErrorNoSlot"}],"abstract":[{"type":"text","text":"When no slot exists for ad"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorNoSlot","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNoSlot"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AdErrorCodeErrorNoSlot","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AdErrorCodeErrorNoSlot"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AdErrorCodeErrorNoSlot","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AdErrorCode","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/title"},{"value":[{"kind":"identifier","text":"AdErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/fragments"},{"value":[{"text":"AdErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/navigatorTitle"},{"value":"AdErrorCodeErrorNoSlot","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNoSlot\/title"},{"value":[{"text":"AdErrorCodeErrorNoSlot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorNoSlot\/fragments"}]}]}