{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performTap","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"TeadsSDK"}],"role":"symbol","title":"performTap()","roleHeading":"Instance Method","symbolKind":"method","externalID":"s:8TeadsSDK0A8NativeAdC10performTapyyF"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performTap","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"This will open link on SFSafariViewController or open directly an app depending on the link itself","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/performTap()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"For internal use only.","type":"text"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnativead\/performtap()"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd","type":"topic","navigatorTitle":[{"text":"TeadsNativeAd","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A TeadsNativeAd represents an ad that will be displayed by the native code of the application. This ad is fully customizable"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNativeAd","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsnativead","title":"TeadsNativeAd"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAd/performTap()":{"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAd\/performTap()","type":"topic","title":"performTap()","kind":"symbol","url":"\/documentation\/teadssdk\/teadsnativead\/performtap()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performTap","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"For internal use only.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"TeadsNativeAd","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/title"},{"value":[{"kind":"identifier","text":"TeadsNativeAd"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/fragments"},{"value":[{"kind":"identifier","text":"TeadsNativeAd"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAd\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}