{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adRequestSettings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","text":"TeadsAdRequestSettings","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/adrequestsettings"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/adRequestSettings"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"kind":"symbol","metadata":{"symbolKind":"property","title":"adRequestSettings","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"adRequestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdRequestSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings"}],"role":"symbol","roleHeading":"Instance Property","externalID":"s:8TeadsSDK0A15AdapterSettingsC09adRequestD0AA0a2AdfD0Cvp","modules":[{"name":"TeadsSDK"}]},"abstract":[{"type":"text","text":"Request settings (internal use only)"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"title":"TeadsAdRequestSettings","abstract":[{"text":"Specify which settings you want to set for the related ad request.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdRequestSettings"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","kind":"symbol","url":"\/documentation\/teadssdk\/teadsadrequestsettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/adRequestSettings":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/adRequestSettings","role":"symbol","title":"adRequestSettings","url":"\/documentation\/teadssdk\/teadsadaptersettings\/adrequestsettings","abstract":[{"type":"text","text":"Request settings (internal use only)"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"adRequestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdRequestSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings"}],"kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"abstract":[{"type":"text","text":"Settings used to load Teads’ mediation adapter ads"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadaptersettings","title":"TeadsAdapterSettings","navigatorTitle":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TeadsAdRequestSettings","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title"},{"value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments"},{"value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/navigatorTitle"},{"value":"TeadsAdapterSettings","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title"},{"value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle"}]}]}