{"variants":[{"paths":["\/documentation\/teadssdk\/teadsprebidadplacement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsprebidadplacement"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"\/ Prebid ad placement to load inRead ads from Prebid winning bid"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPrebidAdPlacement","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","text":"TeadsAdPlacement","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacement"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This object is reponsible of loading prebid winning ad response"},{"type":"text","text":" "},{"type":"text","text":"In order to create placement, call "},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createPrebidPlacement(settings:delegate:)"}]},{"name":"Important","content":[{"inlineContent":[{"type":"text","text":"You must own\/retain "},{"type":"codeVoice","code":"TeadsPrebidAdPlacement"},{"type":"text","text":" instance, otherwise ads could not be delivered properly"}],"type":"paragraph"}],"type":"aside","style":"important"}],"kind":"content"}],"metadata":{"title":"TeadsPrebidAdPlacement","navigatorTitle":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(pl)TeadsPrebidAdPlacement","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsPrebidAdPlacement","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","role":"symbol"},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/delegate"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/getData(requestSettings:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/loadAd(adResponse:requestSettings:)"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"],"kind":"relationships"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacement":{"title":"TeadsAdPlacement","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacement"}],"url":"\/documentation\/teadssdk\/teadsadplacement","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacement"}],"abstract":[]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"abstract":[{"type":"text","text":"Delegate methods needed to follow Teads inRead ad requests flow"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"title":"TeadsInReadAdPlacementDelegate","url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement/getData(requestSettings:)":{"abstract":[{"type":"text","text":"get prebid request data"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"url":"\/documentation\/teadssdk\/teadsprebidadplacement\/getdata(requestsettings:)","title":"getData(requestSettings:)","required":true,"kind":"symbol","navigatorTitle":[{"text":"getDataWithRequestSettings:error:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/getData(requestSettings:)","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement/delegate":{"abstract":[{"type":"text","text":"TeadsInReadAdPlacementDelegate to follow ad placement lifecycle"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/teadssdk\/teadsprebidadplacement\/delegate","title":"delegate","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/delegate","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createPrebidPlacement(settings:delegate:)":{"abstract":[{"text":"Create an  inRead ad placement to request load Prebid ad response","type":"text"}],"role":"symbol","type":"topic","title":"createPrebidPlacement(settings:delegate:)","url":"\/documentation\/teadssdk\/teads\/createprebidplacement(settings:delegate:)","navigatorTitle":[{"text":"createPrebidPlacementWithSettings:delegate:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPrebidPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"settings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAdPlacementDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"text":"?) -> ","kind":"text"},{"text":"TeadsPrebidAdPlacement","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsPrebidAdPlacement"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createPrebidPlacement(settings:delegate:)","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"role":"collection","title":"TeadsSDK","url":"\/documentation\/teadssdk","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement/loadAd(adResponse:requestSettings:)":{"title":"loadAd(adResponse:requestSettings:)","kind":"symbol","abstract":[{"text":"Load an InRead ad on this placement by passing adResponse value","type":"text"},{"text":" ","type":"text"},{"text":"listen for events by implementing ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate"}],"type":"topic","navigatorTitle":[{"text":"loadAdWithAdResponse:requestSettings:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsprebidadplacement\/loadad(adresponse:requestsettings:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/loadAd(adResponse:requestSettings:)","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"requestSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsInReadAdRequestSettings","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa"},{"text":") -> ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement":{"navigatorTitle":[{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement","abstract":[{"type":"text","text":"\/ Prebid ad placement to load inRead ads from Prebid winning bid"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsprebidadplacement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"title":"TeadsPrebidAdPlacement","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"TeadsPrebidAdPlacement"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/delegate"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/getData(requestSettings:)","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/loadAd(adResponse:requestSettings:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsPrebidAdPlacement"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacement","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","text":"TeadsAdPlacement"},{"kind":"text","text":">"}]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/title","op":"replace","value":"TeadsAdPlacement"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/fragments","op":"replace","value":[{"text":"TeadsAdPlacement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/navigatorTitle","op":"replace","value":[{"text":"TeadsAdPlacement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","op":"replace","value":"TeadsInReadAdPlacementDelegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","op":"replace","value":[{"text":"TeadsInReadAdPlacementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1getData(requestSettings:)\/title","op":"replace","value":"getDataWithRequestSettings:error:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1getData(requestSettings:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getDataWithRequestSettings:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createPrebidPlacement(settings:delegate:)\/title","op":"replace","value":"createPrebidPlacementWithSettings:delegate:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createPrebidPlacement(settings:delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createPrebidPlacementWithSettings:delegate:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1loadAd(adResponse:requestSettings:)\/title","op":"replace","value":"loadAdWithAdResponse:requestSettings:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1loadAd(adResponse:requestSettings:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAdWithAdResponse:requestSettings:"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/title","op":"replace","value":"TeadsPrebidAdPlacement"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/fragments","op":"replace","value":[{"kind":"identifier","text":"TeadsPrebidAdPlacement"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/navigatorTitle","op":"replace","value":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}]}]}]}