{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teads\/createnativeplacement(pid:settings:delegate:)"]}],"abstract":[{"text":"Create a native ad placement to request native ads","type":"text"}],"metadata":{"modules":[{"name":"TeadsSDK"}],"externalID":"s:8TeadsSDK0A0C21createNativePlacement3pid8settings8delegateAA0ad2AdE0_pSgSi_AA0aiE8SettingsCAA0adiE8Delegate_pSgtFZ","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNativePlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","kind":"typeIdentifier","text":"TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate","kind":"typeIdentifier","text":"TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement","kind":"typeIdentifier","text":"TeadsNativeAdPlacement"},{"kind":"text","text":"?"}],"roleHeading":"Type Method","title":"createNativePlacement(pid:settings:delegate:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createNativePlacement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"settings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementSettings","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","kind":"typeIdentifier"},{"text":" = TeadsAdPlacementSettings(), ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsNativeAdPlacementDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"text":"TeadsNativeAdPlacement","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"pid","content":[{"inlineContent":[{"type":"text","text":"Your Teads placement identifier for "},{"type":"strong","inlineContent":[{"text":"native","type":"text"}]},{"type":"text","text":" ads"}],"type":"paragraph"}]},{"name":"settings","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The placement’s related settings you want to apply"}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"TeadsNativeAdPlacementDelegate to follow ad placement lifecycle","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"TeadsNativeAdPlacement instance, this instance must be owned\/retained"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"aside","style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"You must own\/retain ","type":"text"},{"code":"TeadsNativeAdPlacement","type":"codeVoice"},{"text":" instance, otherwise ads could not be delivered properly: you can free placement instance on       ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate\/didReceiveAd(ad:)","type":"reference"},{"text":" or  ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/didFailToReceiveAd(reason:)","type":"reference"}]}],"name":"Important"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314757-native-ad-classic-integration","isActive":true,"type":"reference"},{"text":" documentation","type":"text"}]}],"name":"Note"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)"],"anchor":"Create-Ad-Placements","title":"Create Ad Placements","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createNativePlacement(pid:settings:delegate:)"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate/didReceiveAd(ad:)":{"abstract":[{"type":"text","text":"Called when the Teads SDK has received an ad for you to display"}],"title":"didReceiveAd(ad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","text":"TeadsNativeAd"},{"kind":"text","text":")"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate\/didReceiveAd(ad:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"didReceiveAdWithAd:"}],"role":"symbol","url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate\/didreceivead(ad:)","type":"topic","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createNativePlacement(pid:settings:delegate:)":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createNativePlacement(pid:settings:delegate:)","role":"symbol","title":"createNativePlacement(pid:settings:delegate:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNativePlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TeadsNativeAdPlacement","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsNativeAdPlacement"},{"kind":"text","text":"?"}],"url":"\/documentation\/teadssdk\/teads\/createnativeplacement(pid:settings:delegate:)","abstract":[{"type":"text","text":"Create a native ad placement to request native ads"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/createInReadPlacement(pid:settings:delegate:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createInReadPlacementWithPid:settings:delegate:"}],"abstract":[{"type":"text","text":"Create an inRead ad placement to request inRead ads"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInReadPlacement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"settings"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementSettings","kind":"typeIdentifier","text":"TeadsAdPlacementSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate","kind":"typeIdentifier","text":"TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacement","kind":"typeIdentifier","text":"TeadsInReadAdPlacement"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/createInReadPlacement(pid:settings:delegate:)","title":"createInReadPlacement(pid:settings:delegate:)","url":"\/documentation\/teadssdk\/teads\/createinreadplacement(pid:settings:delegate:)","role":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Teads","kind":"identifier"}],"navigatorTitle":[{"text":"Teads","kind":"identifier"}],"title":"Teads","url":"\/documentation\/teadssdk\/teads","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Teads"},{"type":"text","text":" class defines the main entry point to start implementing TeadsSDK."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","title":"TeadsSDK","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","url":"\/documentation\/teadssdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacement":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"title":"TeadsNativeAdPlacement","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacement","abstract":[{"text":"Native ad placement to request native ads","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdPlacementDelegate":{"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdPlacementDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"title":"TeadsNativeAdPlacementDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsnativeadplacementdelegate","abstract":[{"type":"text","text":"Delegate methods needed to follow Teads native ad requests flow"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementSettings":{"abstract":[{"type":"text","text":"Specify which settings you want to set for your Teads placement."}],"title":"TeadsAdPlacementSettings","url":"\/documentation\/teadssdk\/teadsadplacementsettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementSettings","navigatorTitle":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementDelegate/didFailToReceiveAd(reason:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didFailToReceiveAdWithReason:"}],"title":"didFailToReceiveAd(reason:)","abstract":[{"type":"text","text":"Called when the Teads SDK has not received an ad, the reason will be detailled in the parameter"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementDelegate\/didFailToReceiveAd(reason:)","url":"\/documentation\/teadssdk\/teadsadplacementdelegate\/didfailtoreceivead(reason:)","type":"topic","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdFailReason","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)AdFailReason"},{"kind":"text","text":")"}]},"https://support.teads.tv/support/solutions/articles/36000314757-native-ad-classic-integration":{"title":"Native implementation guide","identifier":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314757-native-ad-classic-integration","titleInlineContent":[{"type":"text","text":"Native implementation guide"}],"url":"https:\/\/support.teads.tv\/support\/solutions\/articles\/36000314757-native-ad-classic-integration","type":"link"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate~1didReceiveAd(ad:)\/title","value":"didReceiveAdWithAd:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate~1didReceiveAd(ad:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveAdWithAd:"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createInReadPlacement(pid:settings:delegate:)\/title","value":"createInReadPlacementWithPid:settings:delegate:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1createInReadPlacement(pid:settings:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createInReadPlacementWithPid:settings:delegate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/title","value":"Teads","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/fragments","value":[{"text":"Teads","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/navigatorTitle","value":[{"text":"Teads","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/title","value":"TeadsNativeAdPlacement","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/fragments","value":[{"kind":"identifier","text":"TeadsNativeAdPlacement"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacement\/navigatorTitle","value":[{"text":"TeadsNativeAdPlacement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/title","value":"TeadsNativeAdPlacementDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdPlacementDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsNativeAdPlacementDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/title","value":"TeadsAdPlacementSettings","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementSettings\/navigatorTitle","value":[{"text":"TeadsAdPlacementSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1didFailToReceiveAd(reason:)\/title","value":"didFailToReceiveAdWithReason:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementDelegate~1didFailToReceiveAd(reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didFailToReceiveAdWithReason:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}