{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"build"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/BuildTeadsAdRequestSettings","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A17AdRequestSettingsC05BuildacdE0a","text":"BuildTeadsAdRequestSettings"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"build","content":[{"type":"paragraph","inlineContent":[{"text":"Build your ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings"},{"text":" from this closure.","type":"text"}]}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings"]]},"abstract":[{"type":"text","text":"Instance settings builder."}],"metadata":{"title":"init(build:)","roleHeading":"Initializer","modules":[{"name":"TeadsSDK"}],"symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"build","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BuildTeadsAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A17AdRequestSettingsC05BuildacdE0a"},{"kind":"text","text":")"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings(im)initWithBuild:","navigatorTitle":[{"text":"initWithBuild:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadrequestsettings\/init(build:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsadrequestsettings\/init(build:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/init(build:)"},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings/BuildTeadsAdRequestSettings":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/BuildTeadsAdRequestSettings","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Convenience closure typealias for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings"}],"url":"\/documentation\/teadssdk\/teadsadrequestsettings\/buildteadsadrequestsettings","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BuildTeadsAdRequestSettings"}],"title":"TeadsAdRequestSettings.BuildTeadsAdRequestSettings","navigatorTitle":[{"text":"BuildTeadsAdRequestSettings","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","url":"\/documentation\/teadssdk","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings/init(build:)":{"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadrequestsettings\/init(build:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings\/init(build:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBuild:"}],"title":"init(build:)","abstract":[{"type":"text","text":"Instance settings builder."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"build","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BuildTeadsAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A17AdRequestSettingsC05BuildacdE0a","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"kind":"symbol","role":"symbol","abstract":[{"text":"Specify which settings you want to set for the related ad request.","type":"text"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","title":"TeadsAdRequestSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsAdRequestSettings","kind":"identifier"}],"navigatorTitle":[{"text":"TeadsAdRequestSettings","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadrequestsettings"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithBuild:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBuild:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBuild:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings","text":"TeadsAdRequestSettings"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"build","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Build your ","type":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","isActive":true,"type":"reference"},{"text":" from this closure.","type":"text"}],"type":"paragraph"}],"name":"build"}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings~1init(build:)\/title","value":"initWithBuild:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithBuild:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings~1init(build:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title","op":"replace","value":"TeadsAdRequestSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments","value":[{"text":"TeadsAdRequestSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"op":"replace"}]}]}