{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads"]]},"metadata":{"extendedModule":"TeadsSDK","externalID":"c:@CM@TeadsSDK@objc(cs)Teads(cm)configureWith:","modules":[{"name":"TeadsSDK"}],"title":"configure(with:)","symbolKind":"method","roleHeading":"Type Method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"configureWith:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/configure(with:)"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/teadssdk\/teads\/configure(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teads\/configure(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"In order to increase TeadsSDK launch speed and load ads faster, call "},{"type":"codeVoice","code":"Teads\/configure()"},{"type":"text","text":" into "},{"type":"codeVoice","code":"AppDelegate.didFinishLaunchingWithOptions"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"partnerKey","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Teads Crash Monitoring"}]},{"type":"text","text":" is a tool we use to monitor crashes that may occur ONLY IN OUR SDK."},{"type":"text","text":" "},{"type":"text","text":"This tool is really helpful for us and it aims to improve our product  continuously."},{"type":"text","text":" "},{"type":"text","text":"You can disable the  crash monitoring feature by adding "},{"type":"codeVoice","code":"disableCrashMonitoring()"},{"type":"text","text":" in the TeadsAdPlacementSettings."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"TeadsSDK does not disturb any third party crash handler\/reporter such as Crashlytics"}]}],"style":"note","type":"aside","name":"Note"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To ensure the crash handler is ready to catch crashes you need to initialize Teads handler in "},{"type":"codeVoice","code":"AppDelegate"}]}],"style":"warning","type":"aside","name":"Warning"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads":{"navigatorTitle":[{"text":"Teads","kind":"identifier"}],"title":"Teads","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads","kind":"symbol","url":"\/documentation\/teadssdk\/teads","role":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"Teads","type":"codeVoice"},{"text":" class defines the main entry point to start implementing TeadsSDK.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Teads","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/Teads/configure(with:)":{"abstract":[{"type":"text","text":"In order to increase TeadsSDK launch speed and load ads faster, call "},{"type":"codeVoice","code":"Teads\/configure()"},{"type":"text","text":" into "},{"type":"codeVoice","code":"AppDelegate.didFinishLaunchingWithOptions"}],"kind":"symbol","navigatorTitle":[{"text":"configureWith:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/Teads\/configure(with:)","type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teads\/configure(with:)","title":"configure(with:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"configureWith:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureWith:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"configureWith:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"partnerKey"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/title","op":"replace","value":"Teads"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/fragments","op":"replace","value":[{"text":"Teads","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Teads"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1configure(with:)\/title","op":"replace","value":"configureWith:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1Teads~1configure(with:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureWith:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}