{"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/registeradview(_:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/registeradview(_:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"title":"registerAdView(_:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerAdView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsMediatedAdViewDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"registerAdView:delegate:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"TeadsSDK"}],"symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)registerAdView:delegate:"},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/registerAdView(_:delegate:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"abstract":[{"type":"text","text":"Register the ad view in case of mediation adapter."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerAdView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"adView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsMediatedAdViewDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"adView","content":[{"inlineContent":[{"type":"text","text":"Slot view returned by Mediation actor"}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"TeadsMediatedAdViewDelegate to update adView slot size"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to perform ad resizing you need to register AdView with a "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"implementing "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate\/didUpdateRatio(_:adRatio:)","isActive":true},{"type":"text","text":" will allows you to resize the  AdView"}]},{"type":"aside","style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"Error is thrown if the ","type":"text"},{"type":"codeVoice","code":"adView"},{"text":" parameter supplied is not a subclass of Mediation third-party networks like Admob or AppLovin","type":"text"}]}]}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"url":"\/documentation\/teadssdk\/teadsadaptersettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterSettings"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","title":"TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediatedAdViewDelegate":{"role":"symbol","url":"\/documentation\/teadssdk\/teadsmediatedadviewdelegate","abstract":[{"text":"When using mediation adapters on inRead placement you must register your view in order to monitor and perform resize updates","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"title":"TeadsMediatedAdViewDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediatedAdViewDelegate/didUpdateRatio(_:adRatio:)":{"type":"topic","role":"symbol","url":"\/documentation\/teadssdk\/teadsmediatedadviewdelegate\/didupdateratio(_:adratio:)","navigatorTitle":[{"text":"didUpdateRatio:adRatio:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Called when the ad ratio is udpated. (only for mediation)"}],"required":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediatedAdViewDelegate\/didUpdateRatio(_:adRatio:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"didUpdateRatio(_:adRatio:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/registerAdView(_:delegate:)":{"url":"\/documentation\/teadssdk\/teadsadaptersettings\/registeradview(_:delegate:)","abstract":[{"type":"text","text":"Register the ad view in case of mediation adapter."}],"navigatorTitle":[{"text":"registerAdView:delegate:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/registerAdView(_:delegate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerAdView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsMediatedAdViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate"},{"text":")","kind":"text"}],"title":"registerAdView(_:delegate:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"registerAdView:delegate:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerAdView:delegate:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerAdView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"adView"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsMediatedAdViewDelegate","text":"id<TeadsMediatedAdViewDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"adView","content":[{"inlineContent":[{"type":"text","text":"Slot view returned by Mediation actor"}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"TeadsMediatedAdViewDelegate to update adView slot size"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/title","value":"TeadsMediatedAdViewDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsMediatedAdViewDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate\/navigatorTitle","value":[{"text":"TeadsMediatedAdViewDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate~1didUpdateRatio(_:adRatio:)\/title","value":"didUpdateRatio:adRatio:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediatedAdViewDelegate~1didUpdateRatio(_:adRatio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateRatio:adRatio:"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1registerAdView(_:delegate:)\/title","value":"registerAdView:delegate:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1registerAdView(_:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerAdView:delegate:","kind":"identifier"}],"op":"replace"}]}]}