{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUsPrivacy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setUsPrivacyWithConsent:"}],"symbolKind":"method","roleHeading":"Instance Method","title":"setUsPrivacy(consent:)","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)setUsPrivacyWithConsent:","role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUsPrivacy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"consent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"consent","content":[{"inlineContent":[{"type":"text","text":"The CCPA consent string"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"content":[{"inlineContent":[{"type":"text","text":"Consent US Privacy string value should be formated following "},{"identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md#us-privacy-string-format","type":"reference","isActive":true}],"type":"paragraph"}],"name":"Requires","style":"note","type":"aside"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If you use a Content Management Platform, you can skip this step: CMP will store those parameters into ","type":"text"},{"code":"UserDefaults","type":"codeVoice"},{"text":", TeadSDK will automatically retrieve consent value. ","type":"text"},{"identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md","type":"reference","isActive":true},{"text":" IAB documentation.","type":"text"}]}],"name":"Note","style":"note","type":"aside"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setUsPrivacy(consent:)"},"abstract":[{"type":"text","text":"In order to follow the IAB specifications for CCPA, please fill the following parameters with attention."}],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/setusprivacy(consent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/setusprivacy(consent:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"url":"\/documentation\/teadssdk\/teadsadaptersettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdapterSettings"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","title":"TeadsAdapterSettings","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"role":"symbol"},"https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md#us-privacy-string-format":{"title":"IAB specifications","identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md#us-privacy-string-format","titleInlineContent":[{"type":"text","text":"IAB specifications"}],"url":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md#us-privacy-string-format","type":"link"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/setUsPrivacy(consent:)":{"kind":"symbol","abstract":[{"text":"In order to follow the IAB specifications for CCPA, please fill the following parameters with attention.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUsPrivacy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"consent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadaptersettings\/setusprivacy(consent:)","navigatorTitle":[{"text":"setUsPrivacyWithConsent:","kind":"identifier"}],"title":"setUsPrivacy(consent:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/setUsPrivacy(consent:)"},"https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md":{"identifier":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md","title":"CCPA","url":"https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md","type":"link","titleInlineContent":[{"text":"CCPA","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setUsPrivacyWithConsent:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUsPrivacyWithConsent:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setUsPrivacyWithConsent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"consent"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"consent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The CCPA consent string"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"TeadsAdapterSettings","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title"},{"value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments"},{"value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle"},{"value":"setUsPrivacyWithConsent:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setUsPrivacy(consent:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setUsPrivacyWithConsent:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1setUsPrivacy(consent:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}