{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"VAST error"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorVastError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode"]]},"metadata":{"title":"AdErrorCode.errorVastError","externalID":"c:@M@TeadsSDK@E@AdErrorCode@AdErrorCodeErrorVastError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorVastError"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"AdErrorCodeErrorVastError","kind":"identifier"}],"modules":[{"name":"TeadsSDK"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorVastError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"https:\/\/wiki.iabtechlab.com\/index.php?title=VAST_Error_Code_Troubleshooting_Matrix","isActive":true}],"type":"paragraph"}],"name":"Note"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/teadssdk\/aderrorcode\/errorvasterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/aderrorcode\/errorvasterror"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode":{"url":"\/documentation\/teadssdk\/aderrorcode","kind":"symbol","title":"AdErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"AdErrorCode","kind":"identifier"}],"abstract":[{"type":"text","text":"Enumeration of Teads’ error codes."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode","role":"symbol","type":"topic"},"https://wiki.iabtechlab.com/index.php?title=VAST_Error_Code_Troubleshooting_Matrix":{"identifier":"https:\/\/wiki.iabtechlab.com\/index.php?title=VAST_Error_Code_Troubleshooting_Matrix","url":"https:\/\/wiki.iabtechlab.com\/index.php?title=VAST_Error_Code_Troubleshooting_Matrix","titleInlineContent":[{"text":"IAB Error code matrix","type":"text"}],"title":"IAB Error code matrix","type":"link"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/AdErrorCode/errorVastError":{"abstract":[{"text":"VAST error","type":"text"}],"url":"\/documentation\/teadssdk\/aderrorcode\/errorvasterror","title":"AdErrorCode.errorVastError","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorVastError","kind":"identifier"}],"navigatorTitle":[{"text":"AdErrorCodeErrorVastError","kind":"identifier"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/AdErrorCode\/errorVastError"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AdErrorCodeErrorVastError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AdErrorCodeErrorVastError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AdErrorCodeErrorVastError"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/title","value":"AdErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/fragments","value":[{"kind":"identifier","text":"AdErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"AdErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorVastError\/title","value":"AdErrorCodeErrorVastError"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1AdErrorCode~1errorVastError\/fragments","value":[{"kind":"identifier","text":"AdErrorCodeErrorVastError"}]}]}]}