{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:delegate:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"]]},"sections":[],"metadata":{"role":"symbol","title":"init(pid:articleUrl:delegate:)","modules":[{"name":"TeadsSDK"}],"symbolKind":"init","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementMedia(im)initWithPid:articleUrl:delegate:","navigatorTitle":[{"text":"initWithPid:articleUrl:delegate:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"articleUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementEventsDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"kind":"text","text":"?)"}]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/init(pid:articleurl:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/init(pid:articleurl:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"articleUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsAdPlacementEventsDelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"kind":"symbol","title":"TeadsAdPlacementMedia","url":"\/documentation\/teadssdk\/teadsadplacementmedia","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"title":"TeadsAdPlacementEventsDelegate","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/init(pid:articleUrl:delegate:)":{"title":"init(pid:articleUrl:delegate:)","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/init(pid:articleUrl:delegate:)","url":"\/documentation\/teadssdk\/teadsadplacementmedia\/init(pid:articleurl:delegate:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"articleUrl"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithPid:articleUrl:delegate:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithPid:articleUrl:delegate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPid:articleUrl:delegate:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pid"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"articleUrl"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","text":"id<TeadsAdPlacementEventsDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"TeadsAdPlacementMedia","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle"},{"op":"replace","value":"TeadsAdPlacementEventsDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle"},{"op":"replace","value":"initWithPid:articleUrl:delegate:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1init(pid:articleUrl:delegate:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPid:articleUrl:delegate:"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia~1init(pid:articleUrl:delegate:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}