{"metadata":{"role":"collectionGroup","title":"TeadsUIViewPlacement Implementations","modules":[{"name":"TeadsSDK"}],"roleHeading":"API Collection"},"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacementmedia\/teadsuiviewplacement-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/uiViewResult"]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/TeadsUIViewPlacement-Implementations"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia/uiViewResult":{"abstract":[{"type":"text","text":"Default implementation that delegates to loadAd()"},{"type":"text","text":" "},{"type":"text","text":"This maintains consistency with the existing TeadsAdPlacementProtocol pattern"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"PlacementResult"},{"type":"text","text":" is "},{"type":"codeVoice","code":"Self.ViewType"},{"type":"text","text":"."}]},"url":"\/documentation\/teadssdk\/teadsadplacementmedia\/uiviewresult","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia\/uiViewResult","title":"uiViewResult","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uiViewResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ViewType","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A15UIViewPlacementP8ViewTypeQa"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementMedia":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementMedia","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementMedia"}],"kind":"symbol","title":"TeadsAdPlacementMedia","url":"\/documentation\/teadssdk\/teadsadplacementmedia","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementMedia"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/title","value":"TeadsAdPlacementMedia","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/fragments","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementMedia\/navigatorTitle","value":[{"text":"TeadsAdPlacementMedia","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}