{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa","text":"TeadsInReadAdRequestSettings"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"adResponse","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Prebid winning bid ad response string representation (stringified JSON)"}]}]},{"name":"requestSettings","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"settings "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdRequestSettings"},{"type":"text","text":" to tweak your needs"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"a unique load identifier, this identifier will be the same value of "},{"type":"codeVoice","code":"TeadsInReadAd.requestIdentifier"},{"type":"text","text":" property"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/delegate"},{"type":"text","text":" property must be set to perform ad request, otherwise didReceiveAd will not be triggered"}]}],"type":"aside","name":"Requires"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsprebidadplacement\/loadad(adresponse:requestsettings:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsprebidadplacement\/loadad(adresponse:requestsettings:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/loadAd(adResponse:requestSettings:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Load an InRead ad on this placement by passing adResponse value"},{"type":"text","text":" "},{"type":"text","text":"listen for events by implementing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"loadAdWithAdResponse:requestSettings:"}],"role":"symbol","title":"loadAd(adResponse:requestSettings:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"symbolKind":"method","externalID":"c:@M@TeadsSDK@objc(pl)TeadsPrebidAdPlacement(im)loadAdWithAdResponse:requestSettings:","required":true,"modules":[{"name":"TeadsSDK"}]},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"role":"collection","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","kind":"symbol","type":"topic","url":"\/documentation\/teadssdk"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRequestSettings":{"role":"symbol","title":"TeadsAdRequestSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdRequestSettings"}],"abstract":[{"type":"text","text":"Specify which settings you want to set for the related ad request."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsAdRequestSettings"}],"url":"\/documentation\/teadssdk\/teadsadrequestsettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacementDelegate":{"role":"symbol","title":"TeadsInReadAdPlacementDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"abstract":[{"type":"text","text":"Delegate methods needed to follow Teads inRead ad requests flow"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}],"url":"\/documentation\/teadssdk\/teadsinreadadplacementdelegate"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdRequestSettings":{"role":"symbol","title":"TeadsInReadAdRequestSettings","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadAdRequestSettings"}],"abstract":[{"type":"text","text":"Convenience closure typealias for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdRequestSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadAdRequestSettings"}],"url":"\/documentation\/teadssdk\/teadsinreadadrequestsettings"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement/loadAd(adResponse:requestSettings:)":{"navigatorTitle":[{"kind":"identifier","text":"loadAdWithAdResponse:requestSettings:"}],"role":"symbol","title":"loadAd(adResponse:requestSettings:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"abstract":[{"type":"text","text":"Load an InRead ad on this placement by passing adResponse value"},{"type":"text","text":" "},{"type":"text","text":"listen for events by implementing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/loadAd(adResponse:requestSettings:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/teadssdk\/teadsprebidadplacement\/loadad(adresponse:requestsettings:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement":{"role":"symbol","title":"TeadsPrebidAdPlacement","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"abstract":[{"type":"text","text":"\/ Prebid ad placement to load inRead ads from Prebid winning bid"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"url":"\/documentation\/teadssdk\/teadsprebidadplacement"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadAdPlacement/requestAd(requestSettings:)":{"navigatorTitle":[{"kind":"identifier","text":"requestAdWithRequestSettings:"}],"role":"symbol","title":"requestAd(requestSettings:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdRequestSettings","preciseIdentifier":"s:8TeadsSDK0A23InReadAdRequestSettingsa"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"abstract":[{"type":"text","text":"Request an InRead ad on this placement"},{"type":"text","text":" "},{"type":"text","text":"listen for events by implementing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacementDelegate"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadAdPlacement\/requestAd(requestSettings:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/teadssdk\/teadsinreadadplacement\/requestad(requestsettings:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TeadsInReadAdPlacementDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsInReadAdPlacementDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"TeadsInReadAdPlacementDelegate to follow ad placement lifecycle"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement\/delegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/teadssdk\/teadsprebidadplacement\/delegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"loadAdWithAdResponse:requestSettings:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAdWithAdResponse:requestSettings:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSUUID","preciseIdentifier":"c:objc(cs)NSUUID"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"loadAdWithAdResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"adResponse"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRequestSettings","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRequestSettings","text":"TeadsAdRequestSettings"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requestSettings"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/title","value":"TeadsAdRequestSettings"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRequestSettings\/fragments","value":[{"kind":"identifier","text":"TeadsAdRequestSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/title","value":"TeadsInReadAdPlacementDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacementDelegate\/fragments","value":[{"kind":"identifier","text":"TeadsInReadAdPlacementDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1loadAd(adResponse:requestSettings:)\/title","value":"loadAdWithAdResponse:requestSettings:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1loadAd(adResponse:requestSettings:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAdWithAdResponse:requestSettings:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/title","value":"TeadsPrebidAdPlacement"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/fragments","value":[{"kind":"identifier","text":"TeadsPrebidAdPlacement"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1requestAd(requestSettings:)\/title","value":"requestAdWithRequestSettings:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsInReadAdPlacement~1requestAd(requestSettings:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAdWithRequestSettings:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}