{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadFluentProtocol\/didUpdateRatio(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"((","kind":"text"},{"text":"TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"symbolKind":"method","externalID":"s:8TeadsSDK0A20InReadFluentProtocolP14didUpdateRatioyxyAA0a2AdI0CcF","required":true,"roleHeading":"Instance Method","title":"didUpdateRatio(_:)","modules":[{"name":"TeadsSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Called when the Teads SDK needs you to resize your view the creative inform us of its new ratio","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsinreadfluentprotocol\/didupdateratio(_:)"]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadFluentProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateRatio","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"closure","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","text":"TeadsAdRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Declare a state variable","type":"text"}],"type":"paragraph"},{"code":["@State private var slotHeight: CGFloat = 0.0"],"syntax":null,"type":"codeListing"},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"slotHeight"},{"type":"text","text":" must be applied to the overall View"}],"type":"paragraph"},{"code":["TeadsInRead.AdView(placement: $inReadAdPlacement) {","\/\/...","}",".frame(height: slotHeight)"],"syntax":null,"type":"codeListing"},{"inlineContent":[{"text":"When it called it is the right place to update your view ratio. A basic implementation may look litke this:","type":"text"}],"type":"paragraph"},{"code":["didUpdateRatio { _, adRatio in","    slotHeight = adRatio.calculateHeight(for: rect.size.width)","}"],"syntax":null,"type":"codeListing"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadFluentProtocol/didUpdateRatio(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateRatio"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"TeadsAdRatio","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsAdRatio"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"url":"\/documentation\/teadssdk\/teadsinreadfluentprotocol\/didupdateratio(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadFluentProtocol\/didUpdateRatio(_:)","abstract":[{"text":"Called when the Teads SDK needs you to resize your view the creative inform us of its new ratio","type":"text"}],"required":true,"title":"didUpdateRatio(_:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsInReadFluentProtocol":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsInReadFluentProtocol"}],"url":"\/documentation\/teadssdk\/teadsinreadfluentprotocol","type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsInReadFluentProtocol","navigatorTitle":[{"kind":"identifier","text":"TeadsInReadFluentProtocol"}],"abstract":[],"title":"TeadsInReadFluentProtocol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdRatio":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdRatio"}],"url":"\/documentation\/teadssdk\/teadsadratio","type":"topic","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdRatio","navigatorTitle":[{"kind":"identifier","text":"TeadsAdRatio"}],"abstract":[{"text":"This class is used to help in resizing a given ad view to a given aspect ratio.","type":"text"}],"title":"TeadsAdRatio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/title","value":"TeadsAdRatio"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/fragments","value":[{"text":"TeadsAdRatio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdRatio\/navigatorTitle","value":[{"text":"TeadsAdRatio","kind":"identifier"}]}]}]}