{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/oberror\/message"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/oberror\/message"]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError\/message","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@TeadsSDK@objc(cs)OBError(py)message","title":"message","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"TeadsSDK"}],"navigatorTitle":[{"kind":"identifier","text":"message"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBError":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBError"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBError"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError","title":"OBError","abstract":[],"url":"\/documentation\/teadssdk\/oberror"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBError/message":{"role":"symbol","abstract":[],"kind":"symbol","title":"message","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError\/message","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/teadssdk\/oberror\/message","navigatorTitle":[{"kind":"identifier","text":"message"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"message"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"message","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"message","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/title","value":"OBError"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/fragments","value":[{"kind":"identifier","text":"OBError"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/navigatorTitle","value":[{"text":"OBError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError~1message\/title","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError~1message\/fragments","value":[{"text":"message","kind":"identifier"}]}]}]}