{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/oberror\/zerorecommendations(message:code:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/oberror\/zerorecommendations(message:code:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError\/zeroRecommendations(message:code:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"title":"zeroRecommendations(message:code:)","modules":[{"name":"TeadsSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@TeadsSDK@objc(cs)OBError(cm)zeroRecommendationsWithMessage:code:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zeroRecommendations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"code","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorCode","text":"OBErrorCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBError","text":"OBError"}],"navigatorTitle":[{"text":"zeroRecommendationsWithMessage:code:","kind":"identifier"}],"roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zeroRecommendations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode","preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorCode","kind":"typeIdentifier","text":"OBErrorCode"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBError","kind":"typeIdentifier","text":"OBError"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"type":"topic","url":"\/documentation\/teadssdk","title":"TeadsSDK","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","role":"collection","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBError":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBError"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OBError"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError","title":"OBError","abstract":[],"url":"\/documentation\/teadssdk\/oberror"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBErrorCode":{"url":"\/documentation\/teadssdk\/oberrorcode","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode","abstract":[],"title":"OBErrorCode","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"OBErrorCode","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/OBError/zeroRecommendations(message:code:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zeroRecommendations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OBErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorCode"},{"text":") -> ","kind":"text"},{"text":"OBError","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBError"}],"role":"symbol","abstract":[],"type":"topic","title":"zeroRecommendations(message:code:)","url":"\/documentation\/teadssdk\/oberror\/zerorecommendations(message:code:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"zeroRecommendationsWithMessage:code:"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError\/zeroRecommendations(message:code:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"zeroRecommendationsWithMessage:code:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"zeroRecommendationsWithMessage:code:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@objc(cs)OBError","text":"OBError","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBError"},{"text":" *) ","kind":"text"},{"text":"zeroRecommendationsWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"code:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@TeadsSDK@E@OBErrorCode","text":"OBErrorCode","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/OBErrorCode"},{"text":") ","kind":"text"},{"text":"code","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OBError","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/title"},{"value":[{"kind":"identifier","text":"OBError"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/fragments"},{"value":[{"text":"OBError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError\/navigatorTitle"},{"value":"OBErrorCode","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/title"},{"value":[{"text":"OBErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"OBErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBErrorCode\/navigatorTitle"},{"value":"zeroRecommendationsWithMessage:code:","op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError~1zeroRecommendations(message:code:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"zeroRecommendationsWithMessage:code:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1OBError~1zeroRecommendations(message:code:)\/fragments"}]}]}