{"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"contentAspectRatio","navigatorTitle":[{"kind":"identifier","text":"contentAspectRatio"}],"externalID":"c:@M@TeadsSDK@objc(cs)VideoComponent(py)contentAspectRatio","symbolKind":"property","modules":[{"name":"TeadsSDK"}],"roleHeading":"Instance Property","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/videocomponent\/contentaspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/videocomponent\/contentaspectratio"]}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent\/contentAspectRatio","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Media content aspect ratio (width\/height)."}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/VideoComponent/contentAspectRatio":{"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent\/contentAspectRatio","url":"\/documentation\/teadssdk\/videocomponent\/contentaspectratio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"contentAspectRatio","abstract":[{"text":"Media content aspect ratio (width\/height).","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"contentAspectRatio","kind":"identifier"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"url":"\/documentation\/teadssdk","role":"collection","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/VideoComponent":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoComponent"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoComponent"}],"title":"VideoComponent","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/VideoComponent","role":"symbol","abstract":[{"text":"Native video component containing media content","type":"text"}],"url":"\/documentation\/teadssdk\/videocomponent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"contentAspectRatio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"contentAspectRatio","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":" ","kind":"text"},{"text":"contentAspectRatio","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent~1contentAspectRatio\/title","op":"replace","value":"contentAspectRatio"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent~1contentAspectRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"contentAspectRatio"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/title","op":"replace","value":"VideoComponent"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/fragments","op":"replace","value":[{"text":"VideoComponent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1VideoComponent\/navigatorTitle","op":"replace","value":[{"text":"VideoComponent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}