{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"To improve performances and user experience, media such as videos or images are preloaded.","type":"text"},{"text":" ","type":"text"},{"text":"This setting prevents TeadsSDK from automatically preloading media.","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableMediaPreload","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","title":"disableMediaPreload()","platforms":[{"unavailable":false,"deprecated":true,"message":"This is not used anymore and will be removed in a future version of the SDK","beta":false}],"symbolKind":"method","navigatorTitle":[{"text":"disableMediaPreload","kind":"identifier"}],"role":"symbol","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdapterSettings(im)disableMediaPreload"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableMediaPreload"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"deprecationSummary":[{"inlineContent":[{"text":"This is not used anymore and will be removed in a future version of the SDK","type":"text"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings"]]},"variants":[{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/disablemediapreload()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadaptersettings\/disablemediapreload()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableMediaPreload()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings":{"navigatorTitle":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsAdapterSettings","kind":"identifier"}],"title":"TeadsAdapterSettings","kind":"symbol","abstract":[{"text":"Settings used to load Teads’ mediation adapter ads","type":"text"}],"type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings","role":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdapterSettings/disableMediaPreload()":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"To improve performances and user experience, media such as videos or images are preloaded."},{"type":"text","text":" "},{"type":"text","text":"This setting prevents TeadsSDK from automatically preloading media."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdapterSettings\/disableMediaPreload()","navigatorTitle":[{"kind":"identifier","text":"disableMediaPreload"}],"deprecated":true,"title":"disableMediaPreload()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableMediaPreload"},{"kind":"text","text":"()"}],"url":"\/documentation\/teadssdk\/teadsadaptersettings\/disablemediapreload()","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":true,"unavailable":false,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"disableMediaPreload","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disableMediaPreload","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"disableMediaPreload"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"This is not used anymore and will be removed in a future version of the SDK","type":"text"}]}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/title","value":"TeadsAdapterSettings","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/fragments","value":[{"text":"TeadsAdapterSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdapterSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableMediaPreload()\/title","value":"disableMediaPreload","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdapterSettings~1disableMediaPreload()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableMediaPreload"}],"op":"replace"}]}]}