{"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/mediaViewTag","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder"]]},"abstract":[{"type":"text","text":"A non-zero tag for media content view to be rendered."}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaViewTag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","roleHeading":"Instance Property","title":"mediaViewTag","symbolKind":"property","modules":[{"name":"TeadsSDK"}],"externalID":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder(py)mediaViewTag","navigatorTitle":[{"text":"mediaViewTag","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/teadssdk\/tagbinderbuilder\/mediaviewtag"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/tagbinderbuilder\/mediaviewtag"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaViewTag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"UIView element must be a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","type":"reference"}]}],"kind":"content"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:tagBinder:)":{"abstract":[{"text":"Binds the native asset ad views to this native ad using view tags binder","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsNativeAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tagBinder","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"TagBinderBuilder","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","title":"bind(_:tagBinder:)","kind":"symbol","url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)","type":"topic","navigatorTitle":[{"text":"bind:tagBinder:","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder":{"abstract":[{"type":"text","text":"This builder allows you to bind UI elements programmatically using "},{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","type":"reference","isActive":true}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TagBinderBuilder","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","title":"TagBinderBuilder","url":"\/documentation\/teadssdk\/tagbinderbuilder","navigatorTitle":[{"text":"TagBinderBuilder","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/mediaViewTag":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/mediaViewTag","abstract":[{"text":"A non-zero tag for media content view to be rendered.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/tagbinderbuilder\/mediaviewtag","navigatorTitle":[{"kind":"identifier","text":"mediaViewTag"}],"title":"mediaViewTag","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaViewTag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsMediaView":{"navigatorTitle":[{"kind":"identifier","text":"TeadsMediaView"}],"title":"TeadsMediaView","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsMediaView","url":"\/documentation\/teadssdk\/teadsmediaview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsMediaView"}],"abstract":[{"type":"text","text":"The TeadsMediaView can load either images, videos and VPAID content."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mediaViewTag"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mediaViewTag"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"mediaViewTag","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/title","value":"bind:tagBinder:"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bind:tagBinder:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/title","value":"TagBinderBuilder"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/fragments","value":[{"text":"TagBinderBuilder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/navigatorTitle","value":[{"text":"TagBinderBuilder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1mediaViewTag\/title","value":"mediaViewTag"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1mediaViewTag\/fragments","value":[{"kind":"identifier","text":"mediaViewTag"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/title","value":"TeadsMediaView"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/fragments","value":[{"kind":"identifier","text":"TeadsMediaView"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsMediaView\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsMediaView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}