{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Your Teads placement identifier for "},{"inlineContent":[{"type":"text","text":"inRead"}],"type":"strong"},{"type":"text","text":" or "},{"inlineContent":[{"type":"text","text":"native"}],"type":"strong"},{"type":"text","text":" ads"}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement\/pid","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"text":"No use for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement"}],"type":"paragraph"}]}],"kind":"content"}],"metadata":{"modules":[{"name":"TeadsSDK"}],"title":"pid","role":"symbol","externalID":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacement(py)pid","required":true,"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pid"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"pid","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsadplacement\/pid"]},{"paths":["\/documentation\/teadssdk\/teadsadplacement\/pid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement"]]},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrebidAdPlacement":{"kind":"symbol","url":"\/documentation\/teadssdk\/teadsprebidadplacement","type":"topic","abstract":[{"text":"\/ Prebid ad placement to load inRead ads from Prebid winning bid","type":"text"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrebidAdPlacement","navigatorTitle":[{"kind":"identifier","text":"TeadsPrebidAdPlacement"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TeadsPrebidAdPlacement","kind":"identifier"}],"title":"TeadsPrebidAdPlacement"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacement/pid":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pid","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"required":true,"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacement\/pid","abstract":[{"text":"Your Teads placement identifier for ","type":"text"},{"inlineContent":[{"type":"text","text":"inRead"}],"type":"strong"},{"type":"text","text":" or "},{"inlineContent":[{"text":"native","type":"text"}],"type":"strong"},{"type":"text","text":" ads"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement\/pid","role":"symbol","title":"pid","navigatorTitle":[{"kind":"identifier","text":"pid"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","title":"TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","abstract":[{"type":"text","text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server."}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacement":{"role":"symbol","title":"TeadsAdPlacement","url":"\/documentation\/teadssdk\/teadsadplacement","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TeadsAdPlacement"}],"navigatorTitle":[{"text":"TeadsAdPlacement","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacement","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"pid","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"pid","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"pid"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/title","value":"TeadsPrebidAdPlacement"},{"value":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/fragments","op":"replace"},{"value":[{"text":"TeadsPrebidAdPlacement","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrebidAdPlacement\/navigatorTitle","op":"replace"},{"value":"pid","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement~1pid\/title","op":"replace"},{"value":[{"text":"pid","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement~1pid\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/title","value":"TeadsAdPlacement"},{"op":"replace","value":[{"text":"TeadsAdPlacement","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacement\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}