{"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","extendedModule":"SwiftUICore","title":"teadsAdPlacement(config:delegate:)","externalID":"s:7SwiftUI4ViewP8TeadsSDKE16teadsAdPlacement6config8delegateQr6ConfigQyd___AD0dgH14EventsDelegate_pSgtAD0d6UIViewH0Rd__lF::SYNTHESIZED::s:8TeadsSDK0A6NativeV6AdViewV","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"teadsAdPlacement"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Placement"},{"kind":"text","text":">("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Placement","preciseIdentifier":"s:7SwiftUI4ViewP8TeadsSDKE16teadsAdPlacement6config8delegateQr6ConfigQyd___AD0dgH14EventsDelegate_pSgtAD0d6UIViewH0Rd__lFQO0H0qd__mfp"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Config","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","text":"TeadsAdPlacementEventsDelegate"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"modules":[{"name":"TeadsSDK","relatedModules":["SwiftUICore"]}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"teadsAdPlacement","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Placement","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP8TeadsSDKE16teadsAdPlacement6config8delegateQr6ConfigQyd___AD0dgH14EventsDelegate_pSgtAD0d6UIViewH0Rd__lFQO0H0qd__mfp"},{"text":".","kind":"text"},{"text":"Config","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"text":"? = nil) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placement","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"TeadsUIViewPlacement","kind":"typeIdentifier","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement","preciseIdentifier":"s:8TeadsSDK0A15UIViewPlacementP"},{"text":"\n","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView"]]},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsnative\/adview\/teadsadplacement(config:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/teadsAdPlacement(config:delegate:)","interfaceLanguage":"swift"},"abstract":[{"text":"Add a Teads Ad Placement to the view using generic configuration","type":"text"}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsUIViewPlacement":{"type":"topic","title":"TeadsUIViewPlacement","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsUIViewPlacement","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsUIViewPlacement","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsuiviewplacement","abstract":[{"type":"text","text":"Protocol for ad placements that return UIView-based content from loadAd()"}],"navigatorTitle":[{"text":"TeadsUIViewPlacement","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView":{"abstract":[{"type":"text","text":"The AdView is responsible to manage manage a Teads native ad."}],"kind":"symbol","type":"topic","url":"\/documentation\/teadssdk\/teadsnative\/adview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdView"}],"navigatorTitle":[{"kind":"identifier","text":"AdView"}],"title":"TeadsNative.AdView","role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementProtocol/Config":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementProtocol\/Config","title":"Config","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/teadssdk\/teadsadplacementprotocol\/config","fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"Config"}],"role":"symbol","required":true},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"title":"TeadsNative","url":"\/documentation\/teadssdk\/teadsnative","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementEventsDelegate":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementEventsDelegate","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"abstract":[],"kind":"symbol","title":"TeadsAdPlacementEventsDelegate","role":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementeventsdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/AdView/teadsAdPlacement(config:delegate:)":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/AdView\/teadsAdPlacement(config:delegate:)","title":"teadsAdPlacement(config:delegate:)","abstract":[{"type":"text","text":"Add a Teads Ad Placement to the view using generic configuration"}],"url":"\/documentation\/teadssdk\/teadsnative\/adview\/teadsadplacement(config:delegate:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"teadsAdPlacement","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Placement","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placement","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP8TeadsSDKE16teadsAdPlacement6config8delegateQr6ConfigQyd___AD0dgH14EventsDelegate_pSgtAD0d6UIViewH0Rd__lFQO0H0qd__mfp"},{"text":".","kind":"text"},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A19AdPlacementProtocolP6ConfigQa"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TeadsAdPlacementEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@objc(pl)TeadsAdPlacementEventsDelegate"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TeadsAdPlacementEventsDelegate","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TeadsAdPlacementEventsDelegate"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/fragments"},{"op":"replace","value":[{"text":"TeadsAdPlacementEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementEventsDelegate\/navigatorTitle"}]}]}