{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconImageViewTag","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"UIView element must be a "},{"code":"UIImageView","type":"codeVoice"}]}],"kind":"content"}],"metadata":{"modules":[{"name":"TeadsSDK"}],"title":"iconImageViewTag","navigatorTitle":[{"text":"iconImageViewTag","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconImageViewTag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"symbolKind":"property","externalID":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder(py)iconImageViewTag","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/iconImageViewTag"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"A non-zero tag for icon image view to be rendered."}],"variants":[{"paths":["\/documentation\/teadssdk\/tagbinderbuilder\/iconimageviewtag"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/tagbinderbuilder\/iconimageviewtag"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection","url":"\/documentation\/teadssdk","kind":"symbol","type":"topic","title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder":{"abstract":[{"type":"text","text":"This builder allows you to bind UI elements programmatically using "},{"type":"reference","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","isActive":true}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TagBinderBuilder","kind":"identifier"}],"navigatorTitle":[{"text":"TagBinderBuilder","kind":"identifier"}],"type":"topic","title":"TagBinderBuilder","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder","url":"\/documentation\/teadssdk\/tagbinderbuilder","kind":"symbol"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNativeAdView/bind(_:tagBinder:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TeadsNativeAd","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TeadsNativeAd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tagBinder","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"TagBinderBuilder","preciseIdentifier":"c:@M@TeadsSDK@objc(cs)TagBinderBuilder","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNativeAdView\/bind(_:tagBinder:)","navigatorTitle":[{"kind":"identifier","text":"bind:tagBinder:"}],"url":"\/documentation\/teadssdk\/teadsnativeadview\/bind(_:tagbinder:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Binds the native asset ad views to this native ad using view tags binder"}],"title":"bind(_:tagBinder:)","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TagBinderBuilder/iconImageViewTag":{"type":"topic","url":"\/documentation\/teadssdk\/tagbinderbuilder\/iconimageviewtag","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconImageViewTag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"iconImageViewTag"}],"title":"iconImageViewTag","kind":"symbol","abstract":[{"type":"text","text":"A non-zero tag for icon image view to be rendered."}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TagBinderBuilder\/iconImageViewTag","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"iconImageViewTag","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"iconImageViewTag","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"iconImageViewTag","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/title","op":"replace","value":"TagBinderBuilder"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/fragments","op":"replace","value":[{"text":"TagBinderBuilder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TagBinderBuilder"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/title","op":"replace","value":"bind:tagBinder:"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsNativeAdView~1bind(_:tagBinder:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bind:tagBinder:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1iconImageViewTag\/title","op":"replace","value":"iconImageViewTag"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TagBinderBuilder~1iconImageViewTag\/fragments","op":"replace","value":[{"text":"iconImageViewTag","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}