{"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementFeed"]]},"sections":[],"variants":[{"paths":["\/documentation\/teadssdk\/teadsadplacementfeed\/showexploremore(onexploremoredismissed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/teadssdk\/teadsadplacementfeed\/showexploremore(onexploremoredismissed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showExploreMore"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onExploreMoreDismissed"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"title":"showExploreMore(onExploreMoreDismissed:)","externalID":"c:@M@TeadsSDK@objc(cs)TeadsAdPlacementFeed(im)showExploreMoreOnExploreMoreDismissed:","symbolKind":"method","navigatorTitle":[{"text":"showExploreMoreOnExploreMoreDismissed:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showExploreMore"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onExploreMoreDismissed"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"TeadsSDK"}]},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementFeed\/showExploreMore(onExploreMoreDismissed:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementFeed":{"kind":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementFeed","title":"TeadsAdPlacementFeed","navigatorTitle":[{"kind":"identifier","text":"TeadsAdPlacementFeed"}],"url":"\/documentation\/teadssdk\/teadsadplacementfeed","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsAdPlacementFeed"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsAdPlacementFeed/showExploreMore(onExploreMoreDismissed:)":{"navigatorTitle":[{"kind":"identifier","text":"showExploreMoreOnExploreMoreDismissed:"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsadplacementfeed\/showexploremore(onexploremoredismissed:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showExploreMore","kind":"identifier"},{"text":"(","kind":"text"},{"text":"onExploreMoreDismissed","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","type":"topic","title":"showExploreMore(onExploreMoreDismissed:)","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsAdPlacementFeed\/showExploreMore(onExploreMoreDismissed:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"showExploreMoreOnExploreMoreDismissed:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showExploreMoreOnExploreMoreDismissed:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"showExploreMoreOnExploreMoreDismissed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)()) "},{"kind":"internalParam","text":"onExploreMoreDismissed"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementFeed\/title","value":"TeadsAdPlacementFeed","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementFeed\/fragments","value":[{"kind":"identifier","text":"TeadsAdPlacementFeed"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementFeed\/navigatorTitle","value":[{"kind":"identifier","text":"TeadsAdPlacementFeed"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementFeed~1showExploreMore(onExploreMoreDismissed:)\/title","value":"showExploreMoreOnExploreMoreDismissed:","op":"replace"},{"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsAdPlacementFeed~1showExploreMore(onExploreMoreDismissed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showExploreMoreOnExploreMoreDismissed:"}],"op":"replace"}]}]}