{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsprivacy\/setusprivacystring(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/teadssdk\/teadsprivacy\/setusprivacystring(_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUSPrivacyString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"privacyString","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"privacyString","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CCPA privacy string"}]}]}],"kind":"parameters"}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"setUSPrivacyString:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUSPrivacyString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"setUSPrivacyString(_:)","modules":[{"name":"TeadsSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@TeadsSDK@objc(cs)TeadsPrivacy(im)setUSPrivacyString:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy"]]},"sections":[],"abstract":[{"type":"text","text":"Set custom US Privacy string from host app"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setUSPrivacyString(_:)"},"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"url":"\/documentation\/teadssdk","kind":"symbol","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"title":"TeadsSDK","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","role":"collection"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy/setUSPrivacyString(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Set custom US Privacy string from host app"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy\/setUSPrivacyString(_:)","navigatorTitle":[{"text":"setUSPrivacyString:","kind":"identifier"}],"url":"\/documentation\/teadssdk\/teadsprivacy\/setusprivacystring(_:)","title":"setUSPrivacyString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUSPrivacyString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsPrivacy":{"type":"topic","title":"TeadsPrivacy","abstract":[],"url":"\/documentation\/teadssdk\/teadsprivacy","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsPrivacy","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TeadsPrivacy"}],"navigatorTitle":[{"kind":"identifier","text":"TeadsPrivacy"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setUSPrivacyString:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUSPrivacyString:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setUSPrivacyString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"privacyString","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"privacyString","content":[{"inlineContent":[{"text":"CCPA privacy string","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"setUSPrivacyString:","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setUSPrivacyString(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setUSPrivacyString:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy~1setUSPrivacyString(_:)\/fragments"},{"op":"replace","value":"TeadsPrivacy","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy\/title"},{"op":"replace","value":[{"text":"TeadsPrivacy","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy\/fragments"},{"op":"replace","value":[{"text":"TeadsPrivacy","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1TeadsPrivacy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}