{"metadata":{"role":"symbol","platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"13.0","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"s:8TeadsSDK0A6NativeV9MediaViewV5scaleyAeA0D5ScaleOF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MediaScale","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@MediaScale"},{"text":") -> ","kind":"text"},{"text":"TeadsNative","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV"},{"text":".","kind":"text"},{"text":"MediaView","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV9MediaViewV"}],"modules":[{"name":"TeadsSDK"}],"title":"scale(_:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"scale","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MediaScale","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@MediaScale","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale"},{"text":") -> ","kind":"text"},{"text":"TeadsNative","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative"},{"text":".","kind":"text"},{"text":"MediaView","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV9MediaViewV","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Rendering option of the content"}]}],"name":"scale"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView\/scale(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/teadssdk\/teadsnative\/mediaview\/scale(_:)"]}],"abstract":[{"text":"Specify scale value describing the native ad media scale for rendering.","type":"text"}],"sections":[],"references":{"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative":{"navigatorTitle":[{"text":"TeadsNative","kind":"identifier"}],"title":"TeadsNative","url":"\/documentation\/teadssdk\/teadsnative","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TeadsNative","kind":"identifier"}]},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/MediaView/scale(_:)":{"url":"\/documentation\/teadssdk\/teadsnative\/mediaview\/scale(_:)","abstract":[{"type":"text","text":"Specify scale value describing the native ad media scale for rendering."}],"title":"scale(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MediaScale","kind":"typeIdentifier","preciseIdentifier":"c:@M@TeadsSDK@E@MediaScale"},{"text":") -> ","kind":"text"},{"text":"TeadsNative","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV"},{"text":".","kind":"text"},{"text":"MediaView","kind":"typeIdentifier","preciseIdentifier":"s:8TeadsSDK0A6NativeV9MediaViewV"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView\/scale(_:)"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/TeadsNative/MediaView":{"abstract":[{"type":"text","text":"The MediaView can load either images, videos and VPAID content."}],"navigatorTitle":[{"kind":"identifier","text":"MediaView"}],"identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/TeadsNative\/MediaView","title":"TeadsNative.MediaView","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaView"}],"kind":"symbol","url":"\/documentation\/teadssdk\/teadsnative\/mediaview","type":"topic"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK":{"title":"TeadsSDK","abstract":[{"text":"Teads allows you to integrate a single SDK into your app, and serve premium branded “outstream” video ads from Teads SSP ad server.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/teadssdk","type":"topic","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK"},"doc://tv.teads.TeadsSDK.TeadsSDK/documentation/TeadsSDK/MediaScale":{"abstract":[{"text":"A flag used to determine how TeadsMediaView lays out its content when its bounds change.","type":"text"}],"kind":"symbol","type":"topic","title":"MediaScale","url":"\/documentation\/teadssdk\/mediascale","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaScale"}],"navigatorTitle":[{"kind":"identifier","text":"MediaScale"}],"role":"symbol","identifier":"doc:\/\/tv.teads.TeadsSDK.TeadsSDK\/documentation\/TeadsSDK\/MediaScale"}},"variantOverrides":[{"patch":[{"value":"MediaScale","path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MediaScale"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/fragments","op":"replace"},{"value":[{"text":"MediaScale","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.teads.TeadsSDK.TeadsSDK~1documentation~1TeadsSDK~1MediaScale\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}